/**
 * 자동 생성 파일 — 직접 수정하지 마세요.
 * 원본: motivational_quotes_500_4languages.csv ("한국어" 열)
 * 재생성: node scripts/gen-curated-quotes.mjs
 *
 * 위인 어록이 아닌 무명(작자 미상) 잠언 풀. author 없이 category="wisdom" 으로만 태깅된다.
 */
import type { FamousQuoteSeed } from "@/lib/famousQuotesSeed";

export const CURATED_QUOTES_KO: ReadonlyArray<FamousQuoteSeed> = [
  // ── 시작과 첫걸음 / Beginnings ─────────────────────────
  { id: "cu_ko_001", text: "완벽한 때를 기다리면 영원히 시작하지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_002", text: "오늘의 작은 시작이 내일의 큰 차이를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_003", text: "첫걸음은 언제나 가장 무겁고 가장 중요하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_004", text: "준비가 끝나서 시작하는 게 아니라, 시작해야 준비가 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_005", text: "늦었다고 느끼는 지금이 남은 생에서 가장 이른 순간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_006", text: "시작하지 않은 일은 실패조차 할 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_007", text: "큰 문은 작은 열쇠로 열린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_008", text: "오늘 심지 않은 씨앗은 내일 자라지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_009", text: "시작은 용기의 다른 이름이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_010", text: "지도를 보는 사람보다 한 걸음 걷는 사람이 멀리 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_011", text: "하루를 여는 방식이 인생을 여는 방식이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_012", text: "시작을 미루는 습관이 가장 비싼 비용이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_013", text: "아무것도 하지 않으면 아무 일도 일어나지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_014", text: "서툰 시작이 완벽한 계획을 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_015", text: "오늘은 남은 인생에서 가장 젊은 날이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_016", text: "새로운 길은 처음 걷는 사람에 의해 만들어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_017", text: "두려움은 시작 전에 가장 크고, 시작 후에 가장 작다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_018", text: "계획은 종이 위에서, 변화는 발밑에서 일어난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_019", text: "매일 1퍼센트의 시작이 1년 뒤의 나를 바꾼다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_020", text: "기회는 문을 두드리지 않는다. 당신이 문을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_021", text: "결심은 하루면 충분하고, 시작은 지금이면 충분하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_022", text: "시작이 반이라면, 나머지 반은 계속하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_023", text: "처음부터 잘하는 사람은 없다. 시작한 사람만 잘하게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_024", text: "오늘 하지 않을 이유는 내일도 그대로 남아 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_025", text: "백 번의 다짐보다 한 번의 실행이 낫다.", category: "wisdom", language: "ko" },
  // ── 끈기와 인내 / Persistence ─────────────────────────
  { id: "cu_ko_026", text: "재능은 출발선을 정하고, 끈기는 도착선을 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_027", text: "포기하지 않는 한 아직 결과는 나오지 않았다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_028", text: "매일 조금씩 하는 사람을 이길 방법은 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_029", text: "물방울이 바위를 뚫는 것은 힘이 아니라 반복이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_030", text: "가장 어두운 구간이 대개 결승선 직전이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_031", text: "성장은 지루한 반복 속에 숨어 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_032", text: "천천히 가는 것을 두려워 말고, 멈추는 것을 두려워하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_033", text: "버티는 것도 실력이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_034", text: "오래 하는 사람이 결국 잘하는 사람이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_035", text: "하루의 노력은 티가 나지 않지만 일 년의 노력은 숨길 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_036", text: "대나무는 4년 동안 뿌리를 내리고 5년째에 하늘로 솟는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_037", text: "중단하지 않은 노력에는 이자가 붙는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_038", text: "끝까지 남아 있는 사람에게 기회가 온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_039", text: "의욕이 사라진 날에도 움직이는 것이 프로다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_040", text: "한 번 더 시도하는 것, 그것이 전부다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_041", text: "피로는 목표에 가까워졌다는 신호일 때가 많다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_042", text: "나무는 매일 자라지 않지만 매년 굵어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_043", text: "중요한 일일수록 지겨움을 견뎌야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_044", text: "성공은 갑자기 오는 것이 아니라 누적되어 드러난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_045", text: "오늘 그만두면 어제의 노력까지 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_046", text: "계속하는 힘은 재능보다 희소하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_047", text: "무거운 돌도 백 번 치면 쪼개진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_048", text: "목표를 향한 걸음에는 작은 걸음이란 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_049", text: "숨이 찰 때 비로소 근육이 자란다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_050", text: "하루를 이기면 한 달을 이기고, 한 달을 이기면 인생을 이긴다.", category: "wisdom", language: "ko" },
  // ── 실패와 회복 / Resilience ─────────────────────────
  { id: "cu_ko_051", text: "실패는 결과가 아니라 데이터다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_052", text: "넘어지는 것은 사고지만, 일어나지 않는 것은 선택이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_053", text: "가장 값진 수업료는 실패에 지불한 돈이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_054", text: "같은 실수를 반복하지 않는다면 그것은 실패가 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_055", text: "바닥은 무너지는 곳이 아니라 딛고 서는 곳이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_056", text: "상처는 흉터가 되고, 흉터는 갑옷이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_057", text: "한 번의 실패가 한 사람을 정의하지는 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_058", text: "무너진 뒤에 세운 것이 더 단단하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_059", text: "실패를 두려워하면 배움도 함께 잃는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_060", text: "가장 빠른 회복은 원인을 정직하게 보는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_061", text: "잘못된 길을 오래 걷지 않는 것도 성공이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_062", text: "후회는 과거를 붙잡고, 반성은 미래를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_063", text: "시련은 사람을 시험하는 것이 아니라 드러낸다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_064", text: "폭풍이 지나간 자리에서 뿌리는 더 깊어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_065", text: "다시 일어서는 속도가 그 사람의 크기다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_066", text: "실수를 인정하는 순간 성장은 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_067", text: "모든 전문가는 수많은 실패의 생존자다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_068", text: "안전한 길에는 배움이 적다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_069", text: "실패한 시도는 아무것도 하지 않은 날보다 값지다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_070", text: "무릎이 꺾여도 방향은 꺾이지 않게 하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_071", text: "절망은 사실이 아니라 감정이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_072", text: "오늘의 상실이 내일의 여백이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_073", text: "잃어본 사람만이 지킬 줄 안다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_074", text: "끝이라고 생각한 지점이 대개 전환점이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_075", text: "넘어진 자리를 원망하지 말고 지도에 표시하라.", category: "wisdom", language: "ko" },
  // ── 습관과 루틴 / Habits ─────────────────────────
  { id: "cu_ko_076", text: "의지는 흔들리지만 습관은 버틴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_077", text: "당신이 반복하는 것이 곧 당신이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_078", text: "좋은 습관은 미래의 나에게 보내는 선물이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_079", text: "하루 10분이 10년을 바꾼다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_080", text: "시작을 쉽게 만들면 지속은 저절로 따라온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_081", text: "환경을 바꾸는 것이 결심보다 강력하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_082", text: "하루를 지배하는 사람이 인생을 지배한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_083", text: "완벽한 하루보다 빠지지 않는 하루가 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_084", text: "이틀 연속 거르지 않는 것이 최고의 규칙이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_085", text: "아침 한 시간이 하루 전체의 방향을 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_086", text: "작게 시작해야 오래 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_087", text: "측정하지 않는 습관은 오래가지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_088", text: "루틴은 창의력을 가두지 않고 보호한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_089", text: "반복은 지루하지만 결과는 지루하지 않다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_090", text: "나쁜 습관은 처음엔 손님이고 나중엔 주인이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_091", text: "결심은 잊혀지지만 시스템은 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_092", text: "오늘 한 선택이 내일의 기본값이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_093", text: "버리는 습관 하나가 새 습관 열 개보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_094", text: "하기 싫은 일을 먼저 하면 하루가 가벼워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_095", text: "습관은 복리처럼 쌓인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_096", text: "같은 시간, 같은 자리, 같은 일이 실력을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_097", text: "의욕을 기다리지 말고 일정을 지켜라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_098", text: "하루의 마무리가 다음 날의 출발이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_099", text: "작은 규칙 하나가 무너지면 큰 계획도 무너진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_100", text: "좋은 습관은 자유를 빼앗지 않고 만들어 준다.", category: "wisdom", language: "ko" },
  // ── 시간과 우선순위 / Time ─────────────────────────
  { id: "cu_ko_101", text: "시간은 관리되는 것이 아니라 선택되는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_102", text: "바쁘다는 말은 우선순위가 없다는 말이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_103", text: "무엇을 하지 않을지 정하는 것이 전략이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_104", text: "하루는 모두에게 같지만 밀도는 각자 다르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_105", text: "급한 일이 중요한 일을 밀어내게 두지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_106", text: "시간을 쓰는 방식이 곧 가치관이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_107", text: "잃어버린 시간만은 되살 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_108", text: "모든 것에 예라고 답하면 결국 아무것도 못 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_109", text: "거절은 시간을 지키는 가장 정직한 방법이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_110", text: "내일의 나는 오늘의 나보다 한가하지 않다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_111", text: "한 번에 하나씩이 가장 빠른 길이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_112", text: "중요한 일에는 가장 좋은 시간을 배정하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_113", text: "시간이 없는 게 아니라 순서가 없는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_114", text: "일정을 정하지 않으면 남이 정해 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_115", text: "미루기는 시간을 아끼는 게 아니라 이자를 붙인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_116", text: "짧은 시간에 집중하는 편이 긴 시간을 흘려보내는 것보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_117", text: "계획은 시간을 늘려 주지 않지만 낭비를 줄여 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_118", text: "오늘 저녁의 30분이 내일 아침의 두 시간을 벌어 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_119", text: "마감은 적이 아니라 가장 성실한 동료다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_120", text: "시간을 벌고 싶다면 먼저 정리하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_121", text: "하루를 잘게 쪼개면 인생이 넓어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_122", text: "기다리는 시간도 당신의 시간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_123", text: "바쁨은 성취가 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_124", text: "일주일을 설계하면 한 해가 달라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_125", text: "가장 값비싼 낭비는 무엇을 할지 고민하는 시간이다.", category: "wisdom", language: "ko" },
  // ── 자기 믿음 / Self-Belief ─────────────────────────
  { id: "cu_ko_126", text: "스스로를 믿지 않으면 누구도 대신 믿어 주지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_127", text: "남의 기준으로 살면 남의 인생을 사는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_128", text: "자신에게 하는 말이 가장 오래 남는 말이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_129", text: "당신의 가치는 남의 평가로 정해지지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_130", text: "자신감은 성공의 결과가 아니라 시도의 결과다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_131", text: "비교는 성장을 멈추게 하는 가장 조용한 방법이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_132", text: "당신이 스스로 정한 한계가 대부분의 한계다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_133", text: "자기 자신과의 약속을 지키는 사람이 강해진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_134", text: "목소리를 낮추지 마라. 당신의 이야기는 들릴 가치가 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_135", text: "남과 다른 것이 곧 부족한 것은 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_136", text: "누구도 당신만큼 당신의 가능성을 알지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_137", text: "자신을 돌보는 일은 이기심이 아니라 책임이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_138", text: "부족함을 인정하는 것도 자신감의 일부다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_139", text: "당신은 이미 예전의 당신이 부러워하던 사람이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_140", text: "칭찬은 사양해도 성취는 사양하지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_141", text: "자기 확신은 소음 속에서 방향을 지키는 힘이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_142", text: "스스로에게 가혹한 사람이 가장 늦게 성장한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_143", text: "당신의 속도가 곧 당신의 길이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_144", text: "의심이 들 때는 지나온 길을 돌아보라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_145", text: "완벽하지 않아도 시작할 자격은 충분하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_146", text: "남의 성공이 당신의 실패를 뜻하지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_147", text: "자기 신뢰는 작은 약속들의 누적이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_148", text: "당신의 이야기는 아직 절반도 쓰이지 않았다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_149", text: "자격은 주어지는 것이 아니라 만들어 가는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_150", text: "스스로를 응원하는 사람이 끝까지 간다.", category: "wisdom", language: "ko" },
  // ── 성장과 배움 / Growth ─────────────────────────
  { id: "cu_ko_151", text: "모르는 것을 인정하는 순간부터 배움이 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_152", text: "어제보다 나아졌다면 오늘은 성공한 날이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_153", text: "불편함은 성장의 입구다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_154", text: "질문의 크기가 성장의 크기를 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_155", text: "가르칠 때 가장 많이 배운다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_156", text: "배움에는 정년이 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_157", text: "아는 것과 하는 것 사이의 거리가 실력이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_158", text: "익숙한 곳에는 새로운 것이 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_159", text: "비판은 쓰지만 가장 빠른 지름길이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_160", text: "같은 책도 다른 시기에 읽으면 다른 책이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_161", text: "성장은 직선이 아니라 계단이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_162", text: "배운 것을 써먹지 않으면 배운 것이 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_163", text: "나보다 나은 사람 곁에 있는 것이 가장 빠른 학습이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_164", text: "모방은 창조의 첫 번째 연습이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_165", text: "초심자의 서투름은 부끄러움이 아니라 증거다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_166", text: "피드백을 견디는 힘이 실력을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_167", text: "배움을 멈춘 순간부터 늙기 시작한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_168", text: "깊이는 시간이 만들고, 넓이는 호기심이 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_169", text: "기록하지 않은 경험은 절반만 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_170", text: "모든 전문성은 처음에 낯선 단어에서 시작했다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_171", text: "배움은 채우는 일이자 비우는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_172", text: "어려운 책이 쉬운 책보다 오래 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_173", text: "성장하려면 잘하는 일 옆에 못하는 일을 두어야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_174", text: "오늘 이해한 것을 내일 설명할 수 있어야 진짜다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_175", text: "경험은 시간이 아니라 반성에서 온다.", category: "wisdom", language: "ko" },
  // ── 목표와 비전 / Vision ─────────────────────────
  { id: "cu_ko_176", text: "목적지가 없으면 어떤 바람도 순풍이 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_177", text: "목표는 종이에 적히는 순간 계획이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_178", text: "큰 꿈은 작은 마감으로 이루어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_179", text: "어디로 가는지 알면 속도는 문제가 되지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_180", text: "측정할 수 없는 목표는 소원일 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_181", text: "목표를 낮추지 말고 방법을 바꿔라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_182", text: "비전은 오늘의 고단함에 의미를 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_183", text: "남의 목표를 좇으면 도착해도 공허하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_184", text: "목표는 방향이고, 습관은 엔진이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_185", text: "10년 뒤를 생각하면 오늘의 선택이 쉬워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_186", text: "많은 목표는 목표가 없는 것과 같다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_187", text: "이루고 싶은 것보다 되고 싶은 사람을 먼저 정하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_188", text: "계획은 바뀌어도 방향은 유지하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_189", text: "눈에 보이는 목표가 눈에 보이는 결과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_190", text: "도달할 수 없어 보이는 목표만이 사람을 키운다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_191", text: "목표를 쪼개면 두려움도 함께 쪼개진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_192", text: "성취한 뒤가 아니라 정한 순간부터 달라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_193", text: "목표 없는 노력은 물레방아처럼 제자리를 돈다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_194", text: "가장 위험한 목표는 너무 쉬운 목표다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_195", text: "목표를 공개하면 책임이 따라온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_196", text: "매일의 목표가 평생의 목표를 지탱한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_197", text: "무엇을 원하는지 모르면 무엇을 얻어도 부족하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_198", text: "목표는 지도이고, 실행은 신발이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_199", text: "끝을 그려 놓고 시작하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_200", text: "이루지 못한 목표도 당신을 어딘가로 데려간다.", category: "wisdom", language: "ko" },
  // ── 용기와 두려움 / Courage ─────────────────────────
  { id: "cu_ko_201", text: "용기는 두려움이 없는 상태가 아니라 두려움과 함께 걷는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_202", text: "가장 큰 위험은 아무 위험도 감수하지 않는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_203", text: "두려움은 대개 상상 속에서만 존재한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_204", text: "피하고 싶은 그 일이 대개 해야 할 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_205", text: "용기는 근육처럼 쓸수록 커진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_206", text: "거절당하는 것은 사라지는 것이 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_207", text: "물어보지 않으면 답은 언제나 아니오다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_208", text: "두려움을 말로 꺼내면 절반이 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_209", text: "안전지대는 편안하지만 아무것도 자라지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_210", text: "후회는 실패보다 오래간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_211", text: "용기는 크게 소리치는 것이 아니라 조용히 다시 하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_212", text: "모르는 길에서만 새로운 풍경을 본다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_213", text: "남의 시선은 당신의 인생 비용을 내주지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_214", text: "불확실함을 견디는 능력이 기회를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_215", text: "한 번 용기를 내면 다음 용기는 쉬워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_216", text: "두려움은 나침반이다. 가리키는 곳에 성장이 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_217", text: "위험을 계산하되 두려움에 굴복하지는 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_218", text: "겁이 나는데도 한 걸음 내딛는 것이 성장이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_219", text: "아무도 도전하지 않은 자리에 가장 큰 공간이 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_220", text: "실패보다 시도조차 하지 않은 날들이 더 아프다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_221", text: "용기는 확신이 아니라 결심에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_222", text: "약해 보이는 것을 두려워하면 강해질 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_223", text: "모든 큰 변화는 불편한 대화에서 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_224", text: "두려움에 이름을 붙이면 크기가 줄어든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_225", text: "용기 있는 하루가 평범한 일 년보다 길다.", category: "wisdom", language: "ko" },
  // ── 태도와 마인드셋 / Mindset ─────────────────────────
  { id: "cu_ko_226", text: "같은 상황도 해석에 따라 다른 결과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_227", text: "아직 못 한다는 말 뒤에 아직이라는 단어를 붙여라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_228", text: "문제를 문제로만 보면 문제만 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_229", text: "태도는 능력보다 먼저 눈에 띈다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_230", text: "불평은 상황을 바꾸지 못하고 에너지만 가져간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_231", text: "통제할 수 있는 것에만 감정을 쓰라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_232", text: "운은 준비된 태도 위에 내려앉는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_233", text: "모든 일이 나에게 유리하게 흘러가지 않아도 괜찮다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_234", text: "생각의 방향이 발의 방향을 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_235", text: "겸손은 배움의 문을 열어 두는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_236", text: "남 탓을 멈추는 순간 힘이 돌아온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_237", text: "기대를 낮추면 실망도 줄고 노력도 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_238", text: "긍정은 현실을 외면하는 것이 아니라 해법을 찾는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_239", text: "배우려는 사람에게는 모든 사람이 스승이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_240", text: "결과보다 과정을 사랑하면 오래 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_241", text: "말버릇이 인생의 방향을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_242", text: "여유는 시간이 아니라 마음의 문제다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_243", text: "나쁜 하루가 나쁜 인생을 뜻하지는 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_244", text: "받아들일 것과 바꿀 것을 구분하는 것이 지혜다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_245", text: "화를 내는 데 쓴 시간은 해결에 쓰지 못한 시간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_246", text: "가진 것을 세는 사람이 더 많이 갖게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_247", text: "성숙은 반응 대신 선택하는 능력이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_248", text: "모르는 것을 부끄러워하지 말고 묻지 않는 것을 부끄러워하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_249", text: "어려운 일을 맡았다는 건 신뢰받고 있다는 뜻이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_250", text: "생각을 바꾸면 세상이 바뀌는 것이 아니라 보이는 것이 바뀐다.", category: "wisdom", language: "ko" },
  // ── 실행과 행동 / Action ─────────────────────────
  { id: "cu_ko_251", text: "아이디어는 흔하고 실행은 드물다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_252", text: "생각만 하는 사람과 하는 사람의 차이는 하루면 드러난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_253", text: "움직이는 배만 방향을 바꿀 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_254", text: "초안이 걸작보다 낫다. 존재하기 때문이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_255", text: "완벽주의는 게으름의 가장 우아한 변명이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_256", text: "오늘의 실행이 내일의 자신감이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_257", text: "결정을 미루는 것도 결정이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_258", text: "한 시간의 실행이 한 달의 계획보다 많은 것을 알려 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_259", text: "작게 시작하고 빠르게 고쳐라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_260", text: "말은 계획을 만들고 행동은 결과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_261", text: "하려는 마음보다 하고 있는 손이 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_262", text: "시도한 뒤에야 무엇이 문제인지 알 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_263", text: "고민의 90퍼센트는 실행하면 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_264", text: "아무도 당신의 계획을 대신 실행해 주지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_265", text: "시작 버튼은 언제나 손 안에 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_266", text: "출시하지 않은 제품은 존재하지 않는 제품이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_267", text: "다섯 번 생각하고 한 번 움직이면 늦는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_268", text: "행동은 불안을 이기는 유일한 약이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_269", text: "끝내는 사람이 시작하는 사람보다 귀하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_270", text: "작은 실행이 큰 확신을 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_271", text: "일단 내놓아라. 완성은 반응 속에서 이루어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_272", text: "기록으로만 남은 아이디어는 죽은 아이디어다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_273", text: "해 보기 전까지 어려움은 언제나 과장된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_274", text: "바로 지금이 언제나 가장 좋은 타이밍이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_275", text: "하루에 하나만 끝내도 일 년이면 삼백육십다섯 개다.", category: "wisdom", language: "ko" },
  // ── 집중과 몰입 / Focus ─────────────────────────
  { id: "cu_ko_276", text: "주의를 흩뜨리는 것을 줄이는 것이 능력을 키우는 것보다 빠르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_277", text: "한 가지에 집중한 한 시간이 산만한 하루를 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_278", text: "모든 것을 하려는 사람은 아무것도 깊이 하지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_279", text: "집중은 재능이 아니라 훈련이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_280", text: "알림을 끄는 것이 의지력을 기르는 것보다 쉽다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_281", text: "깊이 있는 결과는 방해받지 않은 시간에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_282", text: "멀티태스킹은 여러 가지를 못하는 가장 빠른 방법이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_283", text: "책상 위의 어수선함은 머릿속의 어수선함이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_284", text: "시작하는 데 필요한 건 의욕이 아니라 5분이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_285", text: "몰입은 자신을 잊는 순간에 찾아온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_286", text: "하나를 끝내고 다음으로 넘어가는 사람이 가장 빠르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_287", text: "집중력은 저장되지 않는다. 오늘 써야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_288", text: "중요한 일에는 방해받지 않을 권리가 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_289", text: "선택지가 적을수록 더 멀리 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_290", text: "잘하는 일 하나가 그럭저럭한 일 열보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_291", text: "주의는 가장 값비싼 자산이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_292", text: "잠깐의 확인이 한 시간의 흐름을 끊는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_293", text: "고요함 속에서 가장 좋은 생각이 태어난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_294", text: "무엇을 볼지 정하는 것이 무엇을 얻을지 정하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_295", text: "산만함은 실패가 아니라 설계의 문제다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_296", text: "한 번에 한 걸음이 언제나 가장 확실하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_297", text: "중요한 것을 먼저 넣어야 남은 것이 들어간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_298", text: "목표가 선명할수록 유혹은 흐려진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_299", text: "쉬는 것도 집중의 일부다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_300", text: "중요한 일을 마친 뒤에야 나머지가 제자리를 찾는다.", category: "wisdom", language: "ko" },
  // ── 규율과 절제 / Discipline ─────────────────────────
  { id: "cu_ko_301", text: "자유는 규율의 끝에서 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_302", text: "하고 싶은 것을 참는 힘이 원하는 것을 얻게 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_303", text: "규율은 미래의 나를 위한 오늘의 배려다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_304", text: "기분이 결정을 지배하게 두지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_305", text: "절제는 결핍이 아니라 선택이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_306", text: "편한 길을 고르면 삶이 어려워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_307", text: "스스로를 다스리는 사람이 가장 강한 사람이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_308", text: "매일의 절제가 평생의 자유를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_309", text: "하기 싫은 날에도 하는 것이 규율이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_310", text: "한 번의 예외가 열 번의 예외를 부른다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_311", text: "기준을 세우면 매번 고민하지 않아도 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_312", text: "충동은 짧고 후회는 길다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_313", text: "쉬운 결정을 반복하면 어려운 인생이 온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_314", text: "절제는 참는 것이 아니라 더 큰 것을 고르는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_315", text: "규칙이 있는 삶이 더 넉넉하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_316", text: "의지력에 기대지 말고 구조를 만들어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_317", text: "잠을 이기려 하지 말고 관리하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_318", text: "하루의 규율이 십 년의 결과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_319", text: "가장 어려운 일은 자기와의 싸움에서 이기는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_320", text: "미루지 않는 것이 최고의 재테크다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_321", text: "절제된 사람만이 큰 기회를 감당할 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_322", text: "당신의 하루는 당신이 허락한 것들로 채워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_323", text: "욕망을 이해하면 다스리기 쉬워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_324", text: "불편함을 견디는 시간이 곧 성장의 시간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_325", text: "약속 시간을 지키는 사람은 신뢰도 지킨다.", category: "wisdom", language: "ko" },
  // ── 사람과 관계 / Relationships ─────────────────────────
  { id: "cu_ko_326", text: "혼자 가면 빠르지만 함께 가면 멀리 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_327", text: "주변 다섯 사람의 평균이 당신이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_328", text: "신뢰는 쌓는 데 몇 년, 무너지는 데 몇 초다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_329", text: "듣는 사람이 결국 더 많이 얻는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_330", text: "받은 도움은 잊지 말고 준 도움은 잊어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_331", text: "사람을 이기려 하지 말고 문제를 이겨라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_332", text: "좋은 관계는 시간이 아니라 진심으로 유지된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_333", text: "누구를 만나느냐가 무엇을 아느냐만큼 중요하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_334", text: "먼저 베푸는 사람이 결국 가장 많이 받는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_335", text: "말을 아끼면 신뢰가 늘어난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_336", text: "비난 대신 질문을 하면 관계가 산다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_337", text: "약속을 지키는 것이 가장 강력한 마케팅이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_338", text: "사람을 남기는 사람이 결국 성공한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_339", text: "경청은 가장 저평가된 리더십이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_340", text: "고마움은 표현될 때 비로소 존재한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_341", text: "누군가의 성장을 돕는 일이 자신을 가장 크게 키운다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_342", text: "사과는 늦을수록 비싸진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_343", text: "기억되고 싶다면 이름을 먼저 기억하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_344", text: "모두를 만족시키려는 사람은 아무도 만족시키지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_345", text: "좋은 동료는 최고의 복지다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_346", text: "거리를 두는 것도 관계를 지키는 방법이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_347", text: "타인의 성공을 축하할 줄 아는 사람이 크게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_348", text: "말투가 내용보다 오래 기억된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_349", text: "혼자만 잘하려는 사람은 결국 혼자 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_350", text: "의견이 달라도 사람을 존중할 수는 있다.", category: "wisdom", language: "ko" },
  // ── 리더십과 영향력 / Leadership ─────────────────────────
  { id: "cu_ko_351", text: "리더십은 직책이 아니라 태도다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_352", text: "먼저 움직이는 사람이 리더가 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_353", text: "말로 이끌지 말고 등으로 이끌어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_354", text: "좋은 리더는 공을 나누고 책임을 가져간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_355", text: "사람은 지시를 따르지 않고 신뢰를 따른다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_356", text: "팀의 수준은 리더가 허용한 기준이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_357", text: "질문하는 리더가 배우는 조직을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_358", text: "영향력은 요구하는 것이 아니라 얻어지는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_359", text: "칭찬은 공개적으로, 지적은 조용히.", category: "wisdom", language: "ko" },
  { id: "cu_ko_360", text: "사람을 키우는 것이 리더의 가장 큰 성과다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_361", text: "리더의 침착함은 팀 전체의 안전망이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_362", text: "모범은 백 번의 훈시보다 강하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_363", text: "가장 좋은 리더는 자신이 필요 없게 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_364", text: "권한은 나누고 기준은 지켜라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_365", text: "리더의 시간이 조직의 우선순위를 말해 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_366", text: "나쁜 소식이 빨리 올라오는 조직이 건강하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_367", text: "결정하지 않는 리더가 가장 위험하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_368", text: "리더는 답을 주기보다 방향을 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_369", text: "신뢰받는 사람만이 변화를 이끌 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_370", text: "잘못을 인정하는 리더가 팀을 강하게 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_371", text: "말한 것을 지키는 것이 리더십의 전부다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_372", text: "사람을 믿으면 사람은 그만큼 자란다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_373", text: "가장 조용한 사람의 의견을 먼저 물어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_374", text: "리더의 성장이 멈추면 조직의 성장도 멈춘다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_375", text: "영향력은 크기가 아니라 방향이 중요하다.", category: "wisdom", language: "ko" },
  // ── 창의와 혁신 / Creativity ─────────────────────────
  { id: "cu_ko_376", text: "새로운 것은 낯선 조합에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_377", text: "나쁜 아이디어 백 개가 좋은 아이디어 하나를 데려온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_378", text: "질문을 바꾸면 답이 바뀐다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_379", text: "창의성은 영감이 아니라 습관의 산물이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_380", text: "제약이 많을수록 창의적인 답이 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_381", text: "다르게 보는 것이 더 열심히 보는 것보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_382", text: "모든 혁신은 처음에 무모해 보였다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_383", text: "익숙한 문제를 낯설게 보는 것이 시작이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_384", text: "메모하지 않은 아이디어는 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_385", text: "경계 위에 서 있는 사람이 새로운 것을 본다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_386", text: "산책은 회의보다 좋은 아이디어를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_387", text: "기존의 답을 의심하는 것이 혁신의 출발점이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_388", text: "서로 다른 분야를 잇는 사람이 가장 창의적이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_389", text: "처음 만든 것은 언제나 부끄럽다. 그래도 만들어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_390", text: "아이디어는 소유가 아니라 실행으로 증명된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_391", text: "남과 같은 방식으로는 남과 다른 결과를 얻을 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_392", text: "호기심은 가장 오래 쓸 수 있는 도구다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_393", text: "버려지는 아이디어가 많을수록 남는 아이디어가 좋다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_394", text: "창작의 적은 비판이 아니라 무관심이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_395", text: "다양한 사람과 일하면 생각의 폭이 넓어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_396", text: "틀을 알아야 틀을 깰 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_397", text: "가장 좋은 아이디어는 대개 두 번째 시도에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_398", text: "쓸모없어 보이는 지식이 나중에 연결된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_399", text: "생각을 손으로 옮기면 비로소 검증할 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_400", text: "따라 하다 보면 자기만의 길이 보인다.", category: "wisdom", language: "ko" },
  // ── 돈과 부 / Wealth ─────────────────────────
  { id: "cu_ko_401", text: "버는 법보다 지키는 법이 어렵다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_402", text: "지출을 통제하지 못하면 수입도 소용없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_403", text: "시간을 사는 데 돈을 쓰는 것이 가장 좋은 소비다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_404", text: "부는 소득이 아니라 습관에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_405", text: "가장 확실한 투자는 자기 자신이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_406", text: "일찍 시작한 저축은 늦게 시작한 큰돈을 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_407", text: "빚은 미래의 자유를 미리 쓰는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_408", text: "남을 위해 만든 가치만큼 돌아온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_409", text: "빠른 부는 대개 빠르게 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_410", text: "모르는 곳에 투자하는 것은 투자가 아니라 도박이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_411", text: "검소함은 가난이 아니라 선택이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_412", text: "돈은 좋은 도구이자 나쁜 주인이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_413", text: "수입원이 하나뿐이면 인생도 하나의 위험에 걸려 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_414", text: "복리는 조급한 사람에게 보답하지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_415", text: "남과 비교하는 지출이 가장 비싸다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_416", text: "가격은 지불하는 것이고 가치는 얻는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_417", text: "기록하지 않은 돈은 새어 나간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_418", text: "경제적 자유란 하기 싫은 일을 거절할 힘이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_419", text: "버는 속도보다 배우는 속도가 중요하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_420", text: "충분함을 아는 사람이 진짜 부자다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_421", text: "위험을 이해하지 못하면 수익도 지킬 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_422", text: "절약은 수비이고 투자는 공격이다. 둘 다 필요하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_423", text: "돈으로 살 수 없는 것을 먼저 지켜라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_424", text: "작은 지출의 반복이 큰 지출보다 무섭다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_425", text: "성공한 사람들은 대체로 지루하게 투자한다.", category: "wisdom", language: "ko" },
  // ── 건강과 균형 / Health ─────────────────────────
  { id: "cu_ko_426", text: "건강은 잃기 전까지 가장 저평가된 자산이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_427", text: "잠은 게으름이 아니라 성과의 조건이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_428", text: "몸을 돌보지 않으면 결국 몸이 일정을 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_429", text: "매일 걷는 30분이 미래의 병상을 줄인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_430", text: "쉬는 것은 멈추는 것이 아니라 준비하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_431", text: "성과는 체력 위에 쌓인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_432", text: "번아웃은 열심히 한 벌이 아니라 균형의 신호다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_433", text: "천천히 먹는 습관이 오래 사는 습관이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_434", text: "일과 삶은 저울이 아니라 리듬이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_435", text: "몸이 보내는 작은 신호를 무시하지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_436", text: "운동은 오늘의 부담이자 내일의 저축이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_437", text: "스트레스는 없애는 것이 아니라 다루는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_438", text: "주말의 회복이 주중의 성과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_439", text: "가장 성실한 투자는 매일의 잠과 물이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_440", text: "아픈 뒤에 쉬는 것보다 아프기 전에 쉬는 것이 싸다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_441", text: "하루 한 번은 화면에서 눈을 떼라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_442", text: "산책은 가장 저렴한 상담이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_443", text: "몸이 편해야 마음도 정리된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_444", text: "무리한 하루는 사흘의 회복을 부른다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_445", text: "가족과의 저녁 식사는 일정에 넣을 가치가 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_446", text: "취미는 사치가 아니라 유지비다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_447", text: "숨을 고르는 시간이 속도를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_448", text: "잘 쉰 사람이 잘 결정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_449", text: "평생 쓸 몸은 하나뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_450", text: "바쁠수록 규칙적으로 먹고 자라.", category: "wisdom", language: "ko" },
  // ── 감사와 마음 / Gratitude ─────────────────────────
  { id: "cu_ko_451", text: "가진 것을 세어 보는 순간 부족함이 줄어든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_452", text: "감사는 습관이 될 때 힘이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_453", text: "평범한 하루가 누군가에게는 간절한 하루다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_454", text: "불평의 목록보다 감사의 목록이 길어야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_455", text: "고마움을 늦게 말하면 절반만 전해진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_456", text: "작은 것에 기뻐하는 능력이 삶의 질을 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_457", text: "비교를 멈추면 만족이 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_458", text: "당연한 것은 없다. 다만 익숙해졌을 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_459", text: "오늘 무사히 지나간 하루도 성취다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_460", text: "감사는 과거를 정리하고 미래를 가볍게 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_461", text: "누군가의 수고 덕분에 오늘의 편안함이 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_462", text: "마음이 넉넉한 사람은 나눌 것이 늘 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_463", text: "용서는 상대가 아니라 나를 위한 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_464", text: "하루를 감사로 마치면 다음 날이 가벼워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_465", text: "받은 친절은 다른 사람에게 흘려보내라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_466", text: "기쁨은 크기가 아니라 빈도의 문제다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_467", text: "불안한 마음에는 감사가 가장 좋은 해독제다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_468", text: "말 한마디의 따뜻함은 오래 기억된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_469", text: "충분히 가졌음을 아는 것이 가장 큰 소득이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_470", text: "기억할수록 감사할 일이 많아진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_471", text: "남을 위한 마음이 결국 나를 지켜 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_472", text: "칭찬은 아껴 두면 유통기한이 지나 버린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_473", text: "감사할 줄 아는 사람 곁에는 사람이 모인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_474", text: "하루에 세 가지만 적어도 마음이 달라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_475", text: "고생 끝의 기쁨은 두 배로 진하다.", category: "wisdom", language: "ko" },
  // ── 인생과 의미 / Life ─────────────────────────
  { id: "cu_ko_476", text: "인생은 속도가 아니라 방향이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_477", text: "가장 아까운 시간은 남의 인생을 부러워하는 시간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_478", text: "의미는 발견되는 것이 아니라 만들어지는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_479", text: "무엇을 남길지 생각하면 오늘이 달라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_480", text: "잘 사는 것은 잘 선택하는 일의 반복이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_481", text: "삶의 크기는 감당한 책임의 크기와 같다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_482", text: "끝을 생각하면 사소한 것에 덜 흔들린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_483", text: "오늘 하루가 인생의 축소판이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_484", text: "무엇을 하느냐보다 왜 하느냐가 오래간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_485", text: "가장 큰 성공은 자기다운 삶을 사는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_486", text: "누군가에게 도움이 된 하루는 헛되지 않다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_487", text: "삶은 계획대로 되지 않지만 방향대로는 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_488", text: "가진 것보다 나눈 것이 오래 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_489", text: "후회 없는 삶이 아니라 후회를 줄이는 삶을 살라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_490", text: "늦은 나이는 없다. 늦은 결심만 있을 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_491", text: "잘 산 하루가 모여 잘 산 인생이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_492", text: "남과 다른 길을 가면 남과 다른 풍경을 본다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_493", text: "사랑하는 일에 시간을 쓰는 것이 최고의 사치다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_494", text: "고통은 지나가지만 배움은 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_495", text: "가장 소중한 것들은 대개 조용히 곁에 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_496", text: "누구의 인생도 완벽하지 않다. 다만 각자 다를 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_497", text: "삶은 한 번뿐이지만 매일 새로 시작할 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_498", text: "지금 이 순간이 언젠가 그리워질 시절이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_499", text: "어떻게 기억될지가 어떻게 살지를 알려 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_500", text: "살아 있다는 것 자체가 아직 기회가 남았다는 뜻이다.", category: "wisdom", language: "ko" },
];
