/**
 * 자동 생성 파일 — 직접 수정하지 마세요.
 * 원본: motivational_quotes_500_4languages.csv ("Espanol" 열)
 * 재생성: node scripts/gen-curated-quotes.mjs
 *
 * 위인 어록이 아닌 무명(작자 미상) 잠언 풀. author 없이 category="wisdom" 으로만 태깅된다.
 */
import type { FamousQuoteSeed } from "@/lib/famousQuotesSeed";

export const CURATED_QUOTES_ES: ReadonlyArray<FamousQuoteSeed> = [
  // ── 시작과 첫걸음 / Beginnings ─────────────────────────
  { id: "cu_es_001", text: "Si esperas el momento perfecto, nunca empezarás.", category: "wisdom", language: "en" },
  { id: "cu_es_002", text: "Un pequeño comienzo hoy marca una gran diferencia mañana.", category: "wisdom", language: "en" },
  { id: "cu_es_003", text: "El primer paso siempre es el más pesado y el más importante.", category: "wisdom", language: "en" },
  { id: "cu_es_004", text: "No empiezas porque estás listo; te vuelves listo al empezar.", category: "wisdom", language: "en" },
  { id: "cu_es_005", text: "El momento en que crees que es tarde es el más temprano que te queda.", category: "wisdom", language: "en" },
  { id: "cu_es_006", text: "Lo que nunca empiezas ni siquiera puede fracasar.", category: "wisdom", language: "en" },
  { id: "cu_es_007", text: "Las puertas grandes se abren con llaves pequeñas.", category: "wisdom", language: "en" },
  { id: "cu_es_008", text: "La semilla que no siembras hoy no crecerá mañana.", category: "wisdom", language: "en" },
  { id: "cu_es_009", text: "Empezar es otro nombre para el valor.", category: "wisdom", language: "en" },
  { id: "cu_es_010", text: "Quien da un paso llega más lejos que quien estudia el mapa.", category: "wisdom", language: "en" },
  { id: "cu_es_011", text: "Cómo abres el día se convierte en cómo abres la vida.", category: "wisdom", language: "en" },
  { id: "cu_es_012", text: "El hábito de aplazar el comienzo es el costo más caro.", category: "wisdom", language: "en" },
  { id: "cu_es_013", text: "Si no haces nada, nada sucede.", category: "wisdom", language: "en" },
  { id: "cu_es_014", text: "Un comienzo torpe vence a un plan perfecto.", category: "wisdom", language: "en" },
  { id: "cu_es_015", text: "Hoy es el día más joven del resto de tu vida.", category: "wisdom", language: "en" },
  { id: "cu_es_016", text: "Los caminos nuevos los crean quienes los recorren primero.", category: "wisdom", language: "en" },
  { id: "cu_es_017", text: "El miedo es mayor antes de empezar y menor después.", category: "wisdom", language: "en" },
  { id: "cu_es_018", text: "Los planes ocurren en el papel; el cambio, bajo tus pies.", category: "wisdom", language: "en" },
  { id: "cu_es_019", text: "Un uno por ciento cada día cambia quién eres en un año.", category: "wisdom", language: "en" },
  { id: "cu_es_020", text: "La oportunidad no llama; tú construyes la puerta.", category: "wisdom", language: "en" },
  { id: "cu_es_021", text: "Una decisión necesita un día; empezar solo necesita ahora.", category: "wisdom", language: "en" },
  { id: "cu_es_022", text: "Si empezar es la mitad, continuar es la otra mitad.", category: "wisdom", language: "en" },
  { id: "cu_es_023", text: "Nadie es bueno al principio; solo quien empieza llega a serlo.", category: "wisdom", language: "en" },
  { id: "cu_es_024", text: "La excusa de hoy seguirá ahí mañana.", category: "wisdom", language: "en" },
  { id: "cu_es_025", text: "Una acción vale más que cien promesas.", category: "wisdom", language: "en" },
  // ── 끈기와 인내 / Persistence ─────────────────────────
  { id: "cu_es_026", text: "El talento marca la salida; la constancia marca la meta.", category: "wisdom", language: "en" },
  { id: "cu_es_027", text: "Mientras no te rindas, el resultado aún no está decidido.", category: "wisdom", language: "en" },
  { id: "cu_es_028", text: "No hay forma de vencer a quien aparece todos los días.", category: "wisdom", language: "en" },
  { id: "cu_es_029", text: "La gota perfora la roca no por fuerza, sino por repetición.", category: "wisdom", language: "en" },
  { id: "cu_es_030", text: "El tramo más oscuro suele estar justo antes de la meta.", category: "wisdom", language: "en" },
  { id: "cu_es_031", text: "El crecimiento se esconde en la repetición aburrida.", category: "wisdom", language: "en" },
  { id: "cu_es_032", text: "No temas avanzar despacio; teme detenerte.", category: "wisdom", language: "en" },
  { id: "cu_es_033", text: "Resistir también es una habilidad.", category: "wisdom", language: "en" },
  { id: "cu_es_034", text: "Quien más dura termina siendo el mejor.", category: "wisdom", language: "en" },
  { id: "cu_es_035", text: "Un día de esfuerzo no se ve; un año no se puede ocultar.", category: "wisdom", language: "en" },
  { id: "cu_es_036", text: "El bambú pasa años echando raíces antes de crecer hacia el cielo.", category: "wisdom", language: "en" },
  { id: "cu_es_037", text: "El esfuerzo ininterrumpido genera intereses.", category: "wisdom", language: "en" },
  { id: "cu_es_038", text: "La oportunidad encuentra a quien sigue en pie al final.", category: "wisdom", language: "en" },
  { id: "cu_es_039", text: "El profesional actúa incluso cuando la motivación desaparece.", category: "wisdom", language: "en" },
  { id: "cu_es_040", text: "Un intento más: ese es todo el secreto.", category: "wisdom", language: "en" },
  { id: "cu_es_041", text: "El cansancio suele indicar que la meta está cerca.", category: "wisdom", language: "en" },
  { id: "cu_es_042", text: "Un árbol no crece cada día, pero engrosa cada año.", category: "wisdom", language: "en" },
  { id: "cu_es_043", text: "Cuanto más importante el trabajo, más tedio exige.", category: "wisdom", language: "en" },
  { id: "cu_es_044", text: "El éxito no llega de golpe; se acumula y luego se revela.", category: "wisdom", language: "en" },
  { id: "cu_es_045", text: "Si abandonas hoy, también desaparece el esfuerzo de ayer.", category: "wisdom", language: "en" },
  { id: "cu_es_046", text: "La capacidad de continuar es más rara que el talento.", category: "wisdom", language: "en" },
  { id: "cu_es_047", text: "Incluso una piedra pesada se parte tras cien golpes.", category: "wisdom", language: "en" },
  { id: "cu_es_048", text: "Camino a una meta, ningún paso es pequeño.", category: "wisdom", language: "en" },
  { id: "cu_es_049", text: "El músculo crece solo cuando falta el aliento.", category: "wisdom", language: "en" },
  { id: "cu_es_050", text: "Gana un día y ganarás un mes; gana un mes y ganarás la vida.", category: "wisdom", language: "en" },
  // ── 실패와 회복 / Resilience ─────────────────────────
  { id: "cu_es_051", text: "El fracaso no es un veredicto, es información.", category: "wisdom", language: "en" },
  { id: "cu_es_052", text: "Caer es un accidente; quedarse abajo es una elección.", category: "wisdom", language: "en" },
  { id: "cu_es_053", text: "La matrícula más valiosa es la que pagas al fracaso.", category: "wisdom", language: "en" },
  { id: "cu_es_054", text: "Si no repites el error, no fue un fracaso.", category: "wisdom", language: "en" },
  { id: "cu_es_055", text: "El fondo no es donde te hundes, sino donde te impulsas.", category: "wisdom", language: "en" },
  { id: "cu_es_056", text: "Las heridas se vuelven cicatrices, y las cicatrices, armadura.", category: "wisdom", language: "en" },
  { id: "cu_es_057", text: "Un solo fracaso no define a una persona.", category: "wisdom", language: "en" },
  { id: "cu_es_058", text: "Lo que reconstruyes tras el derrumbe es más firme.", category: "wisdom", language: "en" },
  { id: "cu_es_059", text: "Si temes al fracaso, pierdes también la lección.", category: "wisdom", language: "en" },
  { id: "cu_es_060", text: "La recuperación más rápida empieza mirando la causa con honestidad.", category: "wisdom", language: "en" },
  { id: "cu_es_061", text: "No recorrer mucho tiempo un mal camino también es un éxito.", category: "wisdom", language: "en" },
  { id: "cu_es_062", text: "El arrepentimiento retiene el pasado; la reflexión construye el futuro.", category: "wisdom", language: "en" },
  { id: "cu_es_063", text: "La adversidad no te pone a prueba; te revela.", category: "wisdom", language: "en" },
  { id: "cu_es_064", text: "Las raíces crecen más hondas donde pasó la tormenta.", category: "wisdom", language: "en" },
  { id: "cu_es_065", text: "La rapidez con que te levantas es tu verdadera medida.", category: "wisdom", language: "en" },
  { id: "cu_es_066", text: "El crecimiento empieza al admitir el error.", category: "wisdom", language: "en" },
  { id: "cu_es_067", text: "Todo experto es sobreviviente de innumerables fracasos.", category: "wisdom", language: "en" },
  { id: "cu_es_068", text: "Los caminos seguros enseñan poco.", category: "wisdom", language: "en" },
  { id: "cu_es_069", text: "Un intento fallido vale más que un día sin hacer nada.", category: "wisdom", language: "en" },
  { id: "cu_es_070", text: "Que se doblen tus rodillas, nunca tu rumbo.", category: "wisdom", language: "en" },
  { id: "cu_es_071", text: "La desesperación es un sentimiento, no un hecho.", category: "wisdom", language: "en" },
  { id: "cu_es_072", text: "La pérdida de hoy es el espacio libre de mañana.", category: "wisdom", language: "en" },
  { id: "cu_es_073", text: "Solo quien ha perdido sabe proteger.", category: "wisdom", language: "en" },
  { id: "cu_es_074", text: "El punto que creías el final suele ser el giro.", category: "wisdom", language: "en" },
  { id: "cu_es_075", text: "No maldigas dónde caíste; márcalo en tu mapa.", category: "wisdom", language: "en" },
  // ── 습관과 루틴 / Habits ─────────────────────────
  { id: "cu_es_076", text: "La voluntad flaquea; los hábitos permanecen.", category: "wisdom", language: "en" },
  { id: "cu_es_077", text: "Eres lo que repites.", category: "wisdom", language: "en" },
  { id: "cu_es_078", text: "Un buen hábito es un regalo a tu yo futuro.", category: "wisdom", language: "en" },
  { id: "cu_es_079", text: "Diez minutos al día cambian diez años.", category: "wisdom", language: "en" },
  { id: "cu_es_080", text: "Haz fácil el comienzo y la constancia llegará sola.", category: "wisdom", language: "en" },
  { id: "cu_es_081", text: "Cambiar el entorno supera a cualquier propósito.", category: "wisdom", language: "en" },
  { id: "cu_es_082", text: "Quien domina el día domina la vida.", category: "wisdom", language: "en" },
  { id: "cu_es_083", text: "Mejor un día sin faltar que un día perfecto.", category: "wisdom", language: "en" },
  { id: "cu_es_084", text: "Nunca faltes dos veces seguidas: la mejor regla que existe.", category: "wisdom", language: "en" },
  { id: "cu_es_085", text: "La primera hora marca el rumbo de todo el día.", category: "wisdom", language: "en" },
  { id: "cu_es_086", text: "Empieza pequeño si quieres que dure.", category: "wisdom", language: "en" },
  { id: "cu_es_087", text: "Un hábito que no mides no perdura.", category: "wisdom", language: "en" },
  { id: "cu_es_088", text: "La rutina no encierra la creatividad; la protege.", category: "wisdom", language: "en" },
  { id: "cu_es_089", text: "La repetición aburre; sus resultados no.", category: "wisdom", language: "en" },
  { id: "cu_es_090", text: "Un mal hábito empieza como invitado y acaba como dueño.", category: "wisdom", language: "en" },
  { id: "cu_es_091", text: "Los propósitos se olvidan; los sistemas permanecen.", category: "wisdom", language: "en" },
  { id: "cu_es_092", text: "La elección de hoy es el ajuste por defecto de mañana.", category: "wisdom", language: "en" },
  { id: "cu_es_093", text: "Dejar un hábito vale más que sumar diez.", category: "wisdom", language: "en" },
  { id: "cu_es_094", text: "Haz primero lo que temes y el día se aligera.", category: "wisdom", language: "en" },
  { id: "cu_es_095", text: "Los hábitos se acumulan como el interés compuesto.", category: "wisdom", language: "en" },
  { id: "cu_es_096", text: "Misma hora, mismo lugar, mismo trabajo: eso es maestría.", category: "wisdom", language: "en" },
  { id: "cu_es_097", text: "No esperes la motivación; cumple el horario.", category: "wisdom", language: "en" },
  { id: "cu_es_098", text: "Cómo terminas el día es cómo empiezas el siguiente.", category: "wisdom", language: "en" },
  { id: "cu_es_099", text: "Rompe una regla pequeña y el gran plan se rompe.", category: "wisdom", language: "en" },
  { id: "cu_es_100", text: "Los buenos hábitos no quitan libertad; la crean.", category: "wisdom", language: "en" },
  // ── 시간과 우선순위 / Time ─────────────────────────
  { id: "cu_es_101", text: "El tiempo no se gestiona; se elige.", category: "wisdom", language: "en" },
  { id: "cu_es_102", text: "Decir que estás ocupado suele significar que no tienes prioridades.", category: "wisdom", language: "en" },
  { id: "cu_es_103", text: "Decidir qué no hacer es la estrategia.", category: "wisdom", language: "en" },
  { id: "cu_es_104", text: "Todos tienen el mismo día; no todos lo llenan igual.", category: "wisdom", language: "en" },
  { id: "cu_es_105", text: "Nunca dejes que lo urgente desplace a lo importante.", category: "wisdom", language: "en" },
  { id: "cu_es_106", text: "Cómo gastas tus horas revela lo que valoras.", category: "wisdom", language: "en" },
  { id: "cu_es_107", text: "El tiempo es lo único que no puedes recuperar.", category: "wisdom", language: "en" },
  { id: "cu_es_108", text: "Di sí a todo y no terminarás nada.", category: "wisdom", language: "en" },
  { id: "cu_es_109", text: "Decir que no es la forma más honesta de proteger tu tiempo.", category: "wisdom", language: "en" },
  { id: "cu_es_110", text: "El tú de mañana no estará más libre que el de hoy.", category: "wisdom", language: "en" },
  { id: "cu_es_111", text: "Una cosa a la vez es el camino más rápido.", category: "wisdom", language: "en" },
  { id: "cu_es_112", text: "Dedica tus mejores horas a lo más importante.", category: "wisdom", language: "en" },
  { id: "cu_es_113", text: "No te falta tiempo; te falta orden.", category: "wisdom", language: "en" },
  { id: "cu_es_114", text: "Si no planificas tu día, alguien lo hará por ti.", category: "wisdom", language: "en" },
  { id: "cu_es_115", text: "Procrastinar no ahorra tiempo; cobra intereses.", category: "wisdom", language: "en" },
  { id: "cu_es_116", text: "Una hora concentrada vale más que un día disperso.", category: "wisdom", language: "en" },
  { id: "cu_es_117", text: "Planificar no añade horas; elimina desperdicio.", category: "wisdom", language: "en" },
  { id: "cu_es_118", text: "Treinta minutos esta noche compran dos horas mañana.", category: "wisdom", language: "en" },
  { id: "cu_es_119", text: "Una fecha límite no es enemiga, sino tu colega más fiel.", category: "wisdom", language: "en" },
  { id: "cu_es_120", text: "Si quieres más tiempo, empieza por ordenar.", category: "wisdom", language: "en" },
  { id: "cu_es_121", text: "Divide bien el día y la vida se ensancha.", category: "wisdom", language: "en" },
  { id: "cu_es_122", text: "El tiempo de espera también es tu tiempo.", category: "wisdom", language: "en" },
  { id: "cu_es_123", text: "Estar ocupado no es lo mismo que lograr.", category: "wisdom", language: "en" },
  { id: "cu_es_124", text: "Diseña tu semana y cambiará tu año.", category: "wisdom", language: "en" },
  { id: "cu_es_125", text: "El desperdicio más caro es dudar sobre qué hacer.", category: "wisdom", language: "en" },
  // ── 자기 믿음 / Self-Belief ─────────────────────────
  { id: "cu_es_126", text: "Si no crees en ti, nadie lo hará por ti.", category: "wisdom", language: "en" },
  { id: "cu_es_127", text: "Vivir según el criterio ajeno es vivir la vida de otro.", category: "wisdom", language: "en" },
  { id: "cu_es_128", text: "Lo que te dices a ti mismo es lo que más perdura.", category: "wisdom", language: "en" },
  { id: "cu_es_129", text: "Tu valor no lo define la opinión de nadie.", category: "wisdom", language: "en" },
  { id: "cu_es_130", text: "La confianza nace de intentar, no de triunfar.", category: "wisdom", language: "en" },
  { id: "cu_es_131", text: "Compararse es la forma más silenciosa de dejar de crecer.", category: "wisdom", language: "en" },
  { id: "cu_es_132", text: "La mayoría de tus límites los pones tú.", category: "wisdom", language: "en" },
  { id: "cu_es_133", text: "La fuerza viene de cumplir las promesas que te haces.", category: "wisdom", language: "en" },
  { id: "cu_es_134", text: "No bajes la voz; tu historia merece ser escuchada.", category: "wisdom", language: "en" },
  { id: "cu_es_135", text: "Ser diferente no es ser menos.", category: "wisdom", language: "en" },
  { id: "cu_es_136", text: "Nadie conoce tu potencial como tú.", category: "wisdom", language: "en" },
  { id: "cu_es_137", text: "Cuidarte no es egoísmo, es responsabilidad.", category: "wisdom", language: "en" },
  { id: "cu_es_138", text: "Reconocer lo que te falta también es confianza.", category: "wisdom", language: "en" },
  { id: "cu_es_139", text: "Ya eres alguien que tu yo del pasado deseaba ser.", category: "wisdom", language: "en" },
  { id: "cu_es_140", text: "Rechaza el elogio si quieres, nunca el logro.", category: "wisdom", language: "en" },
  { id: "cu_es_141", text: "La confianza en uno mismo mantiene el rumbo entre el ruido.", category: "wisdom", language: "en" },
  { id: "cu_es_142", text: "Quien más duro es consigo mismo crece más lento.", category: "wisdom", language: "en" },
  { id: "cu_es_143", text: "Tu ritmo es tu camino.", category: "wisdom", language: "en" },
  { id: "cu_es_144", text: "Cuando dudes, mira cuánto has avanzado.", category: "wisdom", language: "en" },
  { id: "cu_es_145", text: "No necesitas ser perfecto para empezar.", category: "wisdom", language: "en" },
  { id: "cu_es_146", text: "El éxito ajeno no es tu fracaso.", category: "wisdom", language: "en" },
  { id: "cu_es_147", text: "La confianza propia es la suma de pequeñas promesas cumplidas.", category: "wisdom", language: "en" },
  { id: "cu_es_148", text: "Tu historia aún no está ni a la mitad.", category: "wisdom", language: "en" },
  { id: "cu_es_149", text: "La calificación no se otorga; se construye.", category: "wisdom", language: "en" },
  { id: "cu_es_150", text: "Quien se anima a sí mismo llega hasta el final.", category: "wisdom", language: "en" },
  // ── 성장과 배움 / Growth ─────────────────────────
  { id: "cu_es_151", text: "Aprender comienza al admitir que no sabes.", category: "wisdom", language: "en" },
  { id: "cu_es_152", text: "Si eres mejor que ayer, hoy fue un éxito.", category: "wisdom", language: "en" },
  { id: "cu_es_153", text: "La incomodidad es la puerta del crecimiento.", category: "wisdom", language: "en" },
  { id: "cu_es_154", text: "El tamaño de tus preguntas define tu crecimiento.", category: "wisdom", language: "en" },
  { id: "cu_es_155", text: "Se aprende más cuando se enseña.", category: "wisdom", language: "en" },
  { id: "cu_es_156", text: "Aprender no tiene edad de jubilación.", category: "wisdom", language: "en" },
  { id: "cu_es_157", text: "La habilidad es la distancia entre saber y hacer.", category: "wisdom", language: "en" },
  { id: "cu_es_158", text: "En lo familiar no hay nada nuevo.", category: "wisdom", language: "en" },
  { id: "cu_es_159", text: "La crítica es amarga, pero es el camino más corto.", category: "wisdom", language: "en" },
  { id: "cu_es_160", text: "El mismo libro leído en otro momento es otro libro.", category: "wisdom", language: "en" },
  { id: "cu_es_161", text: "El crecimiento no es una línea; es una escalera.", category: "wisdom", language: "en" },
  { id: "cu_es_162", text: "El conocimiento sin uso no es conocimiento.", category: "wisdom", language: "en" },
  { id: "cu_es_163", text: "Rodearte de gente mejor es la escuela más rápida.", category: "wisdom", language: "en" },
  { id: "cu_es_164", text: "La imitación es el primer ejercicio de la creación.", category: "wisdom", language: "en" },
  { id: "cu_es_165", text: "La torpeza del principiante no es vergüenza, es prueba.", category: "wisdom", language: "en" },
  { id: "cu_es_166", text: "La capacidad de aceptar críticas construye habilidad.", category: "wisdom", language: "en" },
  { id: "cu_es_167", text: "Envejeces desde el instante en que dejas de aprender.", category: "wisdom", language: "en" },
  { id: "cu_es_168", text: "El tiempo da profundidad; la curiosidad, amplitud.", category: "wisdom", language: "en" },
  { id: "cu_es_169", text: "La experiencia sin registrar se conserva a medias.", category: "wisdom", language: "en" },
  { id: "cu_es_170", text: "Toda especialidad empezó como una palabra desconocida.", category: "wisdom", language: "en" },
  { id: "cu_es_171", text: "Aprender es tanto vaciar como llenar.", category: "wisdom", language: "en" },
  { id: "cu_es_172", text: "Un libro difícil permanece más que uno fácil.", category: "wisdom", language: "en" },
  { id: "cu_es_173", text: "Para crecer, pon junto a lo que dominas algo que no dominas.", category: "wisdom", language: "en" },
  { id: "cu_es_174", text: "Solo lo sabes de verdad si puedes explicarlo mañana.", category: "wisdom", language: "en" },
  { id: "cu_es_175", text: "La experiencia viene de la reflexión, no del tiempo.", category: "wisdom", language: "en" },
  // ── 목표와 비전 / Vision ─────────────────────────
  { id: "cu_es_176", text: "Sin destino, ningún viento es favorable.", category: "wisdom", language: "en" },
  { id: "cu_es_177", text: "Una meta se vuelve plan al escribirse.", category: "wisdom", language: "en" },
  { id: "cu_es_178", text: "Los grandes sueños se construyen con pequeños plazos.", category: "wisdom", language: "en" },
  { id: "cu_es_179", text: "Si sabes adónde vas, la velocidad importa menos.", category: "wisdom", language: "en" },
  { id: "cu_es_180", text: "Una meta que no puedes medir es solo un deseo.", category: "wisdom", language: "en" },
  { id: "cu_es_181", text: "No bajes la meta; cambia el método.", category: "wisdom", language: "en" },
  { id: "cu_es_182", text: "La visión da sentido a la dureza de hoy.", category: "wisdom", language: "en" },
  { id: "cu_es_183", text: "Persigue la meta de otro y llegar te dejará vacío.", category: "wisdom", language: "en" },
  { id: "cu_es_184", text: "Las metas dan dirección; los hábitos, el motor.", category: "wisdom", language: "en" },
  { id: "cu_es_185", text: "Piensa en diez años y la decisión de hoy será fácil.", category: "wisdom", language: "en" },
  { id: "cu_es_186", text: "Demasiadas metas equivalen a ninguna.", category: "wisdom", language: "en" },
  { id: "cu_es_187", text: "Decide quién quieres ser antes de qué quieres tener.", category: "wisdom", language: "en" },
  { id: "cu_es_188", text: "Deja que el plan cambie, pero mantén el rumbo.", category: "wisdom", language: "en" },
  { id: "cu_es_189", text: "Una meta visible produce resultados visibles.", category: "wisdom", language: "en" },
  { id: "cu_es_190", text: "Solo las metas que parecen inalcanzables te hacen crecer.", category: "wisdom", language: "en" },
  { id: "cu_es_191", text: "Divide la meta y el miedo se divide con ella.", category: "wisdom", language: "en" },
  { id: "cu_es_192", text: "Cambias al decidir, no al lograr.", category: "wisdom", language: "en" },
  { id: "cu_es_193", text: "El esfuerzo sin meta gira en el sitio como una rueda.", category: "wisdom", language: "en" },
  { id: "cu_es_194", text: "La meta más peligrosa es la demasiado fácil.", category: "wisdom", language: "en" },
  { id: "cu_es_195", text: "Anuncia tu meta y llegará la responsabilidad.", category: "wisdom", language: "en" },
  { id: "cu_es_196", text: "Las metas diarias sostienen la meta de una vida.", category: "wisdom", language: "en" },
  { id: "cu_es_197", text: "Si no sabes qué quieres, nada te bastará.", category: "wisdom", language: "en" },
  { id: "cu_es_198", text: "La meta es el mapa; la ejecución, los zapatos.", category: "wisdom", language: "en" },
  { id: "cu_es_199", text: "Imagina el final antes de empezar.", category: "wisdom", language: "en" },
  { id: "cu_es_200", text: "Incluso una meta no alcanzada te lleva a algún lugar.", category: "wisdom", language: "en" },
  // ── 용기와 두려움 / Courage ─────────────────────────
  { id: "cu_es_201", text: "El valor no es ausencia de miedo, sino caminar con él.", category: "wisdom", language: "en" },
  { id: "cu_es_202", text: "El mayor riesgo es no arriesgar nada.", category: "wisdom", language: "en" },
  { id: "cu_es_203", text: "El miedo suele vivir solo en la imaginación.", category: "wisdom", language: "en" },
  { id: "cu_es_204", text: "Lo que quieres evitar suele ser lo que debes hacer.", category: "wisdom", language: "en" },
  { id: "cu_es_205", text: "El valor crece con el uso, como un músculo.", category: "wisdom", language: "en" },
  { id: "cu_es_206", text: "Ser rechazado no es desaparecer.", category: "wisdom", language: "en" },
  { id: "cu_es_207", text: "Si no preguntas, la respuesta siempre es no.", category: "wisdom", language: "en" },
  { id: "cu_es_208", text: "Di tu miedo en voz alta y la mitad se irá.", category: "wisdom", language: "en" },
  { id: "cu_es_209", text: "La zona de confort es cómoda, pero allí nada crece.", category: "wisdom", language: "en" },
  { id: "cu_es_210", text: "El arrepentimiento dura más que el fracaso.", category: "wisdom", language: "en" },
  { id: "cu_es_211", text: "El valor no es un grito; es intentarlo otra vez en silencio.", category: "wisdom", language: "en" },
  { id: "cu_es_212", text: "Solo los caminos desconocidos ofrecen paisajes nuevos.", category: "wisdom", language: "en" },
  { id: "cu_es_213", text: "Las opiniones ajenas no pagan tu vida.", category: "wisdom", language: "en" },
  { id: "cu_es_214", text: "Tolerar la incertidumbre crea oportunidades.", category: "wisdom", language: "en" },
  { id: "cu_es_215", text: "Sé valiente una vez y la próxima será más fácil.", category: "wisdom", language: "en" },
  { id: "cu_es_216", text: "El miedo es una brújula; el crecimiento está donde apunta.", category: "wisdom", language: "en" },
  { id: "cu_es_217", text: "Calcula el riesgo, pero no te rindas al miedo.", category: "wisdom", language: "en" },
  { id: "cu_es_218", text: "Crecer es avanzar aun teniendo miedo.", category: "wisdom", language: "en" },
  { id: "cu_es_219", text: "El mayor espacio está donde nadie se ha atrevido.", category: "wisdom", language: "en" },
  { id: "cu_es_220", text: "Duelen más los días sin intentar que los de fracaso.", category: "wisdom", language: "en" },
  { id: "cu_es_221", text: "El valor nace de la decisión, no de la certeza.", category: "wisdom", language: "en" },
  { id: "cu_es_222", text: "Si temes parecer débil, nunca serás fuerte.", category: "wisdom", language: "en" },
  { id: "cu_es_223", text: "Todo gran cambio empieza con una conversación incómoda.", category: "wisdom", language: "en" },
  { id: "cu_es_224", text: "Ponle nombre al miedo y se encogerá.", category: "wisdom", language: "en" },
  { id: "cu_es_225", text: "Un día valiente es más largo que un año corriente.", category: "wisdom", language: "en" },
  // ── 태도와 마인드셋 / Mindset ─────────────────────────
  { id: "cu_es_226", text: "La misma situación da resultados distintos según cómo la interpretes.", category: "wisdom", language: "en" },
  { id: "cu_es_227", text: "Añade la palabra todavía a cada no puedo.", category: "wisdom", language: "en" },
  { id: "cu_es_228", text: "Si ves un problema solo como problema, solo queda el problema.", category: "wisdom", language: "en" },
  { id: "cu_es_229", text: "La actitud se nota antes que la capacidad.", category: "wisdom", language: "en" },
  { id: "cu_es_230", text: "Quejarse no cambia nada y te roba energía.", category: "wisdom", language: "en" },
  { id: "cu_es_231", text: "Gasta tus emociones solo en lo que puedes controlar.", category: "wisdom", language: "en" },
  { id: "cu_es_232", text: "La suerte se posa sobre una actitud preparada.", category: "wisdom", language: "en" },
  { id: "cu_es_233", text: "No todo tiene que salir a tu favor, y está bien.", category: "wisdom", language: "en" },
  { id: "cu_es_234", text: "La dirección de tus pensamientos guía tus pasos.", category: "wisdom", language: "en" },
  { id: "cu_es_235", text: "La humildad mantiene abierta la puerta del aprendizaje.", category: "wisdom", language: "en" },
  { id: "cu_es_236", text: "El poder vuelve cuando dejas de culpar a otros.", category: "wisdom", language: "en" },
  { id: "cu_es_237", text: "Baja tus expectativas y bajarán la decepción y el esfuerzo.", category: "wisdom", language: "en" },
  { id: "cu_es_238", text: "El optimismo no ignora la realidad; busca una salida.", category: "wisdom", language: "en" },
  { id: "cu_es_239", text: "Para quien quiere aprender, todos son maestros.", category: "wisdom", language: "en" },
  { id: "cu_es_240", text: "Ama el proceso más que el resultado y durarás.", category: "wisdom", language: "en" },
  { id: "cu_es_241", text: "Las palabras que repites moldean tu vida.", category: "wisdom", language: "en" },
  { id: "cu_es_242", text: "La calma es cuestión de mente, no de tiempo.", category: "wisdom", language: "en" },
  { id: "cu_es_243", text: "Un mal día no significa una mala vida.", category: "wisdom", language: "en" },
  { id: "cu_es_244", text: "La sabiduría es saber qué aceptar y qué cambiar.", category: "wisdom", language: "en" },
  { id: "cu_es_245", text: "El tiempo enfadado es tiempo que no resuelve.", category: "wisdom", language: "en" },
  { id: "cu_es_246", text: "Quien cuenta lo que tiene termina teniendo más.", category: "wisdom", language: "en" },
  { id: "cu_es_247", text: "La madurez es elegir en vez de reaccionar.", category: "wisdom", language: "en" },
  { id: "cu_es_248", text: "No te avergüence ignorar; avergüénzate de no preguntar.", category: "wisdom", language: "en" },
  { id: "cu_es_249", text: "Que te den la tarea difícil significa que confían en ti.", category: "wisdom", language: "en" },
  { id: "cu_es_250", text: "Cambia tu forma de pensar y cambiará lo que ves.", category: "wisdom", language: "en" },
  // ── 실행과 행동 / Action ─────────────────────────
  { id: "cu_es_251", text: "Las ideas abundan; la ejecución escasea.", category: "wisdom", language: "en" },
  { id: "cu_es_252", text: "Un día basta para saber quién piensa y quién actúa.", category: "wisdom", language: "en" },
  { id: "cu_es_253", text: "Solo un barco en movimiento puede cambiar de rumbo.", category: "wisdom", language: "en" },
  { id: "cu_es_254", text: "Un borrador vence a una obra maestra porque existe.", category: "wisdom", language: "en" },
  { id: "cu_es_255", text: "El perfeccionismo es la pereza mejor disfrazada.", category: "wisdom", language: "en" },
  { id: "cu_es_256", text: "La acción de hoy es la confianza de mañana.", category: "wisdom", language: "en" },
  { id: "cu_es_257", text: "Aplazar una decisión también es decidir.", category: "wisdom", language: "en" },
  { id: "cu_es_258", text: "Una hora de acción enseña más que un mes de planes.", category: "wisdom", language: "en" },
  { id: "cu_es_259", text: "Empieza pequeño y corrige rápido.", category: "wisdom", language: "en" },
  { id: "cu_es_260", text: "Las palabras hacen planes; los actos, resultados.", category: "wisdom", language: "en" },
  { id: "cu_es_261", text: "Vale más una mano que trabaja que una mente que quiere.", category: "wisdom", language: "en" },
  { id: "cu_es_262", text: "Solo tras intentarlo sabes cuál es el problema.", category: "wisdom", language: "en" },
  { id: "cu_es_263", text: "El noventa por ciento de las dudas desaparece al actuar.", category: "wisdom", language: "en" },
  { id: "cu_es_264", text: "Nadie ejecutará tu plan por ti.", category: "wisdom", language: "en" },
  { id: "cu_es_265", text: "El botón de inicio siempre está en tu mano.", category: "wisdom", language: "en" },
  { id: "cu_es_266", text: "Un producto sin lanzar es un producto que no existe.", category: "wisdom", language: "en" },
  { id: "cu_es_267", text: "Piensa cinco veces y actúa una, y llegarás tarde.", category: "wisdom", language: "en" },
  { id: "cu_es_268", text: "La acción es la única cura para la ansiedad.", category: "wisdom", language: "en" },
  { id: "cu_es_269", text: "Quien termina es más valioso que quien empieza.", category: "wisdom", language: "en" },
  { id: "cu_es_270", text: "Una pequeña acción vence a una gran convicción.", category: "wisdom", language: "en" },
  { id: "cu_es_271", text: "Publícalo primero; se completa con las reacciones.", category: "wisdom", language: "en" },
  { id: "cu_es_272", text: "Una idea que solo vive en notas está muerta.", category: "wisdom", language: "en" },
  { id: "cu_es_273", text: "La dificultad siempre se exagera hasta que lo intentas.", category: "wisdom", language: "en" },
  { id: "cu_es_274", text: "Ahora mismo siempre es el mejor momento.", category: "wisdom", language: "en" },
  { id: "cu_es_275", text: "Termina una cosa al día y serán trescientas sesenta y cinco al año.", category: "wisdom", language: "en" },
  // ── 집중과 몰입 / Focus ─────────────────────────
  { id: "cu_es_276", text: "Quitar distracciones es más rápido que sumar habilidad.", category: "wisdom", language: "en" },
  { id: "cu_es_277", text: "Una hora concentrada vence a un día disperso.", category: "wisdom", language: "en" },
  { id: "cu_es_278", text: "Quien lo intenta todo no profundiza en nada.", category: "wisdom", language: "en" },
  { id: "cu_es_279", text: "La concentración no es talento; es entrenamiento.", category: "wisdom", language: "en" },
  { id: "cu_es_280", text: "Apagar las notificaciones es más fácil que forjar voluntad.", category: "wisdom", language: "en" },
  { id: "cu_es_281", text: "Los resultados profundos nacen del tiempo sin interrupciones.", category: "wisdom", language: "en" },
  { id: "cu_es_282", text: "La multitarea es el modo más rápido de hacer todo mal.", category: "wisdom", language: "en" },
  { id: "cu_es_283", text: "El desorden del escritorio es desorden mental.", category: "wisdom", language: "en" },
  { id: "cu_es_284", text: "Para empezar no necesitas motivación, sino cinco minutos.", category: "wisdom", language: "en" },
  { id: "cu_es_285", text: "El flujo llega cuando te olvidas de ti mismo.", category: "wisdom", language: "en" },
  { id: "cu_es_286", text: "Termina uno y pasa al siguiente: es lo más rápido.", category: "wisdom", language: "en" },
  { id: "cu_es_287", text: "La atención no se guarda; hay que gastarla hoy.", category: "wisdom", language: "en" },
  { id: "cu_es_288", text: "El trabajo importante tiene derecho a no ser interrumpido.", category: "wisdom", language: "en" },
  { id: "cu_es_289", text: "Cuantas menos opciones, más lejos llegas.", category: "wisdom", language: "en" },
  { id: "cu_es_290", text: "Una cosa bien hecha vale más que diez a medias.", category: "wisdom", language: "en" },
  { id: "cu_es_291", text: "La atención es tu activo más caro.", category: "wisdom", language: "en" },
  { id: "cu_es_292", text: "Una revisión rápida rompe una hora de concentración.", category: "wisdom", language: "en" },
  { id: "cu_es_293", text: "Las mejores ideas nacen en el silencio.", category: "wisdom", language: "en" },
  { id: "cu_es_294", text: "Elegir qué mirar es elegir qué obtendrás.", category: "wisdom", language: "en" },
  { id: "cu_es_295", text: "La distracción no es falta de voluntad, sino de diseño.", category: "wisdom", language: "en" },
  { id: "cu_es_296", text: "Un paso a la vez es siempre lo más seguro.", category: "wisdom", language: "en" },
  { id: "cu_es_297", text: "Pon primero lo grande; lo demás encajará después.", category: "wisdom", language: "en" },
  { id: "cu_es_298", text: "Cuanto más clara la meta, más débil la tentación.", category: "wisdom", language: "en" },
  { id: "cu_es_299", text: "Descansar es parte de concentrarse.", category: "wisdom", language: "en" },
  { id: "cu_es_300", text: "Cuando terminas lo importante, lo demás encuentra su lugar.", category: "wisdom", language: "en" },
  // ── 규율과 절제 / Discipline ─────────────────────────
  { id: "cu_es_301", text: "La libertad empieza donde termina la disciplina.", category: "wisdom", language: "en" },
  { id: "cu_es_302", text: "El poder de contenerte te da lo que deseas.", category: "wisdom", language: "en" },
  { id: "cu_es_303", text: "La disciplina es la amabilidad de hoy hacia tu yo futuro.", category: "wisdom", language: "en" },
  { id: "cu_es_304", text: "No dejes que el ánimo gobierne tus decisiones.", category: "wisdom", language: "en" },
  { id: "cu_es_305", text: "La moderación es elección, no carencia.", category: "wisdom", language: "en" },
  { id: "cu_es_306", text: "Elige el camino fácil y la vida se volverá difícil.", category: "wisdom", language: "en" },
  { id: "cu_es_307", text: "La persona más fuerte es la que se gobierna a sí misma.", category: "wisdom", language: "en" },
  { id: "cu_es_308", text: "La moderación diaria construye libertad de por vida.", category: "wisdom", language: "en" },
  { id: "cu_es_309", text: "La disciplina es hacerlo también los días sin ganas.", category: "wisdom", language: "en" },
  { id: "cu_es_310", text: "Una excepción llama a otras diez.", category: "wisdom", language: "en" },
  { id: "cu_es_311", text: "Fija un criterio y dejarás de decidir cada vez.", category: "wisdom", language: "en" },
  { id: "cu_es_312", text: "El impulso es breve; el arrepentimiento, largo.", category: "wisdom", language: "en" },
  { id: "cu_es_313", text: "Repite decisiones fáciles y tendrás una vida difícil.", category: "wisdom", language: "en" },
  { id: "cu_es_314", text: "La contención no es privación; es elegir algo mayor.", category: "wisdom", language: "en" },
  { id: "cu_es_315", text: "Una vida con reglas es una vida más holgada.", category: "wisdom", language: "en" },
  { id: "cu_es_316", text: "No dependas de la voluntad; construye una estructura.", category: "wisdom", language: "en" },
  { id: "cu_es_317", text: "No luches contra el sueño; adminístralo.", category: "wisdom", language: "en" },
  { id: "cu_es_318", text: "Un día de disciplina crea una década de resultados.", category: "wisdom", language: "en" },
  { id: "cu_es_319", text: "La batalla más difícil es la que ganas contra ti mismo.", category: "wisdom", language: "en" },
  { id: "cu_es_320", text: "No procrastinar es la mejor estrategia de inversión.", category: "wisdom", language: "en" },
  { id: "cu_es_321", text: "Solo el disciplinado puede sostener una gran oportunidad.", category: "wisdom", language: "en" },
  { id: "cu_es_322", text: "Tu día se llena con lo que permites.", category: "wisdom", language: "en" },
  { id: "cu_es_323", text: "Comprende un deseo y será más fácil dominarlo.", category: "wisdom", language: "en" },
  { id: "cu_es_324", text: "El tiempo que soportas la incomodidad es tiempo de crecimiento.", category: "wisdom", language: "en" },
  { id: "cu_es_325", text: "Quien respeta la hora también guarda la confianza.", category: "wisdom", language: "en" },
  // ── 사람과 관계 / Relationships ─────────────────────────
  { id: "cu_es_326", text: "Solo llegas rápido; acompañado llegas lejos.", category: "wisdom", language: "en" },
  { id: "cu_es_327", text: "Te conviertes en el promedio de tus cinco cercanos.", category: "wisdom", language: "en" },
  { id: "cu_es_328", text: "La confianza tarda años en construirse y segundos en romperse.", category: "wisdom", language: "en" },
  { id: "cu_es_329", text: "Quien escucha termina ganando más.", category: "wisdom", language: "en" },
  { id: "cu_es_330", text: "Recuerda la ayuda recibida; olvida la que diste.", category: "wisdom", language: "en" },
  { id: "cu_es_331", text: "No intentes vencer a la gente; vence al problema.", category: "wisdom", language: "en" },
  { id: "cu_es_332", text: "Las buenas relaciones se mantienen con sinceridad, no con tiempo.", category: "wisdom", language: "en" },
  { id: "cu_es_333", text: "A quién conoces importa tanto como lo que sabes.", category: "wisdom", language: "en" },
  { id: "cu_es_334", text: "Quien da primero acaba recibiendo más.", category: "wisdom", language: "en" },
  { id: "cu_es_335", text: "Habla menos y crecerá la confianza.", category: "wisdom", language: "en" },
  { id: "cu_es_336", text: "Pregunta en vez de culpar y la relación sobrevivirá.", category: "wisdom", language: "en" },
  { id: "cu_es_337", text: "Cumplir promesas es el mejor marketing.", category: "wisdom", language: "en" },
  { id: "cu_es_338", text: "Quien conserva a las personas termina triunfando.", category: "wisdom", language: "en" },
  { id: "cu_es_339", text: "Escuchar es la habilidad de liderazgo más subestimada.", category: "wisdom", language: "en" },
  { id: "cu_es_340", text: "La gratitud existe solo cuando se expresa.", category: "wisdom", language: "en" },
  { id: "cu_es_341", text: "Ayudar a otro a crecer es lo que más te hace crecer.", category: "wisdom", language: "en" },
  { id: "cu_es_342", text: "Una disculpa se encarece cuanto más tarda.", category: "wisdom", language: "en" },
  { id: "cu_es_343", text: "Si quieres ser recordado, recuerda primero los nombres.", category: "wisdom", language: "en" },
  { id: "cu_es_344", text: "Quien intenta agradar a todos no agrada a nadie.", category: "wisdom", language: "en" },
  { id: "cu_es_345", text: "Los buenos compañeros son el mejor beneficio.", category: "wisdom", language: "en" },
  { id: "cu_es_346", text: "Mantener distancia también protege la relación.", category: "wisdom", language: "en" },
  { id: "cu_es_347", text: "Quien celebra el éxito ajeno llega lejos.", category: "wisdom", language: "en" },
  { id: "cu_es_348", text: "El tono se recuerda más que el contenido.", category: "wisdom", language: "en" },
  { id: "cu_es_349", text: "Quien solo quiere brillar solo termina solo.", category: "wisdom", language: "en" },
  { id: "cu_es_350", text: "Puedes discrepar y aun así respetar a la persona.", category: "wisdom", language: "en" },
  // ── 리더십과 영향력 / Leadership ─────────────────────────
  { id: "cu_es_351", text: "El liderazgo es una actitud, no un cargo.", category: "wisdom", language: "en" },
  { id: "cu_es_352", text: "Quien se mueve primero se convierte en líder.", category: "wisdom", language: "en" },
  { id: "cu_es_353", text: "Lidera con la espalda, no con la boca.", category: "wisdom", language: "en" },
  { id: "cu_es_354", text: "Un buen líder comparte el mérito y asume la culpa.", category: "wisdom", language: "en" },
  { id: "cu_es_355", text: "La gente no sigue órdenes; sigue la confianza.", category: "wisdom", language: "en" },
  { id: "cu_es_356", text: "Un equipo rinde según el estándar que permite su líder.", category: "wisdom", language: "en" },
  { id: "cu_es_357", text: "Un líder que pregunta crea un equipo que aprende.", category: "wisdom", language: "en" },
  { id: "cu_es_358", text: "La influencia se gana, no se exige.", category: "wisdom", language: "en" },
  { id: "cu_es_359", text: "Elogia en público; corrige en privado.", category: "wisdom", language: "en" },
  { id: "cu_es_360", text: "Formar personas es el mayor logro de un líder.", category: "wisdom", language: "en" },
  { id: "cu_es_361", text: "La calma del líder es la red de seguridad del equipo.", category: "wisdom", language: "en" },
  { id: "cu_es_362", text: "El ejemplo es más fuerte que cien sermones.", category: "wisdom", language: "en" },
  { id: "cu_es_363", text: "El mejor líder se vuelve prescindible.", category: "wisdom", language: "en" },
  { id: "cu_es_364", text: "Comparte la autoridad; mantén el estándar.", category: "wisdom", language: "en" },
  { id: "cu_es_365", text: "La agenda del líder revela las prioridades de la organización.", category: "wisdom", language: "en" },
  { id: "cu_es_366", text: "Un equipo sano es aquel donde las malas noticias llegan rápido.", category: "wisdom", language: "en" },
  { id: "cu_es_367", text: "El líder más peligroso es el que no decide.", category: "wisdom", language: "en" },
  { id: "cu_es_368", text: "Un líder da dirección más que respuestas.", category: "wisdom", language: "en" },
  { id: "cu_es_369", text: "Solo quien inspira confianza puede liderar el cambio.", category: "wisdom", language: "en" },
  { id: "cu_es_370", text: "Un líder que admite errores fortalece al equipo.", category: "wisdom", language: "en" },
  { id: "cu_es_371", text: "Cumplir lo dicho es todo el liderazgo.", category: "wisdom", language: "en" },
  { id: "cu_es_372", text: "Confía en la gente y crecerá a la altura.", category: "wisdom", language: "en" },
  { id: "cu_es_373", text: "Pregunta primero a la persona más callada.", category: "wisdom", language: "en" },
  { id: "cu_es_374", text: "Cuando el líder deja de crecer, la organización también.", category: "wisdom", language: "en" },
  { id: "cu_es_375", text: "En la influencia importa la dirección, no el tamaño.", category: "wisdom", language: "en" },
  // ── 창의와 혁신 / Creativity ─────────────────────────
  { id: "cu_es_376", text: "Lo nuevo surge de combinaciones inesperadas.", category: "wisdom", language: "en" },
  { id: "cu_es_377", text: "Cien malas ideas traen una buena.", category: "wisdom", language: "en" },
  { id: "cu_es_378", text: "Cambia la pregunta y cambiará la respuesta.", category: "wisdom", language: "en" },
  { id: "cu_es_379", text: "La creatividad es fruto del hábito, no de la inspiración.", category: "wisdom", language: "en" },
  { id: "cu_es_380", text: "Cuantas más restricciones, más creativa la solución.", category: "wisdom", language: "en" },
  { id: "cu_es_381", text: "Ver distinto vale más que mirar más fuerte.", category: "wisdom", language: "en" },
  { id: "cu_es_382", text: "Toda innovación pareció imprudente al principio.", category: "wisdom", language: "en" },
  { id: "cu_es_383", text: "Todo empieza al ver extraño un problema familiar.", category: "wisdom", language: "en" },
  { id: "cu_es_384", text: "Una idea que no anotas desaparece.", category: "wisdom", language: "en" },
  { id: "cu_es_385", text: "Quien se sitúa en la frontera ve cosas nuevas.", category: "wisdom", language: "en" },
  { id: "cu_es_386", text: "Un paseo genera mejores ideas que una reunión.", category: "wisdom", language: "en" },
  { id: "cu_es_387", text: "La innovación empieza dudando de la respuesta aceptada.", category: "wisdom", language: "en" },
  { id: "cu_es_388", text: "Los más creativos conectan campos distintos.", category: "wisdom", language: "en" },
  { id: "cu_es_389", text: "Tu primera versión siempre avergüenza. Hazla igual.", category: "wisdom", language: "en" },
  { id: "cu_es_390", text: "Una idea se prueba con la ejecución, no con la propiedad.", category: "wisdom", language: "en" },
  { id: "cu_es_391", text: "El mismo método que todos da el mismo resultado que todos.", category: "wisdom", language: "en" },
  { id: "cu_es_392", text: "La curiosidad es la herramienta más duradera.", category: "wisdom", language: "en" },
  { id: "cu_es_393", text: "Cuantas más ideas deseches, mejores serán las que queden.", category: "wisdom", language: "en" },
  { id: "cu_es_394", text: "El enemigo de la creación es la indiferencia, no la crítica.", category: "wisdom", language: "en" },
  { id: "cu_es_395", text: "Trabajar con gente distinta amplía tu pensamiento.", category: "wisdom", language: "en" },
  { id: "cu_es_396", text: "Debes conocer las reglas para romperlas.", category: "wisdom", language: "en" },
  { id: "cu_es_397", text: "La mejor idea suele aparecer en el segundo intento.", category: "wisdom", language: "en" },
  { id: "cu_es_398", text: "El conocimiento que parece inútil se conecta después.", category: "wisdom", language: "en" },
  { id: "cu_es_399", text: "Solo cuando la idea llega a tus manos puede probarse.", category: "wisdom", language: "en" },
  { id: "cu_es_400", text: "Imita lo suficiente y aparecerá tu propio camino.", category: "wisdom", language: "en" },
  // ── 돈과 부 / Wealth ─────────────────────────
  { id: "cu_es_401", text: "Conservar el dinero es más difícil que ganarlo.", category: "wisdom", language: "en" },
  { id: "cu_es_402", text: "Sin controlar el gasto, el ingreso no sirve.", category: "wisdom", language: "en" },
  { id: "cu_es_403", text: "La mejor compra es recuperar tu tiempo.", category: "wisdom", language: "en" },
  { id: "cu_es_404", text: "La riqueza nace de los hábitos, no de los ingresos.", category: "wisdom", language: "en" },
  { id: "cu_es_405", text: "La inversión más segura eres tú mismo.", category: "wisdom", language: "en" },
  { id: "cu_es_406", text: "Ahorrar pronto vence a ahorrar mucho y tarde.", category: "wisdom", language: "en" },
  { id: "cu_es_407", text: "La deuda gasta por anticipado tu libertad futura.", category: "wisdom", language: "en" },
  { id: "cu_es_408", text: "Recibes en proporción al valor que creas.", category: "wisdom", language: "en" },
  { id: "cu_es_409", text: "El dinero rápido suele irse rápido.", category: "wisdom", language: "en" },
  { id: "cu_es_410", text: "Invertir en lo que no entiendes es apostar.", category: "wisdom", language: "en" },
  { id: "cu_es_411", text: "La frugalidad es elección, no pobreza.", category: "wisdom", language: "en" },
  { id: "cu_es_412", text: "El dinero es buen sirviente y mal amo.", category: "wisdom", language: "en" },
  { id: "cu_es_413", text: "Un solo ingreso significa que un riesgo sostiene tu vida.", category: "wisdom", language: "en" },
  { id: "cu_es_414", text: "El interés compuesto no premia a los impacientes.", category: "wisdom", language: "en" },
  { id: "cu_es_415", text: "El gasto por comparación es el más caro.", category: "wisdom", language: "en" },
  { id: "cu_es_416", text: "El precio es lo que pagas; el valor, lo que obtienes.", category: "wisdom", language: "en" },
  { id: "cu_es_417", text: "El dinero que no registras se escapa.", category: "wisdom", language: "en" },
  { id: "cu_es_418", text: "La libertad financiera es el poder de decir que no.", category: "wisdom", language: "en" },
  { id: "cu_es_419", text: "Importa más lo rápido que aprendes que lo que ganas.", category: "wisdom", language: "en" },
  { id: "cu_es_420", text: "El verdadero rico sabe qué es suficiente.", category: "wisdom", language: "en" },
  { id: "cu_es_421", text: "Si no entiendes el riesgo, no conservarás la ganancia.", category: "wisdom", language: "en" },
  { id: "cu_es_422", text: "Ahorrar es defensa; invertir, ataque. Necesitas ambos.", category: "wisdom", language: "en" },
  { id: "cu_es_423", text: "Protege primero lo que el dinero no compra.", category: "wisdom", language: "en" },
  { id: "cu_es_424", text: "Los gastos pequeños repetidos asustan más que uno grande.", category: "wisdom", language: "en" },
  { id: "cu_es_425", text: "La gente exitosa suele invertir de forma aburrida.", category: "wisdom", language: "en" },
  // ── 건강과 균형 / Health ─────────────────────────
  { id: "cu_es_426", text: "La salud es el activo más subestimado hasta que se pierde.", category: "wisdom", language: "en" },
  { id: "cu_es_427", text: "Dormir no es pereza; es condición del rendimiento.", category: "wisdom", language: "en" },
  { id: "cu_es_428", text: "Descuida tu cuerpo y él marcará tu agenda.", category: "wisdom", language: "en" },
  { id: "cu_es_429", text: "Treinta minutos de caminata al día reducen días de enfermedad.", category: "wisdom", language: "en" },
  { id: "cu_es_430", text: "Descansar no es detenerse; es prepararse.", category: "wisdom", language: "en" },
  { id: "cu_es_431", text: "El logro se construye sobre la resistencia.", category: "wisdom", language: "en" },
  { id: "cu_es_432", text: "El agotamiento no castiga el esfuerzo; avisa del desequilibrio.", category: "wisdom", language: "en" },
  { id: "cu_es_433", text: "Comer despacio se convierte en vivir más.", category: "wisdom", language: "en" },
  { id: "cu_es_434", text: "Trabajo y vida no son balanza, sino ritmo.", category: "wisdom", language: "en" },
  { id: "cu_es_435", text: "No ignores las señales pequeñas de tu cuerpo.", category: "wisdom", language: "en" },
  { id: "cu_es_436", text: "El ejercicio es carga de hoy y ahorro de mañana.", category: "wisdom", language: "en" },
  { id: "cu_es_437", text: "El estrés no se elimina; se gestiona.", category: "wisdom", language: "en" },
  { id: "cu_es_438", text: "La recuperación del fin de semana crea el rendimiento semanal.", category: "wisdom", language: "en" },
  { id: "cu_es_439", text: "Las inversiones más fieles son dormir y beber agua a diario.", category: "wisdom", language: "en" },
  { id: "cu_es_440", text: "Descansar antes de enfermar es más barato que después.", category: "wisdom", language: "en" },
  { id: "cu_es_441", text: "Aparta la vista de la pantalla al menos una vez al día.", category: "wisdom", language: "en" },
  { id: "cu_es_442", text: "Caminar es la terapia más barata.", category: "wisdom", language: "en" },
  { id: "cu_es_443", text: "Un cuerpo tranquilo ordena la mente.", category: "wisdom", language: "en" },
  { id: "cu_es_444", text: "Un día excesivo cuesta tres de recuperación.", category: "wisdom", language: "en" },
  { id: "cu_es_445", text: "La cena en familia merece estar en la agenda.", category: "wisdom", language: "en" },
  { id: "cu_es_446", text: "Una afición no es un lujo; es mantenimiento.", category: "wisdom", language: "en" },
  { id: "cu_es_447", text: "El tiempo que tomas para respirar genera velocidad.", category: "wisdom", language: "en" },
  { id: "cu_es_448", text: "Quien descansa bien decide mejor.", category: "wisdom", language: "en" },
  { id: "cu_es_449", text: "Solo tienes un cuerpo para todo el viaje.", category: "wisdom", language: "en" },
  { id: "cu_es_450", text: "Cuanto más ocupado estés, más regular debe ser comer y dormir.", category: "wisdom", language: "en" },
  // ── 감사와 마음 / Gratitude ─────────────────────────
  { id: "cu_es_451", text: "Cuenta lo que tienes y la carencia se encoge.", category: "wisdom", language: "en" },
  { id: "cu_es_452", text: "La gratitud se vuelve fuerza al hacerse hábito.", category: "wisdom", language: "en" },
  { id: "cu_es_453", text: "Un día común es el día más anhelado para alguien.", category: "wisdom", language: "en" },
  { id: "cu_es_454", text: "Tu lista de gratitud debe superar la de quejas.", category: "wisdom", language: "en" },
  { id: "cu_es_455", text: "El agradecimiento tardío llega a medias.", category: "wisdom", language: "en" },
  { id: "cu_es_456", text: "Disfrutar lo pequeño define tu calidad de vida.", category: "wisdom", language: "en" },
  { id: "cu_es_457", text: "Deja de comparar y empezará la satisfacción.", category: "wisdom", language: "en" },
  { id: "cu_es_458", text: "Nada es obvio; solo nos hemos acostumbrado.", category: "wisdom", language: "en" },
  { id: "cu_es_459", text: "Un día que pasó sin daño también es un logro.", category: "wisdom", language: "en" },
  { id: "cu_es_460", text: "La gratitud ordena el pasado y aligera el futuro.", category: "wisdom", language: "en" },
  { id: "cu_es_461", text: "El esfuerzo de alguien hizo posible tu comodidad de hoy.", category: "wisdom", language: "en" },
  { id: "cu_es_462", text: "Un corazón generoso siempre tiene qué compartir.", category: "wisdom", language: "en" },
  { id: "cu_es_463", text: "Perdonar es para ti, no para el otro.", category: "wisdom", language: "en" },
  { id: "cu_es_464", text: "Termina el día con gratitud y el siguiente será más ligero.", category: "wisdom", language: "en" },
  { id: "cu_es_465", text: "Transmite la amabilidad que recibiste.", category: "wisdom", language: "en" },
  { id: "cu_es_466", text: "La alegría es cuestión de frecuencia, no de tamaño.", category: "wisdom", language: "en" },
  { id: "cu_es_467", text: "La gratitud es el mejor antídoto para la ansiedad.", category: "wisdom", language: "en" },
  { id: "cu_es_468", text: "Una palabra cálida se recuerda mucho tiempo.", category: "wisdom", language: "en" },
  { id: "cu_es_469", text: "Saber que tienes suficiente es la mayor ganancia.", category: "wisdom", language: "en" },
  { id: "cu_es_470", text: "Cuanto más recuerdas, más hay que agradecer.", category: "wisdom", language: "en" },
  { id: "cu_es_471", text: "Un corazón vuelto hacia otros acaba protegiéndote.", category: "wisdom", language: "en" },
  { id: "cu_es_472", text: "El elogio guardado caduca.", category: "wisdom", language: "en" },
  { id: "cu_es_473", text: "La gente se acerca a quien sabe agradecer.", category: "wisdom", language: "en" },
  { id: "cu_es_474", text: "Escribe tres cosas al día y tu ánimo cambiará.", category: "wisdom", language: "en" },
  { id: "cu_es_475", text: "La alegría tras el esfuerzo sabe el doble.", category: "wisdom", language: "en" },
  // ── 인생과 의미 / Life ─────────────────────────
  { id: "cu_es_476", text: "La vida es dirección, no velocidad.", category: "wisdom", language: "en" },
  { id: "cu_es_477", text: "Las horas más perdidas son las de envidiar a otros.", category: "wisdom", language: "en" },
  { id: "cu_es_478", text: "El sentido no se encuentra; se construye.", category: "wisdom", language: "en" },
  { id: "cu_es_479", text: "Piensa en qué dejarás y hoy cambiará.", category: "wisdom", language: "en" },
  { id: "cu_es_480", text: "Vivir bien es repetir buenas decisiones.", category: "wisdom", language: "en" },
  { id: "cu_es_481", text: "El tamaño de una vida iguala la responsabilidad que sostuvo.", category: "wisdom", language: "en" },
  { id: "cu_es_482", text: "Ten presente el final y lo pequeño te alterará menos.", category: "wisdom", language: "en" },
  { id: "cu_es_483", text: "Hoy es una versión reducida de tu vida entera.", category: "wisdom", language: "en" },
  { id: "cu_es_484", text: "El porqué dura más que el qué.", category: "wisdom", language: "en" },
  { id: "cu_es_485", text: "El mayor éxito es vivir una vida propia.", category: "wisdom", language: "en" },
  { id: "cu_es_486", text: "Un día que ayudó a alguien nunca se perdió.", category: "wisdom", language: "en" },
  { id: "cu_es_487", text: "La vida no sigue el plan, pero sí el rumbo.", category: "wisdom", language: "en" },
  { id: "cu_es_488", text: "Lo compartido dura más que lo poseído.", category: "wisdom", language: "en" },
  { id: "cu_es_489", text: "No busques una vida sin arrepentimientos, sino con menos.", category: "wisdom", language: "en" },
  { id: "cu_es_490", text: "No hay edad tardía, solo decisiones tardías.", category: "wisdom", language: "en" },
  { id: "cu_es_491", text: "Los días bien vividos suman una vida bien vivida.", category: "wisdom", language: "en" },
  { id: "cu_es_492", text: "Toma un camino distinto y verás un paisaje distinto.", category: "wisdom", language: "en" },
  { id: "cu_es_493", text: "Dedicar tiempo a lo que amas es el mayor lujo.", category: "wisdom", language: "en" },
  { id: "cu_es_494", text: "El dolor pasa; la lección permanece.", category: "wisdom", language: "en" },
  { id: "cu_es_495", text: "Lo más valioso suele estar en silencio, cerca.", category: "wisdom", language: "en" },
  { id: "cu_es_496", text: "Ninguna vida es perfecta; solo son distintas.", category: "wisdom", language: "en" },
  { id: "cu_es_497", text: "Solo vives una vez, pero puedes empezar cada día.", category: "wisdom", language: "en" },
  { id: "cu_es_498", text: "Este momento será algún día el que añores.", category: "wisdom", language: "en" },
  { id: "cu_es_499", text: "Cómo quieres ser recordado te dice cómo vivir.", category: "wisdom", language: "en" },
  { id: "cu_es_500", text: "Estar vivo significa que aún queda una oportunidad.", category: "wisdom", language: "en" },
];
