/**
 * 자동 생성 파일 — 직접 수정하지 마세요.
 * 원본: motivational_quotes_500_4languages.csv ("English" 열)
 * 재생성: node scripts/gen-curated-quotes.mjs
 *
 * 위인 어록이 아닌 무명(작자 미상) 잠언 풀. author 없이 category="wisdom" 으로만 태깅된다.
 */
import type { FamousQuoteSeed } from "@/lib/famousQuotesSeed";

export const CURATED_QUOTES_EN: ReadonlyArray<FamousQuoteSeed> = [
  // ── 시작과 첫걸음 / Beginnings ─────────────────────────
  { id: "cu_en_001", text: "If you wait for the perfect moment, you will never begin.", category: "wisdom", language: "en" },
  { id: "cu_en_002", text: "A small start today makes a big difference tomorrow.", category: "wisdom", language: "en" },
  { id: "cu_en_003", text: "The first step is always the heaviest and the most important.", category: "wisdom", language: "en" },
  { id: "cu_en_004", text: "You do not start because you are ready; you become ready by starting.", category: "wisdom", language: "en" },
  { id: "cu_en_005", text: "The moment you feel it is too late is the earliest moment you have left.", category: "wisdom", language: "en" },
  { id: "cu_en_006", text: "What you never begin can never even fail.", category: "wisdom", language: "en" },
  { id: "cu_en_007", text: "Big doors open with small keys.", category: "wisdom", language: "en" },
  { id: "cu_en_008", text: "A seed not planted today will not grow tomorrow.", category: "wisdom", language: "en" },
  { id: "cu_en_009", text: "Beginning is another name for courage.", category: "wisdom", language: "en" },
  { id: "cu_en_010", text: "The one who takes a step goes farther than the one who studies the map.", category: "wisdom", language: "en" },
  { id: "cu_en_011", text: "How you open a day becomes how you open a life.", category: "wisdom", language: "en" },
  { id: "cu_en_012", text: "The habit of postponing the start is the most expensive cost.", category: "wisdom", language: "en" },
  { id: "cu_en_013", text: "If you do nothing, nothing happens.", category: "wisdom", language: "en" },
  { id: "cu_en_014", text: "A clumsy start beats a perfect plan.", category: "wisdom", language: "en" },
  { id: "cu_en_015", text: "Today is the youngest day of the rest of your life.", category: "wisdom", language: "en" },
  { id: "cu_en_016", text: "New roads are made by those who walk them first.", category: "wisdom", language: "en" },
  { id: "cu_en_017", text: "Fear is largest before you begin and smallest after.", category: "wisdom", language: "en" },
  { id: "cu_en_018", text: "Plans happen on paper; change happens under your feet.", category: "wisdom", language: "en" },
  { id: "cu_en_019", text: "One percent begun each day changes who you are in a year.", category: "wisdom", language: "en" },
  { id: "cu_en_020", text: "Opportunity does not knock; you build the door.", category: "wisdom", language: "en" },
  { id: "cu_en_021", text: "A decision needs a day; a start needs only now.", category: "wisdom", language: "en" },
  { id: "cu_en_022", text: "If starting is half the work, continuing is the other half.", category: "wisdom", language: "en" },
  { id: "cu_en_023", text: "No one is good at first; only those who start ever get good.", category: "wisdom", language: "en" },
  { id: "cu_en_024", text: "The reason not to start today will still be there tomorrow.", category: "wisdom", language: "en" },
  { id: "cu_en_025", text: "One action is worth a hundred resolutions.", category: "wisdom", language: "en" },
  // ── 끈기와 인내 / Persistence ─────────────────────────
  { id: "cu_en_026", text: "Talent sets the starting line; persistence sets the finish line.", category: "wisdom", language: "en" },
  { id: "cu_en_027", text: "As long as you do not quit, the result is not yet in.", category: "wisdom", language: "en" },
  { id: "cu_en_028", text: "There is no way to beat someone who shows up every day.", category: "wisdom", language: "en" },
  { id: "cu_en_029", text: "A drop pierces stone not by force but by repetition.", category: "wisdom", language: "en" },
  { id: "cu_en_030", text: "The darkest stretch usually lies just before the finish.", category: "wisdom", language: "en" },
  { id: "cu_en_031", text: "Growth hides inside boring repetition.", category: "wisdom", language: "en" },
  { id: "cu_en_032", text: "Do not fear going slowly; fear standing still.", category: "wisdom", language: "en" },
  { id: "cu_en_033", text: "Endurance is a skill of its own.", category: "wisdom", language: "en" },
  { id: "cu_en_034", text: "Those who last the longest end up the best.", category: "wisdom", language: "en" },
  { id: "cu_en_035", text: "A day of effort is invisible; a year of it cannot be hidden.", category: "wisdom", language: "en" },
  { id: "cu_en_036", text: "Bamboo spends years on roots before it shoots toward the sky.", category: "wisdom", language: "en" },
  { id: "cu_en_037", text: "Effort that is never interrupted earns interest.", category: "wisdom", language: "en" },
  { id: "cu_en_038", text: "Opportunity finds whoever is still standing at the end.", category: "wisdom", language: "en" },
  { id: "cu_en_039", text: "A professional moves even on days when motivation is gone.", category: "wisdom", language: "en" },
  { id: "cu_en_040", text: "One more attempt is the whole secret.", category: "wisdom", language: "en" },
  { id: "cu_en_041", text: "Fatigue is often a sign that the goal is near.", category: "wisdom", language: "en" },
  { id: "cu_en_042", text: "A tree does not grow daily, yet it thickens every year.", category: "wisdom", language: "en" },
  { id: "cu_en_043", text: "The more important the work, the more tedium it demands.", category: "wisdom", language: "en" },
  { id: "cu_en_044", text: "Success does not arrive suddenly; it accumulates and then shows.", category: "wisdom", language: "en" },
  { id: "cu_en_045", text: "Quit today and yesterday's effort disappears too.", category: "wisdom", language: "en" },
  { id: "cu_en_046", text: "The ability to continue is rarer than talent.", category: "wisdom", language: "en" },
  { id: "cu_en_047", text: "Even a heavy stone splits after a hundred strikes.", category: "wisdom", language: "en" },
  { id: "cu_en_048", text: "On the way to a goal, no step is a small step.", category: "wisdom", language: "en" },
  { id: "cu_en_049", text: "Muscle grows only when breath runs short.", category: "wisdom", language: "en" },
  { id: "cu_en_050", text: "Win a day, win a month; win a month, win a life.", category: "wisdom", language: "en" },
  // ── 실패와 회복 / Resilience ─────────────────────────
  { id: "cu_en_051", text: "Failure is not a verdict; it is data.", category: "wisdom", language: "en" },
  { id: "cu_en_052", text: "Falling is an accident; staying down is a choice.", category: "wisdom", language: "en" },
  { id: "cu_en_053", text: "The most valuable tuition is what you pay to failure.", category: "wisdom", language: "en" },
  { id: "cu_en_054", text: "If you do not repeat the mistake, it was not a failure.", category: "wisdom", language: "en" },
  { id: "cu_en_055", text: "The bottom is not where you sink but where you push off.", category: "wisdom", language: "en" },
  { id: "cu_en_056", text: "Wounds become scars, and scars become armor.", category: "wisdom", language: "en" },
  { id: "cu_en_057", text: "A single failure does not define a person.", category: "wisdom", language: "en" },
  { id: "cu_en_058", text: "What you rebuild after collapse stands firmer.", category: "wisdom", language: "en" },
  { id: "cu_en_059", text: "Fear failure and you lose the lesson with it.", category: "wisdom", language: "en" },
  { id: "cu_en_060", text: "The fastest recovery begins with an honest look at the cause.", category: "wisdom", language: "en" },
  { id: "cu_en_061", text: "Not walking a wrong road for long is also a success.", category: "wisdom", language: "en" },
  { id: "cu_en_062", text: "Regret holds the past; reflection builds the future.", category: "wisdom", language: "en" },
  { id: "cu_en_063", text: "Hardship does not test you; it reveals you.", category: "wisdom", language: "en" },
  { id: "cu_en_064", text: "Roots grow deeper where the storm has passed.", category: "wisdom", language: "en" },
  { id: "cu_en_065", text: "How fast you rise again is the measure of you.", category: "wisdom", language: "en" },
  { id: "cu_en_066", text: "Growth begins the moment you admit the mistake.", category: "wisdom", language: "en" },
  { id: "cu_en_067", text: "Every expert is a survivor of countless failures.", category: "wisdom", language: "en" },
  { id: "cu_en_068", text: "Safe roads teach little.", category: "wisdom", language: "en" },
  { id: "cu_en_069", text: "A failed attempt is worth more than a day of nothing.", category: "wisdom", language: "en" },
  { id: "cu_en_070", text: "Let your knees bend, but never your direction.", category: "wisdom", language: "en" },
  { id: "cu_en_071", text: "Despair is a feeling, not a fact.", category: "wisdom", language: "en" },
  { id: "cu_en_072", text: "Today's loss becomes tomorrow's open space.", category: "wisdom", language: "en" },
  { id: "cu_en_073", text: "Only those who have lost know how to protect.", category: "wisdom", language: "en" },
  { id: "cu_en_074", text: "The point you thought was the end is usually the turn.", category: "wisdom", language: "en" },
  { id: "cu_en_075", text: "Do not curse where you fell; mark it on your map.", category: "wisdom", language: "en" },
  // ── 습관과 루틴 / Habits ─────────────────────────
  { id: "cu_en_076", text: "Willpower wavers; habits hold.", category: "wisdom", language: "en" },
  { id: "cu_en_077", text: "You are what you repeat.", category: "wisdom", language: "en" },
  { id: "cu_en_078", text: "A good habit is a gift to your future self.", category: "wisdom", language: "en" },
  { id: "cu_en_079", text: "Ten minutes a day changes ten years.", category: "wisdom", language: "en" },
  { id: "cu_en_080", text: "Make starting easy and continuing takes care of itself.", category: "wisdom", language: "en" },
  { id: "cu_en_081", text: "Changing your environment beats making a resolution.", category: "wisdom", language: "en" },
  { id: "cu_en_082", text: "Whoever rules the day rules the life.", category: "wisdom", language: "en" },
  { id: "cu_en_083", text: "A day not missed beats a day made perfect.", category: "wisdom", language: "en" },
  { id: "cu_en_084", text: "Never skip twice in a row: the best rule there is.", category: "wisdom", language: "en" },
  { id: "cu_en_085", text: "The first hour sets the direction of the whole day.", category: "wisdom", language: "en" },
  { id: "cu_en_086", text: "Start small if you want it to last.", category: "wisdom", language: "en" },
  { id: "cu_en_087", text: "A habit you do not measure will not last.", category: "wisdom", language: "en" },
  { id: "cu_en_088", text: "Routine does not cage creativity; it protects it.", category: "wisdom", language: "en" },
  { id: "cu_en_089", text: "Repetition is boring; its results are not.", category: "wisdom", language: "en" },
  { id: "cu_en_090", text: "A bad habit starts as a guest and ends as the host.", category: "wisdom", language: "en" },
  { id: "cu_en_091", text: "Resolutions are forgotten; systems remain.", category: "wisdom", language: "en" },
  { id: "cu_en_092", text: "Today's choice becomes tomorrow's default.", category: "wisdom", language: "en" },
  { id: "cu_en_093", text: "Dropping one habit beats adding ten.", category: "wisdom", language: "en" },
  { id: "cu_en_094", text: "Do the thing you dread first and the day gets lighter.", category: "wisdom", language: "en" },
  { id: "cu_en_095", text: "Habits compound like interest.", category: "wisdom", language: "en" },
  { id: "cu_en_096", text: "Same time, same place, same work: that is mastery.", category: "wisdom", language: "en" },
  { id: "cu_en_097", text: "Do not wait for motivation; keep the schedule.", category: "wisdom", language: "en" },
  { id: "cu_en_098", text: "How you end a day is how you start the next.", category: "wisdom", language: "en" },
  { id: "cu_en_099", text: "Break one small rule and the big plan breaks too.", category: "wisdom", language: "en" },
  { id: "cu_en_100", text: "Good habits do not take freedom; they create it.", category: "wisdom", language: "en" },
  // ── 시간과 우선순위 / Time ─────────────────────────
  { id: "cu_en_101", text: "Time is not managed; it is chosen.", category: "wisdom", language: "en" },
  { id: "cu_en_102", text: "Saying you are busy often means you have no priorities.", category: "wisdom", language: "en" },
  { id: "cu_en_103", text: "Deciding what not to do is strategy.", category: "wisdom", language: "en" },
  { id: "cu_en_104", text: "Everyone gets the same day; not everyone fills it the same.", category: "wisdom", language: "en" },
  { id: "cu_en_105", text: "Never let the urgent push out the important.", category: "wisdom", language: "en" },
  { id: "cu_en_106", text: "How you spend your hours is what you truly value.", category: "wisdom", language: "en" },
  { id: "cu_en_107", text: "Time is the only thing you cannot buy back.", category: "wisdom", language: "en" },
  { id: "cu_en_108", text: "Say yes to everything and you finish nothing.", category: "wisdom", language: "en" },
  { id: "cu_en_109", text: "Saying no is the most honest way to protect your time.", category: "wisdom", language: "en" },
  { id: "cu_en_110", text: "Tomorrow's you will not be freer than today's.", category: "wisdom", language: "en" },
  { id: "cu_en_111", text: "One thing at a time is the fastest route.", category: "wisdom", language: "en" },
  { id: "cu_en_112", text: "Give your best hours to your most important work.", category: "wisdom", language: "en" },
  { id: "cu_en_113", text: "You do not lack time; you lack order.", category: "wisdom", language: "en" },
  { id: "cu_en_114", text: "If you do not schedule your day, someone else will.", category: "wisdom", language: "en" },
  { id: "cu_en_115", text: "Procrastination does not save time; it charges interest.", category: "wisdom", language: "en" },
  { id: "cu_en_116", text: "A short focused hour beats a long distracted day.", category: "wisdom", language: "en" },
  { id: "cu_en_117", text: "Planning does not add hours; it removes waste.", category: "wisdom", language: "en" },
  { id: "cu_en_118", text: "Thirty minutes tonight buys two hours tomorrow.", category: "wisdom", language: "en" },
  { id: "cu_en_119", text: "A deadline is not an enemy but your most reliable colleague.", category: "wisdom", language: "en" },
  { id: "cu_en_120", text: "If you want more time, start by clearing space.", category: "wisdom", language: "en" },
  { id: "cu_en_121", text: "Divide the day well and life widens.", category: "wisdom", language: "en" },
  { id: "cu_en_122", text: "Time spent waiting is still your time.", category: "wisdom", language: "en" },
  { id: "cu_en_123", text: "Being busy is not the same as achieving.", category: "wisdom", language: "en" },
  { id: "cu_en_124", text: "Design your week and your year changes.", category: "wisdom", language: "en" },
  { id: "cu_en_125", text: "The costliest waste is time spent deciding what to do.", category: "wisdom", language: "en" },
  // ── 자기 믿음 / Self-Belief ─────────────────────────
  { id: "cu_en_126", text: "If you do not believe in yourself, no one will do it for you.", category: "wisdom", language: "en" },
  { id: "cu_en_127", text: "Live by another's standard and you live another's life.", category: "wisdom", language: "en" },
  { id: "cu_en_128", text: "What you say to yourself lasts longest.", category: "wisdom", language: "en" },
  { id: "cu_en_129", text: "Your worth is not set by anyone's opinion.", category: "wisdom", language: "en" },
  { id: "cu_en_130", text: "Confidence comes from attempting, not from succeeding.", category: "wisdom", language: "en" },
  { id: "cu_en_131", text: "Comparison is the quietest way to stop growing.", category: "wisdom", language: "en" },
  { id: "cu_en_132", text: "Most of your limits are the ones you set yourself.", category: "wisdom", language: "en" },
  { id: "cu_en_133", text: "Strength comes from keeping promises to yourself.", category: "wisdom", language: "en" },
  { id: "cu_en_134", text: "Do not lower your voice; your story deserves to be heard.", category: "wisdom", language: "en" },
  { id: "cu_en_135", text: "Being different is not the same as being less.", category: "wisdom", language: "en" },
  { id: "cu_en_136", text: "No one knows your potential the way you do.", category: "wisdom", language: "en" },
  { id: "cu_en_137", text: "Caring for yourself is responsibility, not selfishness.", category: "wisdom", language: "en" },
  { id: "cu_en_138", text: "Admitting what you lack is part of confidence.", category: "wisdom", language: "en" },
  { id: "cu_en_139", text: "You are already someone your past self hoped to become.", category: "wisdom", language: "en" },
  { id: "cu_en_140", text: "Decline the praise if you must, but never the achievement.", category: "wisdom", language: "en" },
  { id: "cu_en_141", text: "Self-trust is what holds your direction amid noise.", category: "wisdom", language: "en" },
  { id: "cu_en_142", text: "Those hardest on themselves grow the slowest.", category: "wisdom", language: "en" },
  { id: "cu_en_143", text: "Your pace is your path.", category: "wisdom", language: "en" },
  { id: "cu_en_144", text: "When doubt comes, look back at how far you came.", category: "wisdom", language: "en" },
  { id: "cu_en_145", text: "You need not be perfect to be qualified to begin.", category: "wisdom", language: "en" },
  { id: "cu_en_146", text: "Someone else's success is not your failure.", category: "wisdom", language: "en" },
  { id: "cu_en_147", text: "Self-trust is the sum of small promises kept.", category: "wisdom", language: "en" },
  { id: "cu_en_148", text: "Your story is not even half written.", category: "wisdom", language: "en" },
  { id: "cu_en_149", text: "Qualification is not granted; it is built.", category: "wisdom", language: "en" },
  { id: "cu_en_150", text: "Those who cheer for themselves go the distance.", category: "wisdom", language: "en" },
  // ── 성장과 배움 / Growth ─────────────────────────
  { id: "cu_en_151", text: "Learning begins the moment you admit you do not know.", category: "wisdom", language: "en" },
  { id: "cu_en_152", text: "If you are better than yesterday, today was a success.", category: "wisdom", language: "en" },
  { id: "cu_en_153", text: "Discomfort is the doorway to growth.", category: "wisdom", language: "en" },
  { id: "cu_en_154", text: "The size of your questions sets the size of your growth.", category: "wisdom", language: "en" },
  { id: "cu_en_155", text: "You learn the most when you teach.", category: "wisdom", language: "en" },
  { id: "cu_en_156", text: "Learning has no retirement age.", category: "wisdom", language: "en" },
  { id: "cu_en_157", text: "Skill is the distance between knowing and doing.", category: "wisdom", language: "en" },
  { id: "cu_en_158", text: "Nothing new lives in familiar places.", category: "wisdom", language: "en" },
  { id: "cu_en_159", text: "Criticism tastes bitter but is the shortest road.", category: "wisdom", language: "en" },
  { id: "cu_en_160", text: "The same book read at a different time is a different book.", category: "wisdom", language: "en" },
  { id: "cu_en_161", text: "Growth is not a line; it is a staircase.", category: "wisdom", language: "en" },
  { id: "cu_en_162", text: "Knowledge unused is knowledge unlearned.", category: "wisdom", language: "en" },
  { id: "cu_en_163", text: "Standing beside better people is the fastest schooling.", category: "wisdom", language: "en" },
  { id: "cu_en_164", text: "Imitation is creation's first exercise.", category: "wisdom", language: "en" },
  { id: "cu_en_165", text: "A beginner's clumsiness is not shame but proof.", category: "wisdom", language: "en" },
  { id: "cu_en_166", text: "The ability to absorb feedback builds skill.", category: "wisdom", language: "en" },
  { id: "cu_en_167", text: "You begin to age the moment you stop learning.", category: "wisdom", language: "en" },
  { id: "cu_en_168", text: "Time creates depth; curiosity creates breadth.", category: "wisdom", language: "en" },
  { id: "cu_en_169", text: "Experience unrecorded is experience half kept.", category: "wisdom", language: "en" },
  { id: "cu_en_170", text: "Every expertise began as an unfamiliar word.", category: "wisdom", language: "en" },
  { id: "cu_en_171", text: "Learning is as much unlearning as it is filling.", category: "wisdom", language: "en" },
  { id: "cu_en_172", text: "A difficult book stays with you longer than an easy one.", category: "wisdom", language: "en" },
  { id: "cu_en_173", text: "To grow, keep something you are bad at next to what you do well.", category: "wisdom", language: "en" },
  { id: "cu_en_174", text: "You truly know it only if you can explain it tomorrow.", category: "wisdom", language: "en" },
  { id: "cu_en_175", text: "Experience comes from reflection, not from time.", category: "wisdom", language: "en" },
  // ── 목표와 비전 / Vision ─────────────────────────
  { id: "cu_en_176", text: "Without a destination, no wind is a fair wind.", category: "wisdom", language: "en" },
  { id: "cu_en_177", text: "A goal becomes a plan the moment it is written down.", category: "wisdom", language: "en" },
  { id: "cu_en_178", text: "Big dreams are built from small deadlines.", category: "wisdom", language: "en" },
  { id: "cu_en_179", text: "If you know where you are going, speed matters less.", category: "wisdom", language: "en" },
  { id: "cu_en_180", text: "A goal you cannot measure is only a wish.", category: "wisdom", language: "en" },
  { id: "cu_en_181", text: "Do not lower the goal; change the method.", category: "wisdom", language: "en" },
  { id: "cu_en_182", text: "Vision gives meaning to today's hardship.", category: "wisdom", language: "en" },
  { id: "cu_en_183", text: "Chase another's goal and arrival feels empty.", category: "wisdom", language: "en" },
  { id: "cu_en_184", text: "Goals give direction; habits give the engine.", category: "wisdom", language: "en" },
  { id: "cu_en_185", text: "Think ten years ahead and today's choice gets easy.", category: "wisdom", language: "en" },
  { id: "cu_en_186", text: "Too many goals is the same as none.", category: "wisdom", language: "en" },
  { id: "cu_en_187", text: "Decide who you want to be before what you want to have.", category: "wisdom", language: "en" },
  { id: "cu_en_188", text: "Let the plan change, but keep the direction.", category: "wisdom", language: "en" },
  { id: "cu_en_189", text: "A visible goal produces visible results.", category: "wisdom", language: "en" },
  { id: "cu_en_190", text: "Only goals that look unreachable grow a person.", category: "wisdom", language: "en" },
  { id: "cu_en_191", text: "Break the goal apart and the fear breaks with it.", category: "wisdom", language: "en" },
  { id: "cu_en_192", text: "You change the moment you decide, not after you achieve.", category: "wisdom", language: "en" },
  { id: "cu_en_193", text: "Effort without a goal turns in place like a mill wheel.", category: "wisdom", language: "en" },
  { id: "cu_en_194", text: "The most dangerous goal is one that is too easy.", category: "wisdom", language: "en" },
  { id: "cu_en_195", text: "Announce your goal and accountability follows.", category: "wisdom", language: "en" },
  { id: "cu_en_196", text: "Daily goals hold up a lifetime goal.", category: "wisdom", language: "en" },
  { id: "cu_en_197", text: "If you do not know what you want, nothing will be enough.", category: "wisdom", language: "en" },
  { id: "cu_en_198", text: "The goal is a map; execution is a pair of shoes.", category: "wisdom", language: "en" },
  { id: "cu_en_199", text: "Picture the ending before you begin.", category: "wisdom", language: "en" },
  { id: "cu_en_200", text: "Even an unreached goal takes you somewhere.", category: "wisdom", language: "en" },
  // ── 용기와 두려움 / Courage ─────────────────────────
  { id: "cu_en_201", text: "Courage is not the absence of fear but walking with it.", category: "wisdom", language: "en" },
  { id: "cu_en_202", text: "The greatest risk is taking none at all.", category: "wisdom", language: "en" },
  { id: "cu_en_203", text: "Fear usually lives only in the imagination.", category: "wisdom", language: "en" },
  { id: "cu_en_204", text: "The thing you want to avoid is usually the thing to do.", category: "wisdom", language: "en" },
  { id: "cu_en_205", text: "Courage grows like muscle with use.", category: "wisdom", language: "en" },
  { id: "cu_en_206", text: "Being rejected is not being erased.", category: "wisdom", language: "en" },
  { id: "cu_en_207", text: "If you never ask, the answer is always no.", category: "wisdom", language: "en" },
  { id: "cu_en_208", text: "Say your fear out loud and half of it leaves.", category: "wisdom", language: "en" },
  { id: "cu_en_209", text: "The comfort zone is pleasant, but nothing grows there.", category: "wisdom", language: "en" },
  { id: "cu_en_210", text: "Regret lasts longer than failure.", category: "wisdom", language: "en" },
  { id: "cu_en_211", text: "Courage is not a shout; it is quietly trying again.", category: "wisdom", language: "en" },
  { id: "cu_en_212", text: "Only unknown roads show you new scenery.", category: "wisdom", language: "en" },
  { id: "cu_en_213", text: "Other people's opinions do not pay for your life.", category: "wisdom", language: "en" },
  { id: "cu_en_214", text: "The ability to sit with uncertainty creates opportunity.", category: "wisdom", language: "en" },
  { id: "cu_en_215", text: "Be brave once and the next time is easier.", category: "wisdom", language: "en" },
  { id: "cu_en_216", text: "Fear is a compass; growth lies where it points.", category: "wisdom", language: "en" },
  { id: "cu_en_217", text: "Calculate the risk, but do not surrender to the fear.", category: "wisdom", language: "en" },
  { id: "cu_en_218", text: "Growth is stepping forward while still afraid.", category: "wisdom", language: "en" },
  { id: "cu_en_219", text: "The biggest room is where no one has dared to go.", category: "wisdom", language: "en" },
  { id: "cu_en_220", text: "Days you never tried hurt more than days you failed.", category: "wisdom", language: "en" },
  { id: "cu_en_221", text: "Courage comes from decision, not from certainty.", category: "wisdom", language: "en" },
  { id: "cu_en_222", text: "Fear looking weak and you will never grow strong.", category: "wisdom", language: "en" },
  { id: "cu_en_223", text: "Every great change begins with an uncomfortable conversation.", category: "wisdom", language: "en" },
  { id: "cu_en_224", text: "Name your fear and it shrinks.", category: "wisdom", language: "en" },
  { id: "cu_en_225", text: "One brave day is longer than an ordinary year.", category: "wisdom", language: "en" },
  // ── 태도와 마인드셋 / Mindset ─────────────────────────
  { id: "cu_en_226", text: "The same situation yields different results depending on how you read it.", category: "wisdom", language: "en" },
  { id: "cu_en_227", text: "Add the word yet to every I cannot do this.", category: "wisdom", language: "en" },
  { id: "cu_en_228", text: "See a problem only as a problem and only the problem stays.", category: "wisdom", language: "en" },
  { id: "cu_en_229", text: "Attitude is noticed before ability.", category: "wisdom", language: "en" },
  { id: "cu_en_230", text: "Complaining changes nothing and takes your energy.", category: "wisdom", language: "en" },
  { id: "cu_en_231", text: "Spend your emotion only on what you can control.", category: "wisdom", language: "en" },
  { id: "cu_en_232", text: "Luck settles on a prepared attitude.", category: "wisdom", language: "en" },
  { id: "cu_en_233", text: "Not everything has to go your way, and that is fine.", category: "wisdom", language: "en" },
  { id: "cu_en_234", text: "The direction of your thoughts sets the direction of your feet.", category: "wisdom", language: "en" },
  { id: "cu_en_235", text: "Humility keeps the door of learning open.", category: "wisdom", language: "en" },
  { id: "cu_en_236", text: "Power returns the moment you stop blaming others.", category: "wisdom", language: "en" },
  { id: "cu_en_237", text: "Lower your expectations and both disappointment and effort shrink.", category: "wisdom", language: "en" },
  { id: "cu_en_238", text: "Optimism is not ignoring reality; it is looking for a way.", category: "wisdom", language: "en" },
  { id: "cu_en_239", text: "To one who wants to learn, everyone is a teacher.", category: "wisdom", language: "en" },
  { id: "cu_en_240", text: "Love the process more than the result and you will last.", category: "wisdom", language: "en" },
  { id: "cu_en_241", text: "The words you habitually use shape your life.", category: "wisdom", language: "en" },
  { id: "cu_en_242", text: "Ease is a matter of mind, not of time.", category: "wisdom", language: "en" },
  { id: "cu_en_243", text: "A bad day does not mean a bad life.", category: "wisdom", language: "en" },
  { id: "cu_en_244", text: "Wisdom is knowing what to accept and what to change.", category: "wisdom", language: "en" },
  { id: "cu_en_245", text: "Time spent angry is time not spent solving.", category: "wisdom", language: "en" },
  { id: "cu_en_246", text: "Those who count what they have end up with more.", category: "wisdom", language: "en" },
  { id: "cu_en_247", text: "Maturity is choosing instead of reacting.", category: "wisdom", language: "en" },
  { id: "cu_en_248", text: "Do not be ashamed of not knowing; be ashamed of not asking.", category: "wisdom", language: "en" },
  { id: "cu_en_249", text: "Being handed the hard task means you are trusted.", category: "wisdom", language: "en" },
  { id: "cu_en_250", text: "Change your thinking and what changes is what you see.", category: "wisdom", language: "en" },
  // ── 실행과 행동 / Action ─────────────────────────
  { id: "cu_en_251", text: "Ideas are common; execution is rare.", category: "wisdom", language: "en" },
  { id: "cu_en_252", text: "One day is enough to reveal who thinks and who does.", category: "wisdom", language: "en" },
  { id: "cu_en_253", text: "Only a moving ship can change course.", category: "wisdom", language: "en" },
  { id: "cu_en_254", text: "A draft beats a masterpiece because it exists.", category: "wisdom", language: "en" },
  { id: "cu_en_255", text: "Perfectionism is laziness in its most elegant disguise.", category: "wisdom", language: "en" },
  { id: "cu_en_256", text: "Today's action is tomorrow's confidence.", category: "wisdom", language: "en" },
  { id: "cu_en_257", text: "Delaying a decision is also a decision.", category: "wisdom", language: "en" },
  { id: "cu_en_258", text: "An hour of doing teaches more than a month of planning.", category: "wisdom", language: "en" },
  { id: "cu_en_259", text: "Start small and correct quickly.", category: "wisdom", language: "en" },
  { id: "cu_en_260", text: "Words make plans; actions make results.", category: "wisdom", language: "en" },
  { id: "cu_en_261", text: "Working hands beat willing minds.", category: "wisdom", language: "en" },
  { id: "cu_en_262", text: "Only after you try do you learn what the problem is.", category: "wisdom", language: "en" },
  { id: "cu_en_263", text: "Ninety percent of worry disappears once you act.", category: "wisdom", language: "en" },
  { id: "cu_en_264", text: "No one will execute your plan for you.", category: "wisdom", language: "en" },
  { id: "cu_en_265", text: "The start button is always in your own hand.", category: "wisdom", language: "en" },
  { id: "cu_en_266", text: "A product not shipped is a product that does not exist.", category: "wisdom", language: "en" },
  { id: "cu_en_267", text: "Think five times and move once and you are late.", category: "wisdom", language: "en" },
  { id: "cu_en_268", text: "Action is the only cure for anxiety.", category: "wisdom", language: "en" },
  { id: "cu_en_269", text: "Finishers are rarer than starters.", category: "wisdom", language: "en" },
  { id: "cu_en_270", text: "A small action beats a large conviction.", category: "wisdom", language: "en" },
  { id: "cu_en_271", text: "Put it out first; completion happens in the feedback.", category: "wisdom", language: "en" },
  { id: "cu_en_272", text: "An idea left only in notes is a dead idea.", category: "wisdom", language: "en" },
  { id: "cu_en_273", text: "Difficulty is always exaggerated until you try.", category: "wisdom", language: "en" },
  { id: "cu_en_274", text: "Right now is always the best timing.", category: "wisdom", language: "en" },
  { id: "cu_en_275", text: "Finish one thing a day and you finish three hundred sixty five a year.", category: "wisdom", language: "en" },
  // ── 집중과 몰입 / Focus ─────────────────────────
  { id: "cu_en_276", text: "Removing distraction is faster than adding ability.", category: "wisdom", language: "en" },
  { id: "cu_en_277", text: "One focused hour beats a scattered day.", category: "wisdom", language: "en" },
  { id: "cu_en_278", text: "Whoever tries everything goes deep in nothing.", category: "wisdom", language: "en" },
  { id: "cu_en_279", text: "Focus is not a talent; it is training.", category: "wisdom", language: "en" },
  { id: "cu_en_280", text: "Turning off notifications is easier than building willpower.", category: "wisdom", language: "en" },
  { id: "cu_en_281", text: "Deep results come from uninterrupted time.", category: "wisdom", language: "en" },
  { id: "cu_en_282", text: "Multitasking is the fastest way to do many things badly.", category: "wisdom", language: "en" },
  { id: "cu_en_283", text: "Clutter on the desk is clutter in the mind.", category: "wisdom", language: "en" },
  { id: "cu_en_284", text: "What you need to begin is not motivation but five minutes.", category: "wisdom", language: "en" },
  { id: "cu_en_285", text: "Flow arrives the moment you forget yourself.", category: "wisdom", language: "en" },
  { id: "cu_en_286", text: "Finish one, then move on: that is the fastest way.", category: "wisdom", language: "en" },
  { id: "cu_en_287", text: "Attention cannot be saved; it must be spent today.", category: "wisdom", language: "en" },
  { id: "cu_en_288", text: "Important work has the right not to be interrupted.", category: "wisdom", language: "en" },
  { id: "cu_en_289", text: "The fewer the options, the farther you go.", category: "wisdom", language: "en" },
  { id: "cu_en_290", text: "One thing done well beats ten done adequately.", category: "wisdom", language: "en" },
  { id: "cu_en_291", text: "Attention is your most expensive asset.", category: "wisdom", language: "en" },
  { id: "cu_en_292", text: "A quick check breaks an hour of flow.", category: "wisdom", language: "en" },
  { id: "cu_en_293", text: "The best thoughts are born in quiet.", category: "wisdom", language: "en" },
  { id: "cu_en_294", text: "Choosing what to look at is choosing what you will get.", category: "wisdom", language: "en" },
  { id: "cu_en_295", text: "Distraction is not a failure of will but of design.", category: "wisdom", language: "en" },
  { id: "cu_en_296", text: "One step at a time is always the surest.", category: "wisdom", language: "en" },
  { id: "cu_en_297", text: "Put the big things in first; the rest will fit around them.", category: "wisdom", language: "en" },
  { id: "cu_en_298", text: "The clearer the goal, the dimmer the temptation.", category: "wisdom", language: "en" },
  { id: "cu_en_299", text: "Rest is part of focus.", category: "wisdom", language: "en" },
  { id: "cu_en_300", text: "Once the important work is done, everything else falls into place.", category: "wisdom", language: "en" },
  // ── 규율과 절제 / Discipline ─────────────────────────
  { id: "cu_en_301", text: "Freedom begins where discipline ends.", category: "wisdom", language: "en" },
  { id: "cu_en_302", text: "The power to hold back gets you what you want.", category: "wisdom", language: "en" },
  { id: "cu_en_303", text: "Discipline is today's kindness to your future self.", category: "wisdom", language: "en" },
  { id: "cu_en_304", text: "Do not let mood govern your decisions.", category: "wisdom", language: "en" },
  { id: "cu_en_305", text: "Restraint is a choice, not a lack.", category: "wisdom", language: "en" },
  { id: "cu_en_306", text: "Choose the easy road and life gets hard.", category: "wisdom", language: "en" },
  { id: "cu_en_307", text: "The strongest person is the one who governs himself.", category: "wisdom", language: "en" },
  { id: "cu_en_308", text: "Daily restraint builds lifelong freedom.", category: "wisdom", language: "en" },
  { id: "cu_en_309", text: "Discipline is doing it on the days you do not want to.", category: "wisdom", language: "en" },
  { id: "cu_en_310", text: "One exception invites ten more.", category: "wisdom", language: "en" },
  { id: "cu_en_311", text: "Set a standard and you stop deciding every time.", category: "wisdom", language: "en" },
  { id: "cu_en_312", text: "Impulse is short; regret is long.", category: "wisdom", language: "en" },
  { id: "cu_en_313", text: "Repeat easy decisions and a hard life follows.", category: "wisdom", language: "en" },
  { id: "cu_en_314", text: "Restraint is not denial; it is choosing something bigger.", category: "wisdom", language: "en" },
  { id: "cu_en_315", text: "A life with rules is a life with more room.", category: "wisdom", language: "en" },
  { id: "cu_en_316", text: "Do not lean on willpower; build a structure.", category: "wisdom", language: "en" },
  { id: "cu_en_317", text: "Do not fight sleep; manage it.", category: "wisdom", language: "en" },
  { id: "cu_en_318", text: "A day of discipline creates a decade of results.", category: "wisdom", language: "en" },
  { id: "cu_en_319", text: "The hardest fight is the one you win against yourself.", category: "wisdom", language: "en" },
  { id: "cu_en_320", text: "Not procrastinating is the best investment strategy.", category: "wisdom", language: "en" },
  { id: "cu_en_321", text: "Only the disciplined can carry a big opportunity.", category: "wisdom", language: "en" },
  { id: "cu_en_322", text: "Your day fills with whatever you allow.", category: "wisdom", language: "en" },
  { id: "cu_en_323", text: "Understand a desire and it becomes easier to govern.", category: "wisdom", language: "en" },
  { id: "cu_en_324", text: "Time spent enduring discomfort is time spent growing.", category: "wisdom", language: "en" },
  { id: "cu_en_325", text: "Those who keep the clock also keep trust.", category: "wisdom", language: "en" },
  // ── 사람과 관계 / Relationships ─────────────────────────
  { id: "cu_en_326", text: "Alone you go fast; together you go far.", category: "wisdom", language: "en" },
  { id: "cu_en_327", text: "You become the average of the five closest to you.", category: "wisdom", language: "en" },
  { id: "cu_en_328", text: "Trust takes years to build and seconds to break.", category: "wisdom", language: "en" },
  { id: "cu_en_329", text: "The listener ends up gaining more.", category: "wisdom", language: "en" },
  { id: "cu_en_330", text: "Remember the help you received; forget the help you gave.", category: "wisdom", language: "en" },
  { id: "cu_en_331", text: "Do not try to beat people; beat the problem.", category: "wisdom", language: "en" },
  { id: "cu_en_332", text: "Good relationships are kept by sincerity, not by time.", category: "wisdom", language: "en" },
  { id: "cu_en_333", text: "Whom you meet matters as much as what you know.", category: "wisdom", language: "en" },
  { id: "cu_en_334", text: "Those who give first receive the most in the end.", category: "wisdom", language: "en" },
  { id: "cu_en_335", text: "Speak less and trust grows.", category: "wisdom", language: "en" },
  { id: "cu_en_336", text: "Ask a question instead of casting blame and the relationship lives.", category: "wisdom", language: "en" },
  { id: "cu_en_337", text: "Keeping promises is the strongest marketing there is.", category: "wisdom", language: "en" },
  { id: "cu_en_338", text: "Those who keep people ultimately succeed.", category: "wisdom", language: "en" },
  { id: "cu_en_339", text: "Listening is the most underrated leadership skill.", category: "wisdom", language: "en" },
  { id: "cu_en_340", text: "Gratitude exists only once it is expressed.", category: "wisdom", language: "en" },
  { id: "cu_en_341", text: "Helping someone grow grows you the most.", category: "wisdom", language: "en" },
  { id: "cu_en_342", text: "An apology gets more expensive the longer it waits.", category: "wisdom", language: "en" },
  { id: "cu_en_343", text: "If you want to be remembered, remember names first.", category: "wisdom", language: "en" },
  { id: "cu_en_344", text: "Try to please everyone and you please no one.", category: "wisdom", language: "en" },
  { id: "cu_en_345", text: "Good colleagues are the best benefit package.", category: "wisdom", language: "en" },
  { id: "cu_en_346", text: "Keeping distance is also a way to keep a relationship.", category: "wisdom", language: "en" },
  { id: "cu_en_347", text: "Those who can celebrate others' success grow large.", category: "wisdom", language: "en" },
  { id: "cu_en_348", text: "Tone is remembered longer than content.", category: "wisdom", language: "en" },
  { id: "cu_en_349", text: "Those who only want to shine alone end up alone.", category: "wisdom", language: "en" },
  { id: "cu_en_350", text: "You can disagree and still respect the person.", category: "wisdom", language: "en" },
  // ── 리더십과 영향력 / Leadership ─────────────────────────
  { id: "cu_en_351", text: "Leadership is an attitude, not a title.", category: "wisdom", language: "en" },
  { id: "cu_en_352", text: "Whoever moves first becomes the leader.", category: "wisdom", language: "en" },
  { id: "cu_en_353", text: "Lead with your back, not with your mouth.", category: "wisdom", language: "en" },
  { id: "cu_en_354", text: "A good leader shares credit and takes blame.", category: "wisdom", language: "en" },
  { id: "cu_en_355", text: "People do not follow orders; they follow trust.", category: "wisdom", language: "en" },
  { id: "cu_en_356", text: "A team performs at whatever standard its leader allows.", category: "wisdom", language: "en" },
  { id: "cu_en_357", text: "A leader who asks questions builds a learning team.", category: "wisdom", language: "en" },
  { id: "cu_en_358", text: "Influence is earned, never demanded.", category: "wisdom", language: "en" },
  { id: "cu_en_359", text: "Praise in public; correct in private.", category: "wisdom", language: "en" },
  { id: "cu_en_360", text: "Growing people is a leader's greatest achievement.", category: "wisdom", language: "en" },
  { id: "cu_en_361", text: "A leader's calm is the whole team's safety net.", category: "wisdom", language: "en" },
  { id: "cu_en_362", text: "Example is stronger than a hundred lectures.", category: "wisdom", language: "en" },
  { id: "cu_en_363", text: "The best leader makes himself unnecessary.", category: "wisdom", language: "en" },
  { id: "cu_en_364", text: "Share authority; hold the standard.", category: "wisdom", language: "en" },
  { id: "cu_en_365", text: "A leader's calendar reveals the organization's priorities.", category: "wisdom", language: "en" },
  { id: "cu_en_366", text: "A healthy team is one where bad news travels fast.", category: "wisdom", language: "en" },
  { id: "cu_en_367", text: "The most dangerous leader is the one who will not decide.", category: "wisdom", language: "en" },
  { id: "cu_en_368", text: "A leader gives direction more than answers.", category: "wisdom", language: "en" },
  { id: "cu_en_369", text: "Only the trusted can lead change.", category: "wisdom", language: "en" },
  { id: "cu_en_370", text: "A leader who admits mistakes strengthens the team.", category: "wisdom", language: "en" },
  { id: "cu_en_371", text: "Doing what you said is the whole of leadership.", category: "wisdom", language: "en" },
  { id: "cu_en_372", text: "Trust people and they grow to match it.", category: "wisdom", language: "en" },
  { id: "cu_en_373", text: "Ask the quietest person first.", category: "wisdom", language: "en" },
  { id: "cu_en_374", text: "When a leader stops growing, so does the organization.", category: "wisdom", language: "en" },
  { id: "cu_en_375", text: "What matters about influence is direction, not size.", category: "wisdom", language: "en" },
  // ── 창의와 혁신 / Creativity ─────────────────────────
  { id: "cu_en_376", text: "Newness comes from unfamiliar combinations.", category: "wisdom", language: "en" },
  { id: "cu_en_377", text: "A hundred bad ideas bring one good one.", category: "wisdom", language: "en" },
  { id: "cu_en_378", text: "Change the question and the answer changes.", category: "wisdom", language: "en" },
  { id: "cu_en_379", text: "Creativity is a product of habit, not inspiration.", category: "wisdom", language: "en" },
  { id: "cu_en_380", text: "The tighter the constraints, the more creative the answer.", category: "wisdom", language: "en" },
  { id: "cu_en_381", text: "Seeing differently beats looking harder.", category: "wisdom", language: "en" },
  { id: "cu_en_382", text: "Every innovation looked reckless at first.", category: "wisdom", language: "en" },
  { id: "cu_en_383", text: "It begins with making a familiar problem strange.", category: "wisdom", language: "en" },
  { id: "cu_en_384", text: "An idea not written down disappears.", category: "wisdom", language: "en" },
  { id: "cu_en_385", text: "Those standing at the border see new things.", category: "wisdom", language: "en" },
  { id: "cu_en_386", text: "A walk produces better ideas than a meeting.", category: "wisdom", language: "en" },
  { id: "cu_en_387", text: "Innovation starts by doubting the accepted answer.", category: "wisdom", language: "en" },
  { id: "cu_en_388", text: "The most creative people connect unrelated fields.", category: "wisdom", language: "en" },
  { id: "cu_en_389", text: "Your first version is always embarrassing. Make it anyway.", category: "wisdom", language: "en" },
  { id: "cu_en_390", text: "An idea is proven by execution, not ownership.", category: "wisdom", language: "en" },
  { id: "cu_en_391", text: "The same method as everyone gives the same result as everyone.", category: "wisdom", language: "en" },
  { id: "cu_en_392", text: "Curiosity is the tool with the longest life.", category: "wisdom", language: "en" },
  { id: "cu_en_393", text: "The more ideas you discard, the better the ones you keep.", category: "wisdom", language: "en" },
  { id: "cu_en_394", text: "The enemy of creation is indifference, not criticism.", category: "wisdom", language: "en" },
  { id: "cu_en_395", text: "Working with different people widens your thinking.", category: "wisdom", language: "en" },
  { id: "cu_en_396", text: "You must know the rules to break them.", category: "wisdom", language: "en" },
  { id: "cu_en_397", text: "The best idea usually shows up on the second try.", category: "wisdom", language: "en" },
  { id: "cu_en_398", text: "Knowledge that seems useless connects later.", category: "wisdom", language: "en" },
  { id: "cu_en_399", text: "Only when a thought reaches your hands can it be tested.", category: "wisdom", language: "en" },
  { id: "cu_en_400", text: "Imitate long enough and your own path appears.", category: "wisdom", language: "en" },
  // ── 돈과 부 / Wealth ─────────────────────────
  { id: "cu_en_401", text: "Keeping money is harder than making it.", category: "wisdom", language: "en" },
  { id: "cu_en_402", text: "Uncontrolled spending makes income meaningless.", category: "wisdom", language: "en" },
  { id: "cu_en_403", text: "The best purchase is buying back your time.", category: "wisdom", language: "en" },
  { id: "cu_en_404", text: "Wealth comes from habits, not income.", category: "wisdom", language: "en" },
  { id: "cu_en_405", text: "The surest investment is yourself.", category: "wisdom", language: "en" },
  { id: "cu_en_406", text: "Saving early beats saving big and late.", category: "wisdom", language: "en" },
  { id: "cu_en_407", text: "Debt spends your future freedom in advance.", category: "wisdom", language: "en" },
  { id: "cu_en_408", text: "You are paid in proportion to the value you create.", category: "wisdom", language: "en" },
  { id: "cu_en_409", text: "Fast money usually leaves fast.", category: "wisdom", language: "en" },
  { id: "cu_en_410", text: "Investing in what you do not understand is gambling.", category: "wisdom", language: "en" },
  { id: "cu_en_411", text: "Frugality is a choice, not poverty.", category: "wisdom", language: "en" },
  { id: "cu_en_412", text: "Money is a good tool and a bad master.", category: "wisdom", language: "en" },
  { id: "cu_en_413", text: "One income means one risk holds your whole life.", category: "wisdom", language: "en" },
  { id: "cu_en_414", text: "Compounding does not reward the impatient.", category: "wisdom", language: "en" },
  { id: "cu_en_415", text: "Spending driven by comparison costs the most.", category: "wisdom", language: "en" },
  { id: "cu_en_416", text: "Price is what you pay; value is what you get.", category: "wisdom", language: "en" },
  { id: "cu_en_417", text: "Money you do not track leaks away.", category: "wisdom", language: "en" },
  { id: "cu_en_418", text: "Financial freedom is the power to say no.", category: "wisdom", language: "en" },
  { id: "cu_en_419", text: "How fast you learn matters more than how fast you earn.", category: "wisdom", language: "en" },
  { id: "cu_en_420", text: "The truly rich are those who know what is enough.", category: "wisdom", language: "en" },
  { id: "cu_en_421", text: "If you do not understand the risk, you cannot keep the return.", category: "wisdom", language: "en" },
  { id: "cu_en_422", text: "Saving is defense, investing is offense; you need both.", category: "wisdom", language: "en" },
  { id: "cu_en_423", text: "Protect first what money cannot buy.", category: "wisdom", language: "en" },
  { id: "cu_en_424", text: "Repeated small expenses are scarier than one big one.", category: "wisdom", language: "en" },
  { id: "cu_en_425", text: "Successful people usually invest in boring ways.", category: "wisdom", language: "en" },
  // ── 건강과 균형 / Health ─────────────────────────
  { id: "cu_en_426", text: "Health is the most undervalued asset until you lose it.", category: "wisdom", language: "en" },
  { id: "cu_en_427", text: "Sleep is not laziness; it is a condition of performance.", category: "wisdom", language: "en" },
  { id: "cu_en_428", text: "Neglect your body and it will set your schedule for you.", category: "wisdom", language: "en" },
  { id: "cu_en_429", text: "Thirty minutes of walking a day shortens future sick days.", category: "wisdom", language: "en" },
  { id: "cu_en_430", text: "Resting is not stopping; it is preparing.", category: "wisdom", language: "en" },
  { id: "cu_en_431", text: "Achievement is built on stamina.", category: "wisdom", language: "en" },
  { id: "cu_en_432", text: "Burnout is not a punishment for effort; it is a signal about balance.", category: "wisdom", language: "en" },
  { id: "cu_en_433", text: "Eating slowly becomes living long.", category: "wisdom", language: "en" },
  { id: "cu_en_434", text: "Work and life are not a scale but a rhythm.", category: "wisdom", language: "en" },
  { id: "cu_en_435", text: "Do not ignore the small signals your body sends.", category: "wisdom", language: "en" },
  { id: "cu_en_436", text: "Exercise is today's burden and tomorrow's savings.", category: "wisdom", language: "en" },
  { id: "cu_en_437", text: "Stress is not eliminated; it is managed.", category: "wisdom", language: "en" },
  { id: "cu_en_438", text: "Weekend recovery creates weekday performance.", category: "wisdom", language: "en" },
  { id: "cu_en_439", text: "The most faithful investments are daily sleep and water.", category: "wisdom", language: "en" },
  { id: "cu_en_440", text: "Resting before illness is cheaper than resting after.", category: "wisdom", language: "en" },
  { id: "cu_en_441", text: "Look away from the screen at least once a day.", category: "wisdom", language: "en" },
  { id: "cu_en_442", text: "A walk is the cheapest counseling there is.", category: "wisdom", language: "en" },
  { id: "cu_en_443", text: "A settled body settles the mind.", category: "wisdom", language: "en" },
  { id: "cu_en_444", text: "One overdone day costs three days of recovery.", category: "wisdom", language: "en" },
  { id: "cu_en_445", text: "Dinner with family is worth putting on the calendar.", category: "wisdom", language: "en" },
  { id: "cu_en_446", text: "A hobby is not a luxury; it is maintenance.", category: "wisdom", language: "en" },
  { id: "cu_en_447", text: "Time spent catching your breath creates speed.", category: "wisdom", language: "en" },
  { id: "cu_en_448", text: "Well-rested people make better decisions.", category: "wisdom", language: "en" },
  { id: "cu_en_449", text: "You get only one body for the whole trip.", category: "wisdom", language: "en" },
  { id: "cu_en_450", text: "The busier you are, the more regular your meals and sleep should be.", category: "wisdom", language: "en" },
  // ── 감사와 마음 / Gratitude ─────────────────────────
  { id: "cu_en_451", text: "Count what you have and lack shrinks.", category: "wisdom", language: "en" },
  { id: "cu_en_452", text: "Gratitude becomes power when it becomes habit.", category: "wisdom", language: "en" },
  { id: "cu_en_453", text: "An ordinary day is someone else's most longed-for day.", category: "wisdom", language: "en" },
  { id: "cu_en_454", text: "Your gratitude list should outrun your complaint list.", category: "wisdom", language: "en" },
  { id: "cu_en_455", text: "Thanks delivered late arrives only half.", category: "wisdom", language: "en" },
  { id: "cu_en_456", text: "The ability to enjoy small things sets your quality of life.", category: "wisdom", language: "en" },
  { id: "cu_en_457", text: "Stop comparing and contentment begins.", category: "wisdom", language: "en" },
  { id: "cu_en_458", text: "Nothing is a given; we have only grown used to it.", category: "wisdom", language: "en" },
  { id: "cu_en_459", text: "A day that passed safely is also an achievement.", category: "wisdom", language: "en" },
  { id: "cu_en_460", text: "Gratitude tidies the past and lightens the future.", category: "wisdom", language: "en" },
  { id: "cu_en_461", text: "Someone's labor made today's comfort possible.", category: "wisdom", language: "en" },
  { id: "cu_en_462", text: "A generous heart always has something to share.", category: "wisdom", language: "en" },
  { id: "cu_en_463", text: "Forgiveness is for you, not for the other person.", category: "wisdom", language: "en" },
  { id: "cu_en_464", text: "End a day in gratitude and the next feels lighter.", category: "wisdom", language: "en" },
  { id: "cu_en_465", text: "Pass on the kindness you were given.", category: "wisdom", language: "en" },
  { id: "cu_en_466", text: "Joy is a matter of frequency, not size.", category: "wisdom", language: "en" },
  { id: "cu_en_467", text: "Gratitude is the best antidote to an anxious mind.", category: "wisdom", language: "en" },
  { id: "cu_en_468", text: "One warm word is remembered a long time.", category: "wisdom", language: "en" },
  { id: "cu_en_469", text: "Knowing you have enough is the greatest income.", category: "wisdom", language: "en" },
  { id: "cu_en_470", text: "The more you remember, the more there is to thank.", category: "wisdom", language: "en" },
  { id: "cu_en_471", text: "A heart turned toward others ends up protecting you.", category: "wisdom", language: "en" },
  { id: "cu_en_472", text: "Praise saved for later expires.", category: "wisdom", language: "en" },
  { id: "cu_en_473", text: "People gather around those who know how to be thankful.", category: "wisdom", language: "en" },
  { id: "cu_en_474", text: "Write down three things a day and your mind changes.", category: "wisdom", language: "en" },
  { id: "cu_en_475", text: "Joy after hardship is twice as deep.", category: "wisdom", language: "en" },
  // ── 인생과 의미 / Life ─────────────────────────
  { id: "cu_en_476", text: "Life is about direction, not speed.", category: "wisdom", language: "en" },
  { id: "cu_en_477", text: "The most wasted hours are those spent envying others.", category: "wisdom", language: "en" },
  { id: "cu_en_478", text: "Meaning is not found; it is made.", category: "wisdom", language: "en" },
  { id: "cu_en_479", text: "Think about what you will leave behind and today changes.", category: "wisdom", language: "en" },
  { id: "cu_en_480", text: "Living well is the repetition of choosing well.", category: "wisdom", language: "en" },
  { id: "cu_en_481", text: "The size of a life equals the responsibility it carried.", category: "wisdom", language: "en" },
  { id: "cu_en_482", text: "Keep the end in mind and small things shake you less.", category: "wisdom", language: "en" },
  { id: "cu_en_483", text: "Today is a small model of your whole life.", category: "wisdom", language: "en" },
  { id: "cu_en_484", text: "Why you do it outlasts what you do.", category: "wisdom", language: "en" },
  { id: "cu_en_485", text: "The greatest success is living a life that is yours.", category: "wisdom", language: "en" },
  { id: "cu_en_486", text: "A day that helped someone was never wasted.", category: "wisdom", language: "en" },
  { id: "cu_en_487", text: "Life does not follow the plan, but it follows the direction.", category: "wisdom", language: "en" },
  { id: "cu_en_488", text: "What you shared outlasts what you owned.", category: "wisdom", language: "en" },
  { id: "cu_en_489", text: "Aim not for a life without regret but for fewer regrets.", category: "wisdom", language: "en" },
  { id: "cu_en_490", text: "There is no age too late, only decisions made too late.", category: "wisdom", language: "en" },
  { id: "cu_en_491", text: "Days lived well add up to a life lived well.", category: "wisdom", language: "en" },
  { id: "cu_en_492", text: "Take a different road and see a different view.", category: "wisdom", language: "en" },
  { id: "cu_en_493", text: "Spending time on what you love is the finest luxury.", category: "wisdom", language: "en" },
  { id: "cu_en_494", text: "Pain passes; the lesson stays.", category: "wisdom", language: "en" },
  { id: "cu_en_495", text: "The most precious things are usually quietly nearby.", category: "wisdom", language: "en" },
  { id: "cu_en_496", text: "No life is perfect; every life is simply different.", category: "wisdom", language: "en" },
  { id: "cu_en_497", text: "You live once, yet you may begin again each day.", category: "wisdom", language: "en" },
  { id: "cu_en_498", text: "This moment will one day be the time you miss.", category: "wisdom", language: "en" },
  { id: "cu_en_499", text: "How you want to be remembered tells you how to live.", category: "wisdom", language: "en" },
  { id: "cu_en_500", text: "To be alive is to still have a chance left.", category: "wisdom", language: "en" },
];
