/**
 * 자동 생성 파일 — 직접 수정하지 마세요.
 * 원본: motivational_quotes_500_4languages.csv ("한국어" 열)
 * 재생성: node scripts/gen-curated-quotes.mjs
 *
 * 위인 어록이 아닌 무명(작자 미상) 잠언 풀. author 없이 category="wisdom" 으로만 태깅된다.
 */
import type { FamousQuoteSeed } from "@/lib/famousQuotesSeed";

export const CURATED_QUOTES_KO: ReadonlyArray<FamousQuoteSeed> = [
  // ── 시작과 첫걸음 / Beginnings ─────────────────────────
  { id: "cu_ko_0001", text: "완벽한 때를 기다리면 영원히 시작하지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0002", text: "오늘의 작은 시작이 내일의 큰 차이를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0003", text: "첫걸음은 언제나 가장 무겁고 가장 중요하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0004", text: "준비가 끝나서 시작하는 게 아니라, 시작해야 준비가 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0005", text: "늦었다고 느끼는 지금이 남은 생에서 가장 이른 순간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0006", text: "시작하지 않은 일은 실패조차 할 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0007", text: "큰 문은 작은 열쇠로 열린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0008", text: "오늘 심지 않은 씨앗은 내일 자라지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0009", text: "시작은 용기의 다른 이름이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0010", text: "지도를 보는 사람보다 한 걸음 걷는 사람이 멀리 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0011", text: "하루를 여는 방식이 인생을 여는 방식이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0012", text: "시작을 미루는 습관이 가장 비싼 비용이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0013", text: "아무것도 하지 않으면 아무 일도 일어나지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0014", text: "서툰 시작이 완벽한 계획을 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0015", text: "오늘은 남은 인생에서 가장 젊은 날이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0016", text: "새로운 길은 처음 걷는 사람에 의해 만들어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0017", text: "두려움은 시작 전에 가장 크고, 시작 후에 가장 작다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0018", text: "계획은 종이 위에서, 변화는 발밑에서 일어난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0019", text: "매일 1퍼센트의 시작이 1년 뒤의 나를 바꾼다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0020", text: "기회는 문을 두드리지 않는다. 당신이 문을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0021", text: "결심은 하루면 충분하고, 시작은 지금이면 충분하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0022", text: "시작이 반이라면, 나머지 반은 계속하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0023", text: "처음부터 잘하는 사람은 없다. 시작한 사람만 잘하게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0024", text: "오늘 하지 않을 이유는 내일도 그대로 남아 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0025", text: "백 번의 다짐보다 한 번의 실행이 낫다.", category: "wisdom", language: "ko" },
  // ── 끈기와 인내 / Persistence ─────────────────────────
  { id: "cu_ko_0026", text: "재능은 출발선을 정하고, 끈기는 도착선을 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0027", text: "포기하지 않는 한 아직 결과는 나오지 않았다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0028", text: "매일 조금씩 하는 사람을 이길 방법은 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0029", text: "물방울이 바위를 뚫는 것은 힘이 아니라 반복이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0030", text: "가장 어두운 구간이 대개 결승선 직전이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0031", text: "성장은 지루한 반복 속에 숨어 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0032", text: "천천히 가는 것을 두려워 말고, 멈추는 것을 두려워하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0033", text: "버티는 것도 실력이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0034", text: "오래 하는 사람이 결국 잘하는 사람이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0035", text: "하루의 노력은 티가 나지 않지만 일 년의 노력은 숨길 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0036", text: "대나무는 4년 동안 뿌리를 내리고 5년째에 하늘로 솟는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0037", text: "중단하지 않은 노력에는 이자가 붙는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0038", text: "끝까지 남아 있는 사람에게 기회가 온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0039", text: "의욕이 사라진 날에도 움직이는 것이 프로다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0040", text: "한 번 더 시도하는 것, 그것이 전부다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0041", text: "피로는 목표에 가까워졌다는 신호일 때가 많다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0042", text: "나무는 매일 자라지 않지만 매년 굵어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0043", text: "중요한 일일수록 지겨움을 견뎌야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0044", text: "성공은 갑자기 오는 것이 아니라 누적되어 드러난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0045", text: "오늘 그만두면 어제의 노력까지 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0046", text: "계속하는 힘은 재능보다 희소하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0047", text: "무거운 돌도 백 번 치면 쪼개진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0048", text: "목표를 향한 걸음에는 작은 걸음이란 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0049", text: "숨이 찰 때 비로소 근육이 자란다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0050", text: "하루를 이기면 한 달을 이기고, 한 달을 이기면 인생을 이긴다.", category: "wisdom", language: "ko" },
  // ── 실패와 회복 / Resilience ─────────────────────────
  { id: "cu_ko_0051", text: "실패는 결과가 아니라 데이터다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0052", text: "넘어지는 것은 사고지만, 일어나지 않는 것은 선택이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0053", text: "가장 값진 수업료는 실패에 지불한 돈이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0054", text: "같은 실수를 반복하지 않는다면 그것은 실패가 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0055", text: "바닥은 무너지는 곳이 아니라 딛고 서는 곳이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0056", text: "상처는 흉터가 되고, 흉터는 갑옷이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0057", text: "한 번의 실패가 한 사람을 정의하지는 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0058", text: "무너진 뒤에 세운 것이 더 단단하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0059", text: "실패를 두려워하면 배움도 함께 잃는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0060", text: "가장 빠른 회복은 원인을 정직하게 보는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0061", text: "잘못된 길을 오래 걷지 않는 것도 성공이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0062", text: "후회는 과거를 붙잡고, 반성은 미래를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0063", text: "시련은 사람을 시험하는 것이 아니라 드러낸다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0064", text: "폭풍이 지나간 자리에서 뿌리는 더 깊어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0065", text: "다시 일어서는 속도가 그 사람의 크기다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0066", text: "실수를 인정하는 순간 성장은 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0067", text: "모든 전문가는 수많은 실패의 생존자다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0068", text: "안전한 길에는 배움이 적다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0069", text: "실패한 시도는 아무것도 하지 않은 날보다 값지다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0070", text: "무릎이 꺾여도 방향은 꺾이지 않게 하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0071", text: "절망은 사실이 아니라 감정이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0072", text: "오늘의 상실이 내일의 여백이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0073", text: "잃어본 사람만이 지킬 줄 안다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0074", text: "끝이라고 생각한 지점이 대개 전환점이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0075", text: "넘어진 자리를 원망하지 말고 지도에 표시하라.", category: "wisdom", language: "ko" },
  // ── 습관과 루틴 / Habits ─────────────────────────
  { id: "cu_ko_0076", text: "의지는 흔들리지만 습관은 버틴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0077", text: "당신이 반복하는 것이 곧 당신이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0078", text: "좋은 습관은 미래의 나에게 보내는 선물이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0079", text: "하루 10분이 10년을 바꾼다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0080", text: "시작을 쉽게 만들면 지속은 저절로 따라온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0081", text: "환경을 바꾸는 것이 결심보다 강력하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0082", text: "하루를 지배하는 사람이 인생을 지배한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0083", text: "완벽한 하루보다 빠지지 않는 하루가 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0084", text: "이틀 연속 거르지 않는 것이 최고의 규칙이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0085", text: "아침 한 시간이 하루 전체의 방향을 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0086", text: "작게 시작해야 오래 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0087", text: "측정하지 않는 습관은 오래가지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0088", text: "루틴은 창의력을 가두지 않고 보호한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0089", text: "반복은 지루하지만 결과는 지루하지 않다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0090", text: "나쁜 습관은 처음엔 손님이고 나중엔 주인이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0091", text: "결심은 잊혀지지만 시스템은 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0092", text: "오늘 한 선택이 내일의 기본값이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0093", text: "버리는 습관 하나가 새 습관 열 개보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0094", text: "하기 싫은 일을 먼저 하면 하루가 가벼워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0095", text: "습관은 복리처럼 쌓인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0096", text: "같은 시간, 같은 자리, 같은 일이 실력을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0097", text: "의욕을 기다리지 말고 일정을 지켜라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0098", text: "하루의 마무리가 다음 날의 출발이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0099", text: "작은 규칙 하나가 무너지면 큰 계획도 무너진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0100", text: "좋은 습관은 자유를 빼앗지 않고 만들어 준다.", category: "wisdom", language: "ko" },
  // ── 시간과 우선순위 / Time ─────────────────────────
  { id: "cu_ko_0101", text: "시간은 관리되는 것이 아니라 선택되는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0102", text: "바쁘다는 말은 우선순위가 없다는 말이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0103", text: "무엇을 하지 않을지 정하는 것이 전략이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0104", text: "하루는 모두에게 같지만 밀도는 각자 다르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0105", text: "급한 일이 중요한 일을 밀어내게 두지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0106", text: "시간을 쓰는 방식이 곧 가치관이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0107", text: "잃어버린 시간만은 되살 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0108", text: "모든 것에 예라고 답하면 결국 아무것도 못 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0109", text: "거절은 시간을 지키는 가장 정직한 방법이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0110", text: "내일의 나는 오늘의 나보다 한가하지 않다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0111", text: "한 번에 하나씩이 가장 빠른 길이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0112", text: "중요한 일에는 가장 좋은 시간을 배정하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0113", text: "시간이 없는 게 아니라 순서가 없는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0114", text: "일정을 정하지 않으면 남이 정해 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0115", text: "미루기는 시간을 아끼는 게 아니라 이자를 붙인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0116", text: "짧은 시간에 집중하는 편이 긴 시간을 흘려보내는 것보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0117", text: "계획은 시간을 늘려 주지 않지만 낭비를 줄여 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0118", text: "오늘 저녁의 30분이 내일 아침의 두 시간을 벌어 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0119", text: "마감은 적이 아니라 가장 성실한 동료다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0120", text: "시간을 벌고 싶다면 먼저 정리하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0121", text: "하루를 잘게 쪼개면 인생이 넓어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0122", text: "기다리는 시간도 당신의 시간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0123", text: "바쁨은 성취가 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0124", text: "일주일을 설계하면 한 해가 달라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0125", text: "가장 값비싼 낭비는 무엇을 할지 고민하는 시간이다.", category: "wisdom", language: "ko" },
  // ── 자기 믿음 / Self-Belief ─────────────────────────
  { id: "cu_ko_0126", text: "스스로를 믿지 않으면 누구도 대신 믿어 주지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0127", text: "남의 기준으로 살면 남의 인생을 사는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0128", text: "자신에게 하는 말이 가장 오래 남는 말이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0129", text: "당신의 가치는 남의 평가로 정해지지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0130", text: "자신감은 성공의 결과가 아니라 시도의 결과다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0131", text: "비교는 성장을 멈추게 하는 가장 조용한 방법이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0132", text: "당신이 스스로 정한 한계가 대부분의 한계다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0133", text: "자기 자신과의 약속을 지키는 사람이 강해진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0134", text: "목소리를 낮추지 마라. 당신의 이야기는 들릴 가치가 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0135", text: "남과 다른 것이 곧 부족한 것은 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0136", text: "누구도 당신만큼 당신의 가능성을 알지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0137", text: "자신을 돌보는 일은 이기심이 아니라 책임이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0138", text: "부족함을 인정하는 것도 자신감의 일부다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0139", text: "당신은 이미 예전의 당신이 부러워하던 사람이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0140", text: "칭찬은 사양해도 성취는 사양하지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0141", text: "자기 확신은 소음 속에서 방향을 지키는 힘이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0142", text: "스스로에게 가혹한 사람이 가장 늦게 성장한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0143", text: "당신의 속도가 곧 당신의 길이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0144", text: "의심이 들 때는 지나온 길을 돌아보라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0145", text: "완벽하지 않아도 시작할 자격은 충분하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0146", text: "남의 성공이 당신의 실패를 뜻하지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0147", text: "자기 신뢰는 작은 약속들의 누적이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0148", text: "당신의 이야기는 아직 절반도 쓰이지 않았다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0149", text: "자격은 주어지는 것이 아니라 만들어 가는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0150", text: "스스로를 응원하는 사람이 끝까지 간다.", category: "wisdom", language: "ko" },
  // ── 성장과 배움 / Growth ─────────────────────────
  { id: "cu_ko_0151", text: "모르는 것을 인정하는 순간부터 배움이 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0152", text: "어제보다 나아졌다면 오늘은 성공한 날이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0153", text: "불편함은 성장의 입구다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0154", text: "질문의 크기가 성장의 크기를 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0155", text: "가르칠 때 가장 많이 배운다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0156", text: "배움에는 정년이 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0157", text: "아는 것과 하는 것 사이의 거리가 실력이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0158", text: "익숙한 곳에는 새로운 것이 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0159", text: "비판은 쓰지만 가장 빠른 지름길이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0160", text: "같은 책도 다른 시기에 읽으면 다른 책이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0161", text: "성장은 직선이 아니라 계단이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0162", text: "배운 것을 써먹지 않으면 배운 것이 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0163", text: "나보다 나은 사람 곁에 있는 것이 가장 빠른 학습이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0164", text: "모방은 창조의 첫 번째 연습이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0165", text: "초심자의 서투름은 부끄러움이 아니라 증거다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0166", text: "피드백을 견디는 힘이 실력을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0167", text: "배움을 멈춘 순간부터 늙기 시작한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0168", text: "깊이는 시간이 만들고, 넓이는 호기심이 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0169", text: "기록하지 않은 경험은 절반만 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0170", text: "모든 전문성은 처음에 낯선 단어에서 시작했다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0171", text: "배움은 채우는 일이자 비우는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0172", text: "어려운 책이 쉬운 책보다 오래 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0173", text: "성장하려면 잘하는 일 옆에 못하는 일을 두어야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0174", text: "오늘 이해한 것을 내일 설명할 수 있어야 진짜다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0175", text: "경험은 시간이 아니라 반성에서 온다.", category: "wisdom", language: "ko" },
  // ── 목표와 비전 / Vision ─────────────────────────
  { id: "cu_ko_0176", text: "목적지가 없으면 어떤 바람도 순풍이 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0177", text: "목표는 종이에 적히는 순간 계획이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0178", text: "큰 꿈은 작은 마감으로 이루어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0179", text: "어디로 가는지 알면 속도는 문제가 되지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0180", text: "측정할 수 없는 목표는 소원일 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0181", text: "목표를 낮추지 말고 방법을 바꿔라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0182", text: "비전은 오늘의 고단함에 의미를 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0183", text: "남의 목표를 좇으면 도착해도 공허하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0184", text: "목표는 방향이고, 습관은 엔진이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0185", text: "10년 뒤를 생각하면 오늘의 선택이 쉬워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0186", text: "많은 목표는 목표가 없는 것과 같다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0187", text: "이루고 싶은 것보다 되고 싶은 사람을 먼저 정하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0188", text: "계획은 바뀌어도 방향은 유지하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0189", text: "눈에 보이는 목표가 눈에 보이는 결과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0190", text: "도달할 수 없어 보이는 목표만이 사람을 키운다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0191", text: "목표를 쪼개면 두려움도 함께 쪼개진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0192", text: "성취한 뒤가 아니라 정한 순간부터 달라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0193", text: "목표 없는 노력은 물레방아처럼 제자리를 돈다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0194", text: "가장 위험한 목표는 너무 쉬운 목표다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0195", text: "목표를 공개하면 책임이 따라온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0196", text: "매일의 목표가 평생의 목표를 지탱한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0197", text: "무엇을 원하는지 모르면 무엇을 얻어도 부족하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0198", text: "목표는 지도이고, 실행은 신발이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0199", text: "끝을 그려 놓고 시작하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0200", text: "이루지 못한 목표도 당신을 어딘가로 데려간다.", category: "wisdom", language: "ko" },
  // ── 용기와 두려움 / Courage ─────────────────────────
  { id: "cu_ko_0201", text: "용기는 두려움이 없는 상태가 아니라 두려움과 함께 걷는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0202", text: "가장 큰 위험은 아무 위험도 감수하지 않는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0203", text: "두려움은 대개 상상 속에서만 존재한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0204", text: "피하고 싶은 그 일이 대개 해야 할 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0205", text: "용기는 근육처럼 쓸수록 커진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0206", text: "거절당하는 것은 사라지는 것이 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0207", text: "물어보지 않으면 답은 언제나 아니오다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0208", text: "두려움을 말로 꺼내면 절반이 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0209", text: "안전지대는 편안하지만 아무것도 자라지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0210", text: "후회는 실패보다 오래간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0211", text: "용기는 크게 소리치는 것이 아니라 조용히 다시 하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0212", text: "모르는 길에서만 새로운 풍경을 본다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0213", text: "남의 시선은 당신의 인생 비용을 내주지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0214", text: "불확실함을 견디는 능력이 기회를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0215", text: "한 번 용기를 내면 다음 용기는 쉬워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0216", text: "두려움은 나침반이다. 가리키는 곳에 성장이 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0217", text: "위험을 계산하되 두려움에 굴복하지는 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0218", text: "겁이 나는데도 한 걸음 내딛는 것이 성장이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0219", text: "아무도 도전하지 않은 자리에 가장 큰 공간이 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0220", text: "실패보다 시도조차 하지 않은 날들이 더 아프다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0221", text: "용기는 확신이 아니라 결심에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0222", text: "약해 보이는 것을 두려워하면 강해질 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0223", text: "모든 큰 변화는 불편한 대화에서 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0224", text: "두려움에 이름을 붙이면 크기가 줄어든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0225", text: "용기 있는 하루가 평범한 일 년보다 길다.", category: "wisdom", language: "ko" },
  // ── 태도와 마인드셋 / Mindset ─────────────────────────
  { id: "cu_ko_0226", text: "같은 상황도 해석에 따라 다른 결과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0227", text: "아직 못 한다는 말 뒤에 아직이라는 단어를 붙여라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0228", text: "문제를 문제로만 보면 문제만 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0229", text: "태도는 능력보다 먼저 눈에 띈다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0230", text: "불평은 상황을 바꾸지 못하고 에너지만 가져간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0231", text: "통제할 수 있는 것에만 감정을 쓰라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0232", text: "운은 준비된 태도 위에 내려앉는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0233", text: "모든 일이 나에게 유리하게 흘러가지 않아도 괜찮다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0234", text: "생각의 방향이 발의 방향을 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0235", text: "겸손은 배움의 문을 열어 두는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0236", text: "남 탓을 멈추는 순간 힘이 돌아온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0237", text: "기대를 낮추면 실망도 줄고 노력도 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0238", text: "긍정은 현실을 외면하는 것이 아니라 해법을 찾는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0239", text: "배우려는 사람에게는 모든 사람이 스승이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0240", text: "결과보다 과정을 사랑하면 오래 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0241", text: "말버릇이 인생의 방향을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0242", text: "여유는 시간이 아니라 마음의 문제다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0243", text: "나쁜 하루가 나쁜 인생을 뜻하지는 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0244", text: "받아들일 것과 바꿀 것을 구분하는 것이 지혜다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0245", text: "화를 내는 데 쓴 시간은 해결에 쓰지 못한 시간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0246", text: "가진 것을 세는 사람이 더 많이 갖게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0247", text: "성숙은 반응 대신 선택하는 능력이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0248", text: "모르는 것을 부끄러워하지 말고 묻지 않는 것을 부끄러워하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0249", text: "어려운 일을 맡았다는 건 신뢰받고 있다는 뜻이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0250", text: "생각을 바꾸면 세상이 바뀌는 것이 아니라 보이는 것이 바뀐다.", category: "wisdom", language: "ko" },
  // ── 실행과 행동 / Action ─────────────────────────
  { id: "cu_ko_0251", text: "아이디어는 흔하고 실행은 드물다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0252", text: "생각만 하는 사람과 하는 사람의 차이는 하루면 드러난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0253", text: "움직이는 배만 방향을 바꿀 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0254", text: "초안이 걸작보다 낫다. 존재하기 때문이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0255", text: "완벽주의는 게으름의 가장 우아한 변명이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0256", text: "오늘의 실행이 내일의 자신감이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0257", text: "결정을 미루는 것도 결정이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0258", text: "한 시간의 실행이 한 달의 계획보다 많은 것을 알려 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0259", text: "작게 시작하고 빠르게 고쳐라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0260", text: "말은 계획을 만들고 행동은 결과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0261", text: "하려는 마음보다 하고 있는 손이 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0262", text: "시도한 뒤에야 무엇이 문제인지 알 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0263", text: "고민의 90퍼센트는 실행하면 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0264", text: "아무도 당신의 계획을 대신 실행해 주지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0265", text: "시작 버튼은 언제나 손 안에 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0266", text: "출시하지 않은 제품은 존재하지 않는 제품이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0267", text: "다섯 번 생각하고 한 번 움직이면 늦는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0268", text: "행동은 불안을 이기는 유일한 약이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0269", text: "끝내는 사람이 시작하는 사람보다 귀하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0270", text: "작은 실행이 큰 확신을 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0271", text: "일단 내놓아라. 완성은 반응 속에서 이루어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0272", text: "기록으로만 남은 아이디어는 죽은 아이디어다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0273", text: "해 보기 전까지 어려움은 언제나 과장된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0274", text: "바로 지금이 언제나 가장 좋은 타이밍이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0275", text: "하루에 하나만 끝내도 일 년이면 삼백육십다섯 개다.", category: "wisdom", language: "ko" },
  // ── 집중과 몰입 / Focus ─────────────────────────
  { id: "cu_ko_0276", text: "주의를 흩뜨리는 것을 줄이는 것이 능력을 키우는 것보다 빠르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0277", text: "한 가지에 집중한 한 시간이 산만한 하루를 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0278", text: "모든 것을 하려는 사람은 아무것도 깊이 하지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0279", text: "집중은 재능이 아니라 훈련이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0280", text: "알림을 끄는 것이 의지력을 기르는 것보다 쉽다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0281", text: "깊이 있는 결과는 방해받지 않은 시간에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0282", text: "멀티태스킹은 여러 가지를 못하는 가장 빠른 방법이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0283", text: "책상 위의 어수선함은 머릿속의 어수선함이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0284", text: "시작하는 데 필요한 건 의욕이 아니라 5분이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0285", text: "몰입은 자신을 잊는 순간에 찾아온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0286", text: "하나를 끝내고 다음으로 넘어가는 사람이 가장 빠르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0287", text: "집중력은 저장되지 않는다. 오늘 써야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0288", text: "중요한 일에는 방해받지 않을 권리가 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0289", text: "선택지가 적을수록 더 멀리 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0290", text: "잘하는 일 하나가 그럭저럭한 일 열보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0291", text: "주의는 가장 값비싼 자산이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0292", text: "잠깐의 확인이 한 시간의 흐름을 끊는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0293", text: "고요함 속에서 가장 좋은 생각이 태어난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0294", text: "무엇을 볼지 정하는 것이 무엇을 얻을지 정하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0295", text: "산만함은 실패가 아니라 설계의 문제다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0296", text: "한 번에 한 걸음이 언제나 가장 확실하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0297", text: "중요한 것을 먼저 넣어야 남은 것이 들어간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0298", text: "목표가 선명할수록 유혹은 흐려진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0299", text: "쉬는 것도 집중의 일부다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0300", text: "중요한 일을 마친 뒤에야 나머지가 제자리를 찾는다.", category: "wisdom", language: "ko" },
  // ── 규율과 절제 / Discipline ─────────────────────────
  { id: "cu_ko_0301", text: "자유는 규율의 끝에서 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0302", text: "하고 싶은 것을 참는 힘이 원하는 것을 얻게 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0303", text: "규율은 미래의 나를 위한 오늘의 배려다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0304", text: "기분이 결정을 지배하게 두지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0305", text: "절제는 결핍이 아니라 선택이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0306", text: "편한 길을 고르면 삶이 어려워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0307", text: "스스로를 다스리는 사람이 가장 강한 사람이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0308", text: "매일의 절제가 평생의 자유를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0309", text: "하기 싫은 날에도 하는 것이 규율이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0310", text: "한 번의 예외가 열 번의 예외를 부른다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0311", text: "기준을 세우면 매번 고민하지 않아도 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0312", text: "충동은 짧고 후회는 길다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0313", text: "쉬운 결정을 반복하면 어려운 인생이 온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0314", text: "절제는 참는 것이 아니라 더 큰 것을 고르는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0315", text: "규칙이 있는 삶이 더 넉넉하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0316", text: "의지력에 기대지 말고 구조를 만들어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0317", text: "잠을 이기려 하지 말고 관리하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0318", text: "하루의 규율이 십 년의 결과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0319", text: "가장 어려운 일은 자기와의 싸움에서 이기는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0320", text: "미루지 않는 것이 최고의 재테크다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0321", text: "절제된 사람만이 큰 기회를 감당할 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0322", text: "당신의 하루는 당신이 허락한 것들로 채워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0323", text: "욕망을 이해하면 다스리기 쉬워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0324", text: "불편함을 견디는 시간이 곧 성장의 시간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0325", text: "약속 시간을 지키는 사람은 신뢰도 지킨다.", category: "wisdom", language: "ko" },
  // ── 사람과 관계 / Relationships ─────────────────────────
  { id: "cu_ko_0326", text: "혼자 가면 빠르지만 함께 가면 멀리 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0327", text: "주변 다섯 사람의 평균이 당신이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0328", text: "신뢰는 쌓는 데 몇 년, 무너지는 데 몇 초다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0329", text: "듣는 사람이 결국 더 많이 얻는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0330", text: "받은 도움은 잊지 말고 준 도움은 잊어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0331", text: "사람을 이기려 하지 말고 문제를 이겨라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0332", text: "좋은 관계는 시간이 아니라 진심으로 유지된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0333", text: "누구를 만나느냐가 무엇을 아느냐만큼 중요하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0334", text: "먼저 베푸는 사람이 결국 가장 많이 받는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0335", text: "말을 아끼면 신뢰가 늘어난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0336", text: "비난 대신 질문을 하면 관계가 산다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0337", text: "약속을 지키는 것이 가장 강력한 마케팅이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0338", text: "사람을 남기는 사람이 결국 성공한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0339", text: "경청은 가장 저평가된 리더십이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0340", text: "고마움은 표현될 때 비로소 존재한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0341", text: "누군가의 성장을 돕는 일이 자신을 가장 크게 키운다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0342", text: "사과는 늦을수록 비싸진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0343", text: "기억되고 싶다면 이름을 먼저 기억하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0344", text: "모두를 만족시키려는 사람은 아무도 만족시키지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0345", text: "좋은 동료는 최고의 복지다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0346", text: "거리를 두는 것도 관계를 지키는 방법이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0347", text: "타인의 성공을 축하할 줄 아는 사람이 크게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0348", text: "말투가 내용보다 오래 기억된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0349", text: "혼자만 잘하려는 사람은 결국 혼자 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0350", text: "의견이 달라도 사람을 존중할 수는 있다.", category: "wisdom", language: "ko" },
  // ── 리더십과 영향력 / Leadership ─────────────────────────
  { id: "cu_ko_0351", text: "리더십은 직책이 아니라 태도다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0352", text: "먼저 움직이는 사람이 리더가 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0353", text: "말로 이끌지 말고 등으로 이끌어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0354", text: "좋은 리더는 공을 나누고 책임을 가져간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0355", text: "사람은 지시를 따르지 않고 신뢰를 따른다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0356", text: "팀의 수준은 리더가 허용한 기준이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0357", text: "질문하는 리더가 배우는 조직을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0358", text: "영향력은 요구하는 것이 아니라 얻어지는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0359", text: "칭찬은 공개적으로, 지적은 조용히.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0360", text: "사람을 키우는 것이 리더의 가장 큰 성과다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0361", text: "리더의 침착함은 팀 전체의 안전망이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0362", text: "모범은 백 번의 훈시보다 강하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0363", text: "가장 좋은 리더는 자신이 필요 없게 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0364", text: "권한은 나누고 기준은 지켜라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0365", text: "리더의 시간이 조직의 우선순위를 말해 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0366", text: "나쁜 소식이 빨리 올라오는 조직이 건강하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0367", text: "결정하지 않는 리더가 가장 위험하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0368", text: "리더는 답을 주기보다 방향을 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0369", text: "신뢰받는 사람만이 변화를 이끌 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0370", text: "잘못을 인정하는 리더가 팀을 강하게 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0371", text: "말한 것을 지키는 것이 리더십의 전부다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0372", text: "사람을 믿으면 사람은 그만큼 자란다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0373", text: "가장 조용한 사람의 의견을 먼저 물어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0374", text: "리더의 성장이 멈추면 조직의 성장도 멈춘다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0375", text: "영향력은 크기가 아니라 방향이 중요하다.", category: "wisdom", language: "ko" },
  // ── 창의와 혁신 / Creativity ─────────────────────────
  { id: "cu_ko_0376", text: "새로운 것은 낯선 조합에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0377", text: "나쁜 아이디어 백 개가 좋은 아이디어 하나를 데려온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0378", text: "질문을 바꾸면 답이 바뀐다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0379", text: "창의성은 영감이 아니라 습관의 산물이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0380", text: "제약이 많을수록 창의적인 답이 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0381", text: "다르게 보는 것이 더 열심히 보는 것보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0382", text: "모든 혁신은 처음에 무모해 보였다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0383", text: "익숙한 문제를 낯설게 보는 것이 시작이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0384", text: "메모하지 않은 아이디어는 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0385", text: "경계 위에 서 있는 사람이 새로운 것을 본다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0386", text: "산책은 회의보다 좋은 아이디어를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0387", text: "기존의 답을 의심하는 것이 혁신의 출발점이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0388", text: "서로 다른 분야를 잇는 사람이 가장 창의적이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0389", text: "처음 만든 것은 언제나 부끄럽다. 그래도 만들어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0390", text: "아이디어는 소유가 아니라 실행으로 증명된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0391", text: "남과 같은 방식으로는 남과 다른 결과를 얻을 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0392", text: "호기심은 가장 오래 쓸 수 있는 도구다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0393", text: "버려지는 아이디어가 많을수록 남는 아이디어가 좋다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0394", text: "창작의 적은 비판이 아니라 무관심이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0395", text: "다양한 사람과 일하면 생각의 폭이 넓어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0396", text: "틀을 알아야 틀을 깰 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0397", text: "가장 좋은 아이디어는 대개 두 번째 시도에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0398", text: "쓸모없어 보이는 지식이 나중에 연결된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0399", text: "생각을 손으로 옮기면 비로소 검증할 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0400", text: "따라 하다 보면 자기만의 길이 보인다.", category: "wisdom", language: "ko" },
  // ── 돈과 부 / Wealth ─────────────────────────
  { id: "cu_ko_0401", text: "버는 법보다 지키는 법이 어렵다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0402", text: "지출을 통제하지 못하면 수입도 소용없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0403", text: "시간을 사는 데 돈을 쓰는 것이 가장 좋은 소비다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0404", text: "부는 소득이 아니라 습관에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0405", text: "가장 확실한 투자는 자기 자신이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0406", text: "일찍 시작한 저축은 늦게 시작한 큰돈을 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0407", text: "빚은 미래의 자유를 미리 쓰는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0408", text: "남을 위해 만든 가치만큼 돌아온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0409", text: "빠른 부는 대개 빠르게 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0410", text: "모르는 곳에 투자하는 것은 투자가 아니라 도박이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0411", text: "검소함은 가난이 아니라 선택이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0412", text: "돈은 좋은 도구이자 나쁜 주인이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0413", text: "수입원이 하나뿐이면 인생도 하나의 위험에 걸려 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0414", text: "복리는 조급한 사람에게 보답하지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0415", text: "남과 비교하는 지출이 가장 비싸다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0416", text: "가격은 지불하는 것이고 가치는 얻는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0417", text: "기록하지 않은 돈은 새어 나간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0418", text: "경제적 자유란 하기 싫은 일을 거절할 힘이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0419", text: "버는 속도보다 배우는 속도가 중요하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0420", text: "충분함을 아는 사람이 진짜 부자다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0421", text: "위험을 이해하지 못하면 수익도 지킬 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0422", text: "절약은 수비이고 투자는 공격이다. 둘 다 필요하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0423", text: "돈으로 살 수 없는 것을 먼저 지켜라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0424", text: "작은 지출의 반복이 큰 지출보다 무섭다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0425", text: "성공한 사람들은 대체로 지루하게 투자한다.", category: "wisdom", language: "ko" },
  // ── 건강과 균형 / Health ─────────────────────────
  { id: "cu_ko_0426", text: "건강은 잃기 전까지 가장 저평가된 자산이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0427", text: "잠은 게으름이 아니라 성과의 조건이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0428", text: "몸을 돌보지 않으면 결국 몸이 일정을 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0429", text: "매일 걷는 30분이 미래의 병상을 줄인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0430", text: "쉬는 것은 멈추는 것이 아니라 준비하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0431", text: "성과는 체력 위에 쌓인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0432", text: "번아웃은 열심히 한 벌이 아니라 균형의 신호다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0433", text: "천천히 먹는 습관이 오래 사는 습관이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0434", text: "일과 삶은 저울이 아니라 리듬이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0435", text: "몸이 보내는 작은 신호를 무시하지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0436", text: "운동은 오늘의 부담이자 내일의 저축이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0437", text: "스트레스는 없애는 것이 아니라 다루는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0438", text: "주말의 회복이 주중의 성과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0439", text: "가장 성실한 투자는 매일의 잠과 물이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0440", text: "아픈 뒤에 쉬는 것보다 아프기 전에 쉬는 것이 싸다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0441", text: "하루 한 번은 화면에서 눈을 떼라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0442", text: "산책은 가장 저렴한 상담이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0443", text: "몸이 편해야 마음도 정리된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0444", text: "무리한 하루는 사흘의 회복을 부른다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0445", text: "가족과의 저녁 식사는 일정에 넣을 가치가 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0446", text: "취미는 사치가 아니라 유지비다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0447", text: "숨을 고르는 시간이 속도를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0448", text: "잘 쉰 사람이 잘 결정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0449", text: "평생 쓸 몸은 하나뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0450", text: "바쁠수록 규칙적으로 먹고 자라.", category: "wisdom", language: "ko" },
  // ── 감사와 마음 / Gratitude ─────────────────────────
  { id: "cu_ko_0451", text: "가진 것을 세어 보는 순간 부족함이 줄어든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0452", text: "감사는 습관이 될 때 힘이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0453", text: "평범한 하루가 누군가에게는 간절한 하루다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0454", text: "불평의 목록보다 감사의 목록이 길어야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0455", text: "고마움을 늦게 말하면 절반만 전해진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0456", text: "작은 것에 기뻐하는 능력이 삶의 질을 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0457", text: "비교를 멈추면 만족이 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0458", text: "당연한 것은 없다. 다만 익숙해졌을 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0459", text: "오늘 무사히 지나간 하루도 성취다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0460", text: "감사는 과거를 정리하고 미래를 가볍게 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0461", text: "누군가의 수고 덕분에 오늘의 편안함이 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0462", text: "마음이 넉넉한 사람은 나눌 것이 늘 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0463", text: "용서는 상대가 아니라 나를 위한 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0464", text: "하루를 감사로 마치면 다음 날이 가벼워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0465", text: "받은 친절은 다른 사람에게 흘려보내라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0466", text: "기쁨은 크기가 아니라 빈도의 문제다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0467", text: "불안한 마음에는 감사가 가장 좋은 해독제다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0468", text: "말 한마디의 따뜻함은 오래 기억된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0469", text: "충분히 가졌음을 아는 것이 가장 큰 소득이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0470", text: "기억할수록 감사할 일이 많아진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0471", text: "남을 위한 마음이 결국 나를 지켜 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0472", text: "칭찬은 아껴 두면 유통기한이 지나 버린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0473", text: "감사할 줄 아는 사람 곁에는 사람이 모인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0474", text: "하루에 세 가지만 적어도 마음이 달라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0475", text: "고생 끝의 기쁨은 두 배로 진하다.", category: "wisdom", language: "ko" },
  // ── 인생과 의미 / Life ─────────────────────────
  { id: "cu_ko_0476", text: "인생은 속도가 아니라 방향이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0477", text: "가장 아까운 시간은 남의 인생을 부러워하는 시간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0478", text: "의미는 발견되는 것이 아니라 만들어지는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0479", text: "무엇을 남길지 생각하면 오늘이 달라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0480", text: "잘 사는 것은 잘 선택하는 일의 반복이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0481", text: "삶의 크기는 감당한 책임의 크기와 같다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0482", text: "끝을 생각하면 사소한 것에 덜 흔들린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0483", text: "오늘 하루가 인생의 축소판이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0484", text: "무엇을 하느냐보다 왜 하느냐가 오래간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0485", text: "가장 큰 성공은 자기다운 삶을 사는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0486", text: "누군가에게 도움이 된 하루는 헛되지 않다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0487", text: "삶은 계획대로 되지 않지만 방향대로는 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0488", text: "가진 것보다 나눈 것이 오래 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0489", text: "후회 없는 삶이 아니라 후회를 줄이는 삶을 살라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0490", text: "늦은 나이는 없다. 늦은 결심만 있을 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0491", text: "잘 산 하루가 모여 잘 산 인생이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0492", text: "남과 다른 길을 가면 남과 다른 풍경을 본다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0493", text: "사랑하는 일에 시간을 쓰는 것이 최고의 사치다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0494", text: "고통은 지나가지만 배움은 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0495", text: "가장 소중한 것들은 대개 조용히 곁에 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0496", text: "누구의 인생도 완벽하지 않다. 다만 각자 다를 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0497", text: "삶은 한 번뿐이지만 매일 새로 시작할 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0498", text: "지금 이 순간이 언젠가 그리워질 시절이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0499", text: "어떻게 기억될지가 어떻게 살지를 알려 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0500", text: "살아 있다는 것 자체가 아직 기회가 남았다는 뜻이다.", category: "wisdom", language: "ko" },
  // ── 준비와 기본기 / Fundamentals ─────────────────────────
  { id: "cu_ko_0501", text: "기본기는 화려하지 않지만 무너지지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0502", text: "고수는 어려운 것을 잘하는 사람이 아니라 쉬운 것을 완벽히 하는 사람이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0503", text: "준비된 사람에게 기회는 우연이 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0504", text: "무대 위 3분은 무대 뒤 3년으로 만들어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0505", text: "지루한 반복을 견딘 사람만 무대에 오른다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0506", text: "급할수록 기초로 돌아가라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0507", text: "연습은 실전을 닮을수록 값지다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0508", text: "칼을 갈 시간을 아끼면 나무를 베는 시간이 길어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0509", text: "잘하는 사람은 준비를 지루해하지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0510", text: "기초가 흔들리면 위로 쌓을수록 위험해진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0511", text: "실력은 컨디션이 나쁜 날 드러난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0512", text: "천 번의 연습이 한 번의 확신을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0513", text: "자신 없는 부분을 먼저 연습하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0514", text: "배운 것을 몸이 기억할 때까지가 진짜 학습이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0515", text: "서두르는 사람은 두 번 일한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0516", text: "매뉴얼을 아는 사람보다 손에 익은 사람이 강하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0517", text: "기본을 지키는 것이 가장 어려운 고급 기술이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0518", text: "위기에서는 배운 것이 아니라 익숙한 것이 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0519", text: "점검표 하나가 사고 하나를 막는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0520", text: "미리 겪어 본 실수는 실수가 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0521", text: "화려한 기술보다 정확한 자세가 오래 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0522", text: "준비는 불안을 실력으로 바꾸는 과정이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0523", text: "한 번 더 확인하는 습관이 평판을 지킨다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0524", text: "배우는 순서를 지키면 멀리 갈 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0525", text: "기초 공사는 눈에 보이지 않아서 더 정직해야 한다.", category: "wisdom", language: "ko" },
  // ── 선택과 결단 / Decisions ─────────────────────────
  { id: "cu_ko_0526", text: "인생은 선택의 총합이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0527", text: "모든 선택에는 포기하는 것이 따라온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0528", text: "정보가 70퍼센트 모이면 결정하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0529", text: "되돌릴 수 있는 결정은 빠르게, 되돌릴 수 없는 결정은 신중하게.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0530", text: "고민이 길어질수록 답은 이미 정해져 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0531", text: "무엇을 버릴지 정하는 것이 진짜 전략이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0532", text: "선택이 어려운 이유는 둘 다 좋기 때문이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0533", text: "결정한 뒤에는 뒤를 보지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0534", text: "최선의 선택은 없다. 선택을 최선으로 만들 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0535", text: "남이 대신 고른 길에는 책임질 사람이 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0536", text: "어려운 결정을 미루면 쉬운 결정도 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0537", text: "기준이 있으면 선택은 계산이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0538", text: "가장 나쁜 선택은 아무것도 고르지 않는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0539", text: "10분 뒤, 10개월 뒤, 10년 뒤를 함께 보라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0540", text: "많이 아는 것보다 잘 고르는 것이 어렵다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0541", text: "불편한 진실 쪽이 대개 옳은 선택이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0542", text: "선택지가 하나뿐이라면 아직 다 찾지 않은 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0543", text: "누가 반대하느냐보다 왜 반대하는지를 보라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0544", text: "결단은 정보의 문제가 아니라 용기의 문제다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0545", text: "후회할 것 같은 쪽을 먼저 지워라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0546", text: "급할 때 내린 결정은 대개 급하게 후회한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0547", text: "어떤 문을 닫아야 다른 문이 열린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0548", text: "선택의 질은 준비된 대안의 수에 비례한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0549", text: "스스로 고른 어려움은 견딜 만하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0550", text: "모든 문을 열어 두면 어디에도 들어갈 수 없다.", category: "wisdom", language: "ko" },
  // ── 경쟁과 승부 / Competition ─────────────────────────
  { id: "cu_ko_0551", text: "어제의 나를 이기는 것이 가장 정직한 경쟁이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0552", text: "이기는 법보다 지지 않는 법을 먼저 배워라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0553", text: "경쟁자를 보면 따라가고, 고객을 보면 앞서간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0554", text: "승부는 마지막 5분이 아니라 준비된 5개월에서 갈린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0555", text: "남이 쉬는 시간에 만들어지는 것이 격차다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0556", text: "이겨야 할 상대는 대개 자기 안에 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0557", text: "잘하는 사람을 미워하면 배울 기회를 잃는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0558", text: "경기장에 선 사람만이 결과를 말할 자격이 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0559", text: "한 분야에서 1등이 되려면 그 분야를 좁혀라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0560", text: "규칙을 아는 사람이 규칙 안에서 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0561", text: "경쟁이 치열할수록 기본이 승부를 가른다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0562", text: "이기고도 존경받지 못하면 절반만 이긴 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0563", text: "모두가 뛰는 트랙 대신 나만의 트랙을 만들어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0564", text: "졌을 때 무엇을 배웠는지가 다음 경기를 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0565", text: "1등과 2등의 차이는 대개 아주 작은 습관이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0566", text: "남을 깎아내려 오르는 자리는 오래 가지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0567", text: "실력이 비슷할 때는 태도가 결정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0568", text: "승리보다 회복이 빠른 사람이 결국 강하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0569", text: "시장은 노력이 아니라 결과에 값을 매긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0570", text: "자신의 약점을 아는 사람이 상대의 약점도 본다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0571", text: "이기는 습관은 작은 경기에서 만들어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0572", text: "경쟁자가 없다면 시장이 없는 것일 수도 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0573", text: "압박은 준비된 사람에게만 기회가 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0574", text: "긴 승부에서는 체력과 인성이 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0575", text: "자기 기록과 겨루는 사람은 지치지 않는다.", category: "wisdom", language: "ko" },
  // ── 변화와 적응 / Change ─────────────────────────
  { id: "cu_ko_0576", text: "변하지 않는 유일한 것은 변한다는 사실이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0577", text: "살아남는 것은 강한 것이 아니라 맞추는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0578", text: "어제의 정답이 오늘의 오답이 될 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0579", text: "변화를 거부하면 변화가 당신을 선택한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0580", text: "익숙한 방식이 가장 위험한 관성이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0581", text: "새로운 도구를 배우는 비용이 뒤처지는 비용보다 싸다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0582", text: "바람의 방향은 못 바꿔도 돛은 바꿀 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0583", text: "위기는 변화가 문을 두드리는 소리다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0584", text: "버리지 못하면 새로 담을 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0585", text: "과거의 성공이 다음 변화의 가장 큰 걸림돌이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0586", text: "세상은 준비를 기다려 주지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0587", text: "작은 변화를 자주 겪은 사람은 큰 변화에 강하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0588", text: "배운 것을 버릴 줄 아는 것도 능력이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0589", text: "변화의 초기에는 언제나 소음이 크다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0590", text: "적응은 포기가 아니라 생존의 지혜다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0591", text: "모두가 확신할 때는 이미 늦은 때다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0592", text: "바뀌는 환경보다 바뀌지 않는 나를 점검하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0593", text: "불편함은 새로운 방식이 자리 잡는 소리다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0594", text: "기술은 도구일 뿐, 방향은 사람이 정한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0595", text: "같은 자리에 서 있어도 세상이 움직이면 뒤처진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0596", text: "변화의 속도보다 배우는 속도가 빨라야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0597", text: "위기를 겪은 조직이 다음 위기에 강하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0598", text: "계획을 자주 고치는 것은 실패가 아니라 학습이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0599", text: "낯선 것을 먼저 시도해 본 사람이 표준을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0600", text: "변화는 두렵지만 정체는 더 위험하다.", category: "wisdom", language: "ko" },
  // ── 소통과 말 / Communication ─────────────────────────
  { id: "cu_ko_0601", text: "말은 짧을수록 멀리 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0602", text: "이해받고 싶다면 먼저 이해하려고 하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0603", text: "설명이 길어지는 것은 아직 정리되지 않았다는 뜻이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0604", text: "말은 던지는 것이 아니라 전해지는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0605", text: "한 번 뱉은 말은 다시 담을 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0606", text: "상대의 말을 끊지 않는 것만으로 절반은 설득된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0607", text: "어려운 말을 쉽게 하는 사람이 진짜 전문가다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0608", text: "사실을 말하되 상처를 주지 않는 방법을 찾아라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0609", text: "침묵도 하나의 대답이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0610", text: "자주 말하는 사람보다 정확히 말하는 사람이 신뢰받는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0611", text: "같은 내용도 순서를 바꾸면 다르게 들린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0612", text: "질문은 대화를 열고 단정은 대화를 닫는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0613", text: "잘 쓴 한 문장이 긴 회의보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0614", text: "말투는 내용을 담는 그릇이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0615", text: "모른다고 말하는 것이 신뢰를 가장 빨리 쌓는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0616", text: "상대가 이해할 언어로 말하는 것이 배려다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0617", text: "감정이 격할 때는 말을 하루 미뤄라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0618", text: "글로 정리되지 않는 생각은 말로도 흐릿하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0619", text: "칭찬은 구체적일수록 진심으로 들린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0620", text: "경청은 동의가 아니라 존중이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0621", text: "먼저 결론을 말하고 이유를 덧붙여라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0622", text: "말이 아니라 반응을 보고 소통 여부를 판단하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0623", text: "비판은 행동에, 존중은 사람에게 향해야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0624", text: "어려운 말을 꺼내는 5분이 몇 달을 아껴 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0625", text: "좋은 질문 하나가 좋은 답 열 개보다 낫다.", category: "wisdom", language: "ko" },
  // ── 협업과 팀워크 / Teamwork ─────────────────────────
  { id: "cu_ko_0626", text: "한 사람의 천재보다 열 사람의 합이 강하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0627", text: "팀의 속도는 가장 느린 연결에서 정해진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0628", text: "역할이 분명하면 갈등이 줄어든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0629", text: "서로의 강점을 아는 팀이 위기에서 강하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0630", text: "누가 옳은지보다 무엇이 옳은지를 따져라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0631", text: "정보를 나누는 팀이 실수를 덜 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0632", text: "내가 없어도 돌아가는 구조를 만들어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0633", text: "함께 일하기 좋은 사람이 되는 것도 실력이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0634", text: "같은 목표를 보면 다른 방법도 견딜 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0635", text: "공을 다투는 팀은 오래 가지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0636", text: "도움을 요청하는 것도 협업의 기술이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0637", text: "모두가 말할 수 있는 회의가 좋은 회의다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0638", text: "중복은 낭비지만 겹치는 이해는 안전장치다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0639", text: "약속한 일정을 지키는 것이 최고의 협업이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0640", text: "팀의 문화는 허용된 최악의 행동으로 정해진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0641", text: "기여를 눈에 보이게 만들면 동기가 살아난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0642", text: "비난 없는 회고가 다음 성과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0643", text: "각자 잘하는 일을 하면 전체가 빨라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0644", text: "고맙다는 말은 팀의 윤활유다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0645", text: "합의 없이 시작하면 두 번 일하게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0646", text: "가장 좋은 팀은 서로의 실수를 덮어 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0647", text: "권한 없는 책임은 사람을 지치게 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0648", text: "공동의 적보다 공동의 목표가 오래 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0649", text: "말하지 않은 기대는 반드시 어긋난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0650", text: "혼자 해결하려는 고집이 팀을 느리게 만든다.", category: "wisdom", language: "ko" },
  // ── 일과 장인정신 / Craft ─────────────────────────
  { id: "cu_ko_0651", text: "어떤 일이든 끝까지 다듬는 사람이 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0652", text: "디테일은 아무도 안 볼 때 드러난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0653", text: "작은 일을 대하는 태도가 큰 일을 맡을 자격이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0654", text: "보수와 상관없이 최선을 다한 일이 이력이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0655", text: "자기 이름을 걸 수 있는 결과물만 내보내라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0656", text: "반복되는 일에도 개선의 여지는 늘 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0657", text: "장인은 도구를 탓하지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0658", text: "마감의 품질이 그 사람의 품격이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0659", text: "일을 사랑하지 않아도 잘할 수는 있지만 오래 하기는 어렵다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0660", text: "같은 일을 십 년 하면 다른 눈이 생긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0661", text: "프로는 기분이 아니라 기준으로 일한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0662", text: "서두른 결과물은 반드시 되돌아온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0663", text: "숙련은 시간이 아니라 집중한 시간의 총량이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0664", text: "남이 대충 넘어간 곳에서 차이가 생긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0665", text: "일의 의미는 주어지지 않고 자기가 붙인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0666", text: "고쳐 쓴 흔적이 많을수록 좋은 결과물이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0667", text: "자기 일을 설명할 수 있어야 진짜 아는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0668", text: "남는 것은 결과물이지 변명이 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0669", text: "처음과 끝을 스스로 책임지는 사람이 성장한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0670", text: "잘 만든 것은 설명이 필요 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0671", text: "일에 대한 자부심은 태도에서 새어 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0672", text: "손이 느려도 정확한 사람이 결국 빠르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0673", text: "일의 마지막 10퍼센트가 품질의 90퍼센트다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0674", text: "누군가 볼 것이라 생각하고 만들면 결국 누군가 본다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0675", text: "일터에서의 정직이 가장 확실한 경력 관리다.", category: "wisdom", language: "ko" },
  // ── 독서와 지식 / Reading ─────────────────────────
  { id: "cu_ko_0676", text: "한 권의 책은 한 사람의 인생을 압축한 파일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0677", text: "읽지 않은 사람은 자기 경험 안에서만 산다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0678", text: "지식은 쌓는 것이 아니라 연결하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0679", text: "밑줄만 긋고 덮은 책은 읽지 않은 책이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0680", text: "한 권을 세 번 읽는 것이 세 권을 한 번 읽는 것보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0681", text: "모르는 분야의 책이 가장 크게 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0682", text: "읽은 뒤 한 줄이라도 실천하면 그 책은 값을 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0683", text: "정보는 넘치지만 이해는 여전히 귀하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0684", text: "검색은 답을 주고 독서는 질문을 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0685", text: "좋은 책은 읽는 속도를 늦추게 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0686", text: "아는 것이 많아질수록 모르는 것도 늘어난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0687", text: "메모 없는 독서는 물을 체로 뜨는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0688", text: "어려운 문장을 견디는 힘이 사고력을 키운다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0689", text: "고전이 살아남은 이유는 여전히 유용하기 때문이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0690", text: "남의 생각을 읽는 시간이 내 생각을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0691", text: "한 페이지라도 매일 읽는 사람을 이길 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0692", text: "지식은 나눌수록 줄지 않고 늘어난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0693", text: "읽는 목적이 분명하면 속도는 저절로 붙는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0694", text: "출처를 확인하는 습관이 판단력을 지킨다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0695", text: "다 읽지 못한 책도 읽은 만큼 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0696", text: "같은 문장을 다르게 이해하는 것이 성장의 증거다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0697", text: "책값보다 비싼 것은 읽지 않은 시간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0698", text: "배운 것을 남에게 설명할 때 지식이 내 것이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0699", text: "서점에 자주 가는 사람은 생각이 늙지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0700", text: "읽지 않고 판단하면 편견만 굳어진다.", category: "wisdom", language: "ko" },
  // ── 리스크와 불확실성 / Risk ─────────────────────────
  { id: "cu_ko_0701", text: "모든 것이 확실해질 때까지 기다리면 아무것도 남지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0702", text: "감당할 수 있는 크기의 위험만 감수하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0703", text: "최악을 계산해 두면 두려움이 줄어든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0704", text: "한 번에 전부를 걸지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0705", text: "위험을 피하는 것도 하나의 위험이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0706", text: "되돌릴 수 있는 실험은 많이 할수록 좋다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0707", text: "불확실성은 없애는 것이 아니라 줄이는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0708", text: "안전장치를 먼저 만든 뒤에 뛰어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0709", text: "모두가 안전하다고 말할 때가 가장 위험하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0710", text: "잃어도 되는 만큼만 걸어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0711", text: "계획 B가 있는 사람이 계획 A를 과감하게 실행한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0712", text: "예측하려 하지 말고 대비하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0713", text: "생존이 우선이고 수익은 그다음이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0714", text: "위험은 모르는 데서 오지 아는 데서 오지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0715", text: "한 가지에만 의존하는 구조는 언젠가 무너진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0716", text: "작게 실패해 보는 것이 가장 싼 보험이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0717", text: "확률이 낮아도 손실이 크면 피하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0718", text: "모르는 것을 모른다고 인정하는 것이 첫 번째 방어선이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0719", text: "위기는 예고 없이 오지만 준비는 예고 없이 도와준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0720", text: "모든 달걀을 한 바구니에 담지 않는 이유는 바구니를 못 믿어서다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0721", text: "여유 자금과 여유 시간이 최고의 방패다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0722", text: "불확실한 상황에서는 단순한 원칙이 이긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0723", text: "남들이 두려워할 때 기회가 만들어진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0724", text: "위험을 계량하면 감정이 개입할 자리가 줄어든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0725", text: "배가 항구에 있으면 안전하지만 그것이 배의 목적은 아니다.", category: "wisdom", language: "ko" },
  // ── 정리와 단순함 / Simplicity ─────────────────────────
  { id: "cu_ko_0726", text: "복잡한 것을 단순하게 만드는 것이 실력이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0727", text: "더할 것이 없을 때가 아니라 뺄 것이 없을 때 완성된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0728", text: "물건을 줄이면 결정도 줄어든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0729", text: "공간의 여백이 생각의 여백을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0730", text: "정리는 버리는 기술이 아니라 고르는 기술이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0731", text: "하루의 끝에 책상을 비우면 내일이 가벼워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0732", text: "필요한 것만 남기면 나머지는 다 여유다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0733", text: "많이 가진 사람이 아니라 덜 필요한 사람이 자유롭다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0734", text: "설명이 복잡하면 설계가 잘못된 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0735", text: "규칙은 적을수록 잘 지켜진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0736", text: "자주 쓰는 것만 가까이 두어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0737", text: "미루어 둔 정리는 이자를 붙여 돌아온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0738", text: "기능이 많은 도구보다 손에 맞는 도구가 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0739", text: "목록을 줄이면 실행률이 올라간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0740", text: "단순함은 게으름이 아니라 깊은 이해의 결과다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0741", text: "모으는 즐거움보다 비우는 홀가분함이 오래 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0742", text: "시작 전에 정리하면 일이 절반으로 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0743", text: "이름을 붙이면 찾는 시간이 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0744", text: "가진 것을 다 쓰지 못하면 짐이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0745", text: "단순한 삶은 적게 사는 것이 아니라 분명하게 사는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0746", text: "정리된 파일 하나가 열 번의 회의를 줄인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0747", text: "핵심만 남기면 속도는 저절로 빨라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0748", text: "물건은 공간을, 미련은 마음을 차지한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0749", text: "버리기 어려운 것부터 목록에 올려라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0750", text: "가장 좋은 수납은 사지 않는 것이다.", category: "wisdom", language: "ko" },
  // ── 감정과 평정심 / Equanimity ─────────────────────────
  { id: "cu_ko_0751", text: "감정은 손님이다. 머물게 하되 주인 자리는 주지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0752", text: "화가 났을 때 내린 결정은 대부분 비싸다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0753", text: "숨을 한 번 고르는 것이 최고의 위기관리다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0754", text: "감정을 억누르지 말고 이름을 붙여라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0755", text: "기분은 날씨처럼 지나간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0756", text: "평정심은 무감각이 아니라 균형이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0757", text: "남의 감정까지 내가 책임질 필요는 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0758", text: "불안은 대개 아직 오지 않은 일에 대한 세금이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0759", text: "반응하기 전에 3초를 벌어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0760", text: "감정을 글로 옮기면 크기가 정확해진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0761", text: "타인의 무례가 내 하루를 결정하게 두지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0762", text: "잘 쉬지 못한 마음은 작은 일에도 흔들린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0763", text: "기대를 조정하면 분노도 조정된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0764", text: "슬픔은 없애는 것이 아니라 지나가게 두는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0765", text: "감정의 파도 아래에는 늘 잔잔한 층이 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0766", text: "조용한 사람이 반드시 약한 것은 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0767", text: "참는 것과 다스리는 것은 다르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0768", text: "스스로에게 관대해야 남에게도 관대해진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0769", text: "마음이 급할수록 걸음을 늦춰라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0770", text: "모든 감정에는 알려 주려는 정보가 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0771", text: "후회는 감정이고 교훈은 선택이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0772", text: "기쁨도 슬픔도 오래 머물지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0773", text: "화를 참는 것보다 화가 나는 이유를 아는 것이 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0774", text: "평온한 얼굴은 훈련된 마음의 결과다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0775", text: "오늘의 기분이 오늘의 실력은 아니다.", category: "wisdom", language: "ko" },
  // ── 원칙과 정직 / Integrity ─────────────────────────
  { id: "cu_ko_0776", text: "원칙은 편할 때가 아니라 불편할 때 증명된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0777", text: "정직은 기억할 것이 적어서 편하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0778", text: "한 번의 거짓말은 열 번의 설명을 부른다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0779", text: "아무도 보지 않을 때의 행동이 진짜 성품이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0780", text: "타협할 것과 타협하지 않을 것을 미리 정해 두어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0781", text: "평판은 오랜 시간의 작은 선택들이 쌓인 결과다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0782", text: "이익보다 오래 남는 것은 신용이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0783", text: "규칙을 지키는 비용은 어기는 비용보다 늘 싸다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0784", text: "말과 행동이 같은 사람은 설득할 필요가 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0785", text: "작은 부정직이 큰 신뢰를 무너뜨린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0786", text: "잘못을 빨리 인정하면 손실도 작아진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0787", text: "모두가 그렇게 한다는 말은 이유가 되지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0788", text: "원칙이 있는 사람은 매번 고민하지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0789", text: "약속은 지킬 수 있는 만큼만 하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0790", text: "이름은 가장 오래 쓰는 자산이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0791", text: "정직한 실패가 교묘한 성공보다 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0792", text: "숨겨야 하는 성과는 성과가 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0793", text: "기준을 낮추는 순간 모든 것이 낮아진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0794", text: "양심은 가장 조용하지만 가장 정확한 조언자다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0795", text: "신뢰는 이자를 낳고 불신은 비용을 낳는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0796", text: "불편한 진실을 말해 주는 사람을 곁에 두어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0797", text: "편법으로 얻은 시간은 반드시 되돌려 주게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0798", text: "공짜로 얻은 것에는 늘 값이 붙어 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0799", text: "자신에게 정직하지 못하면 남에게도 그렇게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0800", text: "원칙은 지킬 때보다 세울 때 더 신중해야 한다.", category: "wisdom", language: "ko" },
  // ── 겸손과 자기인식 / Humility ─────────────────────────
  { id: "cu_ko_0801", text: "자신을 아는 것이 모든 지혜의 시작이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0802", text: "가장 위험한 무지는 안다고 착각하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0803", text: "많이 아는 사람일수록 조심스럽게 말한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0804", text: "자만은 성공 직후에 가장 크게 자란다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0805", text: "남의 조언을 듣는 것은 약함이 아니라 절약이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0806", text: "내 관점은 세상의 일부일 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0807", text: "칭찬을 들을 때 가장 조심해야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0808", text: "모르는 것을 물어보는 데 드는 비용은 늘 가장 싸다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0809", text: "자기 실력을 정확히 아는 것도 실력이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0810", text: "성공은 여러 사람의 도움이 겹친 결과다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0811", text: "고개를 숙이면 더 많은 것이 보인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0812", text: "내가 옳다는 확신이 클수록 한 번 더 확인하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0813", text: "자신을 과대평가하면 준비를 게을리하게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0814", text: "다른 의견은 위협이 아니라 정보다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0815", text: "자기 약점을 말할 수 있는 사람이 강한 사람이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0816", text: "경험이 많다는 이유로 배움을 멈추지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0817", text: "나를 가장 오래 속이는 사람은 나 자신이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0818", text: "성찰이 없으면 경력은 반복일 뿐이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0819", text: "겸손은 자기를 낮추는 것이 아니라 정확히 보는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0820", text: "어제의 나를 부끄러워할 수 있다면 성장한 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0821", text: "남의 성공에서 배우고 나의 성공은 의심하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0822", text: "자리는 사람을 크게 보이게 하지만 크게 만들지는 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0823", text: "한계를 아는 사람만이 한계를 넘는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0824", text: "잘 모르겠다는 말이 대화를 깊게 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0825", text: "배울 것이 없어 보이는 사람에게도 배울 것이 있다.", category: "wisdom", language: "ko" },
  // ── 야망과 큰 그림 / Ambition ─────────────────────────
  { id: "cu_ko_0826", text: "작게 생각하는 데도 같은 노력이 든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0827", text: "한계를 정하는 것은 대부분 상상력의 부족이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0828", text: "큰 목표는 좋은 사람들을 끌어당긴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0829", text: "남들이 웃는 계획이 대개 판을 바꾼다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0830", text: "현실적인 목표만 세우면 현실만 반복된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0831", text: "10년의 그림이 있으면 1년의 실패는 견딜 만하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0832", text: "야망은 방향이 있을 때만 힘이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0833", text: "남의 허락을 기다리면 평생 기다리게 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0834", text: "지금의 자원이 아니라 지금의 결심으로 시작하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0835", text: "크게 실패해도 남는 것이 있는 목표를 골라라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0836", text: "목표가 크면 사소한 갈등이 작아 보인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0837", text: "산 정상을 보되 발밑을 확인하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0838", text: "위대한 일은 대부분 지루한 일의 연속이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0839", text: "무엇이 가능한지는 시도해 본 사람만 안다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0840", text: "욕심과 야망의 차이는 누구를 위한 것이냐다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0841", text: "한 세대의 문제를 풀면 이름이 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0842", text: "가장 큰 위험은 목표가 너무 작은 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0843", text: "세상을 바꾸려면 먼저 한 사람을 도와라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0844", text: "비전은 팀에게 나눠 줄 때 커진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0845", text: "불가능해 보이는 일도 나누면 가능한 조각이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0846", text: "지금 하는 일이 5년 뒤 무엇이 되는지 그려 보라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0847", text: "야망 없는 성실은 쳇바퀴가 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0848", text: "롤모델보다 넘어야 할 기준을 정하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0849", text: "큰 꿈은 매일의 작은 규칙 없이는 무너진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0850", text: "무엇을 이루고 싶은지보다 어떤 문제를 풀고 싶은지 물어라.", category: "wisdom", language: "ko" },
  // ── 문제해결 / Problem-Solving ─────────────────────────
  { id: "cu_ko_0851", text: "문제를 정확히 정의하면 절반은 풀린 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0852", text: "증상이 아니라 원인을 고쳐라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0853", text: "왜라는 질문을 다섯 번 반복하면 뿌리가 보인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0854", text: "해결책이 하나뿐이면 아직 충분히 고민하지 않은 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0855", text: "복잡한 문제일수록 종이에 그려라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0856", text: "가장 흔한 실수는 잘못된 문제를 잘 푸는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0857", text: "막힐 때는 문제를 더 작게 쪼개라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0858", text: "모든 제약을 적어 두면 답의 범위가 보인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0859", text: "현장에 답이 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0860", text: "데이터가 없으면 의견 싸움이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0861", text: "해결한 문제를 기록해 두면 다음에 두 배로 빠르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0862", text: "다른 분야의 해법을 빌려 오는 것이 가장 빠르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0863", text: "급한 불을 끄되 소방 시스템도 만들어라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0864", text: "잠시 멈추는 것이 가장 빠른 우회로일 때가 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0865", text: "남의 문제를 풀어 주면 내 문제도 풀린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0866", text: "가정을 적어 두면 어디가 틀렸는지 알 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0867", text: "문제를 남에게 설명하는 순간 답이 보인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0868", text: "모든 해법에는 새로운 문제가 딸려 온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0869", text: "측정하지 않으면 개선했는지 알 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0870", text: "간단한 원인을 먼저 확인하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0871", text: "같은 문제가 반복되면 사람이 아니라 구조를 보라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0872", text: "해결이 어려우면 조건을 바꿔 보라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0873", text: "답을 아는 것보다 답을 찾는 방법을 아는 것이 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0874", text: "어제의 해법이 오늘의 병목이 되기도 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0875", text: "풀리지 않는 문제는 대개 질문이 잘못된 것이다.", category: "wisdom", language: "ko" },
  // ── 기회와 운 / Opportunity ─────────────────────────
  { id: "cu_ko_0876", text: "운은 시도한 횟수에 비례한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0877", text: "기회는 대개 일처럼 생겨서 알아보기 어렵다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0878", text: "운이 좋으려면 먼저 눈에 띄어야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0879", text: "한 번의 기회를 잡으려면 열 번의 준비가 필요하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0880", text: "아는 사람이 많을수록 우연도 많아진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0881", text: "거절당한 자리에 다음 기회가 놓여 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0882", text: "운은 통제할 수 없지만 노출은 통제할 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0883", text: "기회는 준비된 사람의 눈에만 기회로 보인다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0884", text: "작은 부탁을 들어준 인연이 큰 기회가 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0885", text: "기회는 오래 머물지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0886", text: "타이밍이 실력의 일부라는 것을 인정하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0887", text: "남의 성공을 운이라 부르면 배울 것이 사라진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0888", text: "자주 부딪히는 사람에게 기회가 자주 온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0889", text: "운도 실력처럼 관리할 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0890", text: "기회를 놓쳤다면 다음 기회의 준비 시간이 생긴 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0891", text: "남이 하기 싫어하는 일에 기회가 숨어 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0892", text: "열린 마음이 열린 문을 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0893", text: "우연은 준비된 사람에게만 사건이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0894", text: "한 번의 좋은 소개가 일 년의 노력을 아껴 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0895", text: "가능성이 낮아 보여도 문은 두드려 봐야 안다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0896", text: "기회를 만드는 가장 쉬운 방법은 먼저 돕는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0897", text: "기회는 사람을 통해 온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0898", text: "불운을 견딘 사람에게 행운이 의미가 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0899", text: "눈앞의 작은 일을 잘하면 큰 일이 찾아온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0900", text: "준비되지 않은 기회는 오히려 위기다.", category: "wisdom", language: "ko" },
  // ── 성실과 노력 / Diligence ─────────────────────────
  { id: "cu_ko_0901", text: "노력은 배신하지 않지만 방향은 확인해야 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0902", text: "남들이 잘 때 깨어 있는 시간이 격차를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0903", text: "성실은 재능이 없는 사람의 무기가 아니라 재능 있는 사람의 완성이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0904", text: "땀은 거짓말을 하지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0905", text: "열심히 하는 것과 잘하는 것은 다르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0906", text: "보이지 않는 곳에서의 노력이 보이는 결과를 만든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0907", text: "매일 나타나는 것 자체가 이미 상위권이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0908", text: "근면은 운을 부르는 가장 확실한 초대장이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0909", text: "힘든 일을 먼저 맡는 사람이 결국 앞선다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0910", text: "노력의 결과는 늦게 오지만 반드시 온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0911", text: "무명의 시간을 견디는 것도 일의 일부다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0912", text: "남이 안 볼 때 하는 연습이 실전에서 나온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0913", text: "성실은 하루 만에 증명되지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0914", text: "한 번의 최선보다 백 번의 평범한 노력이 낫다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0915", text: "일찍 일어나는 것보다 일찍 시작하는 것이 중요하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0916", text: "노력을 자랑하지 말고 결과로 말하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0917", text: "성실한 사람에게는 다음 일이 온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0918", text: "하기 싫은 마음과 하는 행동은 공존할 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0919", text: "잘하고 싶으면 남들보다 한 번 더 고쳐라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0920", text: "노력은 저축과 같아서 인출 시점을 스스로 정하지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0921", text: "끝까지 마무리하는 사람이 다음에도 불려 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0922", text: "정직한 노동은 언제나 스스로를 지켜 준다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0923", text: "재능을 이기는 것은 재능 있는 사람의 성실이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0924", text: "잘 안 될 때도 계속하는 사람이 결국 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0925", text: "하루의 성실이 평판이 되고 평판이 기회가 된다.", category: "wisdom", language: "ko" },
  // ── 나눔과 기여 / Contribution ─────────────────────────
  { id: "cu_ko_0926", text: "남을 돕는 일은 결국 자신을 돕는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0927", text: "받은 것보다 조금 더 주는 사람이 오래 기억된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0928", text: "가진 것이 적어도 나눌 수는 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0929", text: "지식은 나눌수록 자신이 정확해진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0930", text: "누군가의 사다리가 되어 주는 것이 최고의 성취다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0931", text: "기여는 크기가 아니라 지속성으로 측정된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0932", text: "먼저 주는 사람에게 세상은 관대하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0933", text: "배운 것을 돌려주지 않으면 그 자리에서 멈춘다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0934", text: "이름을 남기려 하지 말고 쓸모를 남겨라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0935", text: "한 사람을 제대로 도우면 그것으로 충분하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0936", text: "공동체가 잘되어야 개인도 오래 잘된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0937", text: "봉사는 시간이 남아서 하는 일이 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0938", text: "말없이 도운 일이 가장 오래 남는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0939", text: "후배에게 길을 알려 주는 것이 길을 넓히는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0940", text: "감사는 갚을 곳이 없으면 다음 사람에게 전하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0941", text: "기부는 금액이 아니라 결심에서 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0942", text: "자신이 겪은 어려움이 남을 돕는 자격이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0943", text: "나눌수록 줄어들지 않는 것들을 먼저 나눠라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0944", text: "주는 습관이 있는 사람 곁은 늘 따뜻하다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0945", text: "사회가 나를 키웠다는 사실을 잊지 마라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0946", text: "누군가의 하루를 가볍게 해 주는 일은 결코 작지 않다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0947", text: "더 나은 상태로 물려주는 것이 세대의 책임이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0948", text: "가르치는 일은 두 사람을 동시에 성장시킨다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0949", text: "사람은 받은 것보다 나눈 것으로 기억된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0950", text: "작은 친절이 누군가의 방향을 바꾼다.", category: "wisdom", language: "ko" },
  // ── 자유와 독립 / Independence ─────────────────────────
  { id: "cu_ko_0951", text: "자기 힘으로 서 본 사람만이 진짜 도움을 줄 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0952", text: "자유에는 언제나 책임이 함께 온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0953", text: "남의 인정이 필요 없어질 때 자유로워진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0954", text: "선택지를 늘리는 것이 자유를 늘리는 일이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0955", text: "의존이 편할수록 자유는 줄어든다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0956", text: "생각의 독립이 가장 어려운 독립이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0957", text: "자기 일정을 스스로 정할 수 있다면 이미 부자다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0958", text: "남의 기준에 맞추다 보면 자기 기준을 잃는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0959", text: "기술을 가진 사람은 어디서든 다시 시작할 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0960", text: "자립은 고립이 아니다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0961", text: "스스로 결정한 삶은 후회의 모양도 다르다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0962", text: "누구에게도 빚지지 않는 하루가 가장 가볍다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0963", text: "자유는 아무것도 안 하는 것이 아니라 원하는 것을 하는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0964", text: "하나의 수입원에 매이면 하나의 목소리만 낼 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0965", text: "스스로 배울 수 있는 사람은 누구에게도 종속되지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0966", text: "자유롭고 싶다면 먼저 단순해져라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0967", text: "규율 없는 자유는 오래가지 못한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0968", text: "남의 인생을 대신 살아 줄 수는 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0969", text: "스스로 책임질 수 있는 만큼만 자유롭다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0970", text: "의견을 바꿀 자유도 자유의 일부다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0971", text: "누구도 당신의 동의 없이 당신을 규정할 수 없다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0972", text: "경제적 독립보다 정신적 독립이 먼저다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0973", text: "남의 시선에서 벗어나면 시간이 늘어난다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0974", text: "스스로 만든 규칙만이 오래 지켜진다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0975", text: "자유의 대가는 불확실성이다.", category: "wisdom", language: "ko" },
  // ── 미래와 희망 / Hope ─────────────────────────
  { id: "cu_ko_0976", text: "희망은 계획이 있을 때 현실이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0977", text: "어두운 밤이 별을 보게 한다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0978", text: "미래는 예측하는 것이 아니라 만드는 것이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0979", text: "아직 오지 않은 날들이 지나간 날들보다 많다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0980", text: "씨앗은 흙 속에서 가장 오래 어둡다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0981", text: "절망은 정보가 부족할 때 가장 크다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0982", text: "내일을 준비하는 사람에게 오늘은 투자다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0983", text: "희망은 감정이 아니라 태도다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0984", text: "끝나 보이는 곳에서 새 길이 시작된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0985", text: "다음 세대를 생각하는 결정이 가장 멀리 간다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0986", text: "계절은 반드시 바뀐다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0987", text: "오늘 심은 나무의 그늘은 내일 사람이 쓴다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0988", text: "버티는 동안에도 세상은 조금씩 바뀐다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0989", text: "기대는 배신할 수 있지만 준비는 배신하지 않는다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0990", text: "낙관은 근거를 찾을 때 힘이 된다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0991", text: "한 사람의 희망이 여러 사람을 살린다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0992", text: "미래는 오늘의 습관이 도착하는 장소다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0993", text: "가장 좋은 시절이 아직 남아 있을 수 있다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0994", text: "기다리는 동안 무엇을 하느냐가 결과를 바꾼다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0995", text: "미래를 걱정하는 대신 오늘을 설계하라.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0996", text: "희망은 남에게 빌려 줄 수 있는 유일한 자산이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0997", text: "모든 겨울은 봄의 준비 기간이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0998", text: "기록해 둔 꿈은 언젠가 다시 찾아온다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_0999", text: "아직 늦지 않았다는 말은 대개 사실이다.", category: "wisdom", language: "ko" },
  { id: "cu_ko_1000", text: "내일의 나를 위해 오늘 한 가지만 해 두어라.", category: "wisdom", language: "ko" },
];
