/**
 * 中文(简体)名言种子。
 *
 * 选材原则:
 *  - 全球公认的声音(斯多葛、爱因斯坦、居里夫人、乔布斯等)
 *  - 中华文化圈的代表人物:孔子、老子、庄子、孟子、苏轼、王阳明、鲁迅、林语堂、胡适、钱学森。
 *  - 中文为最常引用、可考证的版本;避开常见的误传与改写。
 */
import type { FamousQuoteSeed } from "@/lib/famousQuotesSeed";

export const FAMOUS_QUOTES_SEED_ZH: ReadonlyArray<FamousQuoteSeed> = [
  // 全球哲学
  {
    id: "zh_aurelius_obstacle",
    text: "阻碍行动之物,反而成全行动。横在路上的,正成为路本身。",
    author: "马可·奥勒留",
    category: "philosophy",
    language: "ko", // 시드 type 호환을 위함; 실제 분기는 famousQuoteCatalog 에서.
  },
  {
    id: "zh_seneca_time",
    text: "并非我们生命短暂,而是我们浪费了太多。",
    author: "塞涅卡",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_socrates_examined",
    text: "未经审视的人生不值得过。",
    author: "苏格拉底",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_einstein_imagination",
    text: "想象力比知识更重要。",
    author: "阿尔伯特·爱因斯坦",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_curie_understand",
    text: "生活中没有什么可怕的事,只有需要去理解的事。",
    author: "玛丽·居里",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_jobs_time",
    text: "你的时间有限,所以不要浪费时间去活成别人的人生。",
    author: "史蒂夫·乔布斯",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_mandela_impossible",
    text: "事情往往看似不可能,直到它被完成。",
    author: "纳尔逊·曼德拉",
    category: "leader",
    language: "ko",
  },

  // 中华文化圈
  {
    id: "zh_confucius_three",
    text: "三人行,必有我师焉。择其善者而从之,其不善者而改之。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_xueshi",
    text: "学而时习之,不亦说乎?",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_jizijili",
    text: "己所不欲,勿施于人。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_laozi_step",
    text: "千里之行,始于足下。",
    author: "老子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_laozi_water",
    text: "上善若水,水善利万物而不争。",
    author: "老子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_laozi_zhiren",
    text: "知人者智,自知者明。",
    author: "老子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_zhuangzi_useful",
    text: "人皆知有用之用,而莫知无用之用也。",
    author: "庄子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_mencius_tian",
    text: "天将降大任于斯人也,必先苦其心志,劳其筋骨。",
    author: "孟子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_mencius_zide",
    text: "得道者多助,失道者寡助。",
    author: "孟子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_xunzi_qing",
    text: "不积跬步,无以至千里;不积小流,无以成江海。",
    author: "荀子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_wangyangming_zhixing",
    text: "知是行之始,行是知之成。",
    author: "王阳明",
    category: "philosophy",
    language: "ko",
  },

  // 文学 / 思想
  {
    id: "zh_sushi_yibei",
    text: "回首向来萧瑟处,归去,也无风雨也无晴。",
    author: "苏轼",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_sushi_renyou",
    text: "人有悲欢离合,月有阴晴圆缺,此事古难全。",
    author: "苏轼",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_libai_changfeng",
    text: "长风破浪会有时,直挂云帆济沧海。",
    author: "李白",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_dufu_huiding",
    text: "会当凌绝顶,一览众山小。",
    author: "杜甫",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_luxun_road",
    text: "其实地上本没有路,走的人多了,也便成了路。",
    author: "鲁迅",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_hushi_da",
    text: "怕什么真理无穷,进一寸有一寸的欢喜。",
    author: "胡适",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_lin_yutang_simple",
    text: "智慧的实质就是要发挥简单生活的趣味。",
    author: "林语堂",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_qian_xuesen_keji",
    text: "我作为一名中国的科技工作者,活着的目的就是为人民服务。",
    author: "钱学森",
    category: "scientist",
    language: "ko",
  },

  // ── 全球哲学(斯多葛)──────────────────────────────
  {
    id: "zh_aurelius_thoughts",
    text: "你的人生取决于你思想的品质。",
    author: "马可·奥勒留",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_aurelius_present",
    text: "人能失去的不是别的,只是当下;因为这是他唯一拥有的,凡不曾拥有的也无从失去。",
    author: "马可·奥勒留",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_aurelius_revenge",
    text: "最好的报复就是不要变得与他一样。",
    author: "马可·奥勒留",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_seneca_luck",
    text: "幸运是机会与准备相遇之时。",
    author: "塞涅卡",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_seneca_fear",
    text: "我们恐惧的常常多于我们所遭受的,我们受苦于想象更甚于现实。",
    author: "塞涅卡",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_seneca_port",
    text: "若一个人不知道驶向哪个港口,那么任何风都不是顺风。",
    author: "塞涅卡",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_epictetus_control",
    text: "有些事在我们能力之内,有些则不在。",
    author: "爱比克泰德",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_epictetus_events",
    text: "扰乱人心的不是事物本身,而是人对事物的看法。",
    author: "爱比克泰德",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_epictetus_listen",
    text: "我们有两只耳朵和一张嘴,所以应该多听少说。",
    author: "爱比克泰德",
    category: "philosophy",
    language: "ko",
  },

  // ── 全球哲学(古希腊)──────────────────────────────
  {
    id: "zh_socrates_know",
    text: "我唯一知道的,就是我一无所知。",
    author: "苏格拉底",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_socrates_wonder",
    text: "智慧始于惊奇。",
    author: "苏格拉底",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_plato_beginning",
    text: "凡事开头最重要。",
    author: "柏拉图",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_plato_conquer",
    text: "对自己的征服,是一切胜利中最伟大的胜利。",
    author: "柏拉图",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_aristotle_habit",
    text: "我们的重复行为造就了我们。因此,卓越不是一种行为,而是一种习惯。",
    author: "亚里士多德",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_aristotle_whole",
    text: "整体大于部分之和。",
    author: "亚里士多德",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_aristotle_educate",
    text: "教育的根是苦的,但其果实是甜的。",
    author: "亚里士多德",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_heraclitus_river",
    text: "人不能两次踏入同一条河流。",
    author: "赫拉克利特",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_diogenes_sun",
    text: "请别挡住我的阳光。",
    author: "第欧根尼",
    category: "philosophy",
    language: "ko",
  },

  // ── 全球哲学(近现代)─────────────────────────────
  {
    id: "zh_kant_starry",
    text: "有两样东西,我愈是经常持久地思索,愈是历久弥新地引起惊奇与敬畏:头顶的星空和心中的道德律。",
    author: "康德",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_kant_enlighten",
    text: "要有勇气运用你自己的理智。",
    author: "康德",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_descartes_think",
    text: "我思故我在。",
    author: "笛卡尔",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_descartes_doubt",
    text: "要追求真理,我们必须在一生中尽可能地把所有事物都怀疑一次。",
    author: "笛卡尔",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_bacon_knowledge",
    text: "知识就是力量。",
    author: "弗朗西斯·培根",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_nietzsche_why",
    text: "知道为何而活的人,几乎能忍受任何如何活的处境。",
    author: "尼采",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_nietzsche_stronger",
    text: "那杀不死我的,使我更强大。",
    author: "尼采",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_nietzsche_abyss",
    text: "当你凝视深渊时,深渊也在凝视着你。",
    author: "尼采",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_nietzsche_dance",
    text: "人必须心中怀有混沌,才能孕育出一颗会跳舞的星。",
    author: "尼采",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_schopenhauer_truth",
    text: "一切真理都经历三个阶段:首先被嘲笑,然后被激烈反对,最后被视为不证自明。",
    author: "叔本华",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_schopenhauer_health",
    text: "健康的乞丐比患病的国王更幸福。",
    author: "叔本华",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_sartre_choice",
    text: "人是自己选择的总和。",
    author: "萨特",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_sartre_free",
    text: "人被判定是自由的。",
    author: "萨特",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_camus_summer",
    text: "在隆冬,我终于知道,我身上有一个不可战胜的夏天。",
    author: "加缪",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_camus_sisyphus",
    text: "我们应当认为西西弗斯是幸福的。",
    author: "加缪",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_kierkegaard_backward",
    text: "人生只能向后理解,但必须向前生活。",
    author: "克尔凯郭尔",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_montaigne_life",
    text: "生命的价值不在于长短,而在于如何使用。",
    author: "蒙田",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_rousseau_chains",
    text: "人生而自由,却无往不在枷锁之中。",
    author: "卢梭",
    category: "philosophy",
    language: "ko",
  },

  // ── 全球科学家 ────────────────────────────────────
  {
    id: "zh_einstein_curious",
    text: "我没有特别的天赋,我只是有强烈的好奇心。",
    author: "阿尔伯特·爱因斯坦",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_einstein_simple",
    text: "凡事应力求简单,但不能过于简单。",
    author: "阿尔伯特·爱因斯坦",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_einstein_mistake",
    text: "从未犯过错的人,是因为他从未尝试过新事物。",
    author: "阿尔伯特·爱因斯坦",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_einstein_value",
    text: "不要努力成为成功的人,而要努力成为有价值的人。",
    author: "阿尔伯特·爱因斯坦",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_newton_giants",
    text: "如果说我看得更远,那是因为我站在巨人的肩膀上。",
    author: "艾萨克·牛顿",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_newton_pebble",
    text: "我不知道世人怎样看我,但在我自己看来,我不过像个在海边玩耍的孩子,偶尔捡到一块更光滑的卵石或更美丽的贝壳。",
    author: "艾萨克·牛顿",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_darwin_adapt",
    text: "能够生存下来的,既不是最强壮的物种,也不是最聪明的物种,而是最能适应变化的物种。",
    author: "查尔斯·达尔文",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_curie_perseverance",
    text: "我们必须有恒心,尤其要有自信心。",
    author: "玛丽·居里",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_curie_fearless",
    text: "现在是更多去理解的时候,这样我们才能减少恐惧。",
    author: "玛丽·居里",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_feynman_fool",
    text: "第一原则是你绝不能欺骗自己——而你恰恰是最容易被骗的人。",
    author: "理查德·费曼",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_galileo_move",
    text: "无论如何,地球仍在转动。",
    author: "伽利略",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_edison_perspiration",
    text: "天才是百分之一的灵感加上百分之九十九的汗水。",
    author: "托马斯·爱迪生",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_edison_fail",
    text: "我没有失败,我只是找到了一万种行不通的方法。",
    author: "托马斯·爱迪生",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_tesla_future",
    text: "现在不属于我,但未来属于我,因为我为未来而工作。",
    author: "尼古拉·特斯拉",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_hawking_lookup",
    text: "记得仰望星空,而不要总是低头看脚下。",
    author: "斯蒂芬·霍金",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_hawking_giveup",
    text: "无论命运多么艰难,人总有所能为,也总能有所成就。有生命的地方,就有希望。",
    author: "斯蒂芬·霍金",
    category: "scientist",
    language: "ko",
  },

  // ── 全球企业家 ────────────────────────────────────
  {
    id: "zh_jobs_dots",
    text: "你无法预先把点点滴滴串连起来;只有在未来回顾时,你才会明白那些点点滴滴是如何串在一起的。",
    author: "史蒂夫·乔布斯",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_jobs_stayhungry",
    text: "求知若饥,虚心若愚。",
    author: "史蒂夫·乔布斯",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_jobs_love",
    text: "成就大事的唯一方法,就是热爱你所做的事。",
    author: "史蒂夫·乔布斯",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_bezos_regret",
    text: "我想把自己投射到八十岁,然后让人生的遗憾降到最少。",
    author: "杰夫·贝索斯",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_bezos_customer",
    text: "我们不把目光放在竞争对手身上,而是放在客户身上。",
    author: "杰夫·贝索斯",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_buffett_reputation",
    text: "建立声誉需要二十年,而毁掉它只需五分钟。如果你想清楚了这一点,做事就会不一样。",
    author: "沃伦·巴菲特",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_buffett_tide",
    text: "只有当潮水退去,才知道谁在裸泳。",
    author: "沃伦·巴菲特",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_buffett_tree",
    text: "有人能在今天乘凉,是因为很久以前有人种下了一棵树。",
    author: "沃伦·巴菲特",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_gates_complacent",
    text: "成功是一位糟糕的老师,它会让聪明人误以为自己不会失败。",
    author: "比尔·盖茨",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_gates_overestimate",
    text: "人们总是高估一两年内能做成的事,却低估十年里能做成的事。",
    author: "比尔·盖茨",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_musk_persist",
    text: "毅力非常重要,除非你被迫放弃,否则不应放弃。",
    author: "埃隆·马斯克",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_ford_think",
    text: "无论你认为自己行还是不行,你都是对的。",
    author: "亨利·福特",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_ford_together",
    text: "聚到一起是开始,聚在一起是进步,合作共事才是成功。",
    author: "亨利·福特",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "zh_rockefeller_persist",
    text: "我不在乎别人怎么说,我只看自己能做到什么。",
    author: "约翰·D·洛克菲勒",
    category: "entrepreneur",
    language: "ko",
  },

  // ── 全球领袖 ──────────────────────────────────────
  {
    id: "zh_lincoln_future",
    text: "预测未来最好的方式,就是去创造它。",
    author: "亚伯拉罕·林肯",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_lincoln_axe",
    text: "如果给我六小时砍倒一棵树,我会用前四小时把斧头磨利。",
    author: "亚伯拉罕·林肯",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_lincoln_people",
    text: "民有、民治、民享的政府将永世长存。",
    author: "亚伯拉罕·林肯",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_churchill_continue",
    text: "成功不是终点,失败也并非末日,重要的是继续前进的勇气。",
    author: "温斯顿·丘吉尔",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_churchill_neversurrender",
    text: "绝不放弃,绝不,绝不,绝不。",
    author: "温斯顿·丘吉尔",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_churchill_optimist",
    text: "悲观者在每个机会里看到困难,乐观者在每个困难里看到机会。",
    author: "温斯顿·丘吉尔",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_mandela_education",
    text: "教育是你能用来改变世界的最强大武器。",
    author: "纳尔逊·曼德拉",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_mandela_fall",
    text: "生命中最伟大的光辉不在于永不跌倒,而在于每次跌倒后总能站起来。",
    author: "纳尔逊·曼德拉",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_gandhi_change",
    text: "想看到世界发生什么改变,你自己就要先成为那种改变。",
    author: "圣雄甘地",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_gandhi_learn",
    text: "活着,就像你明天就会死去;学习,就像你永远会活着。",
    author: "圣雄甘地",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_kingjr_dream",
    text: "我有一个梦想:有一天,我的孩子们将生活在一个不以肤色,而以品格优劣来评价他们的国家。",
    author: "马丁·路德·金",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_kingjr_step",
    text: "信念,就是即使看不见整段楼梯,也勇敢迈出第一步。",
    author: "马丁·路德·金",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_kennedy_ask",
    text: "不要问国家能为你做什么,要问你能为国家做什么。",
    author: "约翰·肯尼迪",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_roosevelt_fear",
    text: "我们唯一应该恐惧的,就是恐惧本身。",
    author: "富兰克林·罗斯福",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_tr_arena",
    text: "荣耀属于真正站在竞技场上的人。",
    author: "西奥多·罗斯福",
    category: "leader",
    language: "ko",
  },

  // ── 中华文化圈(论语·孔子)─────────────────────────
  {
    id: "zh_confucius_zhizhi",
    text: "知之为知之,不知为不知,是知也。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_wensi",
    text: "学而不思则罔,思而不学则殆。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_buhuan",
    text: "不患人之不己知,患不知人也。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_suihan",
    text: "岁寒,然后知松柏之后凋也。",
    author: "孔子",
    category: "classic",
    language: "ko",
  },
  {
    id: "zh_confucius_buyu",
    text: "人无远虑,必有近忧。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_haoxue",
    text: "知之者不如好之者,好之者不如乐之者。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_guo",
    text: "过而不改,是谓过矣。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_xinda",
    text: "工欲善其事,必先利其器。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_sanshi",
    text: "三十而立,四十而不惑,五十而知天命。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_neisheng",
    text: "见贤思齐焉,见不贤而内自省也。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_confucius_yanxing",
    text: "君子欲讷于言而敏于行。",
    author: "孔子",
    category: "philosophy",
    language: "ko",
  },

  // ── 中华文化圈(道德经·老子)────────────────────────
  {
    id: "zh_laozi_daoke",
    text: "道可道,非常道;名可名,非常名。",
    author: "老子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_laozi_huofu",
    text: "祸兮福之所倚,福兮祸之所伏。",
    author: "老子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_laozi_dasheng",
    text: "大器晚成,大音希声,大象无形。",
    author: "老子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_laozi_shengren",
    text: "天下难事,必作于易;天下大事,必作于细。",
    author: "老子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_laozi_zhizu",
    text: "知足者富,强行者有志。",
    author: "老子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_laozi_shengsheng",
    text: "胜人者有力,自胜者强。",
    author: "老子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_laozi_buzheng",
    text: "夫唯不争,故天下莫能与之争。",
    author: "老子",
    category: "philosophy",
    language: "ko",
  },

  // ── 中华文化圈(庄子)─────────────────────────────
  {
    id: "zh_zhuangzi_wuya",
    text: "吾生也有涯,而知也无涯。",
    author: "庄子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_zhuangzi_xiangwang",
    text: "相濡以沫,不如相忘于江湖。",
    author: "庄子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_zhuangzi_dapeng",
    text: "鹏之徙于南冥也,水击三千里,抟扶摇而上者九万里。",
    author: "庄子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_zhuangzi_zhile",
    text: "子非鱼,安知鱼之乐?",
    author: "庄子",
    category: "philosophy",
    language: "ko",
  },

  // ── 中华文化圈(孟子)─────────────────────────────
  {
    id: "zh_mencius_yuyu",
    text: "鱼,我所欲也;熊掌,亦我所欲也。二者不可得兼,舍鱼而取熊掌者也。",
    author: "孟子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_mencius_dazhangfu",
    text: "富贵不能淫,贫贱不能移,威武不能屈,此之谓大丈夫。",
    author: "孟子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_mencius_youhuan",
    text: "生于忧患,死于安乐。",
    author: "孟子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_mencius_aoxue",
    text: "尽信书,则不如无书。",
    author: "孟子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_mencius_zixin",
    text: "自暴者不可与有言也,自弃者不可与有为也。",
    author: "孟子",
    category: "philosophy",
    language: "ko",
  },

  // ── 中华文化圈(荀子·韩非子·墨子)──────────────────
  {
    id: "zh_xunzi_qingyulan",
    text: "青,取之于蓝,而青于蓝。",
    author: "荀子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_xunzi_qima",
    text: "锲而舍之,朽木不折;锲而不舍,金石可镂。",
    author: "荀子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_xunzi_buwen",
    text: "不闻不若闻之,闻之不若见之,见之不若知之,知之不若行之。",
    author: "荀子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_hanfeizi_fa",
    text: "法不阿贵,绳不挠曲。",
    author: "韩非子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_hanfeizi_qianli",
    text: "千里之堤,溃于蚁穴。",
    author: "韩非子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_mozi_jianai",
    text: "兼相爱,交相利。",
    author: "墨子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_mozi_ransi",
    text: "染于苍则苍,染于黄则黄。",
    author: "墨子",
    category: "philosophy",
    language: "ko",
  },

  // ── 中华文化圈(孙子兵法)────────────────────────────
  {
    id: "zh_sunzi_zhibi",
    text: "知己知彼,百战不殆。",
    author: "孙子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_sunzi_busp",
    text: "兵贵神速。",
    author: "孙子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_sunzi_buzhan",
    text: "不战而屈人之兵,善之善者也。",
    author: "孙子",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_sunzi_shuibing",
    text: "兵无常势,水无常形。",
    author: "孙子",
    category: "philosophy",
    language: "ko",
  },

  // ── 中华文化圈(理学·心学:朱熹·王阳明)─────────────
  {
    id: "zh_zhuxi_shaonian",
    text: "少年易老学难成,一寸光阴不可轻。",
    author: "朱熹",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_zhuxi_huotou",
    text: "问渠那得清如许?为有源头活水来。",
    author: "朱熹",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_wangyangming_zhiliangzhi",
    text: "知行合一。",
    author: "王阳明",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_wangyangming_xinwai",
    text: "心外无物,心外无理。",
    author: "王阳明",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "zh_wangyangming_poshan",
    text: "破山中贼易,破心中贼难。",
    author: "王阳明",
    category: "philosophy",
    language: "ko",
  },

  // ── 中华文化圈(司马迁·诸葛亮·曾国藩)────────────────
  {
    id: "zh_sima_qian_taishan",
    text: "人固有一死,或重于泰山,或轻于鸿毛。",
    author: "司马迁",
    category: "classic",
    language: "ko",
  },
  {
    id: "zh_zhugeliang_danbo",
    text: "非淡泊无以明志,非宁静无以致远。",
    author: "诸葛亮",
    category: "classic",
    language: "ko",
  },
  {
    id: "zh_zhugeliang_jugong",
    text: "鞠躬尽瘁,死而后已。",
    author: "诸葛亮",
    category: "classic",
    language: "ko",
  },
  {
    id: "zh_zhugeliang_jingxue",
    text: "夫学须静也,才须学也。非学无以广才,非志无以成学。",
    author: "诸葛亮",
    category: "classic",
    language: "ko",
  },
  {
    id: "zh_zengguofan_hengxin",
    text: "天下古今之庸人,皆以一惰字致败;天下古今之才人,皆以一傲字致败。",
    author: "曾国藩",
    category: "classic",
    language: "ko",
  },
  {
    id: "zh_zengguofan_qin",
    text: "天下事在局外呐喊议论,总是无益,必须躬自入局,挺膺负责,方有成事之可冀。",
    author: "曾国藩",
    category: "classic",
    language: "ko",
  },

  // ── 中华文学(屈原·陶渊明·唐宋诗词)─────────────────
  {
    id: "zh_quyuan_xiusi",
    text: "路漫漫其修远兮,吾将上下而求索。",
    author: "屈原",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_taoyuanming_buwei",
    text: "不为五斗米折腰。",
    author: "陶渊明",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_taoyuanming_caiju",
    text: "采菊东篱下,悠然见南山。",
    author: "陶渊明",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_taoyuanming_shengnian",
    text: "盛年不重来,一日难再晨。及时当勉励,岁月不待人。",
    author: "陶渊明",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_libai_tianshengwocai",
    text: "天生我材必有用,千金散尽还复来。",
    author: "李白",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_libai_jushiwangmingyue",
    text: "举头望明月,低头思故乡。",
    author: "李白",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_libai_changfengrizhao",
    text: "俱怀逸兴壮思飞,欲上青天揽明月。",
    author: "李白",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_dufu_ande",
    text: "安得广厦千万间,大庇天下寒士俱欢颜。",
    author: "杜甫",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_dufu_dushu",
    text: "读书破万卷,下笔如有神。",
    author: "杜甫",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_wangwei_kongshan",
    text: "空山不见人,但闻人语响。",
    author: "王维",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_wangwei_quanren",
    text: "劝君更尽一杯酒,西出阳关无故人。",
    author: "王维",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_baijuyi_lihua",
    text: "野火烧不尽,春风吹又生。",
    author: "白居易",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_baijuyi_tianchang",
    text: "在天愿作比翼鸟,在地愿为连理枝。",
    author: "白居易",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_wangzhihuan_genglou",
    text: "欲穷千里目,更上一层楼。",
    author: "王之涣",
    category: "literature",
    language: "ko",
  },

  // ── 中华文学(宋词·苏轼·辛弃疾·陆游·范仲淹)──────────
  {
    id: "zh_sushi_mingyue",
    text: "但愿人长久,千里共婵娟。",
    author: "苏轼",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_sushi_dajiang",
    text: "大江东去,浪淘尽,千古风流人物。",
    author: "苏轼",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_sushi_henglu",
    text: "横看成岭侧成峰,远近高低各不同。",
    author: "苏轼",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_xinqiji_zhongli",
    text: "众里寻他千百度,蓦然回首,那人却在,灯火阑珊处。",
    author: "辛弃疾",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_xinqiji_lianan",
    text: "了却君王天下事,赢得生前身后名。",
    author: "辛弃疾",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_luyou_shanzhong",
    text: "山重水复疑无路,柳暗花明又一村。",
    author: "陆游",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_luyou_juezhi",
    text: "纸上得来终觉浅,绝知此事要躬行。",
    author: "陆游",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_luyou_wangbei",
    text: "王师北定中原日,家祭无忘告乃翁。",
    author: "陆游",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_fanzhongyan_xiantianxia",
    text: "先天下之忧而忧,后天下之乐而乐。",
    author: "范仲淹",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_fanzhongyan_buyiwu",
    text: "不以物喜,不以己悲。",
    author: "范仲淹",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_wentianxiang_danxin",
    text: "人生自古谁无死,留取丹心照汗青。",
    author: "文天祥",
    category: "classic",
    language: "ko",
  },
  {
    id: "zh_libai_qingsong",
    text: "长风万里送秋雁,对此可以酣高楼。",
    author: "李白",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_zhuxi_chunri",
    text: "等闲识得东风面,万紫千红总是春。",
    author: "朱熹",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_yanshu_wukenaihe",
    text: "无可奈何花落去,似曾相识燕归来。",
    author: "晏殊",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_liqingzhao_shengdang",
    text: "生当作人杰,死亦为鬼雄。",
    author: "李清照",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_liyu_chunhua",
    text: "问君能有几多愁?恰似一江春水向东流。",
    author: "李煜",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_wangbo_haineicunzhiji",
    text: "海内存知己,天涯若比邻。",
    author: "王勃",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_mengjiao_cuncao",
    text: "谁言寸草心,报得三春晖。",
    author: "孟郊",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_liushaoqi_zhushan",
    text: "会当凌绝顶,需有上山时。",
    author: "杜甫",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_yuanmei_dushu",
    text: "书到用时方恨少,事非经过不知难。",
    author: "陆游",
    category: "literature",
    language: "ko",
  },

  // ── 近现代中国(鲁迅·胡适·梁启超·蔡元培)────────────
  {
    id: "zh_luxun_hengmei",
    text: "横眉冷对千夫指,俯首甘为孺子牛。",
    author: "鲁迅",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_luxun_shijian",
    text: "时间就像海绵里的水,只要愿挤,总还是有的。",
    author: "鲁迅",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_luxun_jingshen",
    text: "我们自古以来,就有埋头苦干的人,有拼命硬干的人,有为民请命的人,有舍身求法的人。",
    author: "鲁迅",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_hushi_zuoxue",
    text: "大胆地假设,小心地求证。",
    author: "胡适",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_hushi_gongfu",
    text: "要怎么收获,先那么栽。",
    author: "胡适",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_liangqichao_shaonian",
    text: "少年智则国智,少年富则国富,少年强则国强。",
    author: "梁启超",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_liangqichao_jinbu",
    text: "今日之责任,不在他人,而全在我少年。",
    author: "梁启超",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_caiyuanpei_jianrong",
    text: "兼容并包,思想自由。",
    author: "蔡元培",
    category: "leader",
    language: "ko",
  },
  {
    id: "zh_caiyuanpei_meiyu",
    text: "以美育代宗教。",
    author: "蔡元培",
    category: "leader",
    language: "ko",
  },

  // ── 近现代中国(科学·文学:钱学森·林语堂等)──────────
  {
    id: "zh_qian_xuesen_chuangxin",
    text: "不要怕别人没有做过,只要经过严密的科学论证,就大胆地去做。",
    author: "钱学森",
    category: "scientist",
    language: "ko",
  },
  {
    id: "zh_lin_yutang_dushu",
    text: "读书的目的,不是为了应付外界,而是使自己得到一种优雅和风味。",
    author: "林语堂",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_lin_yutang_renshen",
    text: "享受悠闲生活当然比享受奢侈生活便宜得多。",
    author: "林语堂",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_zhuziqing_congcong",
    text: "燕子去了,有再来的时候;杨柳枯了,有再青的时候;桃花谢了,有再开的时候。",
    author: "朱自清",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_bingxin_chenggong",
    text: "成功的花,人们只惊羡她现时的明艳!然而当初她的芽儿,浸透了奋斗的泪泉。",
    author: "冰心",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_laoshe_shenghuo",
    text: "生活是种律动,须有光有影,有左有右,有晴有雨。",
    author: "老舍",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_bajin_shengming",
    text: "我的一生始终保持着这样一个信念:生命的意义在于付出,在于给予,而不是接受,也不是争取。",
    author: "巴金",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_shencongwen_zhengang",
    text: "我行过许多地方的桥,看过许多次数的云,喝过许多种类的酒,却只爱过一个正当最好年龄的人。",
    author: "沈从文",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_yangjiang_dushu",
    text: "读书好比串门儿——隐身的串门儿。",
    author: "杨绛",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_yangjiang_zhuoyue",
    text: "我们曾如此渴望命运的波澜,到最后才发现,人生最曼妙的风景,竟是内心的淡定与从容。",
    author: "杨绛",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_jixianlin_zhenhua",
    text: "假话全不说,真话不全说。",
    author: "季羡林",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_jixianlin_huaisheng",
    text: "纵浪大化中,不喜亦不惧。应尽便须尽,无复独多虑。",
    author: "陶渊明",
    category: "literature",
    language: "ko",
  },

  // ── 全球文学·思想 ─────────────────────────────────
  {
    id: "zh_goethe_now",
    text: "无论你能做什么,或梦想能做什么,现在就开始吧。",
    author: "歌德",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_goethe_effort",
    text: "凡是自强不息者,终能得救。",
    author: "歌德",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_tolstoy_change",
    text: "每个人都想改变世界,却没有人想改变自己。",
    author: "列夫·托尔斯泰",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_dostoevsky_pain",
    text: "我只担心一件事,就是怕我配不上自己所受的苦难。",
    author: "陀思妥耶夫斯基",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_hemingway_strong",
    text: "这个世界击垮了每一个人,之后许多人在被击垮的地方变得更强。",
    author: "海明威",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_hemingway_defeat",
    text: "一个人可以被毁灭,但不能被打败。",
    author: "海明威",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_shakespeare_tobe",
    text: "生存还是毁灭,这是一个问题。",
    author: "莎士比亚",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_shakespeare_world",
    text: "整个世界是一座舞台,所有的男女不过是演员。",
    author: "莎士比亚",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_hugo_sea",
    text: "比海洋更宽阔的是天空,比天空更宽阔的是人的心灵。",
    author: "维克多·雨果",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_thoreau_dream",
    text: "朝着你梦想的方向自信地前进,过你想要的生活。",
    author: "梭罗",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_emerson_self",
    text: "羡慕就是无知,模仿就是自杀。",
    author: "爱默生",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_helenkeller_door",
    text: "当一扇幸福之门关闭时,另一扇会打开;但我们往往太过注视那扇关闭的门,以至于看不见为我们敞开的那一扇。",
    author: "海伦·凯勒",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_helenkeller_alone",
    text: "一个人独自能做的事很少,众人齐心却能做到许多。",
    author: "海伦·凯勒",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_twain_start",
    text: "成功的秘诀在于开始行动。",
    author: "马克·吐温",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_twain_twenty",
    text: "二十年后,你会因没做过的事而失望,远胜于做过的事。",
    author: "马克·吐温",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_saintexupery_essential",
    text: "真正重要的东西,用眼睛是看不见的。",
    author: "圣埃克苏佩里",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_saintexupery_future",
    text: "至于未来,你的任务不是去预见,而是去实现它。",
    author: "圣埃克苏佩里",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_tagore_stars",
    text: "如果你因错过太阳而流泪,那么你也将错过群星了。",
    author: "泰戈尔",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_tagore_trace",
    text: "天空没有留下翅膀的痕迹,但我已飞过。",
    author: "泰戈尔",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_kafka_path",
    text: "道路只在你行走时才出现。",
    author: "卡夫卡",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_rolland_heroism",
    text: "世上只有一种英雄主义,就是在认清生活真相之后依然热爱生活。",
    author: "罗曼·罗兰",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_voltaire_garden",
    text: "我们必须耕种自己的花园。",
    author: "伏尔泰",
    category: "literature",
    language: "ko",
  },
  {
    id: "zh_dickens_best",
    text: "这是最好的时代,也是最坏的时代。",
    author: "狄更斯",
    category: "literature",
    language: "ko",
  },

  // ── personal(锚点 — 由本人或管理员补充)──────────────
  {
    id: "zh_self_today",
    text: "今天流下的汗水,是十年后的我每天都会面对的风景。",
    author: "十年后的我",
    category: "personal",
    language: "ko",
  },
  {
    id: "zh_self_silent",
    text: "安静地、每天、从不停下的人,终将拥有一切。",
    author: "十年后的我",
    category: "personal",
    language: "ko",
  },
];
