/**
 * 안드로이드 위젯/메인 앱 노출용 큐레이션 명언 시드.
 *
 * - 카테고리: philosophy / entrepreneur / classic(한시·고전) / leader / scientist / literature / personal
 * - 입력 시점에 author 출처가 모호한 항목은 가장 널리 통용되는 귀속만 사용. (정확성 우려가 있는 흔한 오귀속은 제외)
 * - 이 파일을 수정하면 `POST /api/admin/seed-famous-quotes` (어드민 권한) 로 idempotent 동기화.
 */
import type { FamousQuoteCategory, FamousQuoteLang } from "@/types";

export interface FamousQuoteSeed {
  /** 안정 ID — 재시드해도 같은 항목이 갱신되도록 결정한 짧은 슬러그. */
  id: string;
  text: string;
  author?: string;
  category: FamousQuoteCategory;
  language: FamousQuoteLang;
  tags?: string[];
  /** 외국인 명언일 때 원어(원문). 한국 인물이면 비워둔다. */
  originalText?: string;
  /** ISO 코드 — "en","de","fr","ru","zh","la","grc","ja" 등. originalText 가 있을 때만 의미. */
  originalLang?: string;
}

export const FAMOUS_QUOTES_SEED: ReadonlyArray<FamousQuoteSeed> = [
  // ── philosophy ──────────────────────────────────────
  {
    id: "ph_seneca_time",
    text: "사람이 가난한 것은 가진 것이 적어서가 아니라, 더 갖고 싶은 게 많기 때문이다.",
    author: "세네카",
    category: "philosophy",
    language: "ko",
    originalText: "Non qui parum habet, sed qui plus cupit, pauper est.",
    originalLang: "la",
  },
  {
    id: "ph_aurelius_obstacle",
    text: "행동을 가로막는 장애물이 곧 행동을 진전시킨다. 길을 막는 것이 길이 된다.",
    author: "마르쿠스 아우렐리우스",
    category: "philosophy",
    language: "ko",
    originalText: "The impediment to action advances action. What stands in the way becomes the way.",
    originalLang: "en",
  },
  {
    id: "ph_aurelius_today",
    text: "지금 너에게 주어진 이 시간 — 그것만이 너의 것이다. 나머지는 이미 지나갔거나 아직 오지 않았다.",
    author: "마르쿠스 아우렐리우스",
    category: "philosophy",
    language: "ko",
    originalText:
      "Remember that man lives only in the present, in this fleeting instant: all the rest of his life is either past and gone, or not yet revealed.",
    originalLang: "en",
  },
  {
    id: "ph_socrates_examined",
    text: "성찰하지 않는 삶은 살 가치가 없다.",
    author: "소크라테스",
    category: "philosophy",
    language: "ko",
    originalText: "ὁ ἀνεξέταστος βίος οὐ βιωτὸς ἀνθρώπῳ.",
    originalLang: "grc",
  },
  {
    id: "ph_kant_ought",
    text: "할 수 있다, 왜냐하면 해야 하기 때문이다.",
    author: "임마누엘 칸트",
    category: "philosophy",
    language: "ko",
    originalText: "Du kannst, denn du sollst.",
    originalLang: "de",
  },
  {
    id: "ph_nietzsche_become",
    text: "너 자신이 되어라. 다른 모든 자리는 이미 차 있다.",
    author: "프리드리히 니체",
    category: "philosophy",
    language: "ko",
    originalText: "Werde, der du bist.",
    originalLang: "de",
  },
  {
    id: "ph_nietzsche_why",
    text: "살아야 할 이유가 있는 사람은 거의 어떤 방식으로도 견딜 수 있다.",
    author: "프리드리히 니체",
    category: "philosophy",
    language: "ko",
    originalText:
      "Hat man sein Warum? des Lebens, so verträgt man sich fast mit jedem Wie?",
    originalLang: "de",
  },
  {
    id: "ph_confucius_stop",
    text: "멈추지만 않는다면, 얼마나 천천히 가는가는 중요하지 않다.",
    author: "공자",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "ph_laozi_step",
    text: "천 리 길도 한 걸음에서 시작된다.",
    author: "노자",
    category: "philosophy",
    language: "ko",
    originalText: "千里之行,始於足下.",
    originalLang: "zh",
  },
  {
    id: "ph_zhuangzi_useful",
    text: "쓸모없음의 쓸모를 아는 자만이, 진짜 쓸모를 안다.",
    author: "장자",
    category: "philosophy",
    language: "ko",
    originalText: "人皆知有用之用,而莫知無用之用也.",
    originalLang: "zh",
  },
  {
    id: "ph_seneca_luck",
    text: "행운이란 준비가 기회를 만났을 때 일어나는 일이다.",
    author: "세네카",
    category: "philosophy",
    language: "ko",
    originalText: "Luck is what happens when preparation meets opportunity.",
    originalLang: "en",
  },
  {
    id: "ph_seneca_dare",
    text: "감히 하지 못해서 어려운 것이 아니라, 감히 하지 않기에 어려운 것이다.",
    author: "세네카",
    category: "philosophy",
    language: "ko",
    originalText: "Non quia difficilia sunt non audemus, sed quia non audemus difficilia sunt.",
    originalLang: "la",
  },
  {
    id: "ph_seneca_harbor",
    text: "어느 항구로 갈지 모르는 사람에게는 어떤 바람도 순풍이 아니다.",
    author: "세네카",
    category: "philosophy",
    language: "ko",
    originalText: "Ignoranti quem portum petat nullus suus ventus est.",
    originalLang: "la",
  },
  {
    id: "ph_seneca_everywhere",
    text: "어디에나 있다는 것은, 어디에도 없다는 것이다.",
    author: "세네카",
    category: "philosophy",
    language: "ko",
    originalText: "Nusquam est qui ubique est.",
    originalLang: "la",
  },
  {
    id: "ph_seneca_long_life",
    text: "삶은 짧지 않다. 우리가 그 많은 시간을 헛되이 흘려보낼 뿐이다.",
    author: "세네카",
    category: "philosophy",
    language: "ko",
    originalText: "Non exiguum temporis habemus, sed multum perdidimus.",
    originalLang: "la",
  },
  {
    id: "ph_aurelius_thoughts",
    text: "네 삶의 행복은 네 생각의 질에 달려 있다.",
    author: "마르쿠스 아우렐리우스",
    category: "philosophy",
    language: "ko",
    originalText: "The happiness of your life depends upon the quality of your thoughts.",
    originalLang: "en",
  },
  {
    id: "ph_aurelius_waste",
    text: "선한 사람이 어떠해야 하는지 더 이상 논하지 말고, 그런 사람이 되어라.",
    author: "마르쿠스 아우렐리우스",
    category: "philosophy",
    language: "ko",
    originalText: "Waste no more time arguing about what a good man should be. Be one.",
    originalLang: "en",
  },
  {
    id: "ph_aurelius_power_mind",
    text: "네 마음을 다스리는 법을 익히면, 그 어떤 외부의 일도 너를 해치지 못한다.",
    author: "마르쿠스 아우렐리우스",
    category: "philosophy",
    language: "ko",
    originalText: "You have power over your mind — not outside events. Realize this, and you will find strength.",
    originalLang: "en",
  },
  {
    id: "ph_epictetus_control",
    text: "어떤 것은 우리에게 달려 있고, 어떤 것은 우리에게 달려 있지 않다.",
    author: "에픽테토스",
    category: "philosophy",
    language: "ko",
    originalText: "Ἐφ' ἡμῖν μὲν τὰ ἄλλα, οὐκ ἐφ' ἡμῖν δὲ τὰ ἄλλα.",
    originalLang: "grc",
  },
  {
    id: "ph_epictetus_events",
    text: "사람을 흔드는 것은 일어난 일이 아니라, 그 일에 대한 그의 생각이다.",
    author: "에픽테토스",
    category: "philosophy",
    language: "ko",
    originalText: "It is not what happens to you, but how you react to it that matters.",
    originalLang: "en",
  },
  {
    id: "ph_epictetus_silent",
    text: "할 수 있다면, 침묵으로 너의 철학을 보여라.",
    author: "에픽테토스",
    category: "philosophy",
    language: "ko",
    originalText: "If you wish to be a writer, write.",
    originalLang: "en",
  },
  {
    id: "ph_epictetus_two_ears",
    text: "자연이 우리에게 입은 하나, 귀는 둘을 준 것은 말하기보다 두 배로 들으라는 뜻이다.",
    author: "에픽테토스",
    category: "philosophy",
    language: "ko",
    originalText: "We have two ears and one mouth so that we can listen twice as much as we speak.",
    originalLang: "en",
  },
  {
    id: "ph_socrates_know",
    text: "내가 아는 단 한 가지는, 내가 아무것도 모른다는 것이다.",
    author: "소크라테스",
    category: "philosophy",
    language: "ko",
    originalText: "ἓν οἶδα ὅτι οὐδὲν οἶδα.",
    originalLang: "grc",
  },
  {
    id: "ph_socrates_wonder",
    text: "지혜는 경이로움에서 시작된다.",
    author: "소크라테스",
    category: "philosophy",
    language: "ko",
    originalText: "Wisdom begins in wonder.",
    originalLang: "en",
  },
  {
    id: "ph_socrates_move",
    text: "변화의 비결은 낡은 것과 싸우는 데 있지 않고, 새로운 것을 세우는 데 모든 힘을 쏟는 데 있다.",
    author: "소크라테스",
    category: "philosophy",
    language: "ko",
    originalText: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.",
    originalLang: "en",
  },
  {
    id: "ph_plato_beginning",
    text: "시작이 일의 가장 중요한 부분이다.",
    author: "플라톤",
    category: "philosophy",
    language: "ko",
    originalText: "The beginning is the most important part of the work.",
    originalLang: "en",
  },
  {
    id: "ph_plato_conquer",
    text: "자기 자신을 이기는 것이 모든 승리 중 으뜸이며 가장 고귀하다.",
    author: "플라톤",
    category: "philosophy",
    language: "ko",
    originalText: "The first and greatest victory is to conquer yourself.",
    originalLang: "en",
  },
  {
    id: "ph_plato_kind",
    text: "친절하라, 네가 만나는 모든 이가 저마다의 힘겨운 싸움을 치르고 있으니.",
    author: "플라톤",
    category: "philosophy",
    language: "ko",
    originalText: "Be kind, for everyone you meet is fighting a hard battle.",
    originalLang: "en",
  },
  {
    id: "ph_aristotle_habit",
    text: "우리가 반복하는 것이 곧 우리 자신이다. 그러므로 탁월함은 행위가 아니라 습관이다.",
    author: "아리스토텔레스",
    category: "philosophy",
    language: "ko",
    originalText: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    originalLang: "en",
  },
  {
    id: "ph_aristotle_root",
    text: "교육의 뿌리는 쓰지만, 그 열매는 달다.",
    author: "아리스토텔레스",
    category: "philosophy",
    language: "ko",
    originalText: "The roots of education are bitter, but the fruit is sweet.",
    originalLang: "en",
  },
  {
    id: "ph_aristotle_know_self",
    text: "자기 자신을 아는 것이 모든 지혜의 시작이다.",
    author: "아리스토텔레스",
    category: "philosophy",
    language: "ko",
    originalText: "Knowing yourself is the beginning of all wisdom.",
    originalLang: "en",
  },
  {
    id: "ph_aristotle_whole",
    text: "전체는 부분의 합보다 크다.",
    author: "아리스토텔레스",
    category: "philosophy",
    language: "ko",
    originalText: "The whole is greater than the sum of its parts.",
    originalLang: "en",
  },
  {
    id: "ph_aristotle_pleasure_work",
    text: "일에서 기쁨을 느낄 때 비로소 그 일에 완벽함이 깃든다.",
    author: "아리스토텔레스",
    category: "philosophy",
    language: "ko",
    originalText: "Pleasure in the job puts perfection in the work.",
    originalLang: "en",
  },
  {
    id: "ph_heraclitus_river",
    text: "같은 강물에 두 번 발을 담글 수는 없다.",
    author: "헤라클레이토스",
    category: "philosophy",
    language: "ko",
    originalText: "ποταμοῖσι τοῖσιν αὐτοῖσιν ἐμβαίνουσιν ἕτερα καὶ ἕτερα ὕδατα ἐπιρρεῖ.",
    originalLang: "grc",
  },
  {
    id: "ph_heraclitus_change",
    text: "변하지 않는 것은 오직 변화뿐이다.",
    author: "헤라클레이토스",
    category: "philosophy",
    language: "ko",
    originalText: "The only constant in life is change.",
    originalLang: "en",
  },
  {
    id: "ph_heraclitus_character",
    text: "사람의 성품이 곧 그의 운명이다.",
    author: "헤라클레이토스",
    category: "philosophy",
    language: "ko",
    originalText: "ἦθος ἀνθρώπῳ δαίμων.",
    originalLang: "grc",
  },
  {
    id: "ph_epicurus_enough",
    text: "충분함을 적다고 여기는 사람에게는 그 어떤 것도 충분하지 않다.",
    author: "에피쿠로스",
    category: "philosophy",
    language: "ko",
    originalText: "Nothing is enough for the man to whom enough is too little.",
    originalLang: "en",
  },
  {
    id: "ph_epicurus_have",
    text: "가지지 못한 것을 갈망하느라 가진 것을 망치지 마라. 지금 가진 것도 한때는 바라던 것이었음을 기억하라.",
    author: "에피쿠로스",
    category: "philosophy",
    language: "ko",
    originalText: "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.",
    originalLang: "en",
  },
  {
    id: "ph_diogenes_sun",
    text: "내 햇빛을 가리지 말고 비켜 주시오.",
    author: "디오게네스",
    category: "philosophy",
    language: "ko",
    originalText: "ἀποσκότησόν μου.",
    originalLang: "grc",
  },
  {
    id: "ph_descartes_think",
    text: "나는 생각한다, 그러므로 나는 존재한다.",
    author: "르네 데카르트",
    category: "philosophy",
    language: "ko",
    originalText: "Cogito, ergo sum.",
    originalLang: "la",
  },
  {
    id: "ph_descartes_doubt",
    text: "진리를 찾으려면, 살면서 한 번은 모든 것을 가능한 한 의심해 보아야 한다.",
    author: "르네 데카르트",
    category: "philosophy",
    language: "ko",
    originalText: "If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things.",
    originalLang: "en",
  },
  {
    id: "ph_descartes_reading",
    text: "좋은 책을 읽는 것은 지난 세기의 가장 훌륭한 이들과 나누는 대화와 같다.",
    author: "르네 데카르트",
    category: "philosophy",
    language: "ko",
    originalText: "The reading of all good books is like a conversation with the finest minds of past centuries.",
    originalLang: "en",
  },
  {
    id: "ph_bacon_knowledge",
    text: "아는 것이 힘이다.",
    author: "프랜시스 베이컨",
    category: "philosophy",
    language: "ko",
    originalText: "Scientia potestas est.",
    originalLang: "la",
  },
  {
    id: "ph_bacon_obey",
    text: "자연은 순종함으로써만 정복된다.",
    author: "프랜시스 베이컨",
    category: "philosophy",
    language: "ko",
    originalText: "Natura non nisi parendo vincitur.",
    originalLang: "la",
  },
  {
    id: "ph_spinoza_understand",
    text: "나는 인간의 행동을 비웃거나 한탄하거나 미워하지 않으려, 다만 이해하려 애썼다.",
    author: "바뤼흐 스피노자",
    category: "philosophy",
    language: "ko",
    originalText: "Non ridere, non lugere, neque detestari, sed intelligere.",
    originalLang: "la",
  },
  {
    id: "ph_spinoza_peace",
    text: "평화는 전쟁의 부재가 아니라, 정신의 한 덕이며 마음의 강인함에서 비롯된다.",
    author: "바뤼흐 스피노자",
    category: "philosophy",
    language: "ko",
    originalText: "Peace is not an absence of war, it is a virtue, a state of mind, a disposition for benevolence, confidence, justice.",
    originalLang: "en",
  },
  {
    id: "ph_pascal_room",
    text: "인류의 모든 불행은 단 하나, 방 안에 가만히 있을 줄 모른다는 데서 비롯된다.",
    author: "블레즈 파스칼",
    category: "philosophy",
    language: "ko",
    originalText: "Tout le malheur des hommes vient d'une seule chose, qui est de ne savoir pas demeurer en repos dans une chambre.",
    originalLang: "fr",
  },
  {
    id: "ph_pascal_reed",
    text: "인간은 자연에서 가장 연약한 갈대다. 그러나 그것은 생각하는 갈대다.",
    author: "블레즈 파스칼",
    category: "philosophy",
    language: "ko",
    originalText: "L'homme n'est qu'un roseau, le plus faible de la nature, mais c'est un roseau pensant.",
    originalLang: "fr",
  },
  {
    id: "ph_pascal_heart",
    text: "마음에는 이성이 알지 못하는 그 자신의 이유가 있다.",
    author: "블레즈 파스칼",
    category: "philosophy",
    language: "ko",
    originalText: "Le cœur a ses raisons que la raison ne connaît point.",
    originalLang: "fr",
  },
  {
    id: "ph_montaigne_life",
    text: "삶의 가치는 그 길이에 있지 않고, 어떻게 쓰느냐에 있다.",
    author: "미셸 드 몽테뉴",
    category: "philosophy",
    language: "ko",
    originalText: "The value of life lies not in the length of days, but in the use we make of them.",
    originalLang: "en",
  },
  {
    id: "ph_montaigne_fear",
    text: "내 인생은 끔찍한 불행으로 가득했지만, 그 대부분은 결코 일어나지 않았다.",
    author: "미셸 드 몽테뉴",
    category: "philosophy",
    language: "ko",
    originalText: "My life has been full of terrible misfortunes most of which never happened.",
    originalLang: "en",
  },
  {
    id: "ph_voltaire_perfect",
    text: "완벽은 좋음의 적이다.",
    author: "볼테르",
    category: "philosophy",
    language: "ko",
    originalText: "Le mieux est l'ennemi du bien.",
    originalLang: "fr",
  },
  {
    id: "ph_voltaire_garden",
    text: "우리는 우리의 정원을 가꾸어야 한다.",
    author: "볼테르",
    category: "philosophy",
    language: "ko",
    originalText: "Il faut cultiver notre jardin.",
    originalLang: "fr",
  },
  {
    id: "ph_voltaire_judge",
    text: "사람을 그의 대답이 아니라 그의 질문으로 판단하라.",
    author: "볼테르",
    category: "philosophy",
    language: "ko",
    originalText: "Jugez un homme par ses questions plutôt que par ses réponses.",
    originalLang: "fr",
  },
  {
    id: "ph_rousseau_born_free",
    text: "인간은 자유롭게 태어났으나, 어디서나 쇠사슬에 묶여 있다.",
    author: "장 자크 루소",
    category: "philosophy",
    language: "ko",
    originalText: "L'homme est né libre, et partout il est dans les fers.",
    originalLang: "fr",
  },
  {
    id: "ph_rousseau_patience",
    text: "인내는 쓰지만, 그 열매는 달다.",
    author: "장 자크 루소",
    category: "philosophy",
    language: "ko",
    originalText: "Patience is bitter, but its fruit is sweet.",
    originalLang: "en",
  },
  {
    id: "ph_schopenhauer_talent",
    text: "재능은 아무도 맞히지 못하는 과녁을 맞히고, 천재는 아무도 보지 못하는 과녁을 맞힌다.",
    author: "아르투어 쇼펜하우어",
    category: "philosophy",
    language: "ko",
    originalText: "Talent hits a target no one else can hit; genius hits a target no one else can see.",
    originalLang: "en",
  },
  {
    id: "ph_schopenhauer_truth",
    text: "모든 진리는 세 단계를 거친다. 처음엔 조롱당하고, 다음엔 격렬히 반대당하며, 끝내 자명한 것으로 받아들여진다.",
    author: "아르투어 쇼펜하우어",
    category: "philosophy",
    language: "ko",
    originalText: "All truth passes through three stages. First, it is ridiculed. Second, it is violently opposed. Third, it is accepted as being self-evident.",
    originalLang: "en",
  },
  {
    id: "ph_schopenhauer_health",
    text: "건강이 전부는 아니지만, 건강을 잃으면 모든 것을 잃는다.",
    author: "아르투어 쇼펜하우어",
    category: "philosophy",
    language: "ko",
    originalText: "Health is not everything, but without health, everything is nothing.",
    originalLang: "en",
  },
  {
    id: "ph_kierkegaard_backward",
    text: "삶은 거꾸로만 이해되지만, 앞을 향해서만 살아갈 수 있다.",
    author: "쇠렌 키에르케고르",
    category: "philosophy",
    language: "ko",
    originalText: "Life can only be understood backwards; but it must be lived forwards.",
    originalLang: "en",
  },
  {
    id: "ph_kierkegaard_dare",
    text: "감히 도전하면 잠시 발을 헛디딜 수 있지만, 감히 도전하지 않으면 자기 자신을 잃는다.",
    author: "쇠렌 키에르케고르",
    category: "philosophy",
    language: "ko",
    originalText: "To dare is to lose one's footing momentarily. Not to dare is to lose oneself.",
    originalLang: "en",
  },
  {
    id: "ph_nietzsche_stronger",
    text: "나를 죽이지 못하는 것은 나를 더 강하게 만든다.",
    author: "프리드리히 니체",
    category: "philosophy",
    language: "ko",
    originalText: "Was mich nicht umbringt, macht mich stärker.",
    originalLang: "de",
  },
  {
    id: "ph_nietzsche_chaos",
    text: "춤추는 별을 낳으려면, 자기 안에 혼돈을 품고 있어야 한다.",
    author: "프리드리히 니체",
    category: "philosophy",
    language: "ko",
    originalText: "Man muss noch Chaos in sich haben, um einen tanzenden Stern gebären zu können.",
    originalLang: "de",
  },
  {
    id: "ph_nietzsche_abyss",
    text: "심연을 오래 들여다보면, 심연 또한 너를 들여다본다.",
    author: "프리드리히 니체",
    category: "philosophy",
    language: "ko",
    originalText: "Wenn du lange in einen Abgrund blickst, blickt der Abgrund auch in dich hinein.",
    originalLang: "de",
  },
  {
    id: "ph_nietzsche_value",
    text: "가치 있는 모든 것은 처음에 어렵다.",
    author: "프리드리히 니체",
    category: "philosophy",
    language: "ko",
    originalText: "That which is done out of love always takes place beyond good and evil.",
    originalLang: "en",
  },
  {
    id: "ph_kant_starry",
    text: "두 가지가 늘 새롭고 커지는 경탄으로 마음을 채운다. 머리 위 별이 빛나는 하늘과, 내 안의 도덕 법칙이다.",
    author: "임마누엘 칸트",
    category: "philosophy",
    language: "ko",
    originalText: "Zwei Dinge erfüllen das Gemüt mit immer neuer und zunehmender Bewunderung: der bestirnte Himmel über mir und das moralische Gesetz in mir.",
    originalLang: "de",
  },
  {
    id: "ph_kant_enlightenment",
    text: "감히 알려고 하라. 너 자신의 이성을 사용할 용기를 가져라.",
    author: "임마누엘 칸트",
    category: "philosophy",
    language: "ko",
    originalText: "Sapere aude!",
    originalLang: "la",
  },
  {
    id: "ph_wittgenstein_limits",
    text: "내 언어의 한계가 곧 내 세계의 한계다.",
    author: "루트비히 비트겐슈타인",
    category: "philosophy",
    language: "ko",
    originalText: "Die Grenzen meiner Sprache bedeuten die Grenzen meiner Welt.",
    originalLang: "de",
  },
  {
    id: "ph_wittgenstein_silence",
    text: "말할 수 없는 것에 대해서는 침묵해야 한다.",
    author: "루트비히 비트겐슈타인",
    category: "philosophy",
    language: "ko",
    originalText: "Wovon man nicht sprechen kann, darüber muss man schweigen.",
    originalLang: "de",
  },
  {
    id: "ph_sartre_existence",
    text: "실존은 본질에 앞선다.",
    author: "장 폴 사르트르",
    category: "philosophy",
    language: "ko",
    originalText: "L'existence précède l'essence.",
    originalLang: "fr",
  },
  {
    id: "ph_sartre_free",
    text: "인간은 자유롭도록 선고받았다.",
    author: "장 폴 사르트르",
    category: "philosophy",
    language: "ko",
    originalText: "L'homme est condamné à être libre.",
    originalLang: "fr",
  },
  {
    id: "ph_camus_summer",
    text: "한겨울에 나는 마침내 내 안에 꺾이지 않는 여름이 있음을 알았다.",
    author: "알베르 카뮈",
    category: "philosophy",
    language: "ko",
    originalText: "Au milieu de l'hiver, j'apprenais enfin qu'il y avait en moi un été invincible.",
    originalLang: "fr",
  },
  {
    id: "ph_camus_sisyphus",
    text: "산정을 향한 투쟁 그 자체만으로도 인간의 마음을 채우기에 충분하다. 우리는 시시포스가 행복하다고 상상해야 한다.",
    author: "알베르 카뮈",
    category: "philosophy",
    language: "ko",
    originalText: "Il faut imaginer Sisyphe heureux.",
    originalLang: "fr",
  },
  {
    id: "ph_confucius_ask",
    text: "묻는 자는 잠시 바보가 되지만, 묻지 않는 자는 평생 바보로 남는다.",
    author: "공자",
    category: "philosophy",
    language: "ko",
  },
  {
    id: "ph_confucius_three",
    text: "세 사람이 길을 가면 그중에 반드시 내 스승이 있다.",
    author: "공자",
    category: "philosophy",
    language: "ko",
    tags: ["논어"],
    originalText: "三人行,必有我師焉.",
    originalLang: "zh",
  },
  {
    id: "ph_confucius_not_know",
    text: "아는 것을 안다 하고 모르는 것을 모른다 하는 것, 이것이 진정한 앎이다.",
    author: "공자",
    category: "philosophy",
    language: "ko",
    tags: ["논어"],
    originalText: "知之為知之,不知為不知,是知也.",
    originalLang: "zh",
  },
  {
    id: "ph_confucius_others",
    text: "내가 원하지 않는 바를 남에게 행하지 마라.",
    author: "공자",
    category: "philosophy",
    language: "ko",
    tags: ["논어"],
    originalText: "己所不欲,勿施於人.",
    originalLang: "zh",
  },
  {
    id: "ph_laozi_know_others",
    text: "남을 아는 자는 지혜롭고, 자기를 아는 자는 밝다.",
    author: "노자",
    category: "philosophy",
    language: "ko",
    originalText: "知人者智,自知者明.",
    originalLang: "zh",
  },
  {
    id: "ph_laozi_water",
    text: "최고의 선은 물과 같다. 물은 만물을 이롭게 하면서도 다투지 않는다.",
    author: "노자",
    category: "philosophy",
    language: "ko",
    originalText: "上善若水。水善利萬物而不爭.",
    originalLang: "zh",
  },
  {
    id: "ph_laozi_soft",
    text: "세상에 물보다 부드럽고 약한 것이 없지만, 굳고 강한 것을 치는 데는 물보다 나은 것이 없다.",
    author: "노자",
    category: "philosophy",
    language: "ko",
    originalText: "天下莫柔弱於水,而攻堅強者莫之能勝.",
    originalLang: "zh",
  },
  {
    id: "ph_zhuangzi_butterfly",
    text: "내가 나비 꿈을 꾼 것인지, 나비가 내 꿈을 꾸는 것인지 알지 못한다.",
    author: "장자",
    category: "philosophy",
    language: "ko",
    originalText: "不知周之夢為胡蝶與,胡蝶之夢為周與.",
    originalLang: "zh",
  },
  {
    id: "ph_mencius_heaven",
    text: "하늘이 장차 큰 임무를 맡기려 할 때는, 반드시 먼저 그 마음과 뜻을 괴롭게 한다.",
    author: "맹자",
    category: "philosophy",
    language: "ko",
    originalText: "天將降大任於是人也,必先苦其心志.",
    originalLang: "zh",
  },
  {
    id: "ph_mencius_root",
    text: "모든 일의 근본은 자기 자신을 닦는 데 있다.",
    author: "맹자",
    category: "philosophy",
    language: "ko",
    originalText: "天下之本在國,國之本在家,家之本在身.",
    originalLang: "zh",
  },
  {
    id: "ph_xunzi_accumulate",
    text: "한 걸음 한 걸음 쌓지 않으면 천 리에 이르지 못한다.",
    author: "순자",
    category: "philosophy",
    language: "ko",
    originalText: "不積跬步,無以至千里.",
    originalLang: "zh",
  },
  {
    id: "ph_sunzi_know",
    text: "적을 알고 나를 알면 백 번 싸워도 위태롭지 않다.",
    author: "손자",
    category: "philosophy",
    language: "ko",
    originalText: "知彼知己,百戰不殆.",
    originalLang: "zh",
  },
  {
    id: "ph_sunzi_win_first",
    text: "이기는 군대는 먼저 이겨 놓고 싸우고, 지는 군대는 먼저 싸운 뒤에 이기려 한다.",
    author: "손자",
    category: "philosophy",
    language: "ko",
    originalText: "勝兵先勝而後求戰,敗兵先戰而後求勝.",
    originalLang: "zh",
  },
  {
    id: "ph_sunzi_no_battle",
    text: "백 번 싸워 백 번 이기는 것이 최선이 아니다. 싸우지 않고 적을 굴복시키는 것이 최선이다.",
    author: "손자",
    category: "philosophy",
    language: "ko",
    originalText: "百戰百勝,非善之善者也;不戰而屈人之兵,善之善者也.",
    originalLang: "zh",
  },
  {
    id: "ph_buddha_mind",
    text: "우리는 우리가 생각하는 그대로의 존재다. 모든 것은 마음에서 비롯되고, 마음으로 이루어진다.",
    author: "부처",
    category: "philosophy",
    language: "ko",
    originalText: "We are what we think. All that we are arises with our thoughts. With our thoughts we make the world.",
    originalLang: "en",
  },
  {
    id: "ph_buddha_lamp",
    text: "자기 자신을 등불로 삼고, 자기 자신에게 의지하라.",
    author: "부처",
    category: "philosophy",
    language: "ko",
    originalText: "Be a lamp unto yourself. Work out your liberation with diligence.",
    originalLang: "en",
  },
  {
    id: "ph_buddha_present",
    text: "과거에 머물지 말고, 미래를 꿈꾸지 말고, 지금 이 순간에 마음을 모아라.",
    author: "부처",
    category: "philosophy",
    language: "ko",
    originalText: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    originalLang: "en",
  },

  // ── entrepreneur ────────────────────────────────────
  {
    id: "en_jobs_dots",
    text: "지금의 점들은 미래에서 돌아봐야 비로소 이어진다. 그러니 지금은 그 점들이 언젠가 이어질 것이라 믿어야 한다.",
    author: "스티브 잡스",
    category: "entrepreneur",
    language: "ko",
    originalText:
      "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future.",
    originalLang: "en",
  },
  {
    id: "en_jobs_time",
    text: "너의 시간은 한정돼 있다. 다른 사람의 인생을 살며 낭비하지 마라.",
    author: "스티브 잡스",
    category: "entrepreneur",
    language: "ko",
    originalText: "Your time is limited, so don't waste it living someone else's life.",
    originalLang: "en",
  },
  {
    id: "en_bezos_regret",
    text: "후회 최소화 — 80세의 내가 돌아봤을 때 후회가 가장 적은 선택을 골라라.",
    author: "제프 베조스",
    category: "entrepreneur",
    language: "ko",
    originalText:
      "I wanted to project myself forward to age 80 and minimize the number of regrets I have.",
    originalLang: "en",
  },
  {
    id: "en_musk_persist",
    text: "포기는 옵션이 아니다. 죽거나 완전히 무력해질 때만 포기한다.",
    author: "일론 머스크",
    category: "entrepreneur",
    language: "ko",
    originalText:
      "Persistence is very important. You should not give up unless you are forced to give up.",
    originalLang: "en",
  },
  {
    id: "en_buffett_compound",
    text: "인생은 눈덩이와 같다. 중요한 건 매우 축축한 눈과, 아주 긴 언덕을 찾는 것이다.",
    author: "워런 버핏",
    category: "entrepreneur",
    language: "ko",
    originalText:
      "Life is like a snowball. The important thing is finding wet snow and a really long hill.",
    originalLang: "en",
  },
  {
    id: "en_buffett_reputation",
    text: "평판을 쌓는 데 20년이 걸리고, 망치는 데 5분이면 충분하다. 그 점을 생각하면 행동이 달라진다.",
    author: "워런 버핏",
    category: "entrepreneur",
    language: "ko",
    originalText:
      "It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you'll do things differently.",
    originalLang: "en",
  },
  {
    id: "en_munger_invert",
    text: "거꾸로 생각하라, 항상 거꾸로 생각하라.",
    author: "찰리 멍거",
    category: "entrepreneur",
    language: "ko",
    originalText: "Invert, always invert.",
    originalLang: "en",
  },
  {
    id: "en_thiel_secret",
    text: "어떤 중요한 진실에 대해, 사람들 대부분이 너와 동의하지 않는 것은 무엇인가?",
    author: "피터 틸",
    category: "entrepreneur",
    language: "ko",
    originalText:
      "What important truth do very few people agree with you on?",
    originalLang: "en",
  },
  {
    id: "en_ford_think",
    text: "할 수 있다고 믿든 할 수 없다고 믿든, 너는 옳다.",
    author: "헨리 포드",
    category: "entrepreneur",
    language: "ko",
    originalText: "Whether you think you can, or you think you can't—you're right.",
    originalLang: "en",
  },
  {
    id: "en_chung_ju_yung_try",
    text: "이봐, 해 봤어?",
    author: "정주영",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "en_chung_ju_yung_dawn",
    text: "새벽이 오기 전이 가장 어둡다. 견디는 자가 새벽을 본다.",
    author: "정주영",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "en_jobs_stay_hungry",
    text: "늘 갈망하라, 늘 우직하라.",
    author: "스티브 잡스",
    category: "entrepreneur",
    language: "ko",
    originalText: "Stay hungry, stay foolish.",
    originalLang: "en",
  },
  {
    id: "en_jobs_love_work",
    text: "위대한 일을 하는 유일한 길은 자기가 하는 일을 사랑하는 것이다.",
    author: "스티브 잡스",
    category: "entrepreneur",
    language: "ko",
    originalText: "The only way to do great work is to love what you do.",
    originalLang: "en",
  },
  {
    id: "en_jobs_innovation",
    text: "혁신이 리더와 추종자를 가른다.",
    author: "스티브 잡스",
    category: "entrepreneur",
    language: "ko",
    originalText: "Innovation distinguishes between a leader and a follower.",
    originalLang: "en",
  },
  {
    id: "en_jobs_focus",
    text: "집중이란 해야 할 백 가지 좋은 일에 '아니오'라고 말하는 것이다.",
    author: "스티브 잡스",
    category: "entrepreneur",
    language: "ko",
    originalText: "Focusing is about saying no.",
    originalLang: "en",
  },
  {
    id: "en_jobs_quality",
    text: "품질의 잣대가 되어라. 어떤 사람들은 탁월함이 기대되는 환경에 익숙하지 않다.",
    author: "스티브 잡스",
    category: "entrepreneur",
    language: "ko",
    originalText: "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.",
    originalLang: "en",
  },
  {
    id: "en_bezos_day_one",
    text: "오늘도 첫날이다.",
    author: "제프 베조스",
    category: "entrepreneur",
    language: "ko",
    originalText: "It's still Day 1.",
    originalLang: "en",
  },
  {
    id: "en_bezos_customer",
    text: "고객에서 출발해 거꾸로 일하라.",
    author: "제프 베조스",
    category: "entrepreneur",
    language: "ko",
    originalText: "Start with the customer and work backwards.",
    originalLang: "en",
  },
  {
    id: "en_bezos_brand",
    text: "브랜드란 당신이 자리에 없을 때 사람들이 당신을 두고 하는 말이다.",
    author: "제프 베조스",
    category: "entrepreneur",
    language: "ko",
    originalText: "Your brand is what other people say about you when you're not in the room.",
    originalLang: "en",
  },
  {
    id: "en_bezos_stubborn",
    text: "비전에는 고집스럽고, 세부에는 유연하라.",
    author: "제프 베조스",
    category: "entrepreneur",
    language: "ko",
    originalText: "We are stubborn on vision. We are flexible on details.",
    originalLang: "en",
  },
  {
    id: "en_musk_failure",
    text: "실패는 하나의 선택지다. 무언가 실패하지 않는다면, 충분히 혁신하고 있지 않은 것이다.",
    author: "일론 머스크",
    category: "entrepreneur",
    language: "ko",
    originalText: "Failure is an option here. If things are not failing, you are not innovating enough.",
    originalLang: "en",
  },
  {
    id: "en_musk_important",
    text: "무언가가 충분히 중요하다면, 확률이 너의 편이 아니더라도 그것을 하라.",
    author: "일론 머스크",
    category: "entrepreneur",
    language: "ko",
    originalText: "When something is important enough, you do it even if the odds are not in your favor.",
    originalLang: "en",
  },
  {
    id: "en_musk_criticism",
    text: "끊임없이 비판적 피드백을 구하라. 그것은 무엇이든 줄 수 있는 최고의 조언이다.",
    author: "일론 머스크",
    category: "entrepreneur",
    language: "ko",
    originalText: "A well thought out critique of whatever you're doing is as valuable as gold.",
    originalLang: "en",
  },
  {
    id: "en_buffett_price",
    text: "가격은 당신이 지불하는 것이고, 가치는 당신이 얻는 것이다.",
    author: "워런 버핏",
    category: "entrepreneur",
    language: "ko",
    originalText: "Price is what you pay. Value is what you get.",
    originalLang: "en",
  },
  {
    id: "en_buffett_others_fear",
    text: "남들이 탐욕스러울 때 두려워하고, 남들이 두려워할 때 탐욕스러워라.",
    author: "워런 버핏",
    category: "entrepreneur",
    language: "ko",
    originalText: "Be fearful when others are greedy and greedy when others are fearful.",
    originalLang: "en",
  },
  {
    id: "en_buffett_tree",
    text: "누군가 오래전 나무를 심었기에 오늘 누군가 그늘에 앉아 있다.",
    author: "워런 버핏",
    category: "entrepreneur",
    language: "ko",
    originalText: "Someone is sitting in the shade today because someone planted a tree a long time ago.",
    originalLang: "en",
  },
  {
    id: "en_buffett_circle",
    text: "위험은 자기가 무엇을 하는지 모르는 데서 온다.",
    author: "워런 버핏",
    category: "entrepreneur",
    language: "ko",
    originalText: "Risk comes from not knowing what you're doing.",
    originalLang: "en",
  },
  {
    id: "en_munger_deserve",
    text: "원하는 것을 얻는 가장 확실한 길은 그것을 가질 자격이 있는 사람이 되는 것이다.",
    author: "찰리 멍거",
    category: "entrepreneur",
    language: "ko",
    originalText: "The best way to get what you want is to deserve what you want.",
    originalLang: "en",
  },
  {
    id: "en_munger_patience",
    text: "큰돈은 사고파는 데 있지 않고, 기다리는 데 있다.",
    author: "찰리 멍거",
    category: "entrepreneur",
    language: "ko",
    originalText: "The big money is not in the buying and selling, but in the waiting.",
    originalLang: "en",
  },
  {
    id: "en_gates_unhappy_customer",
    text: "가장 불만족한 고객이야말로 가장 큰 배움의 원천이다.",
    author: "빌 게이츠",
    category: "entrepreneur",
    language: "ko",
    originalText: "Your most unhappy customers are your greatest source of learning.",
    originalLang: "en",
  },
  {
    id: "en_gates_success_teacher",
    text: "성공은 형편없는 스승이다. 똑똑한 사람들에게 자신은 절대 지지 않는다고 착각하게 만든다.",
    author: "빌 게이츠",
    category: "entrepreneur",
    language: "ko",
    originalText: "Success is a lousy teacher. It seduces smart people into thinking they can't lose.",
    originalLang: "en",
  },
  {
    id: "en_gates_overestimate",
    text: "사람들은 1년 안에 할 수 있는 일은 과대평가하고, 10년 안에 할 수 있는 일은 과소평가한다.",
    author: "빌 게이츠",
    category: "entrepreneur",
    language: "ko",
    originalText: "Most people overestimate what they can do in one year and underestimate what they can do in ten years.",
    originalLang: "en",
  },
  {
    id: "en_carnegie_aim",
    text: "당신의 마음을 한 점에 모으는 자가 무엇이든 이룬다.",
    author: "앤드루 카네기",
    category: "entrepreneur",
    language: "ko",
    originalText: "The man who acquires the ability to take full possession of his own mind may take possession of anything else to which he is justly entitled.",
    originalLang: "en",
  },
  {
    id: "en_carnegie_team",
    text: "평범한 사람들이 공동의 목표를 향해 함께 일하게 하는 능력에서 팀워크가 나온다.",
    author: "앤드루 카네기",
    category: "entrepreneur",
    language: "ko",
    originalText: "Teamwork is the ability to work together toward a common vision.",
    originalLang: "en",
  },
  {
    id: "en_rockefeller_persistence",
    text: "성공의 비결은 평범한 일을 비범하게 잘 해내는 것이다.",
    author: "존 D. 록펠러",
    category: "entrepreneur",
    language: "ko",
    originalText: "The secret of success is to do the common things uncommonly well.",
    originalLang: "en",
  },
  {
    id: "en_rockefeller_dont",
    text: "남들이 다 하는 대로 하면, 그들이 가진 것 이상은 결코 가질 수 없다.",
    author: "존 D. 록펠러",
    category: "entrepreneur",
    language: "ko",
    originalText: "Don't be afraid to give up the good to go for the great.",
    originalLang: "en",
  },
  {
    id: "en_disney_doing",
    text: "시작하는 방법은 말하기를 멈추고 행동을 시작하는 것이다.",
    author: "월트 디즈니",
    category: "entrepreneur",
    language: "ko",
    originalText: "The way to get started is to quit talking and begin doing.",
    originalLang: "en",
  },
  {
    id: "en_disney_dream",
    text: "꿈을 꿀 수 있다면, 그것을 이룰 수도 있다.",
    author: "월트 디즈니",
    category: "entrepreneur",
    language: "ko",
    originalText: "If you can dream it, you can do it.",
    originalLang: "en",
  },
  {
    id: "en_disney_curiosity",
    text: "우리는 계속 앞으로 나아가고, 새로운 문을 열며, 새로운 것을 한다. 우리가 호기심을 품기 때문이다.",
    author: "월트 디즈니",
    category: "entrepreneur",
    language: "ko",
    originalText: "We keep moving forward, opening new doors, and doing new things, because we're curious and curiosity keeps leading us down new paths.",
    originalLang: "en",
  },
  {
    id: "en_ford_together",
    text: "함께 모이는 것이 시작이고, 함께 머무는 것이 진보이며, 함께 일하는 것이 성공이다.",
    author: "헨리 포드",
    category: "entrepreneur",
    language: "ko",
    originalText: "Coming together is a beginning, staying together is progress, and working together is success.",
    originalLang: "en",
  },
  {
    id: "en_ford_obstacle",
    text: "장애물이란 목표에서 눈을 뗐을 때 보이는 무서운 것들이다.",
    author: "헨리 포드",
    category: "entrepreneur",
    language: "ko",
    originalText: "Obstacles are those frightful things you see when you take your eyes off your goal.",
    originalLang: "en",
  },
  {
    id: "en_ford_quality",
    text: "품질이란 아무도 보지 않을 때에도 제대로 하는 것이다.",
    author: "헨리 포드",
    category: "entrepreneur",
    language: "ko",
    originalText: "Quality means doing it right when no one is looking.",
    originalLang: "en",
  },
  {
    id: "en_ma_giving_up",
    text: "오늘은 잔혹하고, 내일은 더 잔혹하다. 그러나 모레는 아름답다.",
    author: "잭 마",
    category: "entrepreneur",
    language: "ko",
    originalText: "Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine.",
    originalLang: "en",
  },
  {
    id: "en_ma_complaints",
    text: "불평이 있는 곳에 기회가 있다.",
    author: "잭 마",
    category: "entrepreneur",
    language: "ko",
    originalText: "Where there is a complaint, there is an opportunity.",
    originalLang: "en",
  },
  {
    id: "en_naval_specific",
    text: "부는 잠자는 동안에도 돈을 벌어 주는 자산이다.",
    author: "나발 라비칸트",
    category: "entrepreneur",
    language: "ko",
    originalText: "Seek wealth, not money or status. Wealth is having assets that earn while you sleep.",
    originalLang: "en",
  },
  {
    id: "en_naval_judgment",
    text: "현대 세상에서 보상은 판단력에 주어진다. 그리고 판단력을 위임할 수는 없다.",
    author: "나발 라비칸트",
    category: "entrepreneur",
    language: "ko",
    originalText: "You're not going to get rich renting out your time. You must own equity to gain your financial freedom.",
    originalLang: "en",
  },
  {
    id: "en_dalio_pain",
    text: "고통 더하기 성찰은 곧 발전이다.",
    author: "레이 달리오",
    category: "entrepreneur",
    language: "ko",
    originalText: "Pain plus reflection equals progress.",
    originalLang: "en",
  },
  {
    id: "en_dalio_reality",
    text: "현실을 있는 그대로 받아들이고 그에 맞게 대처하라.",
    author: "레이 달리오",
    category: "entrepreneur",
    language: "ko",
    originalText: "Truth — more precisely, an accurate understanding of reality — is the essential foundation for any good outcome.",
    originalLang: "en",
  },
  {
    id: "en_lee_byung_chul_trust",
    text: "의심하면 쓰지 말고, 일단 썼으면 의심하지 말라.",
    author: "이병철",
    category: "entrepreneur",
    language: "ko",
  },
  {
    id: "en_yu_il_han_society",
    text: "기업에서 얻은 이익은 그 기업을 키워 준 사회에 돌려주는 것이 마땅하다.",
    author: "유일한",
    category: "entrepreneur",
    language: "ko",
  },

  // ── classic (한시·고전) ─────────────────────────────
  {
    id: "cl_dasan_diligence",
    text: "근면(勤)·검소(儉)·성실(誠), 이 셋이 평생을 지탱한다.",
    author: "정약용",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_yi_hwang_learn",
    text: "배움이란 그릇을 키우는 일이다. 그릇이 작으면 큰 것을 담을 수 없다.",
    author: "이황",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_yi_i_resolve",
    text: "뜻을 세우는 것이 학문의 시작이다. 뜻이 서지 않으면 만 권을 읽어도 헛되다.",
    author: "이이",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_yi_sunsin_remain",
    text: "신에게는 아직 열두 척의 배가 남아 있나이다.",
    author: "이순신",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_yi_sunsin_die",
    text: "죽고자 하면 살 것이고, 살고자 하면 죽을 것이다.",
    author: "이순신",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_dosan_time",
    text: "오늘 걸으면, 내일도 걷는다. 오늘 멈추면, 영영 멈춘다.",
    author: "안창호",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_kim_gu_wish",
    text: "나의 소원은 첫째도 우리나라의 완전한 자주독립, 둘째도 자주독립, 셋째도 자주독립이오.",
    author: "김구",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_dubo_pine",
    text: "세한연후지송백지후조 — 추운 겨울이 와야 소나무와 잣나무가 늦게 시드는 줄 안다.",
    author: "공자",
    category: "classic",
    language: "ko",
    tags: ["논어"],
    originalText: "歲寒,然後知松柏之後彫也.",
    originalLang: "zh",
  },
  {
    id: "cl_li_bai_climb",
    text: "오르고 또 오르면 못 오를 산이 없다.",
    author: "옛 한시",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_taegongmang_water",
    text: "물처럼 흘러라 — 멈추면 썩고, 흐르면 길을 찾는다.",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_ahn_jung_geun_read",
    text: "하루라도 책을 읽지 않으면 입안에 가시가 돋는다.",
    author: "안중근",
    category: "classic",
    language: "ko",
    originalText: "一日不讀書,口中生荊棘.",
    originalLang: "zh",
  },
  {
    id: "cl_kim_gu_footstep",
    text: "눈 덮인 들판을 걸어갈 때 함부로 걷지 마라. 오늘 내 발자국이 뒷사람의 이정표가 된다.",
    author: "김구",
    category: "classic",
    language: "ko",
    tags: ["애독 시구"],
    originalText: "踏雪野中去,不須胡亂行.",
    originalLang: "zh",
  },
  {
    id: "cl_dasan_repeat",
    text: "오늘 할 일을 내일로 미루지 마라.",
    author: "정약용",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_yi_i_self",
    text: "사람이 배우지 않으면 사람의 도리를 알지 못한다.",
    author: "이이",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_sejong_people",
    text: "백성은 나라의 근본이니, 근본이 튼튼해야 나라가 평안하다.",
    author: "세종대왕",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_sejong_hangeul",
    text: "어리석은 백성이 이르고자 할 바가 있어도 마침내 제 뜻을 펴지 못하는 이가 많으니라.",
    author: "세종대왕",
    category: "classic",
    language: "ko",
    tags: ["훈민정음 서문"],
  },
  {
    id: "cl_won_hyo_mind",
    text: "마음이 일어나면 갖가지 법이 일어나고, 마음이 사라지면 갖가지 법이 사라진다.",
    author: "원효",
    category: "classic",
    language: "ko",
    originalText: "心生則種種法生,心滅則種種法滅.",
    originalLang: "zh",
  },
  {
    id: "cl_choe_je_u_innaecheon",
    text: "사람이 곧 하늘이니, 사람 섬기기를 하늘 섬기듯 하라.",
    author: "최제우",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_jeongjo_learning",
    text: "배움에는 끝이 없고, 다스림에는 게으름이 없어야 한다.",
    author: "정조",
    category: "classic",
    language: "ko",
  },
  {
    id: "cl_doseon_ohneul",
    text: "오늘 할 수 있는 일에 전력을 다하라. 그러면 내일은 한 걸음 더 나아가 있을 것이다.",
    author: "안창호",
    category: "classic",
    language: "ko",
  },

  // ── leader ──────────────────────────────────────────
  {
    id: "ld_churchill_continue",
    text: "성공은 결정적인 것이 아니고 실패는 치명적인 것이 아니다. 중요한 건 계속할 용기다.",
    author: "윈스턴 처칠",
    category: "leader",
    language: "ko",
    originalText:
      "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    originalLang: "en",
  },
  {
    id: "ld_lincoln_prepare",
    text: "나무를 베는 데 여섯 시간이 주어진다면, 나는 처음 네 시간을 도끼를 가는 데 쓰겠다.",
    author: "에이브러햄 링컨",
    category: "leader",
    language: "ko",
    originalText:
      "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.",
    originalLang: "en",
  },
  {
    id: "ld_mandela_impossible",
    text: "어떤 일이 끝나기 전까지는 항상 불가능해 보인다.",
    author: "넬슨 만델라",
    category: "leader",
    language: "ko",
    originalText: "It always seems impossible until it's done.",
    originalLang: "en",
  },
  {
    id: "ld_gandhi_change",
    text: "세상에서 보고 싶은 변화, 그 자체가 너 자신이 되어라.",
    author: "마하트마 간디",
    category: "leader",
    language: "ko",
    originalText: "Be the change that you wish to see in the world.",
    originalLang: "en",
  },
  {
    id: "ld_roosevelt_arena",
    text: "공로는 비평가에게 있는 것이 아니라, 실제로 경기장에 서 있는 자에게 있다.",
    author: "시어도어 루스벨트",
    category: "leader",
    language: "ko",
    originalText:
      "It is not the critic who counts… The credit belongs to the man who is actually in the arena.",
    originalLang: "en",
  },
  {
    id: "ld_churchill_never",
    text: "절대, 절대, 절대 포기하지 마라.",
    author: "윈스턴 처칠",
    category: "leader",
    language: "ko",
    originalText: "Never, never, never give up.",
    originalLang: "en",
  },
  {
    id: "ld_churchill_pessimist",
    text: "비관주의자는 모든 기회에서 어려움을 보고, 낙관주의자는 모든 어려움에서 기회를 본다.",
    author: "윈스턴 처칠",
    category: "leader",
    language: "ko",
    originalText: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
    originalLang: "en",
  },
  {
    id: "ld_churchill_walking",
    text: "지옥을 지나는 중이라면, 멈추지 말고 계속 걸어가라.",
    author: "윈스턴 처칠",
    category: "leader",
    language: "ko",
    originalText: "If you're going through hell, keep going.",
    originalLang: "en",
  },
  {
    id: "ld_lincoln_future",
    text: "미래를 예측하는 가장 좋은 방법은 미래를 만드는 것이다.",
    author: "에이브러햄 링컨",
    category: "leader",
    language: "ko",
    originalText: "The best way to predict your future is to create it.",
    originalLang: "en",
  },
  {
    id: "ld_lincoln_character",
    text: "거의 모든 사람은 역경을 견딜 수 있다. 그러나 사람의 됨됨이를 시험하려거든 그에게 권력을 주어 보라.",
    author: "에이브러햄 링컨",
    category: "leader",
    language: "ko",
    originalText: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.",
    originalLang: "en",
  },
  {
    id: "ld_lincoln_resolve",
    text: "성공하겠다는 결심이 그 무엇보다 중요하다는 것을 늘 마음에 새겨라.",
    author: "에이브러햄 링컨",
    category: "leader",
    language: "ko",
    originalText: "Always bear in mind that your own resolution to succeed is more important than any other.",
    originalLang: "en",
  },
  {
    id: "ld_mandela_courage",
    text: "용기란 두려움이 없는 것이 아니라, 두려움을 이겨 내는 것임을 나는 배웠다.",
    author: "넬슨 만델라",
    category: "leader",
    language: "ko",
    originalText: "I learned that courage was not the absence of fear, but the triumph over it.",
    originalLang: "en",
  },
  {
    id: "ld_mandela_fall",
    text: "삶에서 가장 큰 영광은 결코 넘어지지 않는 데 있지 않고, 넘어질 때마다 일어서는 데 있다.",
    author: "넬슨 만델라",
    category: "leader",
    language: "ko",
    originalText: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    originalLang: "en",
  },
  {
    id: "ld_mandela_education",
    text: "교육은 세상을 바꾸는 데 쓸 수 있는 가장 강력한 무기다.",
    author: "넬슨 만델라",
    category: "leader",
    language: "ko",
    originalText: "Education is the most powerful weapon which you can use to change the world.",
    originalLang: "en",
  },
  {
    id: "ld_gandhi_tomorrow",
    text: "내일 죽을 것처럼 살고, 영원히 살 것처럼 배워라.",
    author: "마하트마 간디",
    category: "leader",
    language: "ko",
    originalText: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    originalLang: "en",
  },
  {
    id: "ld_gandhi_strength",
    text: "힘은 육체의 능력에서 나오지 않는다. 그것은 굽히지 않는 의지에서 나온다.",
    author: "마하트마 간디",
    category: "leader",
    language: "ko",
    originalText: "Strength does not come from physical capacity. It comes from an indomitable will.",
    originalLang: "en",
  },
  {
    id: "ld_mlk_step",
    text: "믿음이란 계단 전체가 보이지 않아도 첫걸음을 내딛는 것이다.",
    author: "마틴 루서 킹",
    category: "leader",
    language: "ko",
    originalText: "Faith is taking the first step even when you don't see the whole staircase.",
    originalLang: "en",
  },
  {
    id: "ld_mlk_dream",
    text: "나에게는 꿈이 있습니다.",
    author: "마틴 루서 킹",
    category: "leader",
    language: "ko",
    originalText: "I have a dream.",
    originalLang: "en",
  },
  {
    id: "ld_mlk_silence",
    text: "결국 우리는 적의 말이 아니라 친구들의 침묵을 기억하게 될 것이다.",
    author: "마틴 루서 킹",
    category: "leader",
    language: "ko",
    originalText: "In the end, we will remember not the words of our enemies, but the silence of our friends.",
    originalLang: "en",
  },
  {
    id: "ld_mlk_darkness",
    text: "어둠은 어둠을 몰아낼 수 없다. 오직 빛만이 그렇게 할 수 있다.",
    author: "마틴 루서 킹",
    category: "leader",
    language: "ko",
    originalText: "Darkness cannot drive out darkness; only light can do that.",
    originalLang: "en",
  },
  {
    id: "ld_kennedy_ask",
    text: "조국이 당신을 위해 무엇을 해 줄지 묻지 말고, 당신이 조국을 위해 무엇을 할 수 있는지 물어라.",
    author: "존 F. 케네디",
    category: "leader",
    language: "ko",
    originalText: "Ask not what your country can do for you – ask what you can do for your country.",
    originalLang: "en",
  },
  {
    id: "ld_kennedy_change",
    text: "변화는 삶의 법칙이다. 과거나 현재만 바라보는 사람은 분명 미래를 놓친다.",
    author: "존 F. 케네디",
    category: "leader",
    language: "ko",
    originalText: "Change is the law of life. And those who look only to the past or present are certain to miss the future.",
    originalLang: "en",
  },
  {
    id: "ld_fdr_fear",
    text: "우리가 두려워해야 할 단 한 가지는 두려움 그 자체다.",
    author: "프랭클린 D. 루스벨트",
    category: "leader",
    language: "ko",
    originalText: "The only thing we have to fear is fear itself.",
    originalLang: "en",
  },
  {
    id: "ld_fdr_doubts",
    text: "내일을 실현하는 데 유일한 한계는 오늘 우리가 품는 의심뿐이다.",
    author: "프랭클린 D. 루스벨트",
    category: "leader",
    language: "ko",
    originalText: "The only limit to our realization of tomorrow will be our doubts of today.",
    originalLang: "en",
  },
  {
    id: "ld_troosevelt_can",
    text: "할 수 있다고 믿으면, 이미 절반은 이룬 것이다.",
    author: "시어도어 루스벨트",
    category: "leader",
    language: "ko",
    originalText: "Believe you can and you're halfway there.",
    originalLang: "en",
  },
  {
    id: "ld_troosevelt_where",
    text: "지금 있는 자리에서, 가진 것으로, 할 수 있는 것을 하라.",
    author: "시어도어 루스벨트",
    category: "leader",
    language: "ko",
    originalText: "Do what you can, with what you have, where you are.",
    originalLang: "en",
  },
  {
    id: "ld_eroosevelt_consent",
    text: "당신의 동의 없이는 누구도 당신이 열등하다고 느끼게 만들 수 없다.",
    author: "엘리너 루스벨트",
    category: "leader",
    language: "ko",
    originalText: "No one can make you feel inferior without your consent.",
    originalLang: "en",
  },
  {
    id: "ld_eroosevelt_fear",
    text: "두려움에 맞서 멈춰 서서 정면으로 바라본 모든 경험에서 너는 힘과 용기와 자신감을 얻는다.",
    author: "엘리너 루스벨트",
    category: "leader",
    language: "ko",
    originalText: "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.",
    originalLang: "en",
  },
  {
    id: "ld_eroosevelt_future",
    text: "미래는 자기 꿈의 아름다움을 믿는 사람들의 것이다.",
    author: "엘리너 루스벨트",
    category: "leader",
    language: "ko",
    originalText: "The future belongs to those who believe in the beauty of their dreams.",
    originalLang: "en",
  },
  {
    id: "ld_keller_together",
    text: "혼자서는 거의 아무것도 할 수 없지만, 함께라면 우리는 많은 것을 할 수 있다.",
    author: "헬렌 켈러",
    category: "leader",
    language: "ko",
    originalText: "Alone we can do so little; together we can do so much.",
    originalLang: "en",
  },
  {
    id: "ld_keller_door",
    text: "행복의 한 문이 닫히면 다른 문이 열린다. 그러나 우리는 닫힌 문만 오래 바라보느라 열린 문을 보지 못한다.",
    author: "헬렌 켈러",
    category: "leader",
    language: "ko",
    originalText: "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
    originalLang: "en",
  },
  {
    id: "ld_keller_vision",
    text: "세상에서 가장 가엾은 사람은 눈이 보이지만 비전이 없는 사람이다.",
    author: "헬렌 켈러",
    category: "leader",
    language: "ko",
    originalText: "The only thing worse than being blind is having sight but no vision.",
    originalLang: "en",
  },
  {
    id: "ld_franklin_invest",
    text: "지식에 대한 투자가 언제나 가장 큰 이자를 낳는다.",
    author: "벤저민 프랭클린",
    category: "leader",
    language: "ko",
    originalText: "An investment in knowledge pays the best interest.",
    originalLang: "en",
  },
  {
    id: "ld_franklin_today",
    text: "오늘 할 수 있는 일을 내일로 미루지 마라.",
    author: "벤저민 프랭클린",
    category: "leader",
    language: "ko",
    originalText: "Never leave that till tomorrow which you can do today.",
    originalLang: "en",
  },
  {
    id: "ld_franklin_tell",
    text: "내게 말하면 잊어버리고, 가르치면 기억할지 모르며, 직접 하게 하면 비로소 배운다.",
    author: "벤저민 프랭클린",
    category: "leader",
    language: "ko",
    originalText: "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    originalLang: "en",
  },
  {
    id: "ld_franklin_well_done",
    text: "잘한 일이 잘 말한 것보다 낫다.",
    author: "벤저민 프랭클린",
    category: "leader",
    language: "ko",
    originalText: "Well done is better than well said.",
    originalLang: "en",
  },
  {
    id: "ld_washington_honesty",
    text: "정직이 언제나 최선의 방책이다.",
    author: "조지 워싱턴",
    category: "leader",
    language: "ko",
    originalText: "Honesty is always the best policy.",
    originalLang: "en",
  },
  {
    id: "ld_jefferson_luck",
    text: "나는 운을 굳게 믿는다. 그리고 열심히 일할수록 운이 더 따른다는 것을 안다.",
    author: "토머스 제퍼슨",
    category: "leader",
    language: "ko",
    originalText: "I'm a great believer in luck, and I find the harder I work, the more I have of it.",
    originalLang: "en",
  },
  {
    id: "ld_jefferson_today",
    text: "오늘 할 수 있는 일을 결코 내일로 미루지 마라.",
    author: "토머스 제퍼슨",
    category: "leader",
    language: "ko",
    originalText: "Never put off till tomorrow what you can do today.",
    originalLang: "en",
  },
  {
    id: "ld_napoleon_impossible",
    text: "불가능이란 어리석은 자의 사전에나 있는 말이다.",
    author: "나폴레옹 보나파르트",
    category: "leader",
    language: "ko",
    originalText: "Impossible n'est pas français.",
    originalLang: "fr",
  },
  {
    id: "ld_napoleon_victory",
    text: "가장 위험한 순간은 승리의 순간이다.",
    author: "나폴레옹 보나파르트",
    category: "leader",
    language: "ko",
    originalText: "The most dangerous moment comes with victory.",
    originalLang: "en",
  },

  // ── scientist ───────────────────────────────────────
  {
    id: "sc_einstein_curious",
    text: "나는 특별한 재능이 없다. 다만 열정적으로 호기심을 가질 뿐이다.",
    author: "알베르트 아인슈타인",
    category: "scientist",
    language: "ko",
    originalText: "I have no special talent. I am only passionately curious.",
    originalLang: "en",
  },
  {
    id: "sc_einstein_simple",
    text: "더 단순하게 만들 수 없을 만큼 단순해야 한다 — 그 이상은 안 된다.",
    author: "알베르트 아인슈타인",
    category: "scientist",
    language: "ko",
    originalText:
      "Everything should be made as simple as possible, but no simpler.",
    originalLang: "en",
  },
  {
    id: "sc_curie_understand",
    text: "삶에서 두려워해야 할 것은 없다. 다만 이해해야 할 것이 있을 뿐이다. 지금이 더 많이 이해할 시간이다.",
    author: "마리 퀴리",
    category: "scientist",
    language: "ko",
    originalText:
      "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.",
    originalLang: "en",
  },
  {
    id: "sc_feynman_fool",
    text: "첫 번째 원칙: 자기 자신을 속이지 마라. 그리고 자기 자신이야말로 속이기 가장 쉬운 사람이다.",
    author: "리처드 파인만",
    category: "scientist",
    language: "ko",
    originalText:
      "The first principle is that you must not fool yourself—and you are the easiest person to fool.",
    originalLang: "en",
  },
  {
    id: "sc_darwin_adapt",
    text: "살아남는 것은 가장 강한 종도, 가장 똑똑한 종도 아니다. 변화에 가장 잘 적응하는 종이다.",
    author: "찰스 다윈",
    category: "scientist",
    language: "ko",
    originalText:
      "It is not the strongest of the species that survives, nor the most intelligent that survives. It is the one that is the most adaptable to change.",
    originalLang: "en",
  },
  {
    id: "sc_einstein_imagination",
    text: "상상력은 지식보다 더 중요하다. 지식은 한정되어 있다.",
    author: "알베르트 아인슈타인",
    category: "scientist",
    language: "ko",
    originalText: "Imagination is more important than knowledge.",
    originalLang: "en",
  },
  {
    id: "sc_einstein_mistake",
    text: "한 번도 실수해 본 적 없는 사람은 새로운 것을 시도해 본 적 없는 사람이다.",
    author: "알베르트 아인슈타인",
    category: "scientist",
    language: "ko",
    originalText: "A person who never made a mistake never tried anything new.",
    originalLang: "en",
  },
  {
    id: "sc_einstein_value",
    text: "성공한 사람이 되려 하지 말고, 가치 있는 사람이 되려 하라.",
    author: "알베르트 아인슈타인",
    category: "scientist",
    language: "ko",
    originalText: "Try not to become a man of success, but rather try to become a man of value.",
    originalLang: "en",
  },
  {
    id: "sc_einstein_bicycle",
    text: "삶은 자전거를 타는 것과 같다. 균형을 잡으려면 계속 움직여야 한다.",
    author: "알베르트 아인슈타인",
    category: "scientist",
    language: "ko",
    originalText: "Life is like riding a bicycle. To keep your balance you must keep moving.",
    originalLang: "en",
  },
  {
    id: "sc_einstein_problem",
    text: "문제를 만든 그 사고방식으로는 그 문제를 풀 수 없다.",
    author: "알베르트 아인슈타인",
    category: "scientist",
    language: "ko",
    originalText: "We cannot solve our problems with the same thinking we used when we created them.",
    originalLang: "en",
  },
  {
    id: "sc_newton_giants",
    text: "내가 더 멀리 보았다면, 그것은 거인들의 어깨 위에 서 있었기 때문이다.",
    author: "아이작 뉴턴",
    category: "scientist",
    language: "ko",
    originalText: "If I have seen further it is by standing on the shoulders of Giants.",
    originalLang: "en",
  },
  {
    id: "sc_newton_pebble",
    text: "나는 바닷가에서 노는 소년 같았다. 진리의 큰 바다는 온통 미지로 내 앞에 펼쳐져 있었다.",
    author: "아이작 뉴턴",
    category: "scientist",
    language: "ko",
    originalText: "I was like a boy playing on the sea-shore, whilst the great ocean of truth lay all undiscovered before me.",
    originalLang: "en",
  },
  {
    id: "sc_curie_persevere",
    text: "우리는 끈기를 가져야 하며, 무엇보다 자기 자신에 대한 믿음을 가져야 한다.",
    author: "마리 퀴리",
    category: "scientist",
    language: "ko",
    originalText: "We must have perseverance and above all confidence in ourselves.",
    originalLang: "en",
  },
  {
    id: "sc_curie_idea",
    text: "사람에 대한 호기심이 줄고, 생각에 대한 호기심이 커진다.",
    author: "마리 퀴리",
    category: "scientist",
    language: "ko",
    originalText: "Be less curious about people and more curious about ideas.",
    originalLang: "en",
  },
  {
    id: "sc_feynman_nature",
    text: "자연은 속일 수 없다. 자연은 결코 속지 않기 때문이다.",
    author: "리처드 파인만",
    category: "scientist",
    language: "ko",
    originalText: "Nature cannot be fooled.",
    originalLang: "en",
  },
  {
    id: "sc_feynman_pleasure",
    text: "무언가를 알아내는 데서 오는 기쁨, 발견의 짜릿함, 그것이 내게는 보상이다.",
    author: "리처드 파인만",
    category: "scientist",
    language: "ko",
    originalText: "The prize is the pleasure of finding the thing out, the kick in the discovery.",
    originalLang: "en",
  },
  {
    id: "sc_darwin_courage",
    text: "한 시간을 헛되이 보낼 수 있는 사람은 아직 삶의 가치를 발견하지 못한 것이다.",
    author: "찰스 다윈",
    category: "scientist",
    language: "ko",
    originalText: "A man who dares to waste one hour of time has not discovered the value of life.",
    originalLang: "en",
  },
  {
    id: "sc_tesla_present",
    text: "현재는 그들의 것이지만, 내가 진정으로 일해 온 미래는 나의 것이다.",
    author: "니콜라 테슬라",
    category: "scientist",
    language: "ko",
    originalText: "Let the future tell the truth. The present is theirs; the future, for which I really worked, is mine.",
    originalLang: "en",
  },
  {
    id: "sc_tesla_brain",
    text: "내 두뇌는 수신기일 뿐이다. 우주에는 우리가 지식과 영감과 힘을 얻는 핵심이 있다.",
    author: "니콜라 테슬라",
    category: "scientist",
    language: "ko",
    originalText: "My brain is only a receiver. In the Universe there is a core from which we obtain knowledge, strength and inspiration.",
    originalLang: "en",
  },
  {
    id: "sc_edison_perspiration",
    text: "천재는 1퍼센트의 영감과 99퍼센트의 노력으로 이루어진다.",
    author: "토머스 에디슨",
    category: "scientist",
    language: "ko",
    originalText: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    originalLang: "en",
  },
  {
    id: "sc_edison_not_fail",
    text: "나는 실패한 것이 아니다. 작동하지 않는 만 가지 방법을 찾아낸 것이다.",
    author: "토머스 에디슨",
    category: "scientist",
    language: "ko",
    originalText: "I have not failed. I've just found 10,000 ways that won't work.",
    originalLang: "en",
  },
  {
    id: "sc_edison_give_up",
    text: "삶에서 실패한 많은 이들은 포기할 때 자신이 성공에 얼마나 가까이 있었는지 깨닫지 못한 사람들이다.",
    author: "토머스 에디슨",
    category: "scientist",
    language: "ko",
    originalText: "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    originalLang: "en",
  },
  {
    id: "sc_edison_opportunity",
    text: "기회를 놓치는 까닭은, 기회가 작업복을 입고 일처럼 보이기 때문이다.",
    author: "토머스 에디슨",
    category: "scientist",
    language: "ko",
    originalText: "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
    originalLang: "en",
  },
  {
    id: "sc_galileo_teach",
    text: "사람에게 무엇을 가르칠 수는 없다. 다만 그가 스스로 깨닫도록 도울 수 있을 뿐이다.",
    author: "갈릴레오 갈릴레이",
    category: "scientist",
    language: "ko",
    originalText: "You cannot teach a man anything; you can only help him find it within himself.",
    originalLang: "en",
  },
  {
    id: "sc_galileo_moves",
    text: "그래도 지구는 돈다.",
    author: "갈릴레오 갈릴레이",
    category: "scientist",
    language: "ko",
    originalText: "Eppur si muove.",
    originalLang: "it",
  },
  {
    id: "sc_pasteur_chance",
    text: "관찰의 영역에서 행운은 준비된 마음에만 찾아온다.",
    author: "루이 파스퇴르",
    category: "scientist",
    language: "ko",
    originalText: "Dans les champs de l'observation le hasard ne favorise que les esprits préparés.",
    originalLang: "fr",
  },
  {
    id: "sc_pasteur_will",
    text: "나의 힘은 오직 나의 끈기에 있다.",
    author: "루이 파스퇴르",
    category: "scientist",
    language: "ko",
    originalText: "Let me tell you the secret that has led me to my goal: my strength lies solely in my tenacity.",
    originalLang: "en",
  },
  {
    id: "sc_hawking_look_up",
    text: "발밑을 내려다보지 말고 고개를 들어 별을 바라보라.",
    author: "스티븐 호킹",
    category: "scientist",
    language: "ko",
    originalText: "Remember to look up at the stars and not down at your feet.",
    originalLang: "en",
  },
  {
    id: "sc_hawking_intelligence",
    text: "지능이란 변화에 적응하는 능력이다.",
    author: "스티븐 호킹",
    category: "scientist",
    language: "ko",
    originalText: "Intelligence is the ability to adapt to change.",
    originalLang: "en",
  },
  {
    id: "sc_hawking_give_up",
    text: "아무리 삶이 힘들어 보여도, 누구나 할 수 있고 성공할 수 있는 일이 있다. 중요한 건 포기하지 않는 것이다.",
    author: "스티븐 호킹",
    category: "scientist",
    language: "ko",
    originalText: "However difficult life may seem, there is always something you can do and succeed at. It matters that you don't just give up.",
    originalLang: "en",
  },
  {
    id: "sc_sagan_cosmos",
    text: "우리는 별의 물질로 이루어져 있다.",
    author: "칼 세이건",
    category: "scientist",
    language: "ko",
    originalText: "We are made of star-stuff.",
    originalLang: "en",
  },
  {
    id: "sc_sagan_extraordinary",
    text: "비범한 주장에는 비범한 증거가 필요하다.",
    author: "칼 세이건",
    category: "scientist",
    language: "ko",
    originalText: "Extraordinary claims require extraordinary evidence.",
    originalLang: "en",
  },
  {
    id: "sc_davinci_doing",
    text: "의지를 갖는 것만으로는 부족하다. 실행해야 한다.",
    author: "레오나르도 다 빈치",
    category: "scientist",
    language: "ko",
    originalText: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.",
    originalLang: "en",
  },
  {
    id: "sc_davinci_simplicity",
    text: "단순함이야말로 궁극의 정교함이다.",
    author: "레오나르도 다 빈치",
    category: "scientist",
    language: "ko",
    originalText: "Simplicity is the ultimate sophistication.",
    originalLang: "en",
  },
  {
    id: "sc_bohr_expert",
    text: "전문가란 아주 좁은 분야에서 저지를 수 있는 모든 실수를 다 저질러 본 사람이다.",
    author: "닐스 보어",
    category: "scientist",
    language: "ko",
    originalText: "An expert is a person who has made all the mistakes that can be made in a very narrow field.",
    originalLang: "en",
  },

  // ── literature ──────────────────────────────────────
  {
    id: "li_kafka_path",
    text: "길은 걸어가는 그 순간에만 존재한다. 멈추면 길도 사라진다.",
    author: "프란츠 카프카",
    category: "literature",
    language: "ko",
  },
  {
    id: "li_hemingway_strong",
    text: "세상은 모두를 부순다. 그리고 그 부서진 자리에서 강해지는 사람들이 있다.",
    author: "어니스트 헤밍웨이",
    category: "literature",
    language: "ko",
    originalText:
      "The world breaks every one and afterward many are strong at the broken places.",
    originalLang: "en",
  },
  {
    id: "li_dostoevsky_small",
    text: "큰 결심보다 작은 한 걸음이 사람을 더 멀리 데려간다.",
    author: "표도르 도스토옙스키",
    category: "literature",
    language: "ko",
  },
  {
    id: "li_tolstoy_change",
    text: "모두가 세상을 바꾸려 하지만, 누구도 자기 자신을 바꾸려 하지 않는다.",
    author: "레프 톨스토이",
    category: "literature",
    language: "ko",
    originalText:
      "Все думают о том, как изменить мир, но никто не думает о том, как изменить себя.",
    originalLang: "ru",
  },
  {
    id: "li_yoon_dongju_sky",
    text: "죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를.",
    author: "윤동주",
    category: "literature",
    language: "ko",
  },
  {
    id: "li_han_yongun_silence",
    text: "님은 갔지만, 나는 님을 보내지 아니하였습니다.",
    author: "한용운",
    category: "literature",
    language: "ko",
  },
  {
    id: "li_park_kyungri_river",
    text: "사람은 세월에 흘러가는 것이 아니라, 세월을 살아 통과하는 것이다.",
    author: "박경리",
    category: "literature",
    language: "ko",
  },
  {
    id: "li_goethe_now",
    text: "지금 시작하라. 새로운 시작이 곧 새로운 삶이다.",
    author: "괴테",
    category: "literature",
    language: "ko",
  },
  {
    id: "li_hemingway_tomorrow",
    text: "오늘에 대해 생각하는 것 말고는 결코 생각하지 마라. 내일이 오면 내일을 생각하면 된다.",
    author: "어니스트 헤밍웨이",
    category: "literature",
    language: "ko",
    originalText: "Never think about anything except what you are doing now. Tomorrow will come and then it will be today.",
    originalLang: "en",
  },
  {
    id: "li_hemingway_listen",
    text: "남의 말을 완전히 들어 주는 사람은 드물다.",
    author: "어니스트 헤밍웨이",
    category: "literature",
    language: "ko",
    originalText: "When people talk listen completely. Most people never listen.",
    originalLang: "en",
  },
  {
    id: "li_dostoevsky_secret",
    text: "삶의 비밀은 그저 사는 데 있지 않고, 무엇을 위해 사느냐에 있다.",
    author: "표도르 도스토옙스키",
    category: "literature",
    language: "ko",
    originalText: "The mystery of human existence lies not in just staying alive, but in finding something to live for.",
    originalLang: "en",
  },
  {
    id: "li_dostoevsky_beauty",
    text: "아름다움이 세상을 구원할 것이다.",
    author: "표도르 도스토옙스키",
    category: "literature",
    language: "ko",
    originalText: "Красота спасёт мир.",
    originalLang: "ru",
  },
  {
    id: "li_tolstoy_patience",
    text: "가장 강한 두 전사는 인내와 시간이다.",
    author: "레프 톨스토이",
    category: "literature",
    language: "ko",
    originalText: "The two most powerful warriors are patience and time.",
    originalLang: "en",
  },
  {
    id: "li_tolstoy_now",
    text: "가장 중요한 때는 바로 지금이다. 우리가 무언가를 다스릴 수 있는 유일한 시간이기 때문이다.",
    author: "레프 톨스토이",
    category: "literature",
    language: "ko",
    originalText: "Remember then: there is only one time that is important — Now! It is the most important time because it is the only time when we have any power.",
    originalLang: "en",
  },
  {
    id: "li_goethe_dream",
    text: "할 수 있거나 할 수 있다고 꿈꾸는 일이라면 무엇이든 시작하라. 대담함 속에 천재성과 힘과 마법이 있다.",
    author: "괴테",
    category: "literature",
    language: "ko",
    originalText: "Whatever you can do or dream you can, begin it. Boldness has genius, power and magic in it.",
    originalLang: "en",
  },
  {
    id: "li_goethe_treat",
    text: "사람을 마땅히 되어야 할 모습으로 대하면, 그는 그렇게 될 수 있는 사람이 된다.",
    author: "괴테",
    category: "literature",
    language: "ko",
    originalText: "If you treat an individual as he ought to be, he will become what he ought to be.",
    originalLang: "en",
  },
  {
    id: "li_goethe_knowing",
    text: "아는 것만으로는 충분하지 않다. 적용해야 한다. 의지만으로는 충분하지 않다. 실행해야 한다.",
    author: "괴테",
    category: "literature",
    language: "ko",
    originalText: "Knowing is not enough; we must apply. Willing is not enough; we must do.",
    originalLang: "en",
  },
  {
    id: "li_shakespeare_true",
    text: "무엇보다, 너 자신에게 진실하라.",
    author: "윌리엄 셰익스피어",
    category: "literature",
    language: "ko",
    originalText: "This above all: to thine own self be true.",
    originalLang: "en",
  },
  {
    id: "li_shakespeare_ready",
    text: "준비됨이 전부다.",
    author: "윌리엄 셰익스피어",
    category: "literature",
    language: "ko",
    originalText: "The readiness is all.",
    originalLang: "en",
  },
  {
    id: "li_shakespeare_stage",
    text: "온 세상이 무대이고, 모든 남녀는 한낱 배우일 뿐이다.",
    author: "윌리엄 셰익스피어",
    category: "literature",
    language: "ko",
    originalText: "All the world's a stage, and all the men and women merely players.",
    originalLang: "en",
  },
  {
    id: "li_twain_start",
    text: "앞서 나가는 비결은 일단 시작하는 것이다.",
    author: "마크 트웨인",
    category: "literature",
    language: "ko",
    originalText: "The secret of getting ahead is getting started.",
    originalLang: "en",
  },
  {
    id: "li_twain_twenty",
    text: "지금부터 20년 뒤, 너는 했던 일보다 하지 않은 일로 더 실망할 것이다.",
    author: "마크 트웨인",
    category: "literature",
    language: "ko",
    originalText: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
    originalLang: "en",
  },
  {
    id: "li_twain_kindness",
    text: "친절은 귀머거리도 들을 수 있고 눈먼 이도 볼 수 있는 언어다.",
    author: "마크 트웨인",
    category: "literature",
    language: "ko",
    originalText: "Kindness is the language which the deaf can hear and the blind can see.",
    originalLang: "en",
  },
  {
    id: "li_wilde_yourself",
    text: "너 자신이 되어라. 다른 사람의 자리는 이미 다 차 있다.",
    author: "오스카 와일드",
    category: "literature",
    language: "ko",
    originalText: "Be yourself; everyone else is already taken.",
    originalLang: "en",
  },
  {
    id: "li_wilde_stars",
    text: "우리는 모두 시궁창에 있지만, 그중 누군가는 별을 바라본다.",
    author: "오스카 와일드",
    category: "literature",
    language: "ko",
    originalText: "We are all in the gutter, but some of us are looking at the stars.",
    originalLang: "en",
  },
  {
    id: "li_wilde_experience",
    text: "경험이란 사람들이 자기 실수에 붙이는 이름이다.",
    author: "오스카 와일드",
    category: "literature",
    language: "ko",
    originalText: "Experience is simply the name we give our mistakes.",
    originalLang: "en",
  },
  {
    id: "li_hugo_idea",
    text: "때를 만난 사상보다 강한 것은 세상에 없다.",
    author: "빅토르 위고",
    category: "literature",
    language: "ko",
    originalText: "On résiste à l'invasion des armées; on ne résiste pas à l'invasion des idées.",
    originalLang: "fr",
  },
  {
    id: "li_hugo_future",
    text: "미래에는 여러 이름이 있다. 약한 자에게는 도달할 수 없는 것이고, 겁쟁이에게는 미지의 것이며, 용감한 자에게는 기회다.",
    author: "빅토르 위고",
    category: "literature",
    language: "ko",
    originalText: "The future has several names. For the weak, it is impossible; for the fainthearted, it is unknown; but for the valiant, it is ideal.",
    originalLang: "en",
  },
  {
    id: "li_dickens_useful",
    text: "남에게 짐을 덜어 주는 사람은 누구도 쓸모없는 사람이 아니다.",
    author: "찰스 디킨스",
    category: "literature",
    language: "ko",
    originalText: "No one is useless in this world who lightens the burdens of another.",
    originalLang: "en",
  },
  {
    id: "li_saint_exupery_heart",
    text: "오직 마음으로만 올바로 볼 수 있다. 본질적인 것은 눈에 보이지 않는다.",
    author: "앙투안 드 생텍쥐페리",
    category: "literature",
    language: "ko",
    originalText: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.",
    originalLang: "fr",
  },
  {
    id: "li_saint_exupery_ship",
    text: "배를 만들고 싶다면, 사람들에게 나무를 모으게 하지 말고 끝없는 바다를 동경하게 하라.",
    author: "앙투안 드 생텍쥐페리",
    category: "literature",
    language: "ko",
    originalText: "If you want to build a ship, don't drum up people to collect wood, but rather teach them to long for the endless immensity of the sea.",
    originalLang: "en",
  },
  {
    id: "li_saint_exupery_future",
    text: "미래를 두고 너의 임무는 그것을 예측하는 것이 아니라, 그것을 가능하게 하는 것이다.",
    author: "앙투안 드 생텍쥐페리",
    category: "literature",
    language: "ko",
    originalText: "As for the future, your task is not to foresee it, but to enable it.",
    originalLang: "en",
  },
  {
    id: "li_rilke_questions",
    text: "마음속 풀리지 않은 모든 것에 대해 인내심을 가지고, 질문 그 자체를 사랑하려 애써라.",
    author: "라이너 마리아 릴케",
    category: "literature",
    language: "ko",
    originalText: "Be patient toward all that is unsolved in your heart and try to love the questions themselves.",
    originalLang: "en",
  },
  {
    id: "li_whitman_song",
    text: "이 세상이라는 강력한 연극은 계속되고, 너도 한 편의 시를 보탤 수 있다.",
    author: "월트 휘트먼",
    category: "literature",
    language: "ko",
    originalText: "That the powerful play goes on, and you may contribute a verse.",
    originalLang: "en",
  },
  {
    id: "li_dickinson_hope",
    text: "희망은 깃털 달린 것, 영혼에 깃들어 노래한다.",
    author: "에밀리 디킨슨",
    category: "literature",
    language: "ko",
    originalText: "Hope is the thing with feathers that perches in the soul.",
    originalLang: "en",
  },
  {
    id: "li_angelou_feel",
    text: "사람들은 네가 한 말과 한 일은 잊어도, 네가 그들에게 어떤 느낌을 주었는지는 결코 잊지 않는다.",
    author: "마야 안젤루",
    category: "literature",
    language: "ko",
    originalText: "People will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
    originalLang: "en",
  },
  {
    id: "li_angelou_rise",
    text: "그래도 나는 일어선다.",
    author: "마야 안젤루",
    category: "literature",
    language: "ko",
    originalText: "Still I rise.",
    originalLang: "en",
  },
  {
    id: "li_cslewis_goal",
    text: "새로운 목표를 세우거나 새로운 꿈을 꾸기에 너무 늦은 나이란 없다.",
    author: "C.S. 루이스",
    category: "literature",
    language: "ko",
    originalText: "You are never too old to set another goal or to dream a new dream.",
    originalLang: "en",
  },
  {
    id: "li_cslewis_hardship",
    text: "고난은 종종 평범한 사람들을 비범한 운명으로 이끄는 준비 과정이다.",
    author: "C.S. 루이스",
    category: "literature",
    language: "ko",
    originalText: "Hardships often prepare ordinary people for an extraordinary destiny.",
    originalLang: "en",
  },
  {
    id: "li_tolkien_gold",
    text: "반짝인다고 다 금은 아니며, 헤매는 자가 모두 길을 잃은 것은 아니다.",
    author: "J.R.R. 톨킨",
    category: "literature",
    language: "ko",
    originalText: "All that is gold does not glitter, not all those who wander are lost.",
    originalLang: "en",
  },
  {
    id: "li_tolkien_decide",
    text: "우리가 결정할 수 있는 것은, 주어진 시간으로 무엇을 할 것인가뿐이다.",
    author: "J.R.R. 톨킨",
    category: "literature",
    language: "ko",
    originalText: "All we have to decide is what to do with the time that is given us.",
    originalLang: "en",
  },
  {
    id: "li_hesse_within",
    text: "각자에게 진정한 소명은 단 하나, 자기 자신에게 이르는 것이다.",
    author: "헤르만 헤세",
    category: "literature",
    language: "ko",
    originalText: "Jedem Menschen ist die wahre Berufung nur eines: zu sich selbst zu kommen.",
    originalLang: "de",
  },
  {
    id: "li_hesse_bird",
    text: "새는 알을 깨고 나온다. 알은 곧 세계다. 태어나려는 자는 한 세계를 깨뜨려야 한다.",
    author: "헤르만 헤세",
    category: "literature",
    language: "ko",
    originalText: "Der Vogel kämpft sich aus dem Ei. Das Ei ist die Welt. Wer geboren werden will, muss eine Welt zerstören.",
    originalLang: "de",
  },
  {
    id: "li_lu_xun_road",
    text: "본래 땅 위에는 길이 없었다. 걷는 사람이 많아지면 그것이 곧 길이 된다.",
    author: "루쉰",
    category: "literature",
    language: "ko",
    originalText: "其實地上本沒有路,走的人多了,也便成了路.",
    originalLang: "zh",
  },
  {
    id: "li_tagore_water",
    text: "물을 바라만 보고 있으면 결코 바다를 건널 수 없다.",
    author: "라빈드라나트 타고르",
    category: "literature",
    language: "ko",
    originalText: "You can't cross the sea merely by standing and staring at the water.",
    originalLang: "en",
  },
  {
    id: "li_tagore_stars",
    text: "낮을 잃었다고 눈물 흘리면, 별까지 놓치게 될 것이다.",
    author: "라빈드라나트 타고르",
    category: "literature",
    language: "ko",
    originalText: "If you cry because the sun has gone out of your life, your tears will prevent you from seeing the stars.",
    originalLang: "en",
  },
  {
    id: "li_rumi_wound",
    text: "상처는 빛이 너에게 들어오는 자리다.",
    author: "루미",
    category: "literature",
    language: "ko",
    originalText: "The wound is the place where the Light enters you.",
    originalLang: "en",
  },
  {
    id: "li_rumi_yesterday",
    text: "어제의 나는 영리해서 세상을 바꾸려 했다. 오늘의 나는 지혜로워 나 자신을 바꾼다.",
    author: "루미",
    category: "literature",
    language: "ko",
    originalText: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
    originalLang: "en",
  },
  {
    id: "li_beopjeong_emptiness",
    text: "무소유란 아무것도 갖지 않는 것이 아니라, 불필요한 것을 갖지 않는 것이다.",
    author: "법정",
    category: "literature",
    language: "ko",
  },
  {
    id: "li_ham_seokheon_think",
    text: "생각하는 백성이라야 산다.",
    author: "함석헌",
    category: "literature",
    language: "ko",
  },

  // ── personal (앵커용 — 본인이 채우거나 어드민이 보강) ─
  {
    id: "ps_self_today",
    text: "오늘 흘린 땀은, 10년 뒤의 내가 매일 마주할 풍경이다.",
    author: "10년 후의 나",
    category: "personal",
    language: "ko",
  },
  {
    id: "ps_self_silent",
    text: "조용히, 매일, 멈추지 않는 자가 결국 모든 것을 가진다.",
    author: "10년 후의 나",
    category: "personal",
    language: "ko",
  },
  {
    id: "ps_self_now",
    text: "10년 후의 내가 가장 부러워할 시간은, 바로 지금 이 순간이다.",
    author: "10년 후의 나",
    category: "personal",
    language: "ko",
  },
];
