/**
 * English famous-quote seed pool.
 *
 * Curation principle (per user request):
 *  - Globally recognized voices (Stoics, scientists, founders, leaders).
 *  - U.S./U.K./globally English-speaking cultural figures.
 *  - Author names rendered in the form most commonly searchable in English.
 *  - Quotes are the most widely cited, verifiable forms in English. We avoid
 *    well-known misattributions (e.g. the spurious "Be the change…" line).
 */
import type { FamousQuoteSeed } from "@/lib/famousQuotesSeed";

export const FAMOUS_QUOTES_SEED_EN: ReadonlyArray<FamousQuoteSeed> = [
  // Philosophy / Stoics / classics
  {
    id: "en_aurelius_obstacle",
    text: "The impediment to action advances action. What stands in the way becomes the way.",
    author: "Marcus Aurelius",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_aurelius_today",
    text: "You have power over your mind — not outside events. Realize this, and you will find strength.",
    author: "Marcus Aurelius",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_seneca_time",
    text: "It is not that we have a short time to live, but that we waste a lot of it.",
    author: "Seneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_socrates_examined",
    text: "The unexamined life is not worth living.",
    author: "Socrates",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_aristotle_excellence",
    text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    author: "Aristotle",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_nietzsche_why",
    text: "He who has a why to live for can bear almost any how.",
    author: "Friedrich Nietzsche",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_confucius_stop",
    text: "It does not matter how slowly you go, as long as you do not stop.",
    author: "Confucius",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_laozi_step",
    text: "A journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    category: "philosophy",
    language: "en",
  },

  // Entrepreneurs / leaders
  {
    id: "en_jobs_dots",
    text: "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_jobs_time",
    text: "Your time is limited, so don't waste it living someone else's life.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_buffett_reputation",
    text: "It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you'll do things differently.",
    author: "Warren Buffett",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_buffett_compound",
    text: "Someone is sitting in the shade today because someone planted a tree a long time ago.",
    author: "Warren Buffett",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_bezos_regret",
    text: "I knew that if I failed I wouldn't regret that, but I knew the one thing I might regret is not trying.",
    author: "Jeff Bezos",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_edison_perspiration",
    text: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    author: "Thomas Edison",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_einstein_imagination",
    text: "Imagination is more important than knowledge.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_einstein_mistakes",
    text: "A person who never made a mistake never tried anything new.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_curie_understand",
    text: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.",
    author: "Marie Curie",
    category: "scientist",
    language: "en",
  },

  // Leaders
  {
    id: "en_lincoln_future",
    text: "The best way to predict the future is to create it.",
    author: "Abraham Lincoln",
    category: "leader",
    language: "en",
  },
  {
    id: "en_mandela_impossible",
    text: "It always seems impossible until it's done.",
    author: "Nelson Mandela",
    category: "leader",
    language: "en",
  },
  {
    id: "en_mlk_step",
    text: "Faith is taking the first step even when you don't see the whole staircase.",
    author: "Martin Luther King Jr.",
    category: "leader",
    language: "en",
  },
  {
    id: "en_roosevelt_arena",
    text: "It is not the critic who counts… the credit belongs to the man who is actually in the arena.",
    author: "Theodore Roosevelt",
    category: "leader",
    language: "en",
  },
  {
    id: "en_eleanor_dream",
    text: "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    category: "leader",
    language: "en",
  },

  // Literature
  {
    id: "en_angelou_rise",
    text: "You may encounter many defeats, but you must not be defeated.",
    author: "Maya Angelou",
    category: "literature",
    language: "en",
  },
  {
    id: "en_angelou_courage",
    text: "Courage is the most important of all the virtues, because without courage you can't practice any other virtue consistently.",
    author: "Maya Angelou",
    category: "literature",
    language: "en",
  },
  {
    id: "en_hemingway_strong",
    text: "The world breaks everyone, and afterward many are strong at the broken places.",
    author: "Ernest Hemingway",
    category: "literature",
    language: "en",
  },
  {
    id: "en_emerson_self",
    text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    author: "Ralph Waldo Emerson",
    category: "literature",
    language: "en",
  },
  {
    id: "en_thoreau_dreams",
    text: "Go confidently in the direction of your dreams. Live the life you have imagined.",
    author: "Henry David Thoreau",
    category: "literature",
    language: "en",
  },

  // ─────────────────────────────────────────────────────────
  // APPENDED — canonical, widely-documented lines only.
  // ─────────────────────────────────────────────────────────

  // Philosophy — Stoics (Marcus Aurelius / Seneca / Epictetus)
  {
    id: "en_aurelius_thoughts",
    text: "The happiness of your life depends upon the quality of your thoughts.",
    author: "Marcus Aurelius",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_aurelius_waste",
    text: "Do not act as if you had ten thousand years to live. While you have life in you, while you still can, become good.",
    author: "Marcus Aurelius",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_aurelius_simplify",
    text: "If it is not right, do not do it; if it is not true, do not say it.",
    author: "Marcus Aurelius",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_seneca_luck",
    text: "Luck is what happens when preparation meets opportunity.",
    author: "Seneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_seneca_difficult",
    text: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.",
    author: "Seneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_seneca_suffer",
    text: "We suffer more often in imagination than in reality.",
    author: "Seneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_seneca_harbor",
    text: "If one does not know to which port one is sailing, no wind is favorable.",
    author: "Seneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_epictetus_control",
    text: "It's not what happens to you, but how you react to it that matters.",
    author: "Epictetus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_epictetus_wish",
    text: "Don't explain your philosophy. Embody it.",
    author: "Epictetus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_epictetus_listen",
    text: "We have two ears and one mouth so that we can listen twice as much as we speak.",
    author: "Epictetus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_epictetus_master",
    text: "No man is free who is not master of himself.",
    author: "Epictetus",
    category: "philosophy",
    language: "en",
  },

  // Philosophy — Greek (Socrates / Plato / Aristotle / Heraclitus / Epicurus / Diogenes)
  {
    id: "en_socrates_wisdom",
    text: "The only true wisdom is in knowing you know nothing.",
    author: "Socrates",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_socrates_new",
    text: "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
    author: "Socrates",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_socrates_wonder",
    text: "Wonder is the beginning of wisdom.",
    author: "Socrates",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_plato_begin",
    text: "The beginning is the most important part of the work.",
    author: "Plato",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_plato_conquer",
    text: "The first and greatest victory is to conquer yourself.",
    author: "Plato",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_plato_kind",
    text: "Be kind, for everyone you meet is fighting a hard battle.",
    author: "Plato",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_aristotle_courage",
    text: "Courage is the first of human qualities because it is the quality which guarantees the others.",
    author: "Aristotle",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_aristotle_educate",
    text: "Educating the mind without educating the heart is no education at all.",
    author: "Aristotle",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_aristotle_whole",
    text: "The whole is greater than the sum of its parts.",
    author: "Aristotle",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_aristotle_doubt",
    text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
    author: "Aristotle",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_heraclitus_river",
    text: "No man ever steps in the same river twice, for it's not the same river and he's not the same man.",
    author: "Heraclitus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_heraclitus_change",
    text: "There is nothing permanent except change.",
    author: "Heraclitus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_heraclitus_character",
    text: "Character is destiny.",
    author: "Heraclitus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_epicurus_have",
    text: "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.",
    author: "Epicurus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_epicurus_wealth",
    text: "Not what we have but what we enjoy constitutes our abundance.",
    author: "Epicurus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_diogenes_sun",
    text: "Stand out of my light.",
    author: "Diogenes",
    category: "philosophy",
    language: "en",
  },

  // Philosophy — Eastern (Confucius / Lao Tzu / Sun Tzu / Buddha / Rumi)
  {
    id: "en_confucius_gem",
    text: "The gem cannot be polished without friction, nor man perfected without trials.",
    author: "Confucius",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_confucius_love",
    text: "Choose a job you love, and you will never have to work a day in your life.",
    author: "Confucius",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_confucius_lit",
    text: "It is better to light a candle than to curse the darkness.",
    author: "Confucius",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_confucius_silence",
    text: "Silence is a true friend who never betrays.",
    author: "Confucius",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_laozi_master",
    text: "When I let go of what I am, I become what I might be.",
    author: "Lao Tzu",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_laozi_others",
    text: "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.",
    author: "Lao Tzu",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_laozi_water",
    text: "Nothing in the world is as soft and yielding as water. Yet for dissolving the hard and inflexible, nothing can surpass it.",
    author: "Lao Tzu",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_suntzu_know",
    text: "If you know the enemy and know yourself, you need not fear the result of a hundred battles.",
    author: "Sun Tzu",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_suntzu_opportunity",
    text: "In the midst of chaos, there is also opportunity.",
    author: "Sun Tzu",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_suntzu_supreme",
    text: "The supreme art of war is to subdue the enemy without fighting.",
    author: "Sun Tzu",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_buddha_mind",
    text: "The mind is everything. What you think you become.",
    author: "Buddha",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_buddha_anger",
    text: "Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.",
    author: "Buddha",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_buddha_present",
    text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    author: "Buddha",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_rumi_wound",
    text: "The wound is the place where the Light enters you.",
    author: "Rumi",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_rumi_seek",
    text: "What you seek is seeking you.",
    author: "Rumi",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_rumi_lamp",
    text: "Set your life on fire. Seek those who fan your flames.",
    author: "Rumi",
    category: "philosophy",
    language: "en",
  },

  // Philosophy — modern (Kant / Nietzsche / Schopenhauer / Kierkegaard / Sartre / Camus / Spinoza / Pascal / Montaigne / Voltaire / Thoreau / Emerson / James / Russell)
  {
    id: "en_kant_law",
    text: "Act only according to that maxim whereby you can at the same time will that it should become a universal law.",
    author: "Immanuel Kant",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_kant_wonder",
    text: "Two things fill the mind with ever new and increasing admiration and awe: the starry heavens above me and the moral law within me.",
    author: "Immanuel Kant",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_nietzsche_stronger",
    text: "That which does not kill us makes us stronger.",
    author: "Friedrich Nietzsche",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_nietzsche_dance",
    text: "You must have chaos within you to give birth to a dancing star.",
    author: "Friedrich Nietzsche",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_nietzsche_abyss",
    text: "And when you gaze long into an abyss the abyss also gazes into you.",
    author: "Friedrich Nietzsche",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_schopenhauer_truth",
    text: "All truth passes through three stages. First, it is ridiculed. Second, it is violently opposed. Third, it is accepted as being self-evident.",
    author: "Arthur Schopenhauer",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_schopenhauer_talent",
    text: "Talent hits a target no one else can hit; genius hits a target no one else can see.",
    author: "Arthur Schopenhauer",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_kierkegaard_backward",
    text: "Life can only be understood backwards; but it must be lived forwards.",
    author: "Søren Kierkegaard",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_kierkegaard_dare",
    text: "To dare is to lose one's footing momentarily. Not to dare is to lose oneself.",
    author: "Søren Kierkegaard",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_sartre_choice",
    text: "We are our choices.",
    author: "Jean-Paul Sartre",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_sartre_free",
    text: "Man is condemned to be free.",
    author: "Jean-Paul Sartre",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_camus_summer",
    text: "In the depth of winter, I finally learned that within me there lay an invincible summer.",
    author: "Albert Camus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_camus_happy",
    text: "One must imagine Sisyphus happy.",
    author: "Albert Camus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_camus_freedom",
    text: "Real generosity toward the future lies in giving all to the present.",
    author: "Albert Camus",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_spinoza_understand",
    text: "I have made a ceaseless effort not to ridicule, not to bewail, not to scorn human actions, but to understand them.",
    author: "Baruch Spinoza",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_spinoza_peace",
    text: "Peace is not an absence of war, it is a virtue, a state of mind, a disposition for benevolence, confidence, justice.",
    author: "Baruch Spinoza",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_pascal_heart",
    text: "The heart has its reasons which reason knows nothing of.",
    author: "Blaise Pascal",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_pascal_room",
    text: "All of humanity's problems stem from man's inability to sit quietly in a room alone.",
    author: "Blaise Pascal",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_montaigne_fear",
    text: "He who fears he shall suffer, already suffers because he fears.",
    author: "Michel de Montaigne",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_montaigne_life",
    text: "My life has been full of terrible misfortunes most of which never happened.",
    author: "Michel de Montaigne",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_voltaire_doubt",
    text: "Doubt is not a pleasant condition, but certainty is absurd.",
    author: "Voltaire",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_voltaire_judge",
    text: "Judge a man by his questions rather than by his answers.",
    author: "Voltaire",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_voltaire_garden",
    text: "We must cultivate our own garden.",
    author: "Voltaire",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_thoreau_simplify",
    text: "Our life is frittered away by detail. Simplify, simplify.",
    author: "Henry David Thoreau",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_thoreau_success",
    text: "If one advances confidently in the direction of his dreams, he will meet with a success unexpected in common hours.",
    author: "Henry David Thoreau",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_emerson_within",
    text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    author: "Ralph Waldo Emerson",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_emerson_trail",
    text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    author: "Ralph Waldo Emerson",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_emerson_today",
    text: "Write it on your heart that every day is the best day in the year.",
    author: "Ralph Waldo Emerson",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_james_alter",
    text: "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes of mind.",
    author: "William James",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_james_act",
    text: "Act as if what you do makes a difference. It does.",
    author: "William James",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_russell_doubt",
    text: "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.",
    author: "Bertrand Russell",
    category: "philosophy",
    language: "en",
  },
  {
    id: "en_russell_love",
    text: "The good life is one inspired by love and guided by knowledge.",
    author: "Bertrand Russell",
    category: "philosophy",
    language: "en",
  },

  // Scientists (Einstein / Newton / Darwin / Curie / Feynman / Tesla / Edison / Galileo / Hawking / Sagan / da Vinci / Bohr / Hippocrates)
  {
    id: "en_einstein_value",
    text: "Try not to become a man of success, but rather try to become a man of value.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_einstein_curious",
    text: "I have no special talent. I am only passionately curious.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_einstein_simple",
    text: "Everything should be made as simple as possible, but no simpler.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_einstein_bicycle",
    text: "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_einstein_problem",
    text: "We cannot solve our problems with the same thinking we used when we created them.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_newton_giants",
    text: "If I have seen further it is by standing on the shoulders of giants.",
    author: "Isaac Newton",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_newton_ocean",
    text: "I was like a boy playing on the sea-shore, while the great ocean of truth lay all undiscovered before me.",
    author: "Isaac Newton",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_darwin_adapt",
    text: "It is not the strongest of the species that survives, nor the most intelligent that survives. It is the one that is the most adaptable to change.",
    author: "Charles Darwin",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_darwin_courage",
    text: "A man who dares to waste one hour of time has not discovered the value of life.",
    author: "Charles Darwin",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_curie_persevere",
    text: "Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves.",
    author: "Marie Curie",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_curie_curious",
    text: "Be less curious about people and more curious about ideas.",
    author: "Marie Curie",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_feynman_fool",
    text: "The first principle is that you must not fool yourself — and you are the easiest person to fool.",
    author: "Richard Feynman",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_feynman_pleasure",
    text: "I would rather have questions that can't be answered than answers that can't be questioned.",
    author: "Richard Feynman",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_tesla_present",
    text: "The present is theirs; the future, for which I really worked, is mine.",
    author: "Nikola Tesla",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_tesla_energy",
    text: "If you want to find the secrets of the universe, think in terms of energy, frequency and vibration.",
    author: "Nikola Tesla",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_edison_fail",
    text: "I have not failed. I've just found 10,000 ways that won't work.",
    author: "Thomas Edison",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_edison_giveup",
    text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
    author: "Thomas Edison",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_galileo_teach",
    text: "You cannot teach a man anything; you can only help him find it within himself.",
    author: "Galileo Galilei",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_galileo_reason",
    text: "I do not feel obliged to believe that the same God who has endowed us with sense, reason, and intellect has intended us to forgo their use.",
    author: "Galileo Galilei",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_hawking_lookup",
    text: "Remember to look up at the stars and not down at your feet.",
    author: "Stephen Hawking",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_hawking_intelligence",
    text: "Intelligence is the ability to adapt to change.",
    author: "Stephen Hawking",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_hawking_giveup",
    text: "However difficult life may seem, there is always something you can do and succeed at.",
    author: "Stephen Hawking",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_sagan_starstuff",
    text: "We are made of star-stuff.",
    author: "Carl Sagan",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_sagan_extraordinary",
    text: "Extraordinary claims require extraordinary evidence.",
    author: "Carl Sagan",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_davinci_doing",
    text: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.",
    author: "Leonardo da Vinci",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_davinci_simplicity",
    text: "Simplicity is the ultimate sophistication.",
    author: "Leonardo da Vinci",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_davinci_obstacles",
    text: "Obstacles cannot crush me; every obstacle yields to stern resolve.",
    author: "Leonardo da Vinci",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_bohr_expert",
    text: "An expert is a person who has made all the mistakes that can be made in a very narrow field.",
    author: "Niels Bohr",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_hippocrates_food",
    text: "Let food be thy medicine and medicine be thy food.",
    author: "Hippocrates",
    category: "scientist",
    language: "en",
  },
  {
    id: "en_hippocrates_walking",
    text: "Walking is man's best medicine.",
    author: "Hippocrates",
    category: "scientist",
    language: "en",
  },

  // Entrepreneurs (Jobs / Bezos / Musk / Buffett / Munger / Ford / Gates / Thiel / Carnegie / Rockefeller / Disney / Jack Ma / Naval / Dalio / Sam Walton / Reid Hoffman)
  {
    id: "en_jobs_hungry",
    text: "Stay hungry. Stay foolish.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_jobs_quality",
    text: "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_jobs_innovation",
    text: "Innovation distinguishes between a leader and a follower.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_bezos_customer",
    text: "We see our customers as invited guests to a party, and we are the hosts. It's our job every day to make every important aspect of the customer experience a little bit better.",
    author: "Jeff Bezos",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_bezos_day1",
    text: "If you double the number of experiments you do per year you're going to double your inventiveness.",
    author: "Jeff Bezos",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_musk_persist",
    text: "Persistence is very important. You should not give up unless you are forced to give up.",
    author: "Elon Musk",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_musk_failure",
    text: "Failure is an option here. If things are not failing, you are not innovating enough.",
    author: "Elon Musk",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_musk_important",
    text: "When something is important enough, you do it even if the odds are not in your favor.",
    author: "Elon Musk",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_buffett_price",
    text: "Price is what you pay. Value is what you get.",
    author: "Warren Buffett",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_buffett_rule",
    text: "Rule No. 1: Never lose money. Rule No. 2: Never forget Rule No. 1.",
    author: "Warren Buffett",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_buffett_fearful",
    text: "Be fearful when others are greedy and greedy when others are fearful.",
    author: "Warren Buffett",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_munger_invert",
    text: "Invert, always invert.",
    author: "Charlie Munger",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_munger_deserve",
    text: "The best way to get what you want is to deserve what you want.",
    author: "Charlie Munger",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_ford_think",
    text: "Whether you think you can, or you think you can't — you're right.",
    author: "Henry Ford",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_ford_together",
    text: "Coming together is a beginning; keeping together is progress; working together is success.",
    author: "Henry Ford",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_ford_obstacles",
    text: "Obstacles are those frightful things you see when you take your eyes off your goal.",
    author: "Henry Ford",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_gates_success",
    text: "Success is a lousy teacher. It seduces smart people into thinking they can't lose.",
    author: "Bill Gates",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_gates_unhappy",
    text: "Your most unhappy customers are your greatest source of learning.",
    author: "Bill Gates",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_thiel_secret",
    text: "What important truth do very few people agree with you on?",
    author: "Peter Thiel",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_thiel_competition",
    text: "Competition is for losers.",
    author: "Peter Thiel",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_carnegie_team",
    text: "Teamwork is the ability to work together toward a common vision.",
    author: "Andrew Carnegie",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_carnegie_eggs",
    text: "Put all your eggs in one basket, and then watch that basket.",
    author: "Andrew Carnegie",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_rockefeller_dollar",
    text: "I would rather earn one percent of a hundred people's efforts than one hundred percent of my own efforts.",
    author: "John D. Rockefeller",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_rockefeller_secret",
    text: "Don't be afraid to give up the good to go for the great.",
    author: "John D. Rockefeller",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_disney_doing",
    text: "The way to get started is to quit talking and begin doing.",
    author: "Walt Disney",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_disney_dream",
    text: "If you can dream it, you can do it.",
    author: "Walt Disney",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_jackma_giveup",
    text: "Never give up. Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine.",
    author: "Jack Ma",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_jackma_complaints",
    text: "Where there are complaints, there are opportunities.",
    author: "Jack Ma",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_naval_specific",
    text: "Escape competition through authenticity.",
    author: "Naval Ravikant",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_naval_judgment",
    text: "Earn with your mind, not your time.",
    author: "Naval Ravikant",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_dalio_pain",
    text: "Pain plus reflection equals progress.",
    author: "Ray Dalio",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_dalio_truth",
    text: "Truth — more precisely, an accurate understanding of reality — is the essential foundation for any good outcome.",
    author: "Ray Dalio",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_walton_customer",
    text: "There is only one boss. The customer. And he can fire everybody in the company from the chairman on down, simply by spending his money somewhere else.",
    author: "Sam Walton",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "en_hoffman_pivot",
    text: "If you are not embarrassed by the first version of your product, you've launched too late.",
    author: "Reid Hoffman",
    category: "entrepreneur",
    language: "en",
  },

  // Leaders (Lincoln / Churchill / Mandela / Gandhi / MLK / JFK / FDR / T.Roosevelt / E.Roosevelt / Washington / Jefferson / Napoleon / Helen Keller / Franklin / Thatcher)
  {
    id: "en_lincoln_character",
    text: "Character is like a tree and reputation like its shadow. The shadow is what we think of it; the tree is the real thing.",
    author: "Abraham Lincoln",
    category: "leader",
    language: "en",
  },
  {
    id: "en_lincoln_prepare",
    text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.",
    author: "Abraham Lincoln",
    category: "leader",
    language: "en",
  },
  {
    id: "en_lincoln_years",
    text: "And in the end, it's not the years in your life that count. It's the life in your years.",
    author: "Abraham Lincoln",
    category: "leader",
    language: "en",
  },
  {
    id: "en_churchill_continue",
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "leader",
    language: "en",
  },
  {
    id: "en_churchill_nevergivein",
    text: "Never give in. Never give in. Never, never, never, never.",
    author: "Winston Churchill",
    category: "leader",
    language: "en",
  },
  {
    id: "en_churchill_pessimist",
    text: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
    author: "Winston Churchill",
    category: "leader",
    language: "en",
  },
  {
    id: "en_churchill_walking",
    text: "If you're going through hell, keep going.",
    author: "Winston Churchill",
    category: "leader",
    language: "en",
  },
  {
    id: "en_mandela_education",
    text: "Education is the most powerful weapon which you can use to change the world.",
    author: "Nelson Mandela",
    category: "leader",
    language: "en",
  },
  {
    id: "en_mandela_fall",
    text: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Nelson Mandela",
    category: "leader",
    language: "en",
  },
  {
    id: "en_mandela_free",
    text: "For to be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.",
    author: "Nelson Mandela",
    category: "leader",
    language: "en",
  },
  {
    id: "en_gandhi_gentle",
    text: "In a gentle way, you can shake the world.",
    author: "Mahatma Gandhi",
    category: "leader",
    language: "en",
  },
  {
    id: "en_gandhi_tomorrow",
    text: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    author: "Mahatma Gandhi",
    category: "leader",
    language: "en",
  },
  {
    id: "en_gandhi_strength",
    text: "Strength does not come from physical capacity. It comes from an indomitable will.",
    author: "Mahatma Gandhi",
    category: "leader",
    language: "en",
  },
  {
    id: "en_mlk_love",
    text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
    author: "Martin Luther King Jr.",
    category: "leader",
    language: "en",
  },
  {
    id: "en_mlk_silence",
    text: "Our lives begin to end the day we become silent about things that matter.",
    author: "Martin Luther King Jr.",
    category: "leader",
    language: "en",
  },
  {
    id: "en_mlk_keepmoving",
    text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.",
    author: "Martin Luther King Jr.",
    category: "leader",
    language: "en",
  },
  {
    id: "en_jfk_ask",
    text: "Ask not what your country can do for you — ask what you can do for your country.",
    author: "John F. Kennedy",
    category: "leader",
    language: "en",
  },
  {
    id: "en_jfk_change",
    text: "Change is the law of life. And those who look only to the past or present are certain to miss the future.",
    author: "John F. Kennedy",
    category: "leader",
    language: "en",
  },
  {
    id: "en_jfk_effort",
    text: "Efforts and courage are not enough without purpose and direction.",
    author: "John F. Kennedy",
    category: "leader",
    language: "en",
  },
  {
    id: "en_fdr_fear",
    text: "The only thing we have to fear is fear itself.",
    author: "Franklin D. Roosevelt",
    category: "leader",
    language: "en",
  },
  {
    id: "en_fdr_doubts",
    text: "The only limit to our realization of tomorrow will be our doubts of today.",
    author: "Franklin D. Roosevelt",
    category: "leader",
    language: "en",
  },
  {
    id: "en_troosevelt_can",
    text: "Believe you can and you're halfway there.",
    author: "Theodore Roosevelt",
    category: "leader",
    language: "en",
  },
  {
    id: "en_troosevelt_do",
    text: "Do what you can, with what you have, where you are.",
    author: "Theodore Roosevelt",
    category: "leader",
    language: "en",
  },
  {
    id: "en_eleanor_consent",
    text: "No one can make you feel inferior without your consent.",
    author: "Eleanor Roosevelt",
    category: "leader",
    language: "en",
  },
  {
    id: "en_eleanor_fear",
    text: "You must do the thing you think you cannot do.",
    author: "Eleanor Roosevelt",
    category: "leader",
    language: "en",
  },
  {
    id: "en_eleanor_minds",
    text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    author: "Eleanor Roosevelt",
    category: "leader",
    language: "en",
  },
  {
    id: "en_washington_honesty",
    text: "I hope I shall possess firmness and virtue enough to maintain what I consider the most enviable of all titles, the character of an honest man.",
    author: "George Washington",
    category: "leader",
    language: "en",
  },
  {
    id: "en_jefferson_luck",
    text: "I'm a great believer in luck, and I find the harder I work the more I have of it.",
    author: "Thomas Jefferson",
    category: "leader",
    language: "en",
  },
  {
    id: "en_jefferson_today",
    text: "Never put off till tomorrow what you can do today.",
    author: "Thomas Jefferson",
    category: "leader",
    language: "en",
  },
  {
    id: "en_napoleon_impossible",
    text: "Impossible is a word to be found only in the dictionary of fools.",
    author: "Napoleon Bonaparte",
    category: "leader",
    language: "en",
  },
  {
    id: "en_napoleon_lead",
    text: "A leader is a dealer in hope.",
    author: "Napoleon Bonaparte",
    category: "leader",
    language: "en",
  },
  {
    id: "en_keller_alone",
    text: "Alone we can do so little; together we can do so much.",
    author: "Helen Keller",
    category: "leader",
    language: "en",
  },
  {
    id: "en_keller_adventure",
    text: "Life is either a daring adventure or nothing at all.",
    author: "Helen Keller",
    category: "leader",
    language: "en",
  },
  {
    id: "en_keller_face",
    text: "Keep your face to the sunshine and you cannot see a shadow.",
    author: "Helen Keller",
    category: "leader",
    language: "en",
  },
  {
    id: "en_franklin_invest",
    text: "An investment in knowledge pays the best interest.",
    author: "Benjamin Franklin",
    category: "leader",
    language: "en",
  },
  {
    id: "en_franklin_tellme",
    text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    author: "Benjamin Franklin",
    category: "leader",
    language: "en",
  },
  {
    id: "en_franklin_today",
    text: "Don't put off until tomorrow what you can do today.",
    author: "Benjamin Franklin",
    category: "leader",
    language: "en",
  },
  {
    id: "en_thatcher_lead",
    text: "If you want something said, ask a man; if you want something done, ask a woman.",
    author: "Margaret Thatcher",
    category: "leader",
    language: "en",
  },
  {
    id: "en_thatcher_consensus",
    text: "Don't follow the crowd, let the crowd follow you.",
    author: "Margaret Thatcher",
    category: "leader",
    language: "en",
  },

  // Literature (Twain / Wilde / Shakespeare / Hugo / Dickens / Saint-Exupéry / Goethe / Tolstoy / Dostoevsky / Kafka / Whitman / Dickinson / C.S.Lewis / Tolkien / Hesse / Tagore / Shaw / Frost / Kipling / Angelou / Hemingway / Emerson / Thoreau)
  {
    id: "en_twain_started",
    text: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
    category: "literature",
    language: "en",
  },
  {
    id: "en_twain_twentyyears",
    text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
    author: "Mark Twain",
    category: "literature",
    language: "en",
  },
  {
    id: "en_twain_kindness",
    text: "Kindness is the language which the deaf can hear and the blind can see.",
    author: "Mark Twain",
    category: "literature",
    language: "en",
  },
  {
    id: "en_wilde_yourself",
    text: "Be yourself; everyone else is already taken.",
    author: "Oscar Wilde",
    category: "literature",
    language: "en",
  },
  {
    id: "en_wilde_stars",
    text: "We are all in the gutter, but some of us are looking at the stars.",
    author: "Oscar Wilde",
    category: "literature",
    language: "en",
  },
  {
    id: "en_wilde_live",
    text: "To live is the rarest thing in the world. Most people exist, that is all.",
    author: "Oscar Wilde",
    category: "literature",
    language: "en",
  },
  {
    id: "en_shakespeare_true",
    text: "This above all: to thine own self be true.",
    author: "William Shakespeare",
    category: "literature",
    language: "en",
  },
  {
    id: "en_shakespeare_greatness",
    text: "Be not afraid of greatness. Some are born great, some achieve greatness, and some have greatness thrust upon them.",
    author: "William Shakespeare",
    category: "literature",
    language: "en",
  },
  {
    id: "en_shakespeare_action",
    text: "Action is eloquence.",
    author: "William Shakespeare",
    category: "literature",
    language: "en",
  },
  {
    id: "en_hugo_idea",
    text: "Nothing is more powerful than an idea whose time has come.",
    author: "Victor Hugo",
    category: "literature",
    language: "en",
  },
  {
    id: "en_hugo_future",
    text: "He who every morning plans the transactions of the day and follows out that plan, carries a thread that will guide him through the labyrinth of the most busy life.",
    author: "Victor Hugo",
    category: "literature",
    language: "en",
  },
  {
    id: "en_dickens_world",
    text: "No one is useless in this world who lightens the burdens of another.",
    author: "Charles Dickens",
    category: "literature",
    language: "en",
  },
  {
    id: "en_dickens_heart",
    text: "Have a heart that never hardens, and a temper that never tires, and a touch that never hurts.",
    author: "Charles Dickens",
    category: "literature",
    language: "en",
  },
  {
    id: "en_exupery_heart",
    text: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.",
    author: "Antoine de Saint-Exupéry",
    category: "literature",
    language: "en",
  },
  {
    id: "en_exupery_sea",
    text: "If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.",
    author: "Antoine de Saint-Exupéry",
    category: "literature",
    language: "en",
  },
  {
    id: "en_exupery_perfection",
    text: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.",
    author: "Antoine de Saint-Exupéry",
    category: "literature",
    language: "en",
  },
  {
    id: "en_goethe_begin",
    text: "Whatever you can do or dream you can, begin it. Boldness has genius, power and magic in it.",
    author: "Johann Wolfgang von Goethe",
    category: "literature",
    language: "en",
  },
  {
    id: "en_goethe_today",
    text: "Knowing is not enough; we must apply. Willing is not enough; we must do.",
    author: "Johann Wolfgang von Goethe",
    category: "literature",
    language: "en",
  },
  {
    id: "en_goethe_treat",
    text: "Treat people as if they were what they ought to be, and you help them to become what they are capable of being.",
    author: "Johann Wolfgang von Goethe",
    category: "literature",
    language: "en",
  },
  {
    id: "en_tolstoy_change",
    text: "Everyone thinks of changing the world, but no one thinks of changing himself.",
    author: "Leo Tolstoy",
    category: "literature",
    language: "en",
  },
  {
    id: "en_tolstoy_time",
    text: "The two most powerful warriors are patience and time.",
    author: "Leo Tolstoy",
    category: "literature",
    language: "en",
  },
  {
    id: "en_dostoevsky_act",
    text: "The mystery of human existence lies not in just staying alive, but in finding something to live for.",
    author: "Fyodor Dostoevsky",
    category: "literature",
    language: "en",
  },
  {
    id: "en_dostoevsky_step",
    text: "Taking a new step, uttering a new word, is what people fear most.",
    author: "Fyodor Dostoevsky",
    category: "literature",
    language: "en",
  },
  {
    id: "en_kafka_path",
    text: "Paths are made by walking.",
    author: "Franz Kafka",
    category: "literature",
    language: "en",
  },
  {
    id: "en_kafka_book",
    text: "A book must be the axe for the frozen sea within us.",
    author: "Franz Kafka",
    category: "literature",
    language: "en",
  },
  {
    id: "en_whitman_song",
    text: "Keep your face always toward the sunshine — and shadows will fall behind you.",
    author: "Walt Whitman",
    category: "literature",
    language: "en",
  },
  {
    id: "en_whitman_verse",
    text: "That the powerful play goes on, and you may contribute a verse.",
    author: "Walt Whitman",
    category: "literature",
    language: "en",
  },
  {
    id: "en_dickinson_hope",
    text: "Hope is the thing with feathers that perches in the soul.",
    author: "Emily Dickinson",
    category: "literature",
    language: "en",
  },
  {
    id: "en_dickinson_dwell",
    text: "I dwell in possibility.",
    author: "Emily Dickinson",
    category: "literature",
    language: "en",
  },
  {
    id: "en_cslewis_goal",
    text: "You are never too old to set another goal or to dream a new dream.",
    author: "C.S. Lewis",
    category: "literature",
    language: "en",
  },
  {
    id: "en_cslewis_hardships",
    text: "Hardships often prepare ordinary people for an extraordinary destiny.",
    author: "C.S. Lewis",
    category: "literature",
    language: "en",
  },
  {
    id: "en_tolkien_gold",
    text: "Not all those who wander are lost.",
    author: "J.R.R. Tolkien",
    category: "literature",
    language: "en",
  },
  {
    id: "en_tolkien_time",
    text: "All we have to decide is what to do with the time that is given us.",
    author: "J.R.R. Tolkien",
    category: "literature",
    language: "en",
  },
  {
    id: "en_hesse_within",
    text: "Within you there is a stillness and a sanctuary to which you can retreat at any time and be yourself.",
    author: "Hermann Hesse",
    category: "literature",
    language: "en",
  },
  {
    id: "en_hesse_magic",
    text: "Some of us think holding on makes us strong; but sometimes it is letting go.",
    author: "Hermann Hesse",
    category: "literature",
    language: "en",
  },
  {
    id: "en_tagore_faith",
    text: "Faith is the bird that feels the light when the dawn is still dark.",
    author: "Rabindranath Tagore",
    category: "literature",
    language: "en",
  },
  {
    id: "en_tagore_cry",
    text: "If you cry because the sun has gone out of your life, your tears will prevent you from seeing the stars.",
    author: "Rabindranath Tagore",
    category: "literature",
    language: "en",
  },
  {
    id: "en_shaw_create",
    text: "Life isn't about finding yourself. Life is about creating yourself.",
    author: "George Bernard Shaw",
    category: "literature",
    language: "en",
  },
  {
    id: "en_shaw_progress",
    text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.",
    author: "George Bernard Shaw",
    category: "literature",
    language: "en",
  },
  {
    id: "en_frost_road",
    text: "Two roads diverged in a wood, and I — I took the one less traveled by, and that has made all the difference.",
    author: "Robert Frost",
    category: "literature",
    language: "en",
  },
  {
    id: "en_frost_through",
    text: "The best way out is always through.",
    author: "Robert Frost",
    category: "literature",
    language: "en",
  },
  {
    id: "en_kipling_if",
    text: "If you can keep your head when all about you are losing theirs and blaming it on you.",
    author: "Rudyard Kipling",
    category: "literature",
    language: "en",
  },
  {
    id: "en_kipling_dream",
    text: "If you can dream — and not make dreams your master; if you can think — and not make thoughts your aim.",
    author: "Rudyard Kipling",
    category: "literature",
    language: "en",
  },
  {
    id: "en_angelou_feel",
    text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
    author: "Maya Angelou",
    category: "literature",
    language: "en",
  },
  {
    id: "en_angelou_try",
    text: "If you don't like something, change it. If you can't change it, change your attitude.",
    author: "Maya Angelou",
    category: "literature",
    language: "en",
  },
  {
    id: "en_hemingway_today",
    text: "Now is no time to think of what you do not have. Think of what you can do with what there is.",
    author: "Ernest Hemingway",
    category: "literature",
    language: "en",
  },
  {
    id: "en_hemingway_courage",
    text: "Courage is grace under pressure.",
    author: "Ernest Hemingway",
    category: "literature",
    language: "en",
  },
  {
    id: "en_emerson_enthusiasm",
    text: "Nothing great was ever achieved without enthusiasm.",
    author: "Ralph Waldo Emerson",
    category: "literature",
    language: "en",
  },
  {
    id: "en_thoreau_busy",
    text: "It is not enough to be busy; so are the ants. The question is: what are we busy about?",
    author: "Henry David Thoreau",
    category: "literature",
    language: "en",
  },

  // Personal — anchor entries (filled by the user / admin reinforcement)
  {
    id: "en_self_today",
    text: "The sweat I pour today is the view the me of ten years from now will wake to every morning.",
    author: "Me, 10 Years From Now",
    category: "personal",
    language: "en",
  },
  {
    id: "en_self_silent",
    text: "The one who keeps going — quietly, daily, without stopping — ends up holding everything.",
    author: "Me, 10 Years From Now",
    category: "personal",
    language: "en",
  },
];
