/**
 * Semilla de citas célebres en español.
 *
 * Curaduría:
 *  - Voces globales (estoicos, Einstein, Curie) traducidas a español natural.
 *  - Figuras culturales del mundo hispanohablante: Cervantes, Borges, Lorca,
 *    Neruda, García Márquez, Octavio Paz, Frida Kahlo, Sor Juana, Picasso.
 *  - Texto en castellano contemporáneo, evitando paráfrasis demasiado libres.
 */
import type { FamousQuoteSeed } from "@/lib/famousQuotesSeed";

export const FAMOUS_QUOTES_SEED_ES: ReadonlyArray<FamousQuoteSeed> = [
  // Filosofía / clásicos
  {
    id: "es_aurelio_obstaculo",
    text: "El obstáculo a la acción avanza la acción. Lo que se interpone en el camino se convierte en el camino.",
    author: "Marco Aurelio",
    category: "philosophy",
    language: "en", // 시드 type 호환을 위해 en 으로 두되, 실제 출력 언어는 시드 language 분리로 관리.
  },
  {
    id: "es_seneca_tiempo",
    text: "No es que tengamos poco tiempo, sino que perdemos mucho.",
    author: "Séneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_socrates_examinada",
    text: "Una vida sin examen no merece ser vivida.",
    author: "Sócrates",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_aristoteles_habito",
    text: "Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito.",
    author: "Aristóteles",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_nietzsche_porque",
    text: "Quien tiene un porqué para vivir, puede soportar casi cualquier cómo.",
    author: "Friedrich Nietzsche",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_confucio_lento",
    text: "No importa lo despacio que vayas, mientras no te detengas.",
    author: "Confucio",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_laozi_paso",
    text: "Un viaje de mil millas comienza con un solo paso.",
    author: "Lao Tse",
    category: "philosophy",
    language: "en",
  },

  // Ciencia / emprendimiento
  {
    id: "es_einstein_imaginacion",
    text: "La imaginación es más importante que el conocimiento.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_curie_entender",
    text: "Nada en la vida debe temerse, solo comprenderse. Ahora es el momento de comprender más, para temer menos.",
    author: "Marie Curie",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_jobs_tiempo",
    text: "Tu tiempo es limitado, no lo malgastes viviendo la vida de otra persona.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_mandela_imposible",
    text: "Siempre parece imposible, hasta que se hace.",
    author: "Nelson Mandela",
    category: "leader",
    language: "en",
  },

  // Voces hispanohablantes
  {
    id: "es_cervantes_andar",
    text: "El que lee mucho y anda mucho, ve mucho y sabe mucho.",
    author: "Miguel de Cervantes",
    category: "literature",
    language: "en",
  },
  {
    id: "es_cervantes_libertad",
    text: "La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.",
    author: "Miguel de Cervantes",
    category: "literature",
    language: "en",
  },
  {
    id: "es_borges_paraiso",
    text: "Siempre imaginé que el Paraíso sería algún tipo de biblioteca.",
    author: "Jorge Luis Borges",
    category: "literature",
    language: "en",
  },
  {
    id: "es_borges_olvidar",
    text: "Uno está enamorado cuando se da cuenta de que otra persona es única.",
    author: "Jorge Luis Borges",
    category: "literature",
    language: "en",
  },
  {
    id: "es_marquez_vida",
    text: "La vida no es la que uno vivió, sino la que uno recuerda y cómo la recuerda para contarla.",
    author: "Gabriel García Márquez",
    category: "literature",
    language: "en",
  },
  {
    id: "es_neruda_lento",
    text: "Muere lentamente quien no viaja, quien no lee, quien no oye música, quien no encuentra encanto en sí mismo.",
    author: "Pablo Neruda",
    category: "literature",
    language: "en",
  },
  {
    id: "es_lorca_volar",
    text: "Solo el misterio nos hace vivir. Solo el misterio.",
    author: "Federico García Lorca",
    category: "literature",
    language: "en",
  },
  {
    id: "es_paz_palabra",
    text: "La libertad no es una filosofía, ni siquiera es una idea: es un movimiento de la conciencia.",
    author: "Octavio Paz",
    category: "literature",
    language: "en",
  },
  {
    id: "es_machado_camino",
    text: "Caminante, no hay camino, se hace camino al andar.",
    author: "Antonio Machado",
    category: "literature",
    language: "en",
  },
  {
    id: "es_kahlo_alas",
    text: "Pies, ¿para qué los quiero si tengo alas para volar?",
    author: "Frida Kahlo",
    category: "literature",
    language: "en",
  },
  {
    id: "es_sor_juana_palabras",
    text: "Yo no estudio para saber más, sino para ignorar menos.",
    author: "Sor Juana Inés de la Cruz",
    category: "literature",
    language: "en",
  },
  {
    id: "es_picasso_inspiracion",
    text: "La inspiración existe, pero tiene que encontrarte trabajando.",
    author: "Pablo Picasso",
    category: "entrepreneur",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Estoicos: Marco Aurelio, Séneca, Epicteto
  // ───────────────────────────────────────────────────────────
  {
    id: "es_aurelio_pensamientos",
    text: "La felicidad de tu vida depende de la calidad de tus pensamientos.",
    author: "Marco Aurelio",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_aurelio_hoy",
    text: "No vivas como si tuvieras diez mil años por delante. Mientras vivas, mientras puedas, sé bueno.",
    author: "Marco Aurelio",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_aurelio_dentro",
    text: "Mira dentro de ti. Dentro de ti está la fuente del bien, una fuente que siempre brotará mientras sigas cavando.",
    author: "Marco Aurelio",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_seneca_puerto",
    text: "Ningún viento es favorable para quien no sabe a qué puerto se dirige.",
    author: "Séneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_seneca_atreverse",
    text: "No nos atrevemos a muchas cosas porque son difíciles, pero son difíciles porque no nos atrevemos a hacerlas.",
    author: "Séneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_seneca_aprender",
    text: "Mientras enseñamos, aprendemos.",
    author: "Séneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_seneca_suerte",
    text: "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.",
    author: "Séneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_epicteto_depende",
    text: "No son las cosas las que perturban a los hombres, sino las opiniones que tienen sobre ellas.",
    author: "Epicteto",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_epicteto_control",
    text: "Hay cosas que dependen de nosotros y cosas que no. La sabiduría está en distinguir unas de otras.",
    author: "Epicteto",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_epicteto_escuchar",
    text: "Tenemos dos oídos y una sola boca para escuchar el doble de lo que hablamos.",
    author: "Epicteto",
    category: "philosophy",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Filosofía griega: Sócrates, Platón, Aristóteles, Heráclito, Epicuro
  // ───────────────────────────────────────────────────────────
  {
    id: "es_socrates_saber",
    text: "Solo sé que no sé nada.",
    author: "Sócrates",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_socrates_sabiduria",
    text: "La sabiduría comienza con el asombro.",
    author: "Sócrates",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_socrates_construir",
    text: "El secreto del cambio es concentrar toda tu energía no en luchar contra lo viejo, sino en construir lo nuevo.",
    author: "Sócrates",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_platon_principio",
    text: "El principio es la parte más importante de la obra.",
    author: "Platón",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_platon_vencerse",
    text: "La primera y mejor victoria es conquistarse a uno mismo.",
    author: "Platón",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_platon_amable",
    text: "Sé amable, porque cada persona que encuentras está librando una dura batalla.",
    author: "Platón",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_aristoteles_conocerse",
    text: "Conocerse a uno mismo es el principio de toda sabiduría.",
    author: "Aristóteles",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_aristoteles_educacion",
    text: "Las raíces de la educación son amargas, pero su fruto es dulce.",
    author: "Aristóteles",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_aristoteles_esperanza",
    text: "La esperanza es el sueño del hombre despierto.",
    author: "Aristóteles",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_heraclito_rio",
    text: "Ningún hombre se baña dos veces en el mismo río, porque ni el río ni el hombre son los mismos.",
    author: "Heráclito",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_heraclito_cambio",
    text: "Lo único constante es el cambio.",
    author: "Heráclito",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_epicuro_tener",
    text: "No estropees lo que tienes deseando lo que no tienes; recuerda que lo que ahora tienes fue una vez de lo que solo esperabas.",
    author: "Epicuro",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_epicuro_amistad",
    text: "De todas las cosas que la sabiduría procura para la felicidad de toda la vida, la mayor es la amistad.",
    author: "Epicuro",
    category: "philosophy",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Sabiduría oriental: Confucio, Lao Tse, Buda
  // ───────────────────────────────────────────────────────────
  {
    id: "es_confucio_belleza",
    text: "Todo tiene su belleza, pero no todos la ven.",
    author: "Confucio",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_confucio_trabajo",
    text: "Elige un trabajo que ames y no tendrás que trabajar ni un día de tu vida.",
    author: "Confucio",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_confucio_caer",
    text: "Nuestra mayor gloria no está en no caer nunca, sino en levantarnos cada vez que caemos.",
    author: "Confucio",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_confucio_vela",
    text: "Es mejor encender una vela que maldecir la oscuridad.",
    author: "Confucio",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_laozi_conocerse",
    text: "Conocer a los demás es sabiduría; conocerse a uno mismo es iluminación.",
    author: "Lao Tse",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_laozi_dominarse",
    text: "Dominar a los demás es fuerza; dominarse a uno mismo es verdadero poder.",
    author: "Lao Tse",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_laozi_palabras",
    text: "Las palabras sinceras no son agradables; las palabras agradables no son sinceras.",
    author: "Lao Tse",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_buda_mente",
    text: "Lo que somos hoy proviene de nuestros pensamientos de ayer, y nuestros pensamientos de hoy construyen nuestra vida de mañana.",
    author: "Buda",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_buda_camino",
    text: "No hay camino para la felicidad: la felicidad es el camino.",
    author: "Buda",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_buda_vela",
    text: "Miles de velas pueden encenderse con una sola vela, y la vida de esa vela no se acortará.",
    author: "Buda",
    category: "philosophy",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Filosofía moderna: Kant, Schopenhauer, Kierkegaard, Descartes,
  // Spinoza, Pascal, Montaigne, Voltaire, Nietzsche
  // ───────────────────────────────────────────────────────────
  {
    id: "es_kant_atrevete",
    text: "¡Ten el valor de servirte de tu propio entendimiento! Ese es el lema de la Ilustración.",
    author: "Immanuel Kant",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_kant_cielo",
    text: "Dos cosas llenan el ánimo de admiración: el cielo estrellado sobre mí y la ley moral dentro de mí.",
    author: "Immanuel Kant",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_schopenhauer_salud",
    text: "La salud no lo es todo, pero sin ella todo lo demás es nada.",
    author: "Arthur Schopenhauer",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_schopenhauer_talento",
    text: "El talento acierta en un blanco que nadie más puede acertar; el genio acierta en un blanco que nadie más puede ver.",
    author: "Arthur Schopenhauer",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_kierkegaard_vivir",
    text: "La vida solo puede comprenderse mirando hacia atrás, pero ha de vivirse mirando hacia adelante.",
    author: "Søren Kierkegaard",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_kierkegaard_atreverse",
    text: "Atreverse es perder el pie momentáneamente; no atreverse es perderse a uno mismo.",
    author: "Søren Kierkegaard",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_descartes_pienso",
    text: "Pienso, luego existo.",
    author: "René Descartes",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_descartes_dividir",
    text: "Divide cada dificultad en tantas partes como sea posible para resolverla mejor.",
    author: "René Descartes",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_spinoza_paz",
    text: "La paz no es la ausencia de guerra; es una virtud que nace de la fortaleza del alma.",
    author: "Baruch Spinoza",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_spinoza_entender",
    text: "No reír, no lamentar, no detestar, sino comprender.",
    author: "Baruch Spinoza",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_pascal_corazon",
    text: "El corazón tiene razones que la razón no entiende.",
    author: "Blaise Pascal",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_pascal_brevedad",
    text: "He hecho esta carta más larga de lo habitual porque no he tenido tiempo de hacerla más corta.",
    author: "Blaise Pascal",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_montaigne_temor",
    text: "Mi vida ha estado llena de terribles desgracias, la mayoría de las cuales nunca sucedieron.",
    author: "Michel de Montaigne",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_montaigne_propia",
    text: "La cosa más grande del mundo es saber ser de uno mismo.",
    author: "Michel de Montaigne",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_voltaire_jardin",
    text: "Debemos cultivar nuestro jardín.",
    author: "Voltaire",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_voltaire_perfecto",
    text: "Lo mejor es enemigo de lo bueno.",
    author: "Voltaire",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_voltaire_juzgar",
    text: "Juzga a un hombre por sus preguntas más que por sus respuestas.",
    author: "Voltaire",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_nietzsche_baile",
    text: "Y aquellos que fueron vistos bailando fueron considerados locos por quienes no podían escuchar la música.",
    author: "Friedrich Nietzsche",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_nietzsche_fuerte",
    text: "Lo que no me mata, me hace más fuerte.",
    author: "Friedrich Nietzsche",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_nietzsche_abismo",
    text: "Y si miras largo tiempo a un abismo, el abismo también mira dentro de ti.",
    author: "Friedrich Nietzsche",
    category: "philosophy",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Ciencia: Einstein, Newton, Darwin, Curie, Feynman, Tesla,
  // Galileo, Hawking, Sagan, Leonardo da Vinci
  // ───────────────────────────────────────────────────────────
  {
    id: "es_einstein_error",
    text: "Una persona que nunca ha cometido un error nunca ha intentado nada nuevo.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_einstein_vida",
    text: "La vida es como montar en bicicleta: para mantener el equilibrio, debes seguir adelante.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_einstein_curiosidad",
    text: "No tengo talentos especiales, solo soy apasionadamente curioso.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_einstein_valor",
    text: "Esfuérzate no por tener éxito, sino por tener valor.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_newton_gigantes",
    text: "Si he visto más lejos, es porque estoy sentado sobre los hombros de gigantes.",
    author: "Isaac Newton",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_newton_oceano",
    text: "No sé cómo me ve el mundo, pero yo me veo como un niño jugando en la orilla del mar, mientras el gran océano de la verdad permanece inexplorado ante mí.",
    author: "Isaac Newton",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_darwin_adaptarse",
    text: "No es la especie más fuerte la que sobrevive, ni la más inteligente, sino la que mejor responde al cambio.",
    author: "Charles Darwin",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_darwin_amor",
    text: "El amor a todas las criaturas vivientes es el atributo más noble del hombre.",
    author: "Charles Darwin",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_curie_perseverancia",
    text: "La vida no es fácil para ninguno de nosotros. Pero hay que tener perseverancia y, sobre todo, confianza en uno mismo.",
    author: "Marie Curie",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_curie_ideas",
    text: "Hay que tener menos interés por las personas y más por las ideas.",
    author: "Marie Curie",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_feynman_enganar",
    text: "El primer principio es que no debes engañarte a ti mismo, y tú eres la persona más fácil de engañar.",
    author: "Richard Feynman",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_feynman_placer",
    text: "El placer de descubrir las cosas es la mayor recompensa de la ciencia.",
    author: "Richard Feynman",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_tesla_presente",
    text: "El presente es suyo; el futuro, por el que realmente he trabajado, es mío.",
    author: "Nikola Tesla",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_tesla_cerebro",
    text: "El cerebro es solo un receptor; en el universo hay un núcleo del que obtenemos conocimiento, fuerza e inspiración.",
    author: "Nikola Tesla",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_galileo_ensenar",
    text: "No puedes enseñar nada a un hombre; solo puedes ayudarlo a encontrarlo dentro de sí mismo.",
    author: "Galileo Galilei",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_galileo_razon",
    text: "Nunca he encontrado a una persona tan ignorante de la que no pudiera aprender algo.",
    author: "Galileo Galilei",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_hawking_estrellas",
    text: "Mira hacia las estrellas y no hacia tus pies. Intenta darle sentido a lo que ves y pregúntate qué hace que el universo exista.",
    author: "Stephen Hawking",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_hawking_vida",
    text: "Por muy difícil que sea la vida, siempre hay algo que puedes hacer y en lo que puedes tener éxito.",
    author: "Stephen Hawking",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_hawking_inteligencia",
    text: "La inteligencia es la capacidad de adaptarse al cambio.",
    author: "Stephen Hawking",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_sagan_cosmos",
    text: "Somos una manera de que el cosmos se conozca a sí mismo.",
    author: "Carl Sagan",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_sagan_pastel",
    text: "Si deseas hacer un pastel de manzana desde cero, primero debes inventar el universo.",
    author: "Carl Sagan",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_davinci_simplicidad",
    text: "La simplicidad es la máxima sofisticación.",
    author: "Leonardo da Vinci",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_davinci_hacer",
    text: "Saber no es suficiente; debemos aplicar. Querer no es suficiente; debemos hacer.",
    author: "Leonardo da Vinci",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_davinci_obstaculos",
    text: "Los obstáculos no pueden doblegarme; toda obstinación cede ante una resolución firme.",
    author: "Leonardo da Vinci",
    category: "scientist",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Emprendimiento e innovación: Jobs, Bezos, Musk, Buffett,
  // Ford, Gates, Disney
  // ───────────────────────────────────────────────────────────
  {
    id: "es_jobs_innovacion",
    text: "La innovación distingue a un líder de un seguidor.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_jobs_amar",
    text: "La única manera de hacer un gran trabajo es amar lo que haces.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_jobs_puntos",
    text: "No puedes conectar los puntos mirando hacia adelante; solo puedes conectarlos mirando hacia atrás.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_bezos_clientes",
    text: "Vemos a nuestros clientes como invitados a una fiesta en la que nosotros somos los anfitriones.",
    author: "Jeff Bezos",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_bezos_arrepentir",
    text: "Sabía que si fracasaba no me arrepentiría, pero sabía que lo único de lo que sí podría arrepentirme era de no haberlo intentado.",
    author: "Jeff Bezos",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_musk_perseverar",
    text: "La perseverancia es muy importante. No debes rendirte a menos que te veas obligado a hacerlo.",
    author: "Elon Musk",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_musk_importante",
    text: "Cuando algo es lo bastante importante, lo haces aunque las probabilidades no estén a tu favor.",
    author: "Elon Musk",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_buffett_arbol",
    text: "Alguien está sentado hoy a la sombra porque hace mucho tiempo alguien plantó un árbol.",
    author: "Warren Buffett",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_buffett_reputacion",
    text: "Se necesitan veinte años para construir una reputación y cinco minutos para arruinarla.",
    author: "Warren Buffett",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_ford_pensar",
    text: "Tanto si crees que puedes como si crees que no puedes, estás en lo cierto.",
    author: "Henry Ford",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_ford_juntos",
    text: "Reunirse es un comienzo, mantenerse juntos es un progreso, trabajar juntos es el éxito.",
    author: "Henry Ford",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_ford_obstaculos",
    text: "Los obstáculos son esas cosas espantosas que ves cuando apartas los ojos de tu meta.",
    author: "Henry Ford",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_gates_clientes",
    text: "Tus clientes más descontentos son tu mayor fuente de aprendizaje.",
    author: "Bill Gates",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_gates_exito",
    text: "El éxito es un pésimo maestro; seduce a la gente inteligente haciéndoles creer que no pueden perder.",
    author: "Bill Gates",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_disney_empezar",
    text: "La manera de empezar es dejar de hablar y empezar a hacer.",
    author: "Walt Disney",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_disney_sonar",
    text: "Si puedes soñarlo, puedes hacerlo.",
    author: "Walt Disney",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_disney_curiosidad",
    text: "Seguimos avanzando, abriendo nuevas puertas y haciendo cosas nuevas, porque somos curiosos, y la curiosidad nos lleva por nuevos caminos.",
    author: "Walt Disney",
    category: "entrepreneur",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Cervantes y el Siglo de Oro: Calderón, Lope de Vega,
  // Quevedo, Santa Teresa
  // ───────────────────────────────────────────────────────────
  {
    id: "es_cervantes_camino",
    text: "El que no sabe gozar de la ventura cuando le viene, no debe quejarse si se pasa.",
    author: "Miguel de Cervantes",
    category: "literature",
    language: "en",
  },
  {
    id: "es_cervantes_historia",
    text: "La historia es madre de la verdad, émula del tiempo, depósito de las acciones, testigo de lo pasado.",
    author: "Miguel de Cervantes",
    category: "literature",
    language: "en",
  },
  {
    id: "es_cervantes_prevenido",
    text: "El hombre prevenido vale por dos.",
    author: "Miguel de Cervantes",
    category: "literature",
    language: "en",
  },
  {
    id: "es_calderon_vida_sueno",
    text: "¿Qué es la vida? Una ilusión, una sombra, una ficción; y el mayor bien es pequeño, que toda la vida es sueño, y los sueños, sueños son.",
    author: "Pedro Calderón de la Barca",
    category: "literature",
    language: "en",
  },
  {
    id: "es_calderon_obrar_bien",
    text: "Obrar bien es lo que importa, sea sueño o no.",
    author: "Pedro Calderón de la Barca",
    category: "literature",
    language: "en",
  },
  {
    id: "es_lope_versos",
    text: "De los versos que escribí, lo que más quiero es lo que más viví.",
    author: "Lope de Vega",
    category: "literature",
    language: "en",
  },
  {
    id: "es_quevedo_polvo",
    text: "Polvo serán, mas polvo enamorado.",
    author: "Francisco de Quevedo",
    category: "literature",
    language: "en",
  },
  {
    id: "es_quevedo_horas",
    text: "¡Cómo de entre mis manos te resbalas! ¡Oh, cómo te deslizas, edad mía!",
    author: "Francisco de Quevedo",
    category: "literature",
    language: "en",
  },
  {
    id: "es_teresa_nada_turbe",
    text: "Nada te turbe, nada te espante, todo se pasa, la paciencia todo lo alcanza.",
    author: "Santa Teresa de Jesús",
    category: "literature",
    language: "en",
  },
  {
    id: "es_teresa_obras",
    text: "No es el mucho saber lo que harta y satisface el alma, sino el sentir y gustar de las cosas internamente.",
    author: "Santa Teresa de Jesús",
    category: "literature",
    language: "en",
  },
  {
    id: "es_teresa_manos",
    text: "Quien a Dios tiene, nada le falta: solo Dios basta.",
    author: "Santa Teresa de Jesús",
    category: "literature",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Letras hispanoamericanas: Borges, García Márquez, Neruda,
  // Cortázar, Benedetti, Vargas Llosa, Allende, Rubén Darío
  // ───────────────────────────────────────────────────────────
  {
    id: "es_borges_caminos",
    text: "Que otros se jacten de las páginas que han escrito; a mí me enorgullecen las que he leído.",
    author: "Jorge Luis Borges",
    category: "literature",
    language: "en",
  },
  {
    id: "es_borges_destino",
    text: "Uno no es lo que es por lo que escribe, sino por lo que ha leído.",
    author: "Jorge Luis Borges",
    category: "literature",
    language: "en",
  },
  {
    id: "es_borges_felicidad",
    text: "He cometido el peor de los pecados que un hombre puede cometer: no he sido feliz.",
    author: "Jorge Luis Borges",
    category: "literature",
    language: "en",
  },
  {
    id: "es_marquez_amor",
    text: "El amor se hace más grande y noble en la calamidad.",
    author: "Gabriel García Márquez",
    category: "literature",
    language: "en",
  },
  {
    id: "es_marquez_corazon",
    text: "El corazón tiene más cuartos que un hotel de putas; siempre hay sitio para un amor más.",
    author: "Gabriel García Márquez",
    category: "literature",
    language: "en",
  },
  {
    id: "es_marquez_soledad",
    text: "Lo único que me duele de morir es que no sea de amor.",
    author: "Gabriel García Márquez",
    category: "literature",
    language: "en",
  },
  {
    id: "es_neruda_amor",
    text: "Es tan corto el amor, y es tan largo el olvido.",
    author: "Pablo Neruda",
    category: "literature",
    language: "en",
  },
  {
    id: "es_neruda_primavera",
    text: "Podrán cortar todas las flores, pero no podrán detener la primavera.",
    author: "Pablo Neruda",
    category: "literature",
    language: "en",
  },
  {
    id: "es_neruda_pan",
    text: "Algún día en cualquier parte, en cualquier lugar, indefectiblemente te encontrarás a ti mismo.",
    author: "Pablo Neruda",
    category: "literature",
    language: "en",
  },
  {
    id: "es_cortazar_lector",
    text: "Nada está perdido si se tiene el valor de proclamar que todo está perdido y hay que empezar de nuevo.",
    author: "Julio Cortázar",
    category: "literature",
    language: "en",
  },
  {
    id: "es_cortazar_andar",
    text: "Andábamos sin buscarnos, pero sabiendo que andábamos para encontrarnos.",
    author: "Julio Cortázar",
    category: "literature",
    language: "en",
  },
  {
    id: "es_cortazar_puentes",
    text: "Uno no se enamora de las personas, uno se enamora cuando se desconoce, cuando aún no se sabe quién es el otro.",
    author: "Julio Cortázar",
    category: "literature",
    language: "en",
  },
  {
    id: "es_benedetti_no_te_rindas",
    text: "No te rindas, que la vida es eso, continuar el viaje, perseguir tus sueños.",
    author: "Mario Benedetti",
    category: "literature",
    language: "en",
  },
  {
    id: "es_benedetti_corazon",
    text: "Cuando creíamos que teníamos todas las respuestas, de pronto cambiaron todas las preguntas.",
    author: "Mario Benedetti",
    category: "literature",
    language: "en",
  },
  {
    id: "es_benedetti_codo",
    text: "Te quiero porque tu mano sobre la mía suena a verdad.",
    author: "Mario Benedetti",
    category: "literature",
    language: "en",
  },
  {
    id: "es_vargas_llosa_lectura",
    text: "La literatura es fuego, significa inconformismo y rebelión.",
    author: "Mario Vargas Llosa",
    category: "literature",
    language: "en",
  },
  {
    id: "es_vargas_llosa_escribir",
    text: "Escribir es una manera de vivir.",
    author: "Mario Vargas Llosa",
    category: "literature",
    language: "en",
  },
  {
    id: "es_allende_escribir",
    text: "Escribe lo que no debería ser olvidado.",
    author: "Isabel Allende",
    category: "literature",
    language: "en",
  },
  {
    id: "es_allende_miedo",
    text: "Solo somos dueños de aquello que damos; lo que retenemos termina por aprisionarnos.",
    author: "Isabel Allende",
    category: "literature",
    language: "en",
  },
  {
    id: "es_dario_juventud",
    text: "Juventud, divino tesoro, ¡ya te vas para no volver!",
    author: "Rubén Darío",
    category: "literature",
    language: "en",
  },
  {
    id: "es_dario_caminos",
    text: "Yo persigo una forma que no encuentra mi estilo, botón de pensamiento que busca ser la rosa.",
    author: "Rubén Darío",
    category: "literature",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Pensamiento ibérico: Unamuno, Ortega y Gasset, Machado,
  // Bécquer, Rosalía de Castro, Juan Ramón Jiménez
  // ───────────────────────────────────────────────────────────
  {
    id: "es_unamuno_vencer",
    text: "Solo el que sabe es libre, y más libre el que más sabe.",
    author: "Miguel de Unamuno",
    category: "literature",
    language: "en",
  },
  {
    id: "es_unamuno_vida",
    text: "Procura vivir de continuo de tal manera que tu muerte sea una injusticia.",
    author: "Miguel de Unamuno",
    category: "literature",
    language: "en",
  },
  {
    id: "es_unamuno_progreso",
    text: "El progreso consiste en renovarse.",
    author: "Miguel de Unamuno",
    category: "literature",
    language: "en",
  },
  {
    id: "es_ortega_circunstancia",
    text: "Yo soy yo y mi circunstancia, y si no la salvo a ella no me salvo yo.",
    author: "José Ortega y Gasset",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_ortega_esfuerzo",
    text: "El esfuerzo inútil conduce a la melancolía.",
    author: "José Ortega y Gasset",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_ortega_vivir",
    text: "Vivir es sentirse perdido; el que lo acepta ya ha empezado a encontrarse.",
    author: "José Ortega y Gasset",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_machado_hoy",
    text: "Hoy es siempre todavía.",
    author: "Antonio Machado",
    category: "literature",
    language: "en",
  },
  {
    id: "es_machado_palabra",
    text: "Despacito y buena letra: el hacer las cosas bien importa más que el hacerlas.",
    author: "Antonio Machado",
    category: "literature",
    language: "en",
  },
  {
    id: "es_machado_ojo",
    text: "El ojo que ves no es ojo porque tú lo veas; es ojo porque te ve.",
    author: "Antonio Machado",
    category: "literature",
    language: "en",
  },
  {
    id: "es_becquer_poesia",
    text: "Podrá no haber poetas, pero siempre habrá poesía.",
    author: "Gustavo Adolfo Bécquer",
    category: "literature",
    language: "en",
  },
  {
    id: "es_becquer_poesia_eres",
    text: "¿Qué es poesía? Poesía eres tú.",
    author: "Gustavo Adolfo Bécquer",
    category: "literature",
    language: "en",
  },
  {
    id: "es_rosalia_camino",
    text: "Yo no sé lo que busco eternamente en la tierra, en el aire y en el cielo.",
    author: "Rosalía de Castro",
    category: "literature",
    language: "en",
  },
  {
    id: "es_rosalia_sombras",
    text: "Cada loco con su tema, contra gustos no hay disputa: artefactos, bombas, sangre, latrocinios, robos... ¡musa, déjate de tonterías!",
    author: "Rosalía de Castro",
    category: "literature",
    language: "en",
  },
  {
    id: "es_jimenez_raices",
    text: "Las raíces y las alas; pero que las alas arraiguen y las raíces vuelen.",
    author: "Juan Ramón Jiménez",
    category: "literature",
    language: "en",
  },
  {
    id: "es_jimenez_definitiva",
    text: "Si te dan papel pautado, escribe por el otro lado.",
    author: "Juan Ramón Jiménez",
    category: "literature",
    language: "en",
  },
  {
    id: "es_jimenez_inteligencia",
    text: "¡Inteligencia, dame el nombre exacto de las cosas!",
    author: "Juan Ramón Jiménez",
    category: "literature",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Arte y poesía universal: Picasso, Dalí, Gabriela Mistral,
  // Amado Nervo, Vicente Aleixandre
  // ───────────────────────────────────────────────────────────
  {
    id: "es_picasso_nino",
    text: "Todo niño es un artista; el problema es seguir siéndolo cuando creces.",
    author: "Pablo Picasso",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_picasso_accion",
    text: "La acción es la clave fundamental de todo éxito.",
    author: "Pablo Picasso",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_picasso_hacer",
    text: "Yo no busco, encuentro.",
    author: "Pablo Picasso",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_dali_perfeccion",
    text: "No tengas miedo de la perfección, nunca la alcanzarás.",
    author: "Salvador Dalí",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_dali_genio",
    text: "La inteligencia sin ambición es un pájaro sin alas.",
    author: "Salvador Dalí",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_mistral_manana",
    text: "El futuro de los niños es siempre hoy. Mañana será tarde.",
    author: "Gabriela Mistral",
    category: "literature",
    language: "en",
  },
  {
    id: "es_mistral_ensenar",
    text: "Enseñar siempre: en el patio y en la calle como en la sala de clase. Enseñar con la actitud, el gesto y la palabra.",
    author: "Gabriela Mistral",
    category: "literature",
    language: "en",
  },
  {
    id: "es_mistral_dar",
    text: "Se da lo que se tiene, pero también se tiene lo que se da.",
    author: "Gabriela Mistral",
    category: "literature",
    language: "en",
  },
  {
    id: "es_nervo_paz",
    text: "Vida, nada me debes; vida, estamos en paz.",
    author: "Amado Nervo",
    category: "literature",
    language: "en",
  },
  {
    id: "es_nervo_arquitecto",
    text: "Porque veo al final de mi rudo camino que yo fui el arquitecto de mi propio destino.",
    author: "Amado Nervo",
    category: "literature",
    language: "en",
  },
  {
    id: "es_nervo_amar",
    text: "Amemos siempre, amemos, aunque el amado no exista.",
    author: "Amado Nervo",
    category: "literature",
    language: "en",
  },
  {
    id: "es_aleixandre_vida",
    text: "Todo lo que es creación en el universo es amor o resultado de un amor.",
    author: "Vicente Aleixandre",
    category: "literature",
    language: "en",
  },
  {
    id: "es_aleixandre_poeta",
    text: "El poeta es siempre el verdadero hombre, y a él se reduce todo poder, toda fuerza, toda grandeza.",
    author: "Vicente Aleixandre",
    category: "literature",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Voces lusófonas en traducción: Saramago, Pessoa
  // ───────────────────────────────────────────────────────────
  {
    id: "es_saramago_camino",
    text: "Hay que llegar a viejo para saber lo que es ser viejo; lo más difícil es vivirlo.",
    author: "José Saramago",
    category: "literature",
    language: "en",
  },
  {
    id: "es_saramago_ver",
    text: "Si puedes mirar, ve. Si puedes ver, repara.",
    author: "José Saramago",
    category: "literature",
    language: "en",
  },
  {
    id: "es_saramago_palabras",
    text: "Las palabras son buenas, las palabras son malas, las palabras hieren, las palabras curan.",
    author: "José Saramago",
    category: "literature",
    language: "en",
  },
  {
    id: "es_pessoa_navegar",
    text: "Navegar es preciso; vivir no es preciso.",
    author: "Fernando Pessoa",
    category: "literature",
    language: "en",
  },
  {
    id: "es_pessoa_piedra",
    text: "La piedra del camino es buena, porque enseña que el camino sigue.",
    author: "Fernando Pessoa",
    category: "literature",
    language: "en",
  },
  {
    id: "es_pessoa_sonar",
    text: "Tener opiniones es no comprender. La vida es para vivirla, no para pensarla.",
    author: "Fernando Pessoa",
    category: "literature",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Más estoicos y clásicos sobre carácter y constancia
  // ───────────────────────────────────────────────────────────
  {
    id: "es_aurelio_universo",
    text: "Acepta las cosas a las que el destino te encadena, y a las personas con las que te une, pero hazlo con todo el corazón.",
    author: "Marco Aurelio",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_aurelio_perfeccion",
    text: "No te limites a hablar de lo que debe ser un buen hombre: sé uno.",
    author: "Marco Aurelio",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_seneca_camino_largo",
    text: "Largo es el camino de la enseñanza por medio de teorías; breve y eficaz por medio de ejemplos.",
    author: "Séneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_seneca_vivir",
    text: "Mientras esperamos vivir, la vida pasa.",
    author: "Séneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_seneca_aprender_vivir",
    text: "Toda la vida hay que aprender a vivir.",
    author: "Séneca",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_epicteto_circunstancias",
    text: "No es lo que te sucede, sino cómo reaccionas a ello lo que importa.",
    author: "Epicteto",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_epicteto_progreso",
    text: "Solo las personas educadas son libres.",
    author: "Epicteto",
    category: "philosophy",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Más ciencia y descubrimiento
  // ───────────────────────────────────────────────────────────
  {
    id: "es_einstein_perseverar",
    text: "No es que sea muy inteligente, es que me quedo con los problemas más tiempo.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_einstein_aprender",
    text: "Aprende del ayer, vive el hoy, ten esperanza para el mañana. Lo importante es no dejar de hacerse preguntas.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_einstein_valor_persona",
    text: "Intenta no convertirte en una persona de éxito, sino en una persona de valor.",
    author: "Albert Einstein",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_curie_sonadores",
    text: "Soy de las que piensan que la ciencia tiene una gran belleza.",
    author: "Marie Curie",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_galileo_universo",
    text: "Las matemáticas son el alfabeto con el cual Dios ha escrito el universo.",
    author: "Galileo Galilei",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_davinci_aprender",
    text: "El aprendizaje nunca agota la mente.",
    author: "Leonardo da Vinci",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_davinci_tiempo",
    text: "Así como un día bien empleado produce un dulce sueño, así una vida bien usada produce una dulce muerte.",
    author: "Leonardo da Vinci",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_feynman_aprender",
    text: "Estudia mucho lo que más te interese, de la manera más indisciplinada, irreverente y original posible.",
    author: "Richard Feynman",
    category: "scientist",
    language: "en",
  },
  {
    id: "es_sagan_libros",
    text: "Un libro es una prueba de que los humanos somos capaces de hacer magia.",
    author: "Carl Sagan",
    category: "scientist",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Más emprendimiento y trabajo creativo
  // ───────────────────────────────────────────────────────────
  {
    id: "es_jobs_hambre",
    text: "Sigan hambrientos, sigan alocados.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_jobs_calidad",
    text: "Sé un referente de calidad. Algunas personas no están acostumbradas a un entorno donde se espera la excelencia.",
    author: "Steve Jobs",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_ford_calidad",
    text: "La calidad significa hacerlo bien cuando nadie está mirando.",
    author: "Henry Ford",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_ford_fracaso",
    text: "El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez de forma más inteligente.",
    author: "Henry Ford",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_disney_imposible",
    text: "Es divertido hacer lo imposible.",
    author: "Walt Disney",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_bezos_obsesion",
    text: "Si construyes una gran experiencia, los clientes se lo cuentan unos a otros.",
    author: "Jeff Bezos",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_buffett_invertir",
    text: "El riesgo viene de no saber lo que estás haciendo.",
    author: "Warren Buffett",
    category: "entrepreneur",
    language: "en",
  },
  {
    id: "es_gates_paciencia",
    text: "La gente siempre sobreestima lo que puede hacer en un año y subestima lo que puede hacer en diez.",
    author: "Bill Gates",
    category: "entrepreneur",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Sabiduría literaria sobre la vida y la palabra
  // ───────────────────────────────────────────────────────────
  {
    id: "es_galeano_utopia",
    text: "La utopía está en el horizonte: camino dos pasos, ella se aleja dos pasos. ¿Para qué sirve la utopía? Para eso sirve: para caminar.",
    author: "Eduardo Galeano",
    category: "literature",
    language: "en",
  },
  {
    id: "es_galeano_palabras",
    text: "Mucha gente pequeña, en lugares pequeños, haciendo cosas pequeñas, puede cambiar el mundo.",
    author: "Eduardo Galeano",
    category: "literature",
    language: "en",
  },
  {
    id: "es_galeano_fuego",
    text: "El mundo es eso: un montón de gente, un mar de fueguitos. Cada persona brilla con luz propia entre todas las demás.",
    author: "Eduardo Galeano",
    category: "literature",
    language: "en",
  },
  {
    id: "es_lorca_poesia",
    text: "La poesía no quiere adeptos, quiere amantes.",
    author: "Federico García Lorca",
    category: "literature",
    language: "en",
  },
  {
    id: "es_lorca_libros",
    text: "Cuando alguien va al teatro es como si fuera a misa. Pero el libro es la puerta de la imaginación.",
    author: "Federico García Lorca",
    category: "literature",
    language: "en",
  },
  {
    id: "es_paz_soledad",
    text: "La soledad es el fondo último de la condición humana.",
    author: "Octavio Paz",
    category: "literature",
    language: "en",
  },
  {
    id: "es_paz_amor",
    text: "El amor es una de las respuestas que el hombre ha inventado para mirar a la muerte de frente.",
    author: "Octavio Paz",
    category: "literature",
    language: "en",
  },
  {
    id: "es_kahlo_pintar",
    text: "Pinto flores para que así no mueran.",
    author: "Frida Kahlo",
    category: "literature",
    language: "en",
  },
  {
    id: "es_kahlo_realidad",
    text: "Nunca pinto sueños o pesadillas. Pinto mi propia realidad.",
    author: "Frida Kahlo",
    category: "literature",
    language: "en",
  },
  {
    id: "es_sor_juana_necio",
    text: "Hombres necios que acusáis a la mujer sin razón, sin ver que sois la ocasión de lo mismo que culpáis.",
    author: "Sor Juana Inés de la Cruz",
    category: "literature",
    language: "en",
  },
  {
    id: "es_sor_juana_entendimiento",
    text: "Yo no entiendo de esas cosas; solo sé que aquí me vine porque, si es que soy mujer, ninguno lo verifique.",
    author: "Sor Juana Inés de la Cruz",
    category: "literature",
    language: "en",
  },
  {
    id: "es_cela_escritor",
    text: "El escritor no escribe para sus contemporáneos, ni para sus antepasados: escribe para la posteridad.",
    author: "Camilo José Cela",
    category: "literature",
    language: "en",
  },
  {
    id: "es_cela_trabajo",
    text: "La literatura no es más que carpintería; con ambas se construye, y lo difícil es saber hacerlo.",
    author: "Camilo José Cela",
    category: "literature",
    language: "en",
  },
  {
    id: "es_benavente_lograr",
    text: "Lograrás más fácilmente que te perdonen el mal que hagas que el bien que hayas hecho.",
    author: "Jacinto Benavente",
    category: "literature",
    language: "en",
  },
  {
    id: "es_benavente_amistad",
    text: "Tarda en llegar, y al final, al final hay recompensa.",
    author: "Jacinto Benavente",
    category: "literature",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Más filosofía sobre voluntad, sentido y carácter
  // ───────────────────────────────────────────────────────────
  {
    id: "es_nietzsche_uno_mismo",
    text: "Conviértete en quien eres.",
    author: "Friedrich Nietzsche",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_nietzsche_meta",
    text: "Quien tiene un para qué encuentra casi siempre un cómo.",
    author: "Friedrich Nietzsche",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_kant_deber",
    text: "Obra de tal modo que la máxima de tu voluntad pueda valer siempre como principio de una ley universal.",
    author: "Immanuel Kant",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_kant_paciencia",
    text: "La ciencia es conocimiento organizado; la sabiduría es vida organizada.",
    author: "Immanuel Kant",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_schopenhauer_destino",
    text: "Todo el mundo toma los límites de su propia visión por los límites del mundo.",
    author: "Arthur Schopenhauer",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_montaigne_vivir",
    text: "El más grande de todos los logros es saber vivir su vida con sentido.",
    author: "Michel de Montaigne",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_pascal_presente",
    text: "El presente nunca es nuestro fin; el pasado y el presente son nuestros medios, solo el futuro es nuestro fin.",
    author: "Blaise Pascal",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_spinoza_alegria",
    text: "La alegría es el paso del hombre de una menor a una mayor perfección.",
    author: "Baruch Spinoza",
    category: "philosophy",
    language: "en",
  },
  {
    id: "es_kierkegaard_riesgo",
    text: "Atreverse causa ansiedad, pero no atreverse es perderse a uno mismo.",
    author: "Søren Kierkegaard",
    category: "philosophy",
    language: "en",
  },

  // ───────────────────────────────────────────────────────────
  // Cierre: voces sobre esperanza, dignidad y servicio
  // ───────────────────────────────────────────────────────────
  {
    id: "es_mandela_educacion",
    text: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.",
    author: "Nelson Mandela",
    category: "leader",
    language: "en",
  },
  {
    id: "es_mandela_valiente",
    text: "No es valiente quien no tiene miedo, sino quien sabe conquistarlo.",
    author: "Nelson Mandela",
    category: "leader",
    language: "en",
  },
  {
    id: "es_mandela_caer",
    text: "La mayor gloria de vivir no está en no caer nunca, sino en levantarnos cada vez que caemos.",
    author: "Nelson Mandela",
    category: "leader",
    language: "en",
  },
  {
    id: "es_mistral_servir",
    text: "Donde haya un árbol que plantar, plántalo tú. Donde haya un error que enmendar, enmiéndalo tú.",
    author: "Gabriela Mistral",
    category: "literature",
    language: "en",
  },
  {
    id: "es_nervo_serenidad",
    text: "Yo fui el único artífice de mi destino: si extraje las mieles o la hiel de las cosas, fue porque en ellas puse hiel o mieles sabrosas.",
    author: "Amado Nervo",
    category: "literature",
    language: "en",
  },
  {
    id: "es_benedetti_sur",
    text: "El sur también existe.",
    author: "Mario Benedetti",
    category: "literature",
    language: "en",
  },
  {
    id: "es_unamuno_fe",
    text: "La fe que no duda es fe muerta.",
    author: "Miguel de Unamuno",
    category: "literature",
    language: "en",
  },
  {
    id: "es_ortega_claridad",
    text: "La claridad es la cortesía del filósofo.",
    author: "José Ortega y Gasset",
    category: "philosophy",
    language: "en",
  },
];
